### ISSUE TITLE
An option to manually set reference to show full path

### ISSUE THREAD

**Issue by PandaBoy444** [remnoteio/remnote-issues#1]
**Is your feature request related to a problem? Please describe.**
I often reference a Rem where the rems heritage is relevant to the current entry. Currently it gets cut off after one or two parents which is useful most of the time, just not for this usecase

**Describe the solution you'd like**
I would like to have an option to present the full path to a Rem on a reference in the same manner of showing the definition of a Rem in current document

**Describe alternatives you've considered**
I have not thought of any alternatives

Thank you! I love you and your we work!

Edit: I just saw on the readme that this issue tracker is only for bug reports, sorry for not reading it beforehand. I would like it if we could use this page for an "issue" related to remnote, if the conversation still needs to be on discord the two can be synced with a bot. In the same way bug reports can drown and lose hold even when still relevant on normal chat platforms, other issues like feature requests can suffer the same fate.
Note: if you still decide that this page is only for bugs I recommend removing the feature request issue template.

**Comment by mfranzs** [comment]
Fair point! This has actually been on the backlog for a while. We'll slot it into the next update.
