### ISSUE TITLE
problem with LaTex when site zoom in

### ISSUE THREAD

**Issue by TaQuangKhoi** [remnoteio/remnote-issues#100]
*Describe the bug*

**To Reproduce**
1. Go to 'Queue'
2. Ctrl + **+**, to zoom in
3. See error

*Expected behavior*

**Screenshots**
![image](https://user-images.githubusercontent.com/45689286/92738046-d3fdcb00-f3a5-11ea-93cf-776310c1fb11.png)
![image](https://user-images.githubusercontent.com/45689286/92738171-ec6de580-f3a5-11ea-85c8-5cf4d8e4b631.png)
![image](https://user-images.githubusercontent.com/45689286/92738937-98afcc00-f3a6-11ea-8951-fc0954746ef7.png)
![image](https://user-images.githubusercontent.com/45689286/92739361-ffcd8080-f3a6-11ea-8315-5c420832486e.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser **Chrome**
 - Version 85.0.4183.83 (Official Build) (64-bit)

*Smartphone (please complete the following information):*

**Additional context**
$$ x=\dfrac{D}dy$$

**Comment by mfranzs** [comment]
Thanks for the report. I'm having some trouble reproducing this. Does this happen even if you stay on the same page and press Ctrl + + continuously?

**Comment by TaQuangKhoi** [comment]
https://mega.nz/file/vBVmgYoA#ERfbYNS5jzxXNOvZNcMoonD-TB5FoQMDFO4NjLybMZY

this problem just happen with 125% and 150%

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
