### ISSUE TITLE
Chinese Pinyin in Global Search Produces Error

### ISSUE THREAD

**Issue by Add-HX** [remnoteio/remnote-issues#1000]
**Describe the bug**
When attempting to input Hanzi with pinyin, the pinyin does not replace the "Search for Document or Rem" grey text in the search bar and creates a search error.
If the search bar is clicked on by the mouse, the pinyin will overlay the "Search for Document or Rem" text but not produce an error.
Otherwise, if something else has been searched there will be no error.

**To Reproduce**
1. Ctrl-P for search bar
2. Type out pinyin
3. Attempt to press number to commit Hanzi

**Expected behavior**
That typing pinyin in the search bar would automatically replace the grey text in the search bar and not produce an error.

**Screenshots**
Typing out pinyin
![螢幕擷取畫面 (22)](https://user-images.githubusercontent.com/78433128/111089585-e72f5600-8502-11eb-8129-a8d0b5240630.png)
Pressing 1 result
![螢幕擷取畫面 (23)](https://user-images.githubusercontent.com/78433128/111089588-e8f91980-8502-11eb-99db-18479ecf33a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Remnote Application
 - Version: 1.2

**Additional context**
I am using the mainland China pinyin keyboard with traditional characters on.

**Comment by FuryMartin** [comment]
和 #1019 这个问题相同。
你可以在输入中文前打一个空格即可避免这个问题。

Same with the problem in #1019 .
You can press space before you enter Chinese characters to avoid the problem.

**Comment by drkvj** [comment]
merging with #584
