### ISSUE TITLE
Unintentional Bullet point deletion

### ISSUE THREAD

**Issue by SkubalonKing** [remnoteio/remnote-issues#1003]
**Describe the bug**
description in the screenshot provided.

Deleting a child bullet point deleted the hierarchically unassociated bullet point below it "6 Simplicity Is Paramount"

**Expected behavior**
Selecting single bullet point should not automatically delete the following bullet point

**Screenshots**

![Screenshot 2021-03-15 050115](https://user-images.githubusercontent.com/80687827/111150576-7fe9c400-854b-11eb-906e-a31dbb15a36f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.20.110 Chromium: 88.0.4324.192 (Official Build) (64-bit)

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by gibbsonn** [comment]
I get this as well, makes me not trust the app atm tbh
