### ISSUE TITLE
Updating your account (0/2002)

### ISSUE THREAD

**Issue by jparkgit** [remnoteio/remnote-issues#1004]
**Describe the bug**
No progress in "Updating your account (0/2002)". Stuck at 0.

**To Reproduce**
1. Go to Side bar menu

**Expected behavior**
I expect progress in the "Updating your account (0/2002)". However, there isn't any.

**Screenshots**
![Screenshot_20210315-215908_RemNote](https://user-images.githubusercontent.com/80691989/111158004-e4a02f80-85da-11eb-8298-48aa9f055ab7.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - via Google Play Store Remnote application

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.
.

**Comment by awreccan** [comment]
@jparkgit I'm having the same issue on mobile since the 1.3 update - what fixed your issue?
