### ISSUE TITLE
Graph not working

### ISSUE THREAD

**Issue by Saurabh-joshi** [remnoteio/remnote-issues#1006]
**Describe the bug**
It’s been dead for around a month for me, and I have no use of it as of now, but still just letting it known.
The setting gear of graph shows most of the time, but currently that is gone as well.

**To Reproduce**
1. Go to 'Any rem'
2. Click on '3 dots'
3. Scroll down to 'View graph'
4. See the blank page

**Expected behavior**
Some type of graph, I don't have a great interconnected graph, but it wasn't a blank as it's showing now

**Screenshots**
![image](https://user-images.githubusercontent.com/8554869/111209383-f5a86b00-85f1-11eb-9f8f-9889fc39e330.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Opera

**Additional context**
I checked both Windows version and browser version, not working on either of them, tried disabling all the CSS, still not working.

**Comment by drkvj** [comment]
Related discussion here : https://forum.remnote.io/t/graph-not-working/3343

**Comment by drkvj** [comment]
merging with #834
