### ISSUE TITLE
Phone heating problem

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#1007]
**Describe the bug**
Overheating problem when turning off the screen while sync

**To Reproduce**
1. Open an account with a lot of documents that are not sync with the phone
2. turn off screen while sync
3. See error

**Expected behavior**
not experiencing such a situation

**Smartphone (please complete the following information):**
 - Device: Mi max 2
 - OS: Miui 
 - Browser: android app
 - Version: global 11.0.2

**Comment by drkvj** [comment]
Have you been able to reproduce this behaviour? Does this happen all the time that you load documents or only that once? Kindly make a report on the forum, so that we can see if others are also having this problem. Once we have reproduced the issue, we can port it here for the devs to tackle
