### ISSUE TITLE
Minor bug: Incorrect Edit Later count when freshly opening or refreshing RemNote

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#101]
**Describe the bug**
Edit Later count is lower than the actual count when opening RemNote from scratch or when refreshing RemNote

**To Reproduce**
1. Open RemNote newly / refresh RemNote
2. Observe that Edit Later count is incorrect
3. Open Edit Later document
4. Edit Later count is now corrected

**Expected behavior**
Should display the count correctly as soon as RemNote is loaded

**Screenshots**

Upon opening RemNote / refreshing RemNote

![image](https://user-images.githubusercontent.com/68901589/92988981-ab7aeb80-f4e1-11ea-8c63-72fda76681b1.png)

After opening the Edit Later document

![image](https://user-images.githubusercontent.com/68901589/92988998-d1a08b80-f4e1-11ea-97c7-a72833936171.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
Related:
1. Issue #90 had been fixed with the new update but as of late, it seems to come up every now and then and RemNote needs to be refreshed for it to work again. It does stop working a while later.
2. Also seems like hidden rems don't automatically show up after loading anymore (Issue #46)

_All above issues including this one are related to **what takes place after freshly loading RemNote or refreshing** and all of these had been fixed with the new update._

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
