### ISSUE TITLE
The pdf file is blank.

### ISSUE THREAD

**Issue by raven975** [remnoteio/remnote-issues#1013]
**Describe the bug**

**To Reproduce**
The pdf file is blank.

**Expected behavior**
RemNote displays the contents of the pdf file normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/72459756/111456603-299aa200-8752-11eb-83d4-f6c359eea1c0.png)

**Desktop (please complete the following information):**
 - OS:macOS Big Sur 11.2.1
 - Browser:Chrome

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by mfranzs** [comment]
Thanks for reaching out. Is this all PDFs, or only some?

**Comment by raven975** [comment]
Only some.

张紫葳
2021年3月23日 +0800 09:02 Martin Schneider ***@***.***>，写道：

**Comment by drkvj** [comment]
merging with #902
