### ISSUE TITLE
Zoom Status Changes By Itself on MacOS App

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#1015]
**Describe the bug**
When I set a specific zoom status, e.g. 120%, and switch focus to a different window (of a different app), this value of zoom status is "forgotten", and RemNote switches to < 100% zoom (sometimes even super zoomed in like 180%).

**To Reproduce**
1. Set zoom status to 120%
2. Try hovering around / switching focus to a different window than that of RemNote
3. See that the zoom status changes at some point on it's own (either pretty zoomed out or in) and does not maintain the value that was set

**Expected behavior**
If I set zoom to 120%, I would like for it to stay at that instead of changing as soon as I switch windows or hover elsewhere.

**Desktop (please complete the following information):**
 - MacOS Big Sur
 - Desktop App
 - Version 1.2.9

**Comment by eohomegrownapps** [comment]
I've also encountered this -- see #883 and #897

**Comment by anishaaa1** [comment]
> I've also encountered this -- see 883 and 897

Thanks for letting me know, I'll close this to avoid duplicates :)
