### ISSUE TITLE
nonenglish language search issue

### ISSUE THREAD

**Issue by jparkgit** [remnoteio/remnote-issues#1019]
Whenever I search in Korean, an error occurs. 
There are no problems when searching in English.

![nzlwgH3XlK](https://user-images.githubusercontent.com/80691989/111800038-e9cce980-890e-11eb-9352-fbf87ada6bac.gif)
![image](https://user-images.githubusercontent.com/80691989/111800091-f7826f00-890e-11eb-8636-a473f4c99360.png)

**Comment by FuryMartin** [comment]
For the time being, you can press space before you enter non-English characters to avoid such crash.

**Comment by drkvj** [comment]
merging with #584
