### ISSUE TITLE
Practicing with Spaced Repetition Skips all Cards 

### ISSUE THREAD

**Issue by MantisTCO** [remnoteio/remnote-issues#102]
Whenever I'd pick to practice rem within a document using spaced repetition, the cards are ALL skipped and I instantly reach the end of my queue checkpoint. The site states that I've completed x amount of cards in 0 seconds.

1. Go to any of your documents
2. Click on the three dots ('...') on the top right 
3. Then click 'Practice the Rem in this document using spaced repetition'

**Expected behavior**
I am able to go through the queue of all my cards using the spaced repetition algorithm until I reach my daily goal.

![image](https://user-images.githubusercontent.com/71174174/92993476-88106a80-f4fa-11ea-8838-f6dbdd7e0c2c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: Chrome, Brave (both have the issue)
 - Version: Sept Update

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
