### ISSUE TITLE
RemNote pro subscription

### ISSUE THREAD

**Issue by kristenqin** [remnoteio/remnote-issues#1027]
**RemNote pro subscription by inviting my friends**
- I invited my friends successfully, and there are 12$ in my account now, but I don't know how to use them without paying via credit cards.
- ![image](https://user-images.githubusercontent.com/73811370/111938557-3712ac00-8b05-11eb-94e1-62b254e17ade.png)
- I don't know why this happens. Just very annoying that it is unable to use the pro function.
- ![image](https://user-images.githubusercontent.com/73811370/111938585-485bb880-8b05-11eb-8454-ae89d6a36273.png)

**Comment by Shubhgad** [comment]
u have to enter credit/debit card details to use pro function.... as u have $12 in ur account, no charges will be levied for 2 months. if u do not cancel the pro function after two months then u will be charged $6 per month in 3rd month

**Comment by kristenqin** [comment]
Thank you a lot :D!!! I will give it a try. 
And to say thank you for your help, I would like to share what I had found this afternoon which I thought should be one of the pro features, actually not! Maybe this can act as a remnote applied situation. I use the 'add search portal' to congregate all of the same tags to realize categorizing all of the questions rather than only use the tag power rem which I think is difficult to manage. Just type in the tag you've set, and then do the second pic shows, you will achieve this effect, I felt very excited that I can achieve it again, you know, I got this kind of effect just by coincidence the other days, for which I just wanted use it to present the same topics. 
I think this finding is very perfect!!! I just can't wait to share it with others. Hope you won't feel I am noisy.


&nbsp;
&nbsp;

秦颖欣
学策部干事
广东外语外贸大学 社会与公共管理学院 团委学生会
Youth League Committee &amp; Student Union
School of Politics &amp; Public Administration
Guangdong University of Foreign Studies
Tel：18803731374
***@***.***











 
&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月22日(星期一) 晚上6:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [remnoteio/remnote-issues] RemNote pro subscription (#1027)





 
u have to enter credit/debit card details to use pro function.... as u have $12 in ur account, no charges will be levied for 2 months. if u do not cancel the pro function after two months then u will be charged $6 per month in 3rd month

**Comment by mfranzs** [comment]
Thanks for reaching out, and thank you @Shubhgad for answering! This seems resolved.
