### ISSUE TITLE
[[mobile]] - Database run into problem..

### ISSUE THREAD

**Issue by TaQuangKhoi** [remnoteio/remnote-issues#103]
**Describe the bug**
I lost my data (rems i input when offline) with this problem..
Database error before I sync new rems with Remote server

**To Reproduce**
1. Go to 'RemNote' by press on icon 
2. Close RemNote
3. Open it again

**Expected behavior**
I do not want to lost my data..

**Screenshots**
![Screenshot_20200914-213637_RemNote](https://user-images.githubusercontent.com/45689286/93100334-3cfd7f80-f6d3-11ea-9d3a-7e94e8c95a10.jpg)

*Desktop (please complete the following information):*

**Smartphone**
 - Device: Samsung Galaxy J4+
 - OS: Android 9
 - RemNote app i downloaded on Play Store

**Additional context**
Number of rem: > 50.000 rems
Take many time to load all of that

**Comment by mfranzs** [comment]
Thanks for the report. Are you sure that this data was lost? If so, how many minutes of editing was this? The app should have been saving to the local database before it synced.

**Comment by TaQuangKhoi** [comment]
Yea.. i just lost about 10 rems..
Local database runs into problem so i press Refresh button and it deleted all data after that it download rems again from Server..

Sometimes i still have this problem..

**Comment by TaQuangKhoi** [comment]
[[September 25th 2020]]
i open RemNote Mobile App, it shows a white blank screen.. Wait but it does not run..
i quit it and open it again.. so it's Syncing and Storing all rems again from Server..

**Comment by kareldries** [comment]
Same for me, it does not run on Android at all, I get a blank screen. The October 6 update didn't change this unfortunately.

**Comment by mfranzs** [comment]
@kareldries Would it be possible to check the version of the installed app? Do you see version 0.0.10?

**Comment by kareldries** [comment]
> @kareldries Would it be possible to check the version of the installed app? Do you see version 0.0.10?

It was version 0.0.9, I uninstalled and after reinstalling it, it says version 1 and works fine.
Must be a new version in the store then.

Thank you
