### ISSUE TITLE
Error: No se puede resolver un punto DOM desde el punto Slate: {"path": [0,0], "offset": 2} . URL: https://www.remnote.io/document/xBXZ6uZNPm65aAssq

### ISSUE THREAD

**Issue by RenatoDav** [remnoteio/remnote-issues#1031]
Error: No se puede resolver un punto DOM desde el punto Slate: {"path": [0,0], "offset": 2} . URL: https://www.remnote.io/document/xBXZ6uZNPm65aAssq

**Comment by drkvj** [comment]
merged with : #893
