### ISSUE TITLE
Text gets select even though it shouldn't

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#1039]
**Describe the bug**
It acts like I'm pressing and holding when I'm not. This results in text constantly being selected when I click around

**To Reproduce**
Didn't do anything special, been like that ever since the most recent update

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/112238575-37b25c00-8c45-11eb-9816-b5071deb1b9c.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.4.1
 - Browser safari (PWA)
 - Version 14

**Comment by lll637637** [comment]
I also encountered the same problem

**Comment by Deng-Jiajun** [comment]
我也遇到了同样的问题

**Comment by Deng-Jiajun** [comment]
I also encountered the same problem

**Comment by Echology88** [comment]
I'm also against this default huge change of text selecting. It seems that a new click (together with the position of your last click) will select a whole bulk of rems. If this is a new feature that is intended to do so, remnote should offer a botton to toggle it on/off.

**Comment by Hellogordon** [comment]
It is fixed for me, thanks Devs! :)
