### ISSUE TITLE
Setting not saving

### ISSUE THREAD

**Issue by matleonii** [remnoteio/remnote-issues#104]
**Describe the bug**
Everytime I open remnote the "Show Hidden Children Stubs" setting is marked again, even if I uncheck it every time

**To Reproduce**
uncheck the "Show Hidden Children Stubs"
Restart brower
Open Rem note

**Expected behavior**
To have the settings the way I left

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser firefox
 - Version latest

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
