### ISSUE TITLE
Code block resizes on hovering the cursor

### ISSUE THREAD

**Issue by akhiln28** [remnoteio/remnote-issues#1040]
**Describe the bug**
When you hover cursor on the code block, it resizes with jerky movements. 
**To Reproduce**
1. First create a code block. 
2. Create few lines and also some empty lines (no text)
2. Hover your cursor on the code block

**Expected behavior**
The code block should not resize in a jerky way. 
**Screenshots**
Please watch this video for more clarity. 
[video](https://1drv.ms/v/s!AkWQ7hDTMBKoiPMqr6TJTOybVeMNgA)
**Desktop (please complete the following information):**
- on mac os big sur
- sometimes in web as well

**Comment by hannesfrank** [comment]
Custom CSS fix:

```css
#code-node .codeLine:after {
  content: " ";
  visibility: hidden;
}
```

**Comment by akhiln28** [comment]
Thanks for the help. I don't see the issue for newly created blocks after adding the custom css.
