### ISSUE TITLE
RemNote 1.3.4 bug - page automatically goes up

### ISSUE THREAD

**Issue by aakkino** [remnoteio/remnote-issues#1041]
![QQ录屏2021032417022720213241741151](https://user-images.githubusercontent.com/37200028/112327173-296d4a00-8cf0-11eb-8f8d-8f445d22fc64.gif)

**Comment by mfranzs** [comment]
Thanks for reaching out. Do you notice any pattern among the documents where this happens?

**Comment by Gabriela-AD** [comment]
Corresponding Forum [Report](https://forum.remnote.io/t/remnote-1-3-4-bug-page-automatically-goes-up/3514?).

TL:DR so far:
> When I use the split screen, usually only one of the two pages have this problem ( specifically the one that I opened last, while the other one is fine).
To explore.
> It happens when you have text cursor in the document’s title.
> turn off setting - interface - sticky header
Replicated. Having Sticky Header enabled and the cursor in that position does trigger this bug.
Unsure if it triggers regardless of cursor position as well yet.

**Comment by aakkino** [comment]
i

> Thanks for reaching out. Do you notice any pattern among the documents where this happens?

it's been repaired in ver 136，thx
