### ISSUE TITLE
Firefox: Sidebar Menu hover bug in Help Space

### ISSUE THREAD

**Issue by JohannesKaufmann** [remnoteio/remnote-issues#1044]
https://user-images.githubusercontent.com/20886667/112487162-cd9cd280-8d7c-11eb-9504-d4e292f60390.mov

- happens in Firefox Developer Edition (works fine in Chrome)
- happens in the Help Space (no problem in personal workspace)

In order for the items in the sidebar to be **discoverable**, I would actually propose that the sidebar _always stays open_.

**Comment by drkvj** [comment]
@JohannesKaufmann has this been fixed? I think the sidebar has been reworked after that

**Comment by JohannesKaufmann** [comment]
@drkvj good catch! Yes it's not happening anymore 👍
