### ISSUE TITLE
TypeError: Cannot read property 'CUSTOM_REM_TYPE_NAME' of undefined.

### ISSUE THREAD

**Issue by anna-anisienia** [remnoteio/remnote-issues#1046]
I keep experiencing the following error in my Windows Desktop app (RemNote Pro-version):

```
Something went wrong.

Please try refreshing the page. If the problem remains, please provide additional detail on the help page.

TypeError: Cannot read property 'CUSTOM_REM_TYPE_NAME' of undefined. URL: file:///C:/Users/AAnisienia/AppData/Local/Programs/RemNote/resources/app.asar/build/two-documents-rKnG4SGTkwDRhj8XC-P96nCviFEEfZc4KTt
```

![image](https://user-images.githubusercontent.com/38731223/112558257-9d7e1f80-8dce-11eb-8e34-2e865023c47f.png)

The error appears when performing a search. Either when I try linking another Rem using [[Reference]] or when performing a global search.

Could it be because I've recently created my first template and it messes up with indexing?

**Comment by luke-nehemedia** [comment]
I have the same issue when I either search for a rem (using `cmd+P`) or just try to link to a rem (using `[[`) I get an error when I type in "su". 

In my case this happens in the Mac app. 
In the browser everything works fine and as expected. 

And I do not (yet) use templates.
