### ISSUE TITLE
A rem hits in search but the rem is not there

### ISSUE THREAD

**Issue by akiorange** [remnoteio/remnote-issues#1048]
**Describe the bug**
In my case, "Mode" rem (and several other rems) hits in search result (using Command + P) and it tells "Mode" rem in "Statistics" document. However, "Mode" rem doesn't show up in the "Statistics". I can't find "Mode" anywhere else in RemNote.

**To Reproduce**
I couldn't reproduce this issue but this is the second time I experienced this behaviour. In both case, this happened under the following condition.
1. Select rem(s) using Shift + arrow key
2. Rem seemed to disappear when I'm moving the rems using Alt + arrow key

**Expected behavior**
The rems show up in the Document.

**Screenshots**
![ezgif-7-106b35b94a03](https://user-images.githubusercontent.com/44665462/112584458-3a76a200-8e3b-11eb-864b-7c66abbe91c7.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2.3 (20D91)
 - Browser Chrome
 - Version 89.0.4389.90 (Official Build) (arm64)

**Smartphone (please complete the following information):**
None

**Additional context**
- There is no other rems whose name is "Statistics" in my RemNote.
- I accessed  to [Trash can](https://www.remnote.io/trash) but couldn't find "Mode" and other disappeared rems.
- I turned off Custom CSS but it didn't solve this issue.
- I searched from several rems but it didn't change the behavior.
- Why "Statistics" has currently no rems is I moved all rems using Command + A and cut and paste to another locations, so that it's clear "Mode" is not there. This issue was happening before I moved the all rems so it shouldn't affect the issue's behavior.
- [Bug discussion](https://forum.remnote.io/t/rems-hit-in-search-but-dont-show-up-in-the-result-page/3561) opened on RemNote Forum.

**Comment by akiorange** [comment]
I could found two of disappeared rems. I'll call them rem 1 and rem 2.
- Rem 1 showed up while practicing flash cards in the queue, so I clicked "Edit this rem now" and I could access that rem.
- Rem 2 showed up in the documents list page which can be accessed via "Documents" on the sidebar.

I've accidentally moved rem 1 to another location. So I couldn't investigate much about rem1.
Here is a couple of screenshots about rem 2, which is a rem "Median".

- Image 1
![Screen Shot 2021-03-27 at 9 46 26](https://user-images.githubusercontent.com/44665462/112706305-c5f93d00-8ee6-11eb-9d9e-3ac316775565.png)
- Image 2
![Screen Shot 2021-03-27 at 9 47 14](https://user-images.githubusercontent.com/44665462/112706307-c85b9700-8ee6-11eb-8422-70751eb49d98.png)


Few things I noticed:
- (Shown in image 1) "Median" don't have a parent rem, i.e., it is (or at least seems like) top-level rem now whereas it had "Statistics" as a parent rem before disappeared. This was the same for rem 1 as well.
- (Shown in image 1) "Statistics" is listed in "In 1 Document" portal of "Median", but "Median" doesn't appear in "Statistics".
- (Shown in image 2) If I search "Median" via Command + P, it tells "Median" is in "Statistics".

Issue #927 might be related.

**Comment by akiorange** [comment]
Sorry to be long. I noticed several additional things while experimenting with Rem Reference using [[.
Using this, I could access to the all disappeared rems via the following steps:
1. Search for a disappeared rem using [[ 
2. Create a rem reference for the disappeared rem
3. Click the reference, then "Open Rem as Document"

Things I noticed:
- The things in "Few things I noticed" in my previous post are true for the all disappeared rems.
- The search results of Command + P and [[ are different as the following:
  - (Shown in image 3) Command + P search shows "Statistics" as a parent rem.
  - (Shown in image 4) [[ search doesn't show a parent.

- Image 3
![Screen Shot 2021-03-27 at 12 29 28](https://user-images.githubusercontent.com/44665462/112708875-2d6bb880-8ef8-11eb-9b56-fb331a416f44.png)
- Image 4
![Screen Shot 2021-03-27 at 12 28 47](https://user-images.githubusercontent.com/44665462/112708882-352b5d00-8ef8-11eb-8734-c2cfca19824a.png)

**Comment by drkvj** [comment]
You are amazing, love the level of detail you have given here. Kindly port all this info to the bug discussion on the forum as well, I will keep this issue closed here temporarily until we can replicate the issue. Thank you for the report. Let's catch up on the forum.
