### ISSUE TITLE
Search witch compound words

### ISSUE THREAD

**Issue by sdnnvs** [remnoteio/remnote-issues#105]
**Describe the bug**
The search for compound words, for example, "palavras-chave", "guarda-roupas", are not found, while the words "palavras", "chave", "guarda" and "roupas" are found.

**To Reproduce**
1. Make a document containing the text "palavras-chave".
2. In another document, create a search portal and include the compound word "palavras-chave", with or without "".
3. See the results with "palavras", "-", "chave" and "palavras-chave".
4. The document with the compound word "palavras-chave" does appear, but not "palavras", "chave" or "-".

**Expected behavior**
The search is expected to find the compound word "palavras-chave", however, the search returns "palavras-chave", "palavras", "-" and "chave". The document with the compound word "palavras-chave" does appear, but not "palavras", "chave" or "-".

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: [MacOS Catalina, 10.15.6
 - Browser Chrome 
 - Version 85.0.4183.102 64bits

**Additional context**
-

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
