### ISSUE TITLE
Not all questions come in spaced repetition

### ISSUE THREAD

**Issue by atmi517** [remnoteio/remnote-issues#1050]
When I create a question for spaced repetition, especially when I create my concept and descriptors when I revise with the dropdown option some times I give three colon for the concept so the descriptors below will come for spaced repetition. when when I practice the document for spaced repetition it does not come for study.

**To Reproduce**
1. Go to 'a concept with children below as bullets'
2. Click on 'put 3 colon for making spaced repetition card '
3. Take Practice rem of the concept made 
4. The concept doesn't come for revision multiline item card with three colon

**Expected behavior**
After making note,  I want to be able to make spaced repetition with multi line card by putting 3 colon so it comes as spaced repetition while practicing document.

**Desktop (please complete the following information):**
 - OS: [ windows 10
 - Browser [chrome ] , App for windows 10
 

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by hugomarins** [comment]
As I understand it, the 3 colons work when you do not have yet the bullets that you want to appear in the multiline card. Just after typing :::, a new child bullet will be created just below; pressing enter will create the subsequent bullets that are part of the multiline card.

But if the children bullet are already there, as you mentioned, and you realize that turning those bullets (your descriptors) into a multiline card would be a good idea, you will have to select the children bullet that you want to turn in a multiline card and then select on the right extremity of the footer the bullet icon and, inside it, the box icon ("Multiline card item"), as shown below:

![image](https://user-images.githubusercontent.com/54500828/112619059-9aeaec80-8e05-11eb-82a7-2817d64fb657.png)

Look that the line joining the children bullet to its parent is now of a dark color, indicating they compose a multiline card:

![image](https://user-images.githubusercontent.com/54500828/112619220-cff73f00-8e05-11eb-8427-9a1f73ecff4c.png)

**Comment by atmi517** [comment]
Thankyou🧡🧡💛💛🥰🥰🥰....Great work by the team by the way...Thankyou so
much.....

Midhun R

**Comment by drkvj** [comment]
@hugomarins awesome as always. Thank you for tackling this.
