### ISSUE TITLE
RemNote search crash when I input Chinese Chars

### ISSUE THREAD

**Issue by maoqiuzi** [remnoteio/remnote-issues#1053]
**Describe the bug*
When I try to search using cmd+p, it crashes when I input Chinese characters. This happens almost 50% of the times.

However it’s strange if I hit cmd+c, and then input some English chars, then I can input Chinese characters.
*

**To Reproduce**
1. cmd+p
2. input any chinese charactors using mac os chinese input method
3. See error

**Expected behavior**
display searched docs

**Screenshots**
<img width="849" alt="截屏2021-03-26 下午9 39 18" src="https://user-images.githubusercontent.com/1918427/112710188-78e08100-8e7c-11eb-90ea-bf673dc5f61a.png">
<img width="911" alt="截屏2021-03-26 下午9 38 54" src="https://user-images.githubusercontent.com/1918427/112710186-7716bd80-8e7c-11eb-80b9-9a0f925efe25.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 89.0.4389.90

**Additional context**
Actually I found it happens universally on all RemNote surfaces.

**Comment by lll637637** [comment]
This problem has troubled me for a long time. Software developers can download the Chinese input method for testing：https://srf.xunfei.cn/

**Comment by lll637637** [comment]
Many Chinese users are troubled by this problem, it is recommended to fix it as soon as possible

**Comment by backwind1233** [comment]
⭕️⭕️⭕️❌❌❌
It has a long history.

**Comment by drkvj** [comment]
merging with #584
