### ISSUE TITLE
Updating your account (0/1644)

### ISSUE THREAD

**Issue by awreccan** [remnoteio/remnote-issues#1055]
**Describe the bug**
Same as #1004.
On the left sidebar, I can click Documents and see all my Documents in the main page, but the Side Panel itself is stuck with a never ending spinner.
**Chrome Android**: The text under the spinner is "Loading" and "Updating your account (0/1644)". No progress, stuck at 0.
**Android app**: The only text under the spinner is "Loading". No progress, stuck at 0.

**To Reproduce**
- Go to Side bar menu
- See error

**Expected behavior**
I expect progress in the spinner. I expect the Loading to finish.

**Screenshots**
![](https://user-images.githubusercontent.com/80691989/111158004-e4a02f80-85da-11eb-8298-48aa9f055ab7.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T
 - OS: OxygenOS 10, Android 10
 - Browser: Chrome Android v 89.0, as well as RemNote Android app v0.167

**Additional context**
Chrome Android: I cleared cookies and logged out/in - problem persists.
Android app: Cleared cache, storage, reinstalled app - problem persists.

**Comment by chadkennedyonline** [comment]
I'm seeing the same issue. Please post back when you figure out how to fix.
