### ISSUE TITLE
Sync has stopped working on all platforms

### ISSUE THREAD

**Issue by dcoales** [remnoteio/remnote-issues#1059]
**Describe the bug**
Sync has stopped working and hasn't been working for the last half hour on all platforms:

- Edge on Windows,
- Android web browser
- Android app
- Chrome on Chromebook

When I look in the DevTools console I'm getting the following error repeatedly.

ghnGWu7oK5w5Jbuy4:1 Access to XMLHttpRequest at 'https://sync2.remnote.io/sync/knowledge_base_data' from origin 'https://www.remnote.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Server Error
(anonymous) @ 2.e5b53b5b.chunk.js:1
overrideMethod @ react_devtools_backend.js:2430
value @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
2.e5b53b5b.chunk.js:1 Error: Network Error
    at e.exports (2.e5b53b5b.chunk.js:1)
    at XMLHttpRequest.f.onerror (2.e5b53b5b.chunk.js:1)
    at XMLHttpRequest.n (2.e5b53b5b.chunk.js:1)
(anonymous) @ 2.e5b53b5b.chunk.js:1
overrideMethod @ react_devtools_backend.js:2430
value @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
2.e5b53b5b.chunk.js:1 POST https://sync2.remnote.io/sync/user_data net::ERR_FAILED
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
e.exports @ 2.e5b53b5b.chunk.js:1
e.exports @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
c.request @ 2.e5b53b5b.chunk.js:1
n.forEach.c.<computed> @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
B @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
(anonymous) @ main.9d626100.chunk.js:1
u @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
(anonymous) @ 2.e5b53b5b.chunk.js:1
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
c @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
Promise.then (async)
n @ 2.e5b53b5b.chunk.js:1
s @ 2.e5b53b5b.chunk.js:1
ghnGWu7oK5w5Jbuy4:1 Access to XMLHttpRequest at 'https://sync2.remnote.io/sync/knowledge_base_data' from origin 'https://www.remnote.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by prodeveloper** [comment]
Same problem thou mine been going on for much. longer on mobile

**Comment by badjerphoenix** [comment]
I have the same issue as above
Same lines of errors as well
Won't paste in second time since you already have the lines

On top of the Browsers above listed add Brave on to the list

Cannot sync Kbs via any device or platform
Issue been going on for about 2 hrs now

Initially via desktop I had access but could not shut down
Presumably since it could not sync
In last 30 min Desktop has also lost access though still cannot close

I can access via web but no items have been synced
According to web app last sync 2 days ago

**Comment by badjerphoenix** [comment]
Now when I am on the web I cannot even view anything even if I am in the document table
![image](https://user-images.githubusercontent.com/78933852/112738289-290ac400-8f27-11eb-9fe0-5f4d9201d53c.png)
