### ISSUE TITLE
Queue cards not displaying consistently/correctly

### ISSUE THREAD

**Issue by newageoflight** [remnoteio/remnote-issues#106]
# Bug

Sometimes queue cards will (improperly) display like this, especially after clicking any of the review buttons (K, L or ,):

![image](https://user-images.githubusercontent.com/33755603/93153458-a1a4f280-f744-11ea-898c-ae56b66a5ee6.png)

It should also be noted that in such instances the reviewer is treating the entire document as a set card for some reason.

# Expected behaviour

![image](https://user-images.githubusercontent.com/33755603/93153562-e03aad00-f744-11ea-8f92-d81d8b4fb1f9.png)

**Comment by mfranzs** [comment]
Thanks for the report. This card is an experimental "Document Card" - if you'd rather not have them, you can disable them in your settings by unchecking the "Document Card" setting.
