### ISSUE TITLE
Too long scheduling  intervals (Anki SM-2 shceduler)

### ISSUE THREAD

**Issue by hugomarins** [remnoteio/remnote-issues#1062]
Wherever I review my cards (web, Desktop v. 1.3, mobile), the scheduling intervals are getting too long, not following the expected behavior (https://www.remnote.io/p/help/document/8g5xHDmGSotpAR9Pc).

The following card, for example, has a 2 months interval and an ease of 2.3.

![image](https://user-images.githubusercontent.com/54500828/112756636-7e44e500-8fbc-11eb-9e04-5515a5117923.png)

I would expect, when pressing Solid, an interval of 2 * 2.3 * 100% (my interval modifier was not changed from the standard 100%), that is, 4.6 months. But instead, I got 1.1 years, much longer than expected, putting me at a great risk of forgetting the material.

![image](https://user-images.githubusercontent.com/54500828/112756683-c106bd00-8fbc-11eb-9429-f3caec5ae869.png)

![image](https://user-images.githubusercontent.com/54500828/112756771-10e58400-8fbd-11eb-8753-ee2474a6ef00.png)

I've already given other examples in #639. This is messing up my knoledge base.

**Comment by hugomarins** [comment]
Another example of how strangely and wrongly scheduler is behaving:

The card below has 1 month interval and ease of 2.5.

![image](https://user-images.githubusercontent.com/54500828/112759668-72f8b600-8fca-11eb-844b-0bc2ae32f43d.png)

But pressing Solid will give, instead of something about 2.5 months, 1.4 years! An interval 6x longer then what is expected!

![image](https://user-images.githubusercontent.com/54500828/112759706-99b6ec80-8fca-11eb-99ed-d00d7f2d080f.png)

Another problem: when using /data to view the card's history, "scheduled interval" and "next repetition time" are rounded to entire year (hear they show "a year" instead of 1.4 years. I think it would be important to show the fraction or, yet better, year and months.

![image](https://user-images.githubusercontent.com/54500828/112759779-eef2fe00-8fca-11eb-8d54-7d5a6def03b9.png)

**Comment by hugomarins** [comment]
I was trying to hit "Hard" as a workaround untill the team solve the scheduler problem, but sometimes even this is not possible.

The following card has a 3 month interval, and its ease is 2.15.

![image](https://user-images.githubusercontent.com/54500828/112770061-15c92880-8ffb-11eb-93d5-64ce73624680.png)

**Pressing "Solid"** should return and interval of about 6 1/2 months, but behold, **the proposed interval is 10x longer**!!! 5 years (restrained by maximum interval, otherwise would be more). **Even pressing hard would give an interval of 3.3 years (about 6 x longer than the "Solid" should be)**!

![image](https://user-images.githubusercontent.com/54500828/112770211-faaae880-8ffb-11eb-85a3-0badaf97695c.png)

I confess I would expect a faster and more prone response of the team to a problem that big (at least for me). I'm pretty sure it is in the best interest of the company!

Thanks!

**Comment by mfranzs** [comment]
Thanks for reaching out. I've been having some trouble reproducing this issue. 
1. Can you please send over a screenshot of the bottom of your scheduler settings? (Is it still the same as the screenshot in #639?)
2. If it contains no private information, could you please export the "MIGUENS 14 - Radar" folder as raw JSON and email the output to support@remnote.io? 
3. Am I right in understanding that these issues are only appearing on some cards, and not all? Do you notice any pattern with the issues, ex. if it's consistently the same cards, consistently old cards, or right after you refresh?
4. Have you left your scheduler on the "Anki-SM2" setting, or switched to the default scheduler at all?

**Comment by hugomarins** [comment]
Hi @mfranzs , thanks for looking at this issue!
I'll answer your points below:
>Can you please send over a screenshot of the bottom of your scheduler settings? (Is it still the same as the screenshot in #639?) 

If it contains no private information, could you please export the "MIGUENS 14 - Radar" folder as raw JSON and email the output to support@remnote.io?
I sent it in an email to you.

>Am I right in understanding that these issues are only appearing on some cards, and not all? Do you notice any pattern with the issues, ex. if it's consistently the same cards, consistently old cards, or right after you refresh?

Yes, probably not all cards; many cards, but not all. Old cards show it more frequently. This document I exported to you now is my first deck of cards (first document) in RemNote, as soon as I discovered it. I don't know if these cards are having the problem very frequently because they are old or because their intervals are already somewhat large.
But I also noted this problem in newer cards, and most of the times I have to press "Hard" to get an interval similar to that that was supposed to be the one when pressing "Solid". Sometimes the intervals are very very long, as in the cards I've already shown you.

>Have you left your scheduler on the "Anki-SM2" setting, or switched to the default scheduler at all?

In the beginning, I unwittingly turned to "Anki-SM2" setting. When I observed the problem, I switched back to the default. By now, I still use Anki-SM2, especially because I want initial larger intervals (I have already a good number of cards in RemNote, besides thousands of already overdue cards in Anki, and I felt the need of adopting an strategy more aggressive in initial intervals to avoid a hell in my queue). I try to manage my documents in such a way that when they pass the learning phase and the first review (when I start to see some crazy long intervals), I switch it back to the default.
So, I basically use the default for the Global Default Scheduler, but set new documents to a custom scheduler (Anki-SM 2) until the initial learning phase is complete, switching them back to the default later.
I can tell you that I switched back and forth between the default and Anki-SM2 settings a number of times (maybe it may have caused sth wrong in my database).

**Comment by mfranzs** [comment]
Thanks, this info is helpful!

1. When you see a excessively-long interval, can you please check if the interval returns to normal after a page refresh? I've been trying to replicate the long intervals in the backup that you sent, and also haven't been able to do so. I'm wondering if there's some strange edge case here.
2. Can you please confirm that all of your devices are on the latest version of the app? (Web, Mobile, and Desktop)?

**Comment by hugomarins** [comment]
@mfranzs , as far as I know, the devices are all on the latest version of the app.

On the desktop version, version 1.3.6:

![image](https://user-images.githubusercontent.com/54500828/114335142-87889280-9b22-11eb-9962-2308032e8a3a.png)

On my android app (that I don't use much) it says version 0.168:

![SmartSelect_20210412-000608_Google Play Store](https://user-images.githubusercontent.com/54500828/114335320-e51cdf00-9b22-11eb-9220-9279fd53a231.jpg)

Is there a way of finding out the version of the Web app? There is no this info in Settings > Account. Isn't it updated by refreshing? I do it regularly. If there is a way of knowing the version of the Web app, please let me know.

About the excessively-long intervals, I changed the Scheduler to the Anki SM-2 type, and from that document I sent you, the only due card was this:

![image](https://user-images.githubusercontent.com/54500828/114335918-2feb2680-9b24-11eb-938b-3513d773abd8.png)

The metadata says it was rated early yesterday. As I never cram or rate cards early (I only review cards that are due on my queue), I assumed a pressed the "h" bottom (show me in one hour).

Anyway, the card (that had already a 2 months interval), appeared in my queue again today (Desktop app), and, as I showed, pressing solid would give a 1.8 years interval (as the previous interval was 2 months and the ease 2.3, the interval should be about 5 months).

![image](https://user-images.githubusercontent.com/54500828/114335049-3a0c2580-9b22-11eb-9215-0ceaacbfb63f.png)

I did not rate, closed the Desktop App and opened it again, and nothing changed (the same 1.8y interval for solid was shown).

I closed the Desktop app without rating the card, and opened the Web app. It was also showing 1.8y interval:
![image](https://user-images.githubusercontent.com/54500828/114336731-f6b3b600-9b25-11eb-9aa0-2ebb83c6d2ce.png)

I refreshed the page, and nothing changed. 

Tried then the Mobile Android version. It still showed 1.8y interval:
![Screenshot_20210412-003249_RemNote](https://user-images.githubusercontent.com/54500828/114337026-ab4dd780-9b26-11eb-9565-b8e76dfbb2cf.jpg)

Finally I opened the **beta Web App**, and **now things really changed**:

![image](https://user-images.githubusercontent.com/54500828/114336885-55792f80-9b26-11eb-8a1c-d51dbed51ab2.png)

Look that the beta version showed the correct interval. But my joy didn't last long. I rated the card in the beta Web App, but when I went to the metadata to check, I saw that **the real interval scheduled was not the correct one showed only in the beta version, but a 2 years interval**!!!

![image](https://user-images.githubusercontent.com/54500828/114337420-74c48c80-9b27-11eb-8aeb-9a01b547bcca.png)
![image](https://user-images.githubusercontent.com/54500828/114337498-90c82e00-9b27-11eb-9e0f-a1f9ef8027b9.png)

I sent the entire database to you (just in case).

Thanks!

**Comment by hugomarins** [comment]
@mfranzs, another example from that same document I sent you before.

In the Windows Desktop app (1.3.6):

![image](https://user-images.githubusercontent.com/54500828/114436987-606ea700-9b9c-11eb-94ff-8413770f223f.png)

This card had an interval of 1 month and an ease of 2.15. I'm rating it in the target day. So, the interval for solid should be a little longer than 2 months.

But the interval shown when rating was:

- 9.1 months in the Desktop App (1.3.6) (the same after reloading):

![image](https://user-images.githubusercontent.com/54500828/114437071-75e3d100-9b9c-11eb-87a1-3ebc23e5f480.png)

- Initially 2.9 months in the Web app (not beta, the normal one) (it was correct here!). The print I got was incorrect (can't show the image).

But after reloading the page, the wrong long interval again:

![image](https://user-images.githubusercontent.com/54500828/114436297-89db0300-9b9b-11eb-9696-ef68f2237349.png)

- 9.1 months in the Beta Web app also (even after refreshing):

![image](https://user-images.githubusercontent.com/54500828/114436448-b68f1a80-9b9b-11eb-9b22-1d719b28f4f9.png)

The intervals are always wrong for me. If you try to load the exported database I sent you, change the global scheduler to Anki SM-2 type and open the queue of this specific document (shown below), maybe you will be able to replicate this behavior.

![image](https://user-images.githubusercontent.com/54500828/114436649-f7872f00-9b9b-11eb-8199-324aaf1fb20c.png)

Let me know if it worked.

Thanks!

**Comment by mfranzs** [comment]
Thanks again for all of the help! The full database backup enabled me to reproduce the issue, and I believe that I've found the underlying issue here. A fix has been implemented and pushed to the Beta server - could you please try that server and check if it's working for you now?

If you're curious, here's more info:

Our scheduler wasn't initially designed for frequent switching between scheduler settings. This led to an edge case that you stumbled upon:
Let's imagine a very simple scheduler that only multiples the intervals by X each time.
1. You created a lenient scheduler with a "2x" multiplier.
2. You practiced a card with this scheduler 5 times. You're now up to an interval of 2^5 =32
3. You switched the scheduler to a "3x" multiplier"
4. Our scheduling algorithm now (foolishly!) tried to compute what the new interval _should have been_ given your history of replies. It doesn't compute 2^6, but instead computes 3^6= 729.  

I've updated the scheduler to use the _true previously scheduled intervals_ instead of re-computing them. In my example above, this would now yield a new interval of 3*2^5, rather than 3*3^5. 

(Switching from a "3x" scheduler to a "2x" scheduler in my example above would have been fine due to some "days late" logic, which is why this didn't get caught earlier in testing.)

(This is a slight simplification, but roughly what happened.)

Thanks again, and please let me know if the beta server is looking better to you now!

**Comment by hugomarins** [comment]
Thanks @mfranzs, I'm very glad you found the issue. I'll certainly try how things are going in the beta server, and I'll report to you how things are. Thanks a lot and, once more, congratulations for you terrific job in RemNote!

**Comment by mfranzs** [comment]
Thanks again for all of the help! The full database backup enabled me to reproduce the issue, and I believe that I've found the underlying issue here. A fix has been implemented and pushed to the Beta server - could you please try that server and check if it's working for you now?

If you're curious, here's more info:

Our scheduler wasn't initially designed for frequent switching between scheduler settings. This led to an edge case that you stumbled upon:
Let's imagine a very simple scheduler that only multiples the intervals by X each time.
1. You created a lenient scheduler with a "2x" multiplier.
2. You practiced a card with this scheduler 5 times. You're now up to an interval of 2^5 =32
3. You switched the scheduler to a "3x" multiplier"
4. Our scheduling algorithm now (foolishly!) tried to compute what the new interval _should have been_ given your history of replies. It doesn't compute 2^6, but instead computes 3^6= 729.  

I've updated the scheduler to use the _true previously scheduled intervals_ instead of re-computing them. In my example above, this would now yield a new interval of 3*2^5, rather than 3*3^5. 

(Switching from a "3x" scheduler to a "2x" scheduler in my example above would have been fine due to some "days late" logic, which is why this didn't get caught earlier in testing.)

(This is a slight simplification, but roughly what happened.)

Thanks again, and please let me know if the beta server is looking better to you now!

**Comment by mfranzs** [comment]
(Note that this might take another 1/2 an hour to appear on the Beta server - sorry for my early signal.)

**Comment by hugomarins** [comment]
That's ok. I noted that the beta wasn't updated yet and imagined it would take some time. Thanks again!

**Comment by mfranzs** [comment]
(I'll post a message here when it's updated for real - might take longer than expected.)

**Comment by mfranzs** [comment]
(Live now.)

**Comment by hugomarins** [comment]
Thanks @mfranzs, I'm already trying, and it looks like (so far) that the specific subject of this post is solved.

As you are already dealing with the scheduler, I would sugest you looking at #1067, regarding ease being changed (when pressing Hard, Forgot or Easy) during the learning phase. I noted this is still happening:

![image](https://user-images.githubusercontent.com/54500828/114462153-0f20e080-9bb9-11eb-9856-7d0440ecdc1f.png)

**Comment by hugomarins** [comment]
I've been testing for a few days and everything looks to be working as supposed. Thanks @mfranzs for correcting this!
