### ISSUE TITLE
Unable to Delete Local Knowledge Base

### ISSUE THREAD

**Issue by NukeyFox** [remnoteio/remnote-issues#1065]
Description:
A local Knowledge Base does not delete when following the typical steps of deleting a knowledge base. The Knowledge Base continues to show up in any lists of Knowledge Base. The Knowledge Base and all its documents are still accessible.

1. Starting from any open Knowledge Base, including the one to be deleted.
2. Open Settings > Knowledge Bases
2. Go to a select a knowledge base and click the three dots. In my case the knowledge base is called "Databases".
3. The Update Local Knowledge Base panel should appear. Click Delete Knowledge Base.
4. A pop-up "Are you sure you want to delete this Knowledge Base? This CANNOT be undone." will appear. Click OK.
5. A panel will show up asking to input the name of the Knowledge Base. Type the name (in my case "Databases") and click Submit.

Expected behavior:
The mentioned Knowledge Base should be inaccessible and no longer show up in any list of Knowledge Bases.

Desktop
 - Windows 10
 - Using the downloaded Remnote app for Windows
 - Remnote version 1.3

**Comment by mfranzs** [comment]
Thanks for reaching out. I'm having some trouble reproducing this. What happens after step 6?

**Comment by NukeyFox** [comment]
> Thanks for reaching out. I'm having some trouble reproducing this. What happens after step 6?

Thanks for the reply. I believe the problem has been resolved in the latest update.
