### ISSUE TITLE
Backup stopped working in desktop about a month ago

### ISSUE THREAD

**Issue by ognsya** [remnoteio/remnote-issues#1069]
**Describe the bug**
No new backups created since beginning of March. Several users reported this already. 
This is very worrying.

This was reported a while ago here, but it seems there was no report done in Github:
https://forum.remnote.io/t/no-local-daily-backups-anymore/3269/4

**Desktop (please complete the following information):**
Windows
This is true for current and all previous versions since beginning of March.

**Comment by ognsya** [comment]
A backup appeared for March 30th (first one since March 5th).

File size is dramatically different - it was 2MB before, and now its 42kb, even though I haven't deleted any Rem since.

Is this all compression?

**Comment by ognsya** [comment]
(I deleted a comment I made earlier due to incorrect information)

**Comment by drkvj** [comment]
To update on the forum once it is fixed. Link here : https://forum.remnote.io/t/no-local-daily-backups-anymore/3269?u=karthikk
