### ISSUE TITLE
Latex picture overlapped with the latex expression 

### ISSUE THREAD

**Issue by wangsen992** [remnoteio/remnote-issues#107]
**Describe the bug**
When inputting a rather long latex expression, the generated picture for the expression will cover up some portion of the latex source, making it hard to edit the formula. 

**To Reproduce**
1. Go to any rem
2. Input '\latex' then put in this expression 
`\frac{\partial \overline{p^2/2}}{\partial t} + \overline{U_j}\frac{\partial \overline{p^2/2}}{\partial x_j} = -\overline{u_j p}\frac{\partial \overline{P}}{\partial x_j} - \frac{\partial \overline{p^2u_j}/2}{\partial x_j} + k\overline{p\frac{\partial^2 p}{\partial x_j \partial x_j}}`
3. See the outcome (in screenshots)

**Expected behavior**
The generated picture should not cover the source, allowing interactive editing of the latex formula.

**Screenshots**
<img width="710" alt="Screen Shot 2020-09-15 at 11 26 24 AM" src="https://user-images.githubusercontent.com/6318958/93161972-4c69e080-f746-11ea-8399-cad6faced2b0.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]:  MacOS Catalina
 - Browser [e.g. chrome, safari] : Brave
 - Version [e.g. 22] : 1.11.104

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
