### ISSUE TITLE
Garbled PDF after import

### ISSUE THREAD

**Issue by LvShuaiChao** [remnoteio/remnote-issues#1075]
Pdf documents can be opened normally in other software, such as edge browser,
![image](https://user-images.githubusercontent.com/35528109/113082758-9f504480-920d-11eb-8390-077570d66d8f.png)
But importing it into remnote shows a jumble
![image](https://user-images.githubusercontent.com/35528109/113082794-abd49d00-920d-11eb-853a-c8ef93cf3b20.png)
The corresponding PDF resources are
[环境规制能否助推区域经济高质量发展_来自长江经济带的经验证据_薛莲.pdf](https://github.com/remnoteio/remnote-issues/files/6233464/_._.pdf)

**Comment by drkvj** [comment]
merging with #524
