### ISSUE TITLE
"View Graph" mode not working/loading.

### ISSUE THREAD

**Issue by Julesthejules** [remnoteio/remnote-issues#1079]
**Describe the bug**
When I click on the "View Graph" button, it doesn't load and remains blank.  

**Screenshots**
<img width="1331" alt="Screen Shot 2021-03-31 at 7 35 54 PM" src="https://user-images.githubusercontent.com/81720281/113224462-82d9f980-9259-11eb-90c7-3630a0608572.png">

**Desktop (please complete the following information):**
MacOS Mojave
Version. 10.14.6.
Happens on other devices like iPhone 11 and iPad Pro 2020 too.

**Comment by drkvj** [comment]
merging with #1006
