### ISSUE TITLE
Moving a Rem causes it to be added to the "Edit Later" queue

### ISSUE THREAD

**Issue by halhenke** [remnoteio/remnote-issues#108]
**Describe the bug**
Moving a Rem causes it to be added to the "Edit Later" queue

**To Reproduce**
1. Go to a Rem you wish to move (mine were on the top level)
2. Click `Command Shift M`
3. Choose Destination
4. Moved Rem now has the "Edit Later" Tag

**Expected behavior**
Rem to move without changing Edit Status

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser Chrome Canary
 - Version 87.0.4261.0

**Comment by mfranzs** [comment]
Thanks for the report. If you check https://www.remnote.io/keyboard_shortcuts, what do you see listed for "Set New Parent (Move)" and "Set New Parent (Move) and Untag as Edit Later"? Have either been customized?

**Comment by halhenke** [comment]
I have:

```
Set New Parent (Move)     Cmd + M
Set New Parent (Move) and Untag as Edit Later    Cmd + Shift + M
```

Neither has been customized

Ugh - just checked the prompt and it seems the Move Sortcut is `Cmd +M` there also - i think it changed fairly recently and i didnt notice 🤦 

Sorry for the false alarm

**Comment by mfranzs** [comment]
All good, thanks for the clarification!
