### ISSUE TITLE
Can't copy text from custom elements into clipboard

### ISSUE THREAD

**Issue by JohannesKaufmann** [remnoteio/remnote-issues#1082]
**Expected**: When I select the title and press `cmd+c` to copy, the text in the clipboard is "Universal Descriptors"

**Actual**: The text in the clipboard is just "s" since the text from the reference custom elements is missing.

This is probably related to how the actual `text` value is saved in the slate data structure for custom elements.

<img width="786" alt="Screenshot 2021-04-02 at 13 28 44" src="https://user-images.githubusercontent.com/20886667/113411965-681d9700-93b7-11eb-8afe-ee9ccad8335b.png">

----

The head tag also just has `<title>s</title>`, which is confusing and bad for SEO.

<img width="76" alt="Screenshot 2021-04-02 at 13 28 56" src="https://user-images.githubusercontent.com/20886667/113411976-6eac0e80-93b7-11eb-89a4-c8318f59dc90.png">

**Comment by drkvj** [comment]
Is this happening for the title only or every other rem as well?

**Comment by drkvj** [comment]
This is working. Unable to reproduce
