### ISSUE TITLE
After merging, duplicated reference portals are created at the bottom of page

### ISSUE THREAD

**Issue by marcothesis** [remnoteio/remnote-issues#1085]
****There are 3 issues I like to highlight below with screenshots:**

**1. Most glaring of which is duplicated reference portals are created after merging.**
**2. Text references are still not as reliable**
**3. Merge button still persist even after merging****

![d1](https://user-images.githubusercontent.com/10230857/113464663-0d407a00-9461-11eb-9a1d-df6b4a7be23d.png)

**Same thing happen when I merge all the duplicated stubs, more duplicated reference portals get created below:**

![d2](https://user-images.githubusercontent.com/10230857/113464665-1c272c80-9461-11eb-9f8c-54770358dab6.png)

**Comment by drkvj** [comment]
I have been able to reproduce this. 
The criteria being : 
Before merging two rems, the reference search portals need to expanded (I guess this sort of inserts them into the rem) 
And hence with the merge, it brings them along as well, like any other content would. 

Current workaround: Delete all the portals, you will generate new ones with the proper results. 

@mfranzs Kindly take a look at this.
