### ISSUE TITLE
Disappeared edit menu when an image follows the current line

### ISSUE THREAD

**Issue by hl778** [remnoteio/remnote-issues#1088]
**Describe the bug**
The pop-up edit menu of a Rem (bold, underline, highlights, etc) disappears, when an image is below the Rem. 

**To Reproduce**
1. Create a new document
2. Create a new bullet point (Rem) in the document, and put some random text
3. Insert an image as a new Rem below the above Rem. 
4. Highlight some of the text created in step 2, and try to **bold** it through the pop-up edit menu
5. The bug appears. When the mouse hovers over the edit menu, the menu disappears, which causes unable to edit text. That is, **when text is followed by an image in the next line**, it is unable to bold the text through the pop-up edit menu, because the menu just disappears once the mouse is over it. 

**Expected behavior**
In step 5 above, the edit menu should not disappear, it should allow users to edit highlighted text.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional version number 21H1
 - Browser: Chrome
 - Version: 89.0.4389.114

**Additional context**
The bug happens on both Windows 10 desktop application and Chrome browser. 

If unable to reproduce the bug, try to highlight a different part of the text, and the bug will appear quite often.

**Comment by drkvj** [comment]
Thanks for the submit, I have been able to reproduce the bug successfully. 

The trick to catch it is to make sure the pop-up menu falls below the rem and that happens when we highlight the first few rems (otherwise the pop up appears above the rem and which case it is working fine even if there is an image above). 
CC: @mfranzs
