### ISSUE TITLE
Can't press "Show Answer" for long cards

### ISSUE THREAD

**Issue by mfranzs** [remnoteio/remnote-issues#1090]
"When I make a multi-line cards and I want to preview it, when I press show anwser it suddenly disappear. It's quite annoying because I have to press the backward card to see the answer otherwise it will disappear"

**Comment by anishaaa1** [comment]
Linking #792, in case they can be merged, or my issue can be closed to avoid duplicates.

**Comment by drkvj** [comment]
yes merging with #792
