### ISSUE TITLE
Can't add nested slots with mouse click

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#1093]
Suppose this nested template:
![image](https://user-images.githubusercontent.com/4137110/113503763-1b12ff80-9534-11eb-9064-d65653418722.png)

**To Reproduce**
1. Tag with `#Paper`
2. Click on `1 unfilled slot`. It shows `Except (8 descendants)`.
3. Clicking on that adds only `[[Except]]` and there is no way to add the other slots since the `1 unfilled slot` is gone.

![image](https://user-images.githubusercontent.com/4137110/113503837-ad1b0800-9534-11eb-8223-3029e9050121.png)

**Expected behavior**
I think it would be better to add all nested slots of the clicked one since the unnecessary child slots can be deleted after but adding them later is impossible.

Using Ctrl + Alt + P to add all slots adds all slots as expected:

![image](https://user-images.githubusercontent.com/4137110/113503850-c02dd800-9534-11eb-9e1c-daf9fa1dbd51.png)

**Comment by drkvj** [comment]
@hannesfrank kindly port this to the feature requests on the forum for more visibility and user voting.
