### ISSUE TITLE
Typo in the queue settings

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#1094]
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/113504148-81008680-9536-11eb-8455-facfcc565ea5.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.4.2
 - Browser safari (PWA)
 - Version 14

**Comment by drkvj** [comment]
This is embarrassing :D Thanks man!
