### ISSUE TITLE
error al iniciar remnote

### ISSUE THREAD

**Issue by baleska** [remnoteio/remnote-issues#1097]
al ingresar a remnote y escribir un documento, aparece algo salio mal y no me permite escribir ningun documento. quisiera saber la solucion gracias

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment]
Kindly provide more detail in order to understand what's happening please. A screen recording would help a lot.
