### ISSUE TITLE
Semicolon is not recognized as separator for keyword extraction from PDFs

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#1098]
These are the metadata from my pdf:
![image](https://user-images.githubusercontent.com/4137110/113580820-8c32df80-9626-11eb-8841-b60ef350eb4c.png)
You can see authors are separated by comma and keywords by semicolon.

Authors are parsed fine. But only one keyword is extracted:
![image](https://user-images.githubusercontent.com/4137110/113581461-7671ea00-9627-11eb-8b6e-df36bdf66752.png)

I don't know what the PDF specification here is exactly. Here is some information: https://stackoverflow.com/questions/44608608/the-separator-between-keywords-in-pdf-meta-data
Looks like semicolon is recommended by the majority. ExifTool uses comma and falls back to space otherwise.

Another RemNote UX note: If I upload the pdf and delete it the now unreferenced keyword rem is still there (I assume). Maybe we should distinguish between user generated rems (from `[[`, Ctrl + Enter) and programmatically reference-created rem (pdf keywords/authors) and the latter should be autodeleted if no reference exists anymore?

**Comment by drkvj** [comment]
Kindly port the feature requests to the forum for more discoverability please.
