### ISSUE TITLE
[web clipper] have option to save created rems to a specific rem of my choosing

### ISSUE THREAD

**Issue by PandaBoy444** [remnoteio/remnote-issues#11]
**Is your feature request related to a problem? Please describe.**
When I clip a rem, it saves it to the [links] rem without asking me. My workflow is based on the daily note so I would like it to appear there in my case, but I can imagine many people would like to choose where it should appear.

**Describe the solution you'd like**
Give an option as to where to save new clip rem, including "latest" tag or something. eg 'save on latest daily document', just an idea though.
**Describe alternatives you've considered**
Give preset options to common use cases so that users won't make a mess. I don't like this idea but it would be much easier to implement and debug.

Thank you!

**Comment by mfranzs** [comment]
Thanks for the clear feature request! Adding more customization here is on our roadmap. We'd like to integrate this into the Power-Up system, but this integration is further down the line.
