### ISSUE TITLE
I keep on getting a "can´t read properly 'customReferencePrefix' " kind of error 

### ISSUE THREAD

**Issue by jafya** [remnoteio/remnote-issues#1103]
**Describe the bug**
I keep on getting a  "can´t read properly 'customReferencePrefix' " kind of error 

**To Reproduce**
1. Open app
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/82121343/113932974-f21c9400-97eb-11eb-8d94-6194a91b476b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by mfranzs** [comment]
Can you please make sure that you're on the latest version of the app, 1.3.6? You might need to re-download from https://www.remnote.io/download.

**Comment by drkvj** [comment]
@jafya kindly open a bug report on the forum if the above solution didn't fix the problem for you. thank you.
