### ISSUE TITLE
Queue target does not reset every day on OS X desktop app

### ISSUE THREAD

**Issue by dmrd** [remnoteio/remnote-issues#1104]
Describe the bug
Queue target does not reset every day

To Reproduce
1. Study in the queue one day and complete the daily target
2. Come back the next day & the target is not reset. The previous # completed carries over. This can continue for several days (so it just counts # of cards completed)

Platform (please complete the following information):
OS: OSX Big Sur (11.0)
desktop app, local database

**Comment by mfranzs** [comment]
Thanks for reaching out - can you confirm that this in >1.3.6? We had addressed a related issue here in a recent update.

**Comment by robertmartin8** [comment]
I'm on the latest version and also have this issue.

**Comment by luke-nehemedia** [comment]
I can also confirm this. Have the same issue.
