### ISSUE TITLE
Strange behaviour when editing aliases containing LaTeX

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#1105]
https://user-images.githubusercontent.com/8283298/114104339-92dd8300-98c2-11eb-864a-c0963987abf1.mov

- LaTeX not editable in alias edit dialog
- When highlighting LaTeX, alias edit dialog closes

**Comment by drkvj** [comment]
Merging it with https://github.com/remnoteio/remnote-issues/issues/489.
