### ISSUE TITLE
Filters don’t work on mobile

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#111]
**Describe the bug**
If you click "Filter this Document", nothing happens

**To Reproduce**
1. Click on the triple dots 
2. Click on "Filter this Document"
3. See error

**Expected behavior**
A popup window should appear so you can filter, it even works on the desktop layout but not on the mobile layout
**Screenshots**
This is how it looks like on the desktop layout
![image](https://user-images.githubusercontent.com/69430941/93695126-9589ae00-fb13-11ea-88b5-92de10f489e6.png)
On the mobile layout, nothing happens though

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: ios 14
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
