### ISSUE TITLE
[feature request] shortcut for multi-line card Item

### ISSUE THREAD

**Issue by Jackiexiao** [remnoteio/remnote-issues#1110]
- sorry for using issue to raise my feature request, but I really want this feature. it have been months but no progress yet.
- related discussion
    - [ Shortcut to turn existing list into bullet point rem? - Feature Requests - RemNote](https://forum.remnote.io/t/shortcut-to-turn-existing-list-into-bullet-point-rem/2126)
    - [ Multi line rem shortcuts - Feature Requests - RemNote](https://forum.remnote.io/t/multi-line-rem-shortcuts/2914)
- thx for your time

**Comment by drkvj** [comment]
Hey! Thanks for taking the time and submitting this, but as you may already know we have to prioritise our dev time based on popular feature requests. I have to close this report here, but hopefully we get the feature executed soon :)

**Comment by Jackiexiao** [comment]
ok
