### ISSUE TITLE
PDF reader hangs during zoom

### ISSUE THREAD

**Issue by elizhenning** [remnoteio/remnote-issues#1113]
**Describe the bug**
PDF reader hangs during zoom. Happens regularly on both desktop and browser.
Possibly similar to [https://github.com/remnoteio/remnote-issues/issues/496](https://github.com/remnoteio/remnote-issues/issues/496)

**To Reproduce**
1. PDF loaded in split-screen
2. Click + button to zoom in
3. PDF hangs as blank with working circle indicator
4. Sometimes PDF re-renders with the same zoom level as before

**Expected behavior**
Zoom should result in zooming.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, also RemNote desktop
 - Version Chrome 89

**Comment by drkvj** [comment]
I am porting this issue to the forum [here](https://forum.remnote.io/t/pdf-reader-hangs-during-zoom/3996?u=karthikk), once we have reproduced this issue, we will automatically open the issue again and fix it. 
Thank you for reporting!
