### ISSUE TITLE
automatically add template and/or slots are not working

### ISSUE THREAD

**Issue by gtjkl** [remnoteio/remnote-issues#1114]
Automatically add template and/or slots are not working. When I trigger the template by typing ##, it doesn't exist.

**To Reproduce**
1. Create a plain text parent rem
2. Add two child rems
3. Go to parent rem and add automatically add template
4. Go to each child and turn into slot

**Expected behavior**
When I trigger by typing ##, one of the options will be the template.

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
Verified with one of the moderators that it is a bug. I tried it on the desktop app and web app.

**Comment by drkvj** [comment]
This was a misunderstanding, not a bug. it has been explained to the user and it's solved
