### ISSUE TITLE
The problem of exporting to an empty file in Markdown format

### ISSUE THREAD

**Issue by LvShuaiChao** [remnoteio/remnote-issues#1118]
Sometimes when RemNote notes are exported to Markdown format, there will be an empty file with 22 bytes.

![image](https://user-images.githubusercontent.com/35528109/114867533-85c31580-9e27-11eb-8832-3ec13935837a.png)

I use Win10 64-bit system

**Comment by drkvj** [comment]
Closing as it is a duplicate report
