### ISSUE TITLE
The problem of exporting to an empty file in Markdown format

### ISSUE THREAD

**Issue by LvShuaiChao** [remnoteio/remnote-issues#1119]
Sometimes when RemNote notes are exported to Markdown format, there will be an empty file with 22 bytes.
Exporting notes to Markdown format is very important to me and others, and I would be very grateful if developers can give enough attention
![image](https://user-images.githubusercontent.com/35528109/114867533-85c31580-9e27-11eb-8832-3ec13935837a.png)

![image](https://user-images.githubusercontent.com/35528109/114867577-91164100-9e27-11eb-8951-d3dfac2235d6.png)

I use Win10 64-bit system

**Comment by drkvj** [comment]
Closing this issue as there is an existing report shown above and a related forum discussion thread here : https://forum.remnote.io/t/exporting-create-empty-zip-file/3800 

If anyone is able to reproduce when this behaviour happens, it will be incredibly helpful in fixing this bug. Thanks for the report!
