### ISSUE TITLE
Deleting a document doesn’t work on mobile

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#112]
**Describe the bug**
If you are on mobile, using the desktop layout (because the mobile layout is limited at the moment) you can't delete documents if you click "Delete this Document". You can delete them on the mobile layout though

**To Reproduce**
1. Zoom into a Rem
2. Click on the triple dots
3. Click on "Delete this Document"

**Expected behavior**
It should delete the document when I click that option
**Screenshots**
On mobile, you get this pop up![image](https://user-images.githubusercontent.com/69430941/93705692-8577cb80-fb1f-11ea-8cbb-e4f8785328d2.png)Might be connected to the issue

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: ios 14
 - Browser safari
 - Version 14

**Comment by 8888Daniel8888** [comment]
Update: the popup actually appears on my iPad when I do the exact same thing on the desktop layout

**Comment by mfranzs** [comment]
Thanks for the report. I'm having some trouble reproducing this - what error do you see in step 4?

**Comment by 8888Daniel8888** [comment]
The issue seems to be gone now, will reopen when I see it again
