### ISSUE TITLE
There are fewer and fewer words on the sidebar

### ISSUE THREAD

**Issue by LvShuaiChao** [remnoteio/remnote-issues#1120]
There are fewer and fewer words on the sidebar
![image](https://user-images.githubusercontent.com/35528109/114950518-d2d5d480-9e85-11eb-9f82-c40bbcf5871f.png)

**Comment by drkvj** [comment]
hey @LvShuaiChao! For clarification, this is the Breadcrumb Labs feature, not the sidebar. Being a Lab feature, it's not fully developed yet and we could totally use such feedback, but the right place for this would be on the forum feedbacks section [here](https://forum.remnote.io/c/21-category/21/none). I will go ahead and create a new post for you there.
