### ISSUE TITLE
NO PUEDO UTILIZAR MI REMNOTE URGENTE :(

### ISSUE THREAD

**Issue by ireneegh** [remnoteio/remnote-issues#1124]
Buenas noches, cada vez que intento hacer un nuevo documento o siquiera escribir me aparece lo siguiente:

Algo salió mal. 

Intente actualizar la página. Si el problema persiste, proporcione detalles adicionales en la página de ayuda .

Error: no se puede resolver un punto DOM desde el punto Slate: {"path": [0,0], "offset": 6} . URL: https://www.remnote.io/document/n9wHL6yZb5KusrQFn

Por favor necesito ayuda urgentemente!
Espero su respuesta

Irene Espinoza Ghersi

![image](https://user-images.githubusercontent.com/82697725/115104571-031d8180-9f1f-11eb-8b5f-40fcc81f9fad.png)

**Comment by drkvj** [comment]
merge with : #893
