### ISSUE TITLE
Chinese character input issue

### ISSUE THREAD

**Issue by bleedingsaber** [remnoteio/remnote-issues#1125]
**Describe the bug**
I think I come across same issue:
https://github.com/remnoteio/remnote-issues/issues/1080
This means I almost can not type to insert any Chinese rems between lines.

**To Reproduce**
![2021-04-17 at 3 06 PM](https://user-images.githubusercontent.com/82697316/115105042-005a7500-9f8f-11eb-9a3d-bb9316ed9fa0.jpg)
![2021-04-17 at 2 56 PM](https://user-images.githubusercontent.com/82697316/115105045-07818300-9f8f-11eb-9948-b83ffb399758.jpg)
![2021-04-17 at 3 09 PM](https://user-images.githubusercontent.com/82697316/115105102-58917700-9f8f-11eb-891a-801c78a59927.jpg)

**Desktop:**
Mac OS
Both desk app and browser

Not sure my description is clearly or not and don't know the reason and how to fix it, but this issue confuse me so much to force me register GitHub to report bug.

**Comment by link-ding** [comment]
![image](https://user-images.githubusercontent.com/49264539/115107089-14f93600-9fac-11eb-8d50-aa8b85cd7579.png)
我去年八月就提出来了, 到现在都没改. 建议放弃换个其他的软件吧 你可以去看看 #61 里面已经打上的是长期问题

**Comment by bleedingsaber** [comment]
> ![image](https://user-images.githubusercontent.com/49264539/115107089-14f93600-9fac-11eb-8d50-aa8b85cd7579.png)
> 我去年八月就提出来了, 到现在都没改. 建议放弃换个其他的软件吧 你可以去看看 #61 里面已经打上的是长期问题

我也纳闷，这个问题貌似很明显。难道是很难解决？

**Comment by link-ding** [comment]
> > ![image](https://user-images.githubusercontent.com/49264539/115107089-14f93600-9fac-11eb-8d50-aa8b85cd7579.png)
> > 我去年八月就提出来了, 到现在都没改. 建议放弃换个其他的软件吧 你可以去看看 #61 里面已经打上的是长期问题
> 
> 我也纳闷，这个问题貌似很明显。难道是很难解决？

毕竟我们不是目标用户, 早点换了早点解脱. remnote各种不稳定 bug非常之多

**Comment by drkvj** [comment]
嘿！对于修复此错误的延迟，我们深表歉意。 RemNote整个时间仅由一个开发人员管理，但是自一月份以来，我们一直在努力扩大开发团队，以便可以更快地解决此类问题。
直到最近，我们还没有意识到我们拥有大量使用中文或日文的用户群，因此我们没有优先考虑。但是由于华人社区的努力，我们意识到了这些问题，因此我们肯定也将非拉丁语用户社区的关注列为优先事项。
现在，RemNote的国际化对我们来说是当务之急。
感谢您的耐心等待。

**Comment by drkvj** [comment]
Merging with #584

**Comment by link-ding** [comment]
> 嘿！对于修复此错误的延迟，我们深表歉意。 RemNote整个时间仅由一个开发人员管理，但是自一月份以来，我们一直在努力扩大开发团队，以便可以更快地解决此类问题。
> 直到最近，我们还没有意识到我们拥有大量使用中文或日文的用户群，因此我们没有优先考虑。但是由于华人社区的努力，我们意识到了这些问题，因此我们肯定也将非拉丁语用户社区的关注列为优先事项。
> 现在，RemNote的国际化对我们来说是当务之急。
> 感谢您的耐心等待。

This kind of software that can exist a bug for more than a year without solving it, who will still use it? Obsidian must be better choice.

**Comment by wo4wangle** [comment]
Really hope to fix this issue! 
There are plenty of users in china, but this problem scare many new user and make the chinese remnote fans feel sad.
