### ISSUE TITLE
I can’t turn off that x after a reference

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#113]
**Describe the bug**
When I try to click on it, it goes to the text that was referenced. I can only turn it off with an external trackpad
**To Reproduce**
1. Create a reference
2. write :: after it
3. Try to get rid off the x after the reference 

**Expected behavior**
If I click on that x, I want it to disappear

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/93708427-68022c00-fb36-11ea-80a9-bc202ebf3999.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iPad 14
 - Browser safari
 - Version 14

**Additional context**
I have no clue what that x even does

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
