### ISSUE TITLE
No puedo ingresar a la pagina

### ISSUE THREAD

**Issue by marianamedic** [remnoteio/remnote-issues#1138]
buenas noches, no puedo ingresar a mi remnote por la página web, cuando trato de ingresar, me dice que algo salió mal, ayúdeme por favor

![Captura](https://user-images.githubusercontent.com/83152451/115981077-d2f56480-a556-11eb-807f-2e8e97b46b52.PNG)

**Comment by bambeli** [comment]
Me pasa lo mismo, pero ni siquiera me salen los documentos al lado. Ya publiqué mi problema también

![image](https://user-images.githubusercontent.com/83154156/115982588-ac84f880-a559-11eb-81a7-a270206cbc15.png)

**Comment by drkvj** [comment]
Kindly try force refreshing using CMD/CTRL + Shift + R. 

@bambeli are you not able to go beyond this error at all to access the database?

**Comment by drkvj** [comment]
merging with #1139
