### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by bambeli** [remnoteio/remnote-issues#1139]
**Describe the bug**
My documents are not loading

**To Reproduce**
1. Go to 'https://www.remnote.io/'
2. See error

**Expected behavior**
The documents to load on the left side so I can open them and edit them

**Screenshots**
![image](https://user-images.githubusercontent.com/83154156/115982466-8874e780-a558-11eb-9a63-766a8eff44ef.png)
![image](https://user-images.githubusercontent.com/83154156/115982699-49e02c80-a55a-11eb-99d0-8092d7572006.png)

**Desktop (please complete the following information):**
 - OS: microsoft
 - Browser chrome
 - Version 90.0.4430.85

**Additional context**
I was editing a document earlier today, it was working VERY slowly, I had to wait for it to select various rems (with mouse and with shift + up and down arrows) for quite some time (as opposed to other days when it was working normally and relatively quickly). Now, since about 6 hours ago it stopped loading completely and it just shows a "please reload" message (as seen on the screenshot).
Also, I can work from the desktop app, but it has gotten even slower as the hours passed and now I just gave up since I wasted too much time trying to edit the document. But I guess it's a little bit better than the browser. (update: as you can see in screenshot 2, I expanded the page and it just got stuck on the minimized version I had, and it takes so long for it to load)
Thank you.

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment]
Kindly try CTRL + Shift + R on the webpage

**Comment by drkvj** [comment]
Note: This is similar to #1060, but that happens only to the windows desktop where this and #1138 happens on the webapp as well

**Comment by drkvj** [comment]
merging with #771

**Comment by bambeli** [comment]
> Kindly try CTRL + Shift + R on the webpage. Are you still facing these issues?

It does refresh the page, but afterwards it still shows the same message with the green "refresh" that doesn't work
