### ISSUE TITLE
Displays unrelated things during queue

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#114]
**Describe the bug**
Displays unrelated things during queue

**To Reproduce**
1. Create documents like Anatomy, Histology, Embriology
2. Put them all in one folder
3. Practice this folder with spaced repetition

**Expected behavior**
not showing irrelevant things

**Screenshots**
Video: 
https://mega.nz/file/Tx8SzaBJ#6iGSmqt3Q_5jycjFgIV1gg0uzzoWH_XgZtNVub6evWE
Screenshot:
![image](https://user-images.githubusercontent.com/20538090/93753695-3c9c4180-fc09-11ea-9237-621b35d05ad3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Version [e.g. 22]: 86.0.4240.42

**Comment by mfranzs** [comment]
This looks like a "Document Card", which is an experimental feature. Please turn off this feature in your settings if you don't like seeing these.
