### ISSUE TITLE
Can't go back on desktop app

### ISSUE THREAD

**Issue by bambeli** [remnoteio/remnote-issues#1140]
![image](https://user-images.githubusercontent.com/83154156/115982832-2ec1ec80-a55b-11eb-8e18-6b6657fdf1e9.png)

When I press the "back arrow", it should take me back to the page I was jut in, instead it says "error 404" and I have to go to the folder and document again, and scroll back down to where I was,
This has been happening since a long time ago, I just hadn't reported it because I thought it was gonna get fixed, but it hasn't, so maybe you don't know it's happening :)
Thank you.

**Comment by drkvj** [comment]
Thanks for reporting this, this issue has been persisting for some users, but we are not able to reproduce this. Any info about how this started might help us catch the bug. Merging it with #477. Kindly follow up there or on the forum discussion (links in the report)
