### ISSUE TITLE
Trying to delete documents that are tagged in portals sorted by creation time will crash / freeze RemNote

### ISSUE THREAD

**Issue by marcothesis** [remnoteio/remnote-issues#1142]
**Describe the bug**
RemNote will crash whenever I try to delete rems with many linked references.

**To Reproduce**
1. Find a rem with many linked references
![delete](https://user-images.githubusercontent.com/10230857/115990509-371b3580-a5f6-11eb-9a3c-5b2cde74329c.png)
2. Try to delete using either backspacing the rem or click 'delete' from the rem menu on the left.
3. RemNote will freeze or crash, unable to click anything anywhere. I have to restart app or reload browser, and the 'to be deleted' rem will still be there.

**Comment by drkvj** [comment]
Any idea how big these backlinks have to be for this to happen?

**Comment by marcothesis** [comment]
> Any idea how big these backlinks have to be for this to happen?

I'm not sure but the example shown has more than 900 backlinks. I don't have many things to delete in this way and I surely would not want to risk trying. If I come across any other number, I will update.

**Comment by marcothesis** [comment]
Similar behavior and could be related: https://forum.remnote.io/t/unable-to-delete-orphan-rem/4485

**Comment by marcothesis** [comment]
I think I have identified the root cause of this issue as well as those found in some other threads relevant to delete crash.

This is primarily due to the new feature introduced in **beta 1.3.7** with the ability to sort by creation time and should warrant a a priority=1 or immediate fix. @drkvj @mfranzs 

**Go to a tagged or reference rem. If its tagged rem portal below is sorted by creation time, trying to delete this document will crash RemNote.**
![creation time](https://user-images.githubusercontent.com/10230857/117384819-685d0500-af16-11eb-98e8-97b0604d5dea.png)

**Now, change the same tagged rem portal below to unsorted. You can now delete the document successfully.**
![unsorted](https://user-images.githubusercontent.com/10230857/117384828-6b57f580-af16-11eb-87d0-ec3191b35964.png)

This new feature alone has introduced quite a no. of bugs, no?
