### ISSUE TITLE
Indenting causes the bullet list to go up

### ISSUE THREAD

**Issue by Prayaero** [remnoteio/remnote-issues#1144]
**Describe the bug**
So indenting happens normally when creating a new document then after some time when I have created tons of indents, the new indent goes up in the list instead of going to the side. This also happens when I try to use the Numbered list then use a Bullet list, the bullet goes up instead of towards the side.

**To Reproduce**
1. Using normal bullet indent normally
2. Indent
3. The indent goes up instead of towards the side

See Video for details:
https://user-images.githubusercontent.com/65183226/116022625-1cd86a80-a67d-11eb-971b-2858dfbe7628.mp4
So in the video, I want the "Return to Function" bullet to line up with the "Controlled Motion" bullet but instead of going to the side, it goes up

**Expected behavior**
The new bullet indent should go towards the side not go up

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave Browser
 - Version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)

**Additional context**
This also happens to my other classmates, not just me.

In case video link doesn't work, here's a backup URL
https://drive.google.com/file/d/1i3MDqT8igqFHtmbxIMIFD1cwtUv7IPBZ/view?usp=sharing

**Comment by Prayaero** [comment]
Here's another example where instead of going towards the side normally, it goes up

https://user-images.githubusercontent.com/65183226/116025418-07663f00-a683-11eb-9af5-a6248064ff45.mp4

**Comment by drkvj** [comment]
The issue reported in the first video appears to be faulty, but I am having trouble replicating this. Have you encountered this behaviour elsewhere, or is this happening only to that specific rem? 

The second video you posted isn't a bug, it's working as intended. Will explain what's happening there: 
1. You changed a few rems into list card items (numbered) 
2. Then you brought them out one level of indentation
3. They became normal rems under the parent rem S/Sx of Psychiatric Illness 1st Half
4. Then you changed them into List card items again. So they travelled based on priority. 

This is working as intended, as a content of a card will be prioritised in order than other normal rem descendants. Is this affecting your workflow?

**Comment by drkvj** [comment]
merging this bug with #939
