### ISSUE TITLE
login with google on linux is not working

### ISSUE THREAD

**Issue by kiambati-maxwel** [remnoteio/remnote-issues#1148]
[**Describe](url) the bug**
A clear and concise description of what the [bug]([url]([url](url))) is.

**To Reproduce**
3. Scroll down to  #'....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment]
Closing this as it is a duplicate report
