### ISSUE TITLE
login with google on linux is not working

### ISSUE THREAD

**Issue by kiambati-maxwel** [remnoteio/remnote-issues#1149]
**Describe the bug**

I downloaded and executed remnote image for linux.
I tried to login with google on my machine 
it display this error

![remnote error](https://user-images.githubusercontent.com/45457417/116078212-ffb49380-a69e-11eb-9af4-09dc6fcf1e0d.png

**Desktop (please complete the following information):**

 - OS: [e.g. Ubuntu 20.10]
 - Browser [e.g. chrome, safari, firefox]

**Comment by drkvj** [comment]
Merging this with #400
