### ISSUE TITLE
Ipad - after clicking on a rem and scrolling, it skips to the next rem

### ISSUE THREAD

**Issue by corode** [remnoteio/remnote-issues#115]
When I'm in the queue on my iPad pro and I click show answer, it shows the answer. However, when I try to scroll down (on a multiline rem) to see the full answer, it skips to the next rem when I attempt to scroll down.

**To Reproduce**
Use an iPad/touchscreen device on the web version
Study a long, list rem in the queue
Click show answer and the multi-line rem appears
Try and scroll down
Error - it skips to the next rem as soon as I touch the screen

**Expected behaviour**
The rem to scroll down when I attempt it rather than skipping to the next rem before I have pressed one of the 'faces' to show how well I knew the answer

**Screenshots**
Can't screenshot as the error happens when I touch the screen

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPad Pro 2020
 - OS: iPadOS 14
 - Browser safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
