### ISSUE TITLE
Set code content search invisible

### ISSUE THREAD

**Issue by LvShuaiChao** [remnoteio/remnote-issues#1153]
Many of the contents in the code block are places that you don't need to pay attention to, but every time you search, you will find them; And the code block is very long, other keywords are very short compared with it, it is not easy to find the really useful content.
Suggestions:
  Can I add an option in front of the code block to make the search invisible?
  Or is the search display in the code block a little shorter?
![image](https://user-images.githubusercontent.com/35528109/116542391-300a6500-a91f-11eb-9926-54a40c91f7e9.png)

**Comment by drkvj** [comment]
This is a duplicate, hence closing it
