### ISSUE TITLE
Flashcards Crash when typing Chinese Characters || Error: Cannot resolve a Slate point from DOM point: [object Text],2

### ISSUE THREAD

**Issue by ncb7788** [remnoteio/remnote-issues#1155]
Hello, 

I'm studying Chinese in Roam using flashcards fill in the blank option, and about every 4 cards when I type in a character the app crashes, displaying this message. 
Error: Cannot resolve a Slate point from DOM point: [object Text],2

![Screen Shot 2021-04-29 at 10 08 29 AM](https://user-images.githubusercontent.com/73501659/116573986-ebf17300-a8d2-11eb-8809-498c4a679372.png)
![Screen Shot 2021-04-29 at 10 09 36 AM](https://user-images.githubusercontent.com/73501659/116574108-062b5100-a8d3-11eb-8955-865e7ce92b83.png)

**Comment by drkvj** [comment]
this is related to the issue reported here and hence merging this to that : #584
