### ISSUE TITLE
Image Occlusion Not working sometimes (it does not save my image occlusions when i exit out of it sometimes and i have to make image occlusions again) 

### ISSUE THREAD

**Issue by jyleechiro** [remnoteio/remnote-issues#1162]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by luke-nehemedia** [comment]
I can confirm the issue. I often have to create the occlusions a couple of times until they are eventually saved.

**Comment by drkvj** [comment]
merging with #1156
