### ISSUE TITLE
Editing a List card from the queue opens editor for next element in list instead.

### ISSUE THREAD

**Issue by Shallash** [remnoteio/remnote-issues#1163]
### **Describe the bug**
When we use the edit now button while an element of the list card is revealed, it opens an edit window with only the *next* element in the list card visible to edit. Example: using the edit button when element 1. is obscured and revealed in the front and the back of the card respectively, opens an edit window with only element 2. visible.

### **To Reproduce**
1. Create a blank document
2. Type in something, at the end, type in `::1.` to make that Rem a List-Card
3. Fill in the children of the rem, at least two
4. Open Queue
5. Go to the card where the first list element is obscured/clozed (demonstrated in Screenshot 2)
6. Reveal the back of the card (demonstrated in screenshot 3)
7. Click the "Edit Now" button or press `E`

### **Expected behavior**
The edit window opening, with the list rem that was just visible appearing.

### Screenshots

These are the original Rems
![image](https://user-images.githubusercontent.com/71895835/116745066-768fba80-aa18-11eb-827f-cfff8335035e.png)
This is the first card of the list:
![image](https://user-images.githubusercontent.com/71895835/116745637-fe75c480-aa18-11eb-9dcb-208b7e0199a2.png)
This is what the back of the card looks like:
![image](https://user-images.githubusercontent.com/71895835/116745749-2fee9000-aa19-11eb-9cee-b7c1ebe0f797.png)
This is what appears when I press E or click the edit now button:
![Screenshot (17)](https://user-images.githubusercontent.com/71895835/116745914-6af0c380-aa19-11eb-82b6-dbf241a5c88a.png)

### Desktop (please complete the following information):
Desktop Version 1.3.6.477 Windows

### Additional context
* This problem persists if you mark a card for edit later, and open the edit later window. 
* This problem doesn't occur if we try to edit the *last* element in the list.
* Issue was reproduced by `gravityshades#3931` on the discord.
 
### Suggestion
If a change is implemented in this behaviour, I think that it's more intuitive for the edit window to have the element that was in the card at the time, *plus* all the elements in the list previous to that element.

**Comment by drkvj** [comment]
merging with #184
