### ISSUE TITLE
Can't Update RemNote on MacOS

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#1168]
**Describe the bug**
I can see that there is an update on my desktop app because the `Reload and Update` button is visible. I tried to click it a few times and saw that it restarted the app, but neither would the `Reload and Update` button go away after restarting, nor would the app actually update.

**To Reproduce**
1. Click `Reload and Update` in the sidebar
2. Note that the app restarts
3. See that the `Reload and Update` button persists + app has not actually updated (from version number in Settings > Account > Desktop App).

**Screenshots**

After restarting:

![image](https://user-images.githubusercontent.com/68901589/116995690-abcb2f80-acda-11eb-9b01-3616141175cf.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Desktop App
 - Version 1.3.6

**Comment by luke-nehemedia** [comment]
Same issue here, also on macOS Big Sur.
