### ISSUE TITLE
Issue with Search Portals - Only looking at TAG and not the other as it once did.

### ISSUE THREAD

**Issue by kurapr** [remnoteio/remnote-issues#1171]
I had the portal give me search results on the Page, itself AND things that were highlighted green. It was working perfectly....now once I go into each one of my projects/pages and click on refresh it ignores where the portal is and pulls it across the entire Database. Really not good for when I'm trying to pull a summary based on that page and only the green highlighted items...

(sorry if you see this multiple places, I wasn't sure which forum/support place would be best)

https://user-images.githubusercontent.com/68754599/117091846-2e2b1200-ad22-11eb-93b8-b020cf758f66.mp4

**Comment by drkvj** [comment]
merging with #1175
