### ISSUE TITLE
app doesn't update (MacOS desktop ver)

### ISSUE THREAD

**Issue by klimekwiktor** [remnoteio/remnote-issues#1172]
**Issue:**
Remnote app doesn't update to version 1.3.8. on desktop app.
I've tried to close it multiple times by clicking reload and update and by exiting the app (cmd + q).
I've also tried to reset the whole system multiple times.

**Reproduction clues**
Macbook Air (M1) 2020
MacOS Big Sur 11.3
Desktop Remnote ver 1.3.6
Reload and update was initialized when remnote app was opened on a document and while in the queue.

(I know that i can download new app from the website, but that is not a feature, is it?)

**Comment by smonv** [comment]
I got the same problem on Intel based Macbook Pro

**Comment by drkvj** [comment]
merging with #1177
