### ISSUE TITLE
My account help page can not load 

### ISSUE THREAD

**Issue by rogerophy** [remnoteio/remnote-issues#1173]
**Describe the bug**

My account help page can not load, when I log in my account "rogerpvt.2017@gmail.com" , whatever browser I tried, none of them can show page right.

The error shows that
1. No windows present. 

2. document deleted. 

**To Reproduce**
1. Go to 'Help'
2. Click on 'latest upgrade'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. win10]
 - Browser [chrome, edge, firefox
 - Version [latest for now]

![捕获](https://user-images.githubusercontent.com/83705508/117137764-2aac8f00-ade5-11eb-8818-9c3a642a8f04.PNG)

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment]
I have reproduced this, can you confirm if turning off the lab feature "Multi Windowed Pane" makes this alright?
