### ISSUE TITLE
The update does not take place

### ISSUE THREAD

**Issue by Drususgi** [remnoteio/remnote-issues#1177]
Hi
On a MacBook Pro, macOS Big Sur version 11.3.1, RemNote 1.3.6, I have a notification that says "Update available" and "Reload and update". When I do so, another notification pops up stating that "RemNote 1.3.8 has been downloaded and will be automatically installed on release". Then when I close RemNote and relaunch it, no updates have been made.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment]
Thank you for the report, yes we have identified the problem. We will work on fixing this asap!
