### ISSUE TITLE
buenas tardes, no s epuede actualizar mi cuenta, ayudenme por favor, mi cuenta está como marianamedic5@gmail.com

### ISSUE THREAD

**Issue by marianamedic** [remnoteio/remnote-issues#1179]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by hannesfrank** [comment]
This sounds like an account specific issue. If you still have this problem, please write an email to support@remnote.io or open a support ticket from the "?" menu so we can help you more directly.
