### ISSUE TITLE
feature completion request on import Markdown docs 

### ISSUE THREAD

**Issue by Delli** [remnoteio/remnote-issues#118]
thanks for md code block enhancement in the editor.  
Please consider **the import** of code blocks also. 
I am sure this is on the list.  but anyways perhaps to flip the mindset on the priority ?

I want to remind again the difference it wil makes for onboarding and long term value for such  a big group of knowledge workers. thanks in advance for considering the priority.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
