### ISSUE TITLE
the sidebar appears delayed

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#119]
**Describe the bug**
when I move my cursor to the left side of the screen, the sidebar appears delayed instead of almost instantly
**To Reproduce**
1. move the cursor to the left side of the screen a few times
2. See error

**Expected behavior**
the sidebar should move into frame almost instantly

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: ios 14
 - browser: safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. The sidebar will only open when your mouse has stopped moving to avoid accidentally opening it. We'll see if we can make this tighter, but for now this is as designed.
