### ISSUE TITLE
Popup from hovering over a bullet point clears selection thus prevents moving multiple rems via drag and drop 

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#121]
**Describe the bug**
After selecting multiple rems, if I move the cursor over one selected bullet point to move, it shows the pop which shows the children of that rem. I think because of this pop up the selected rems get deselected 

**To Reproduce**

1. Select multiple rems
2. Try to move all that selection to another hierarchy by dragging on one of the selected bullet points. Check the GIF 

**Expected behavior**
Should be able to select multiple rems and move them all at once, just like how it used to be

**Screenshots**
![pop_hover_prevents_multi_move](https://user-images.githubusercontent.com/24322880/94350081-80bf8580-ffff-11ea-82e0-dcfdb2b30a26.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 85.0.4183.102 (Official Build) (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. This has been fixed in the latest release - please let us know if you see this again.
