### ISSUE TITLE
Hard and Good/Solid options have the same interval + minute intervals not "working" when exiting/re-entering queue

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#122]
**Describe the bug**
1. I had my initial learning phase fixed steps set to the following – 0.0138d (20m), 1d, 3d, 5d and for some reason the Hard and Good options both had the same intervals each time I did the rem
2. When I exit the queue and go back into it only **a few seconds later**, the rem that had a 20m interval comes up immediately

Not sure if related, but in case they are, I've put them in the same bug report.

**To Reproduce**
1. Set initial learning phase fixed steps to 0.0138, 1, 3, 5
2. Observe that in the examples, RemNote correctly shows that after you'd click Solid, it would appear in your queue 20m later
3. Create a new flashcard and open it in the queue
4. Observe that:
     a) Hard and Good intervals appear to be the same (20m) and/or
     b) After clicking Hard/Good, it either appears immediately in the queue or when you exit the queue and come back to it in a matter of a few seconds or even a minute, it comes up in the queue (way ahead of 20m)

**Expected behavior**
Hard interval should not be the same as Good. Not sure how the Hard interval is calculated but I've clicked Hard on a few rems but they still appear to have the same interval as Good.

**Screenshots**

When I did the below rem for the first time in the queue

![image](https://user-images.githubusercontent.com/68901589/94364608-b3d74700-00db-11eb-92a5-ba6b6aaf9968.png)

When I did the below rem for the second time in the queue

![image](https://user-images.githubusercontent.com/68901589/94364611-b9349180-00db-11eb-883a-463978175970.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
I have since changed the initial learning phase fixed steps to 1d, 3d, 5d but the Hard and Good options still have the same interval.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
