### ISSUE TITLE
Can't edit title of a document/zoomed rem

### ISSUE THREAD

**Issue by SG60** [remnoteio/remnote-issues#123]
I'm currently not able to edit the title of a zoomed rem or document. Remnote simply doesn't react to my keyboard when the title is focused.

**Comment by mfranzs** [comment]
Thanks for the report. Are you still having this problem? Did it go away when you refreshed the page? We're having trouble reproducing it.

**Comment by SG60** [comment]
Thanks for the reply. It's not happening at the moment. When it happens seems fairly random and I'm not sure what causes it. I'll comment on this issue if the problem appears again.

I'm on the chromium-based Microsoft Edge if that makes any difference.

**Comment by SG60** [comment]
Closing this as it hasn't happened since December.
