### ISSUE TITLE
Help/Latest Updates → “Document deleted” 

### ISSUE THREAD

**Issue by ognsya** [remnoteio/remnote-issues#1231]
Navigating to Help/Latest Updates leads to “Document deleted”.

Happens only when I have Windowed Panes option enabled in Labs.

Related: https://forum.remnote.io/t/help-updates-document-deleted/4866

**Comment by talenelat-elin** [comment]
Probably a duplicate of #1173

**Comment by hannesfrank** [comment]
Thanks for the report @ognsya and the duplicate detection @talenelat-elin :) This should be fixed in v1.3.13.
