### ISSUE TITLE
Reference context menu stopped working since Version 1.3.13

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#1239]
None of the actions in the rem reference work after the Version 1.3.13 update. Below is the demonstration of 'copy reference to clipboard', but nothing in that context menu works.

![copy_reference_to_clipboard](https://user-images.githubusercontent.com/24322880/120879049-79c91980-c575-11eb-880d-b38b6b070cd4.gif)

**Comment by sjy19980901** [comment]
Hi, I also encountered this problem after the update today. Now I have solved it by accident. The details are as follows:
Open Remnote on your desktop, then open the Remote PWA app and you'll be done.
Both programs must be open.

**Comment by sjy19980901** [comment]
Need to be used on PWA applications

**Comment by anishaaa1** [comment]
I have this issue as well.
Device and OS specs: MacOS Big Sur | Desktop App Version 1.3.13 (same as OP)

**Comment by tfiwm** [comment]
Cl
