### ISSUE TITLE
Aliases don't work

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#1243]
https://user-images.githubusercontent.com/8283298/120899506-f7e5f880-c627-11eb-97b3-3e7b02e4057d.mov

**Comment by tfiwm** [comment]
This looks like a subset of [#1239 - Reference context menu stopped working since Version 1.3.13](https://github.com/remnoteio/remnote-issues/issues/1239)

**Comment by Gabriela-AD** [comment]
Ported:

Pressing Enter for Alias -> Error
![image](https://user-images.githubusercontent.com/72152979/120955299-f6f8b800-c748-11eb-8b7d-b6d556a1e36f.png)

**Comment by Gabriela-AD** [comment]
Ported:

Mac
![image](https://user-images.githubusercontent.com/72152979/120956761-29f07b00-c74c-11eb-9017-b4dec53b8bc0.png)
