### ISSUE TITLE
Missing flashcards

### ISSUE THREAD

**Issue by faerch90** [remnoteio/remnote-issues#125]
**Describe the bug**
Some flashcards doesn't make it into the queue. There is no pattern that i can see, but when you look at the data page is next practice should have happened in the past.

**To Reproduce**
Create a rem flashcard with ::
Wait and see if it shows up for practise.

**Expected behavior**
I would expect that every time i use :: the flashcard would appear in the queue

**Screenshots**
![image](https://user-images.githubusercontent.com/65782471/94420727-dc674b80-0184-11eb-8620-197e12e00e39.jpeg)
I have never seen the card in my queue even though it saids that i hit solid. Its like its been skipped. At this moment my queue is empty.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: 85.0.4183.121

**Smartphone (please complete the following information):**
 - Device: iphone se
 - OS: ios 14
 - Browser: safari
 - Version: 

**Additional context**
Edit: I have tried to isolated a document with a few rem and tried to "practice without spaced repetition". No cards show up in the queue.

**Comment by tfiwm** [comment]
Just wanted to say that I have been chasing this down for months now. Like stated here, it is hard to find a pattern. The closest I could find was, if we create cards and try not to edit or access those cards then the probability of that card not showing up in the queue is high.

**Comment by karnikram** [comment]
This is a recurring issue for me as well.

Ex:
![Screenshot from 2020-09-30 10-25-52](https://user-images.githubusercontent.com/12653355/94644678-94246680-0307-11eb-9382-287c2b4de103.png)

 I have to make an edit to the card or practice within the document directly for the card to show up on my queue.

**Comment by faerch90** [comment]
Just a little update:
I created 12 flashcards in a daily doc through a portal today. Only 8 showed up in the queue even when i tried to force it with "practice all". I had to go through and find the ones that where missing, remove :: and make it a flascard again. Then they showed up.
I think you guys are doing an amazing job. But this is introducing ALOT of friction in my workflow.
Thanks for all your hard work!

**Comment by Sreyas-Sivaanand** [comment]
Yeah this is a serious bug. I created around 15 to 20 cards. Only 2 showed up and even when i practiced it without spaced repetition only 2 showed up. 
No of cards (around 6 or 7)
![image](https://user-images.githubusercontent.com/72657387/95655945-8ac9a400-0b28-11eb-9be0-f02cd606e08f.png)

same while practising without spaced repetition (only 2)
![image](https://user-images.githubusercontent.com/72657387/95655975-b9477f00-0b28-11eb-8952-2e7a3046bec9.png)

**Comment by karnikram** [comment]
One other way to fix this (apart from editing the rem's content) is to look for cards under `remnote.io/cards` that are not marked as 'Active' and activating them again. But I'm still not sure why they go inactive.

**Comment by mfranzs** [comment]
Very sorry for the delay - we've been having trouble reproducing this to track it down. 

Do any of you happen to have an account with no private information, where you'd feel comfortable sending us a full raw backup? I normally wouldn't ask for this, but we've been having trouble tracking down this issue. Feel free to say no, especially if you have anything remotely private. If you're okay with this, please download a "Full Raw Backup (JSON)" backup from https://www.remnote.io/export and email it to us at support@remnote.io . Thanks!

**Comment by tfiwm** [comment]
@mfranzs  what if we create a dummy account, create some rems in it (maybe use API to automate that). Make sure that we have Rems with all combinations of Rem types and content types. Then do all the reviews for the first day, then skip one day, then do half the reviews the next day (letting some of them lapse). Then let it sit there for few days and then check. I am hoping that would reproduce the issue.

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
