### ISSUE TITLE
Cursor getting stuck when holding up/down arrow keys

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#126]
Notice how `.rem-container--focused` moved to `s2` while the cursor is still on `Multiline`. The cursor can't be moved with arrow keys after it happened. 
![hold down up](https://user-images.githubusercontent.com/4137110/94528551-d8950100-0238-11eb-8b16-b089314882f8.gif)
It might be a timing issue caused by my slow laptop. Haven't tested elsewhere yet.

**Comment by drkvj** [comment]
Unable to reproduce this at this point, kindly make a new report on the forum and we can explore this further thanks!
