### ISSUE TITLE
Unable to log in and log out on multiple devices 

### ISSUE THREAD

**Issue by parakayw** [remnoteio/remnote-issues#127]
**Describe the bug**
Unable to log in on multiple devices. Oddly it automatically logs me in on my desktop but I am unable to log out. When attempting to log in on other devices the screen is a perpetual state of loading and syncing. I have the same issue when trying to log out of the desktop, it perpetually is attempting to log out and sync but never succeeds. 

*
**Expected behavior**
I expect automatic syncing when logging in and out of remnote. 

![image](https://user-images.githubusercontent.com/65185185/94589101-7644fc00-024a-11eb-868e-4a1afee0e601.png)

**Desktop (please complete the following information):**
 - OS: PC and Ipad
 - Browser Tried multiple browsers but the main one is chrome

**Additional context**

**Comment by mfranzs** [comment]
Thanks for reaching out. Are you still having this issue if you try again? If so, can you please email us the debug log from https://www.remnote.io/download_sync_debug_log to support@remnote.io?

**Comment by mfranzs** [comment]
I believe that this is fixed as of the October 26th 2020 update.
