### ISSUE TITLE
Daily documents - out of order

### ISSUE THREAD

**Issue by faerch90** [remnoteio/remnote-issues#128]
**Describe the bug**
Almost every time i get an update, the order of the daily document gets completely scrambled.

**To Reproduce**
No way for me to reproduce. But it happens every time an update hits or the server has been down.

**Expected behavior**
All of the daily document should be in order of date created. The auto sort power-up has no effect for some reason.

**Screenshots**
I will provide one if needed.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: 85.0.4183.121

**Smartphone (please complete the following information):**
 - Device: iPhone se
 - OS: ios 14
 - Browser safari
 - Version 

**Additional context**
Its really hard to keep an overview of week and months with just a long list of dates. Maybe some improvements could be made here?

**Comment by drkvj** [comment]
Thanks for submitting this, and apologies for not responding sooner, we are now cleaning up all the reports, to make sure this can be an efficient process from now
Have you been noticing such behaviour still? Kindly follow this discussion on the forum, where we will be actively handling such matters from now on.
Also, kindly submit your ideas for improvement as a feature request on the forum.
