### ISSUE TITLE
I can‘t scroll up and edit

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#129]
**Describe the bug**
When I try to scroll up to the upper part of the page and then click on the text, so that I can edit it, I get transported to back where my cursor last was instead
**To Reproduce**
1. Write or copy paste(that's what I did) a long text into a single bullet point
2. Click somewhere in the text
3. Scroll up to and try to click somewhere else

**Expected behavior**
When I click on another part of the screen, I expect to see the cursor where I clicked on
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/94617211-83450800-02a9-11eb-944e-0c3ea0a4a379.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 14.0.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
