### ISSUE TITLE
"Help & Tutorials" button doesn't work

### ISSUE THREAD

**Issue by metamas** [remnoteio/remnote-issues#1298]
**Describe the bug**
Selecting the "Help & Tutorials" option from the "?" menu does nothing.

**To Reproduce**
1. Go to the "?" menu in the bottom right corner of any page
2. Click on the "Help & Tutorials" option
3. Nothing happens; The "Help & Tutorials" page is not displayed

**Expected behavior**
I expected some type of local Help document to appear, or a web page to open.

![image](https://user-images.githubusercontent.com/2520253/128921860-8d45b09d-588c-454d-b85e-1b60cd302d47.png)

**Desktop**
 - OS: macOS 11.5.1
 - Version: RemNote 1.3 (native)

**Comment by Gabriela-AD** [comment]
Ported:
> Operating System: MacOS Catalina
> "when I right-clicked "Help & Tutorials" (which doesn't work), I saw that it was linking to a file location that doesn't exist (file:///help)."

Able to replicate on the Desktop App, on Windows. This seems to be a widespread bug.

**Comment by metamas** [comment]
This has been fixed in the recent update 👍
