### ISSUE TITLE
New Documents not on the sidebar

### ISSUE THREAD

**Issue by krzysztofsobczak** [remnoteio/remnote-issues#13]
**Describe the bug**
When I create a new document or a folder it is not appearing on the sidebar. 

**To Reproduce**
1. Create a new document or folder
2. Mark it as document

**Expected behaviour**
Created document is visible on the sidebar

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser new Edge
 - Version: 84.0.522.52 (Official build) (64-bit)

**Comment by mfranzs** [comment]
Resolving in #14
