### ISSUE TITLE
Settings options are partially cut off with the new UI

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#130]
**Describe the bug**
It's kinda a visual bug but part of the right side of settings isn't visible because of the new UI
**To Reproduce**
1. Go to settings
2. See error

**Expected behavior**
I don't want that cut off, maybe make settings its own page again and not just a pop up, make the pop up bigger or let me scroll horizontally
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/94618785-04050380-02ac-11eb-81ec-bc25ba3836ee.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: ios 14.0.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.

**Comment by 8888Daniel8888** [comment]
Really minor thing that doesn't even matter but the keyboard options are still cut off on the mobile version![image](https://user-images.githubusercontent.com/69430941/95287771-1a403000-0867-11eb-9d9a-d8a9f97c464e.png) won't be reopening because it doesn't affect my workflow but still going to mention it for the weirdos using an external keyboard with their phone (if that's even possible)

**Comment by mfranzs** [comment]
Have you requested the desktop view here? The side panel is supposed to
move to the top on mobile.

**Comment by 8888Daniel8888** [comment]
That screenshot is the mobile view. Everything else not cut off btw

**Comment by 8888Daniel8888** [comment]
![image](https://user-images.githubusercontent.com/69430941/95289856-1b279080-086c-11eb-9040-779b226ccc24.gif) see? The placing of the side panel doesn't bother me tbh. It does look a little cramped but it's ok
