### ISSUE TITLE
 Freezes when pressing the customize button

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#131]
**Describe the bug**
Remnote tab freezes when entering customize section

**To Reproduce**
1. I go to the main medicine folder
![image](https://user-images.githubusercontent.com/20538090/94619513-b42b3a00-02b5-11eb-8456-ae921182f4c9.png)
2. Click on customize button
3. See problem
![image](https://user-images.githubusercontent.com/20538090/94619581-c907cd80-02b5-11eb-9415-f871cd214f7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.53

**Comment by mfranzs** [comment]
Thanks for the report. To clarify, the documents listed in "Documents/Folders With This Scheduler" are erroneous, correct? (You didn't add them yourself.)

**Comment by Eikosa** [comment]
it shows all rems in the document (i think), normally this shouldn't happen because I am already scheduling a parent document

**Comment by drkvj** [comment]
Unable to reproduce this at the moment, kindly revert back with a new discussion on the forum if you are still experiencing such behaviour. Thank you for the report!
