### ISSUE TITLE
lists appear as multilines

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#132]
**Describe the bug**
when you create a list inside a multiline, the list looks just like a multiline until you zoom into it

**To Reproduce**
1. create a document
2. create a multiline
3. create a list inside the multiline

**Expected behavior**
I want to see the numbers that are usual for lists. It is kinda confusing and looks like a visual bug
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/94738393-a1753b80-036f-11eb-961e-bde263d82c1e.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: 14.0.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
