### ISSUE TITLE
clicking on “Make Rem Reference“ is buggy

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#133]
**Describe the bug**
when I click the aforementioned option out of the popup window that appears when you select text, it selects instead of opening the popup for referencing 
**To Reproduce**
1. select a rem
2. Click on “Make Rem Reference“
3. See error

**Expected behavior**
the popup window that suggests references should appear
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/94739597-84da0300-0371-11eb-8143-ebabdcf46b47.gif)
**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: ios 14.0.1
 - Browser safari
 - Version 14

**Additional context**
This bug is rather old, I just never had the time to report it

**Comment by drkvj** [comment]
@8888Daniel8888 thanks for the report, can you confirm if this bug is still persistent?

**Comment by 8888Daniel8888** [comment]
No I'm pretty sure it's been fixed
