### ISSUE TITLE
The reference suggestions does not work properly

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#134]
**Describe the bug**
A reference seems to be missing in the popup window for “Make a reference“ unless I delete enough letters. It does not really make sense why it is not suggested in the first place
**To Reproduce**
1. Click on “Make a reference“
2. look for a suggestion that is exactly the same word and also the top level rem
3. See error

**Expected behavior**
I do not understand why the same exact word is not being suggested, as it intuitively should
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/94741183-0c287600-0374-11eb-9284-1be11dbe0642.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iOS 14.0.1
 - Browser safari
 - Version 14

**Additional context**
edit: the cause of this might be that the suggestion I am looking for is the top level rem, I did not pay attention to that, it still seems a little weird

**Comment by mfranzs** [comment]
I believe that this Rem does not appear at first simply because the maximum # of search results are already being returned. However, some of these results look odd to me - could you please paste the accented a character here so we can check if that's causing the problems?

**Comment by 8888Daniel8888** [comment]
You mean this? ä

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
