### ISSUE TITLE
Rem and list issue

### ISSUE THREAD

**Issue by adr123** [remnoteio/remnote-issues#136]
**Describe the bug**
Creating a new rem with a name, content, and a numbered rem under it will cause the rem's content to blink inconsistently.

**To Reproduce**
1. Make a new rem, give it a name and a content (Can only be using the :: seperator). 
2. Then create a new rem subordinate to the one you created in step 1, and make it a numbered rem using /list and clicking on the "Turn into a list item"
3. Wiggle your cursor in long strokes near the rem you created in step 1, maybe gloss over the rem rapidly. Notice how the content blinks.

**Expected behavior**
I expected no blinking to happen when I created these rems.

**Screenshots**
![image](https://user-images.githubusercontent.com/24881520/94753121-7debca00-034a-11eb-94b5-3662960d5fef.png)
![image](https://user-images.githubusercontent.com/24881520/94753129-83491480-034a-11eb-82ac-bf49fea6def1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 85.0.4183.121

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
