### ISSUE TITLE
Right-click menu of references disappears before you can click anything on it

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#137]
**Describe the bug**
The title is self-explanatory but when I right-click on a reference to click the 'Show Content' or any other button in the menu that appears, as soon as I move the cursor towards the menu, it disappears before I can click anything.

**To Reproduce**
1. Right-click on a reference
2. Attempt to move the cursor towards the right-click menu
3. Observe that the menu disappears before you can reach it

**Expected behavior**
The menu should stay on-screen until I've clicked something in the menu or clicked outside of it to exit the menu.

**Screenshots**

![ezgif-3-8ba10fa8bfa1](https://user-images.githubusercontent.com/68901589/94779280-be455980-03d7-11eb-819a-dc8bab5411c2.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Comment by mfranzs** [comment]
Thanks for reaching out. The right click menu looks strangely far away from where you click here. Do you have any custom CSS, or does this change if you zoom in and out?

**Comment by anishaaa1** [comment]
> Thanks for reaching out. The right click menu looks strangely far away from where you click here. Do you have any custom CSS, or does this change if you zoom in and out?

I was zoomed in at the time of recording this, which is probably why it appears so far away. Is that why it disappears when I try to hover towards it?
Thanks!

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
