### ISSUE TITLE
Does not cancel previous markup when returning to question

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#138]
**Describe the bug**
When I mark one question and move on to another question, it continues the marking I made before and increases it gradually

**To Reproduce**
1. Go to queue
2. Click show answer button
3. Click easy
![image](https://user-images.githubusercontent.com/20538090/94858645-09915380-043c-11eb-8073-99b605485a32.png)
4. Click back button top left corner of the queue
5. Click show answer button
6. Now when you look at the time under the easy button again you will see that it has increased.
![image](https://user-images.githubusercontent.com/20538090/94858669-1150f800-043c-11eb-9207-810b994e7dd8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 86.0.4240.68

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
