### ISSUE TITLE
LaTeX texts shake on hover

### ISSUE THREAD

**Issue by colorizer** [remnoteio/remnote-issues#139]
While moving the mouse over the rems containing LaTeX equations, the text wiggles to the left and right. This is uncomfortable to use. [Note: No other plugin or CSS has been used]

**Steps to reproduce the behavior:**
1. Create any Rem which contains latex codes.
2. Finish the rem and move to next line.
3. Move mouse over the lines containing these equations.
4. The text wiggles sideways.

**Screenshots**
![Peek 2020-10-02 14-15](https://user-images.githubusercontent.com/64630824/94906046-726be080-04bb-11eb-850e-df18dcfcacc2.gif)

**Desktop:**
 - OS: Kubuntu 20.04
 - Browser: Firefox 
 - Version 80.0.1

**Additional context**
Similar shake has been observed while hovering over the documents list in the sidebar. May be it is connected to this bug. 
![Peek 2020-10-02 14-13](https://user-images.githubusercontent.com/64630824/94906074-7f88cf80-04bb-11eb-8366-1e4c164160c2.gif)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
