### ISSUE TITLE
Draft and Finished categories have a wrong title on the sidebar

### ISSUE THREAD

**Issue by krzysztofsobczak** [remnoteio/remnote-issues#14]
**Describe the bug**
Draft and Finished categories have a wrong title on the sidebar, it is "Empty Search Portal"

**To Reproduce**
1. Have a document marked either as Draft or Finished

**Expected behavior**
Document is under the correct category on the side bar

**Screenshots**
<img width="220" alt="remnote bug" src="https://user-images.githubusercontent.com/11649630/89129608-7c428900-d4f6-11ea-886d-fe2588f04d11.png">

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser new Edge
 - Version 84.0.522.52

**Additional context**
Possibly related to #13

**Comment by mfranzs** [comment]
This sounds like an error specific to your account's sidebar. Can you please follow these steps?

1) Press "Ctrl + O".
2) Search for "Document Sidebar".
3) Press the "Restore default sections" button at the top of the page that opens.

**Comment by krzysztofsobczak** [comment]
Yes, that worked, thanks.
