### ISSUE TITLE
Terminating a Cloze with }} creates two more Clozes

### ISSUE THREAD

**Issue by colorizer** [remnoteio/remnote-issues#140]
**Describe the bug**
When I create cloze on the go using '{{', if I try to end the cloze using '}}' it results in two more new Clozes.

**To Reproduce**
1. Go to any rem.
2. Start a Cloze using {{
3. Type your content
4. End the cloze using }}

**Expected behavior**
There will be two more blank clozes next to the one you've created.

**Screenshots**
![Peek 2020-10-02 14-41](https://user-images.githubusercontent.com/64630824/94907172-5d904c80-04bd-11eb-944c-c5e47ea23a94.gif)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - Browser: Firefox
 - Version: 80.0.1

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
