### ISSUE TITLE
Tab Key to move out of LaTeX or Cloze or any other inline blocks

### ISSUE THREAD

**Issue by colorizer** [remnoteio/remnote-issues#141]
**Is your feature request related to a problem? Please describe.**
I've been using the LaTeX and Cloze features for a while. While creating either of those, one could notice that, it automatically generates the end brackets.
For example, while creating LaTeX code using '$$', the Remnote automatically generates the $$ after the cursor so that even if I click outside the block, the code won't throw any error. However, I have to type out '$$' anyway to end the block. Or use the mouse which is cumbersome.
Also, when creating cloze, if I try to end it with }}, it results in a bug (already reported).

**Describe the solution you'd like**
It would be great if I could press "Tab" key to move the cursor after the '$$' that Remnote generates at the end. Currently, Tab key indents the Rem even when inside the block.

**Describe alternatives you've considered**
Another solution will be the obvious "End" key. But still, while typing fast, Tab key is the one which is comfortable to use.

**Additional context**
A screenshot of current behaviour.
![Peek 2020-10-02 14-59](https://user-images.githubusercontent.com/64630824/94908958-0d66b980-04c0-11eb-8b12-165f763702d7.gif)
Here is a screenshot from Vim in which I use Tab key to move out of the latex block
![Peek 2020-10-02 15-02](https://user-images.githubusercontent.com/64630824/94909175-6e8e8d00-04c0-11eb-97c5-70bf690650f0.gif)

**Comment by mfranzs** [comment]
We've implemented this in the latest update, with the `Esc` key to exit a LaTeX block.
