### ISSUE TITLE
Copying References slash commands missing

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#143]
There are 3 keyboard shortcuts, but only one slash command for a linking related rem copy. And the slash command has a different name.

**Keyboard:**

![image](https://user-images.githubusercontent.com/4137110/94992445-5f741180-058a-11eb-9ac5-bac7038771a0.png)

**Slash commands:**

![image](https://user-images.githubusercontent.com/4137110/94992440-5420e600-058a-11eb-878b-e3aa63b6f262.png)

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
