### ISSUE TITLE
Hide parents & siblings only hides parents, not siblings

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#145]
Hide parents & siblings only hides the parents.

Hide siblings works expected.

![033961c7-78d3-44e4-85ca-fb88c5eb7288](https://user-images.githubusercontent.com/4137110/95025139-04c0df80-0688-11eb-941d-0c31789c7340.gif)

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
