### ISSUE TITLE
No difference between spaced repetitions and non-spaced repetitions in Image Occlusion

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#146]
1. Create a image occlusion rem
2. Practice without spaced repetition
3. Now if you go to the metadata you can see that it is added to a later time, just like in spaced learning. Normally such a thing should not have happened

**Comment by mfranzs** [comment]
Thanks for reaching out. Practicing without spaced repetition still counts as a practice session, and you're awarded an increased interval accordingly. The change with "practice without spaced repetition" is that it will show all cards even if they're not in your queue. When selecting the next interval, the scheduler tries to take the fast that the previous interval has not yet fully elapsed, and we'll be fine-tuning that in the future as well.
