### ISSUE TITLE
Each sub-rem under the flashcard rem becomes a flashcard when indented

### ISSUE THREAD

**Issue by donny741** [remnoteio/remnote-issues#1474]
**Describe the bug**
When indenting a rem under the flashcard rem, it automatically generates new flashcard for upper rem

**To Reproduce**
1. Create a flashcard rem
2. Add two rems under the flashcard
3. Indent the second rem

**Expected behavior**
Second rem becomes a sub-rem of the first rem, but first rem does not become a flashcard.

**Screenshots**
![ezgif com-gif-maker-2](https://user-images.githubusercontent.com/20892205/145898131-9d97be7e-c93e-4f72-9d84-f36b2e5e7ff6.gif)

**Desktop (please complete the following information):**
 - OS: macOS 11.6.1
 - Native app. V1.5.0

**Context**
I've noticed this problem some time after 1.5.0 update

**Comment by TaQuangKhoi** [comment]
It will be fixed on v1.5.1..
If your are Pro/LLL user, you can try v1.5.1 on beta.remnote.io
