### ISSUE TITLE
Edit later

### ISSUE THREAD

**Issue by andfsilva** [remnoteio/remnote-issues#15]
**Describe the bug**
In the sidebar appears one document as edit later. When I click in edit later, there´s nothing in the document "edit later".
First noticed the issue: first of august.

**Screenshots**
Side bar:
![image](https://user-images.githubusercontent.com/68829450/89137981-5c1fc380-d510-11ea-97e8-6ec507fd6be5.png)

In the document:
![image](https://user-images.githubusercontent.com/68829450/89138001-6b067600-d510-11ea-86c5-30f9a2441076.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 84.0.4147

**Comment by mfranzs** [comment]
Thanks for the report. If you press the "refresh" icon on the right, do you see any change?

**Comment by andfsilva** [comment]
Sorry Martin,
Where is this refresh icon?
I refreshed the portals and nothing different happened.
I also clicked on the icon to the left of "Edit later" and on the number (1) and nothing different happened.
Att,
Anderson

________________________________
De: Martin Schneider <notifications@github.com>
Enviado: terça-feira, 4 de agosto de 2020 05:09
Para: remnoteio/remnote-issues <remnote-issues@noreply.github.com>
Cc: andfsilva <andersonsilva85@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [remnoteio/remnote-issues] Edit later (#15)


Thanks for the report. If you press the "refresh" icon on the right, do you see any change?

**Comment by mfranzs** [comment]
(Resolved externally.)
