### ISSUE TITLE
Unnecessary Gap

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#150]
![image](https://user-images.githubusercontent.com/20538090/95138447-e97ece80-0772-11eb-8cc1-ec02062c0849.png)

There is an unnecessary gap at the bottom of the document, I don't know how it occurs, but I guess it happened because i hid the children rems.

**Comment by moritzWa** [comment]
Could you elaborate on what you mean by an _unnecessary gap_? Perhaps highlight it in your screenshot. Otherwise, I'd close this issue.

**Comment by Eikosa** [comment]
https://mega.nz/file/61FzBQyI#FHw6s-zV-KFIpE2G22vyWrIltJp6BMD41L6SkUfUMi8
You can review the video

**Comment by moritzWa** [comment]
Thanks! This should not happen. I see you have modified the CSS. Does this issue go away when you disable those modifications. If yes, please contact the developer of this plugin/CSS extension with your issue.

**Comment by Eikosa** [comment]
https://www.remnote.io/a/5fca9711596ee400450d943d
Unfortunately my problem is not solved, this is the buggy document

**Comment by Eikosa** [comment]
but now when I look from the incognito tab, I see that there is no problem. I did not understand

**Comment by moritzWa** [comment]
Please check your chrome extensions.

**Comment by drkvj** [comment]
If you are still facing such issues, kindly make a new bug report on the forum where we can explore this further and try to reproduce the bug
