### ISSUE TITLE
Import published document to my account does not work

### ISSUE THREAD

**Issue by tspng** [remnoteio/remnote-issues#151]
**Describe the bug**
Import published documents (from https://www.remnote.io/community) to my account does not work.

**To Reproduce**
1. Go to https://www.remnote.io/av/recitation-1-big-o-notation/3JMvvg2a8pFLpTqm5 for example
2. Click on *Import it to your own account* link in document
3. Open web browser's developer console
4. See error (`Uncaught (in promise) ReferenceError: CURRENT_USER_REM_COLLECTION is not defined`)

**Expected behavior**
The document should be imported into my account.

**Screenshots**
![Screenshot 2020-10-06 at 10 40 34](https://user-images.githubusercontent.com/293209/95179018-61bfb100-07c0-11eb-9c52-01a5a6d7360c.png)

**Desktop (please complete the following information):**
 - OS: macOS v10.15.7
 - Browser: Google Chrome
 - Version: Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
I also tried to logout and login again, as well as using incognito mode but the issue remains.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
