### ISSUE TITLE
Changing the document status of a folder makes it vanish from the side bar

### ISSUE THREAD

**Issue by ArthurusDent** [remnoteio/remnote-issues#1523]
**Describe the bug**
I changed the document status of a folder in my side bar and now it's not being listed anywhere anymore. Thankfully it's still in "All Notes".

**To Reproduce**
1. Right-click on a folder in your sidebar.
2. "Change Document Status" --> Choose a different status.
3. The folder vanishes.

That's how the folder looks like:

![Screenshot 2022-02-08 125539](https://user-images.githubusercontent.com/6848629/152982806-b6a8c6e6-02e4-431d-bcdd-0e1b3a408480.png)

**Expected behavior**
The folder should turn up in the correct new place.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - happened in the Desktop App, can't be reverted either in the App or in Chrome
 - Version 1.6.5

**Smartphone (please complete the following information):**
Not tested.

**Comment by TaQuangKhoi** [comment]
Fixed in 1.6.6
