### ISSUE TITLE
keyboard randomly pops up

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#154]
**Describe the bug**
I don't know what triggers it but at times, the slightest touch makes the keyboard pop up. This is happening on the mobile version. Other random things are happening too, like something in the toolbar popping up, it's really weird

**To Reproduce**
1. Try to scroll through text, slightly vary how long you hold. (Possible bug might be that the sensitivity was overdone way too high. It led to quite a few miss edits that I can't find anymore)
2. See error

**Expected behavior**
While simply scrolling, I don't want the keyboard to pop up every time
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/95301357-ca6e6280-0880-11eb-8aa9-3c83424a00aa.gif)
![image](https://user-images.githubusercontent.com/69430941/98458996-87acec80-2196-11eb-9f11-acfcae9d2975.gif)
**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.1
 - Browser safari
 - Version 14

**Additional context**
This bug report is a month old now but I made some updates in the hopes that it will get fixed soon. I'm very surprised that there aren't any other reports on this issue, because together with https://github.com/remnoteio/remnote-issues/issues/185 I find these issues to be the most annoying to deal with

**Comment by mfranzs** [comment]
Thanks for the report. Are you still encountering this issue after the November 17th Update?

**Comment by 8888Daniel8888** [comment]
No, not anymore
