### ISSUE TITLE
Arrow Navigation not possible in WBA 

### ISSUE THREAD

**Issue by JJger148** [remnoteio/remnote-issues#155]
**Describe the bug**
I can’t use the arrows to navigate in the WBA on IPadOS 14. Also using my mouse to klick into other rems does not work.

**To Reproduce**
2. Click on ‘another rem'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IPadOS 14
 - Browser: Safari WBA

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
