### ISSUE TITLE
Card counter resetting at inappropriate times

### ISSUE THREAD

**Issue by adr123** [remnoteio/remnote-issues#156]
**Describe the bug**
The counter of studied cards will reset at around 12pm CST every day. More specifically, the card counter will start going down around 30 minutes before 12pm CST, and by 12 they would all be gone.

**To Reproduce**
Study cards and wait till 12pm CST.

**Expected behavior**
I expected the card counter to preserve its information throughout the full day, resetting only at around ~12am CST.

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.111

**Comment by mfranzs** [comment]
Thanks for reaching out. May I ask what time zone you're in? (Is it CST?)

**Comment by adr123** [comment]
Yes its CST

**Comment by adr123** [comment]
Happened again today, I studied ~80 rems at around 7-8am CST, and then I check my cards again at 1:20pm to see the card tracker reset to 0.

**Comment by adr123** [comment]
Today I completed 83 cards at around 7am (CST) and went to check up on remnote a few minutes ago (~11:36AM). I saw that the card counter had decreased by around 40 cards, and then it continued to go down to 29 cards by 11:43AM.

**Comment by drkvj** [comment]
Thanks for submitting this, and apologies for not responding sooner, we are now cleaning up all the reports, to make sure this can be an efficient process from now
Have you been noticing such behaviour still? Kindly follow this discussion on the forum at this related [topic](https://forum.remnote.io/t/documenting-issues-related-to-inconsistencies-in-the-queue-behaviour/3569?u=karthikk), where we will be actively handling such matters from now on.
