### ISSUE TITLE
Power-up "Automatically Add Template" not applied

### ISSUE THREAD

**Issue by jmourelos** [remnoteio/remnote-issues#157]
**Describe the bug**
When trying to apply the Power-up "Automatically Add Template", the Power-up "Automatically Sort" is applied instead.

**To Reproduce**
1. Go to a document containing a Rem
2. Click on right side of the Rem
3. Type '/template'
4. The Power-up "Automatically Add Template" will be the only choice visible
5. After applying it, on the right side of the Rem the Power-up will show up "Automatically Sort"

**Expected behavior**
When choosing the Power-up "Automatically Add Template", that should be the Power-up applied.

**Desktop:**
 - OS: Mac OS 10.15.7
 - Browser chrome
 - Version 85.0.4183.121

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
