### ISSUE TITLE
RemNote Stuck automatically logging me out and failing to sync.

### ISSUE THREAD

**Issue by RuiRojo** [remnoteio/remnote-issues#159]
**Describe the bug**
RemNote stuck constantly trying to log me out and I can't get it to sync before doing so, so I get stuck in the loop.

**To Reproduce**
This seems to happen quite reliably when I change my IP, like when connecting/disconnecting from a VPN.
However, I am pretty sure it doesn't _only_ happen when I do that while having remnote open.

**Expected behavior**
Well, it would be best to have it seamlessly work regardless of the IP change. But most importantly, the loop should not happen. Would it make sense for remnote to allow logging out without syncing, but keep the info in the browser for the next log in?
Is the "export as JSON" a reliable alternative for this?

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Brave Browser
 - Version: 1.14.84

**Comment by mfranzs** [comment]
Thanks for reaching out.

1. To clarify, RemNote is _automatically_ logging out without you pressing the "Logout" button, correct?
2. Do you get stuck on the "Logging Out" page? If so, what step do you get stuck on?

Thanks,
Martin

**Comment by RuiRojo** [comment]
1. Yes

2. I can't reproduce it right now (which gets my hopes up!) so don't trust the details of my answer here. It starts by just leaving me at whatever rem I was, but toggling every half second to offline mode, and not deciding whether I'm logged in or not (as shown in the top of the sidebar). At this point it is not possible to work (but one can still go into the settings and export). There's no way to sync. If I succeed in clicking to log out, then I get the warning that I should sync first or I will lose all the changes. Reloading doesn't fix it.

**Comment by RuiRojo** [comment]
It just happened again now, for the first time from the Progressive Web App, and it was out of the blue, without changing my VPN status (I was connected though).

**Comment by mfranzs** [comment]
To confirm, have these issues stopped after the October 26th update?

**Comment by RuiRojo** [comment]
I haven't had this problem since the update! I'll post an update if it happens.

**Comment by mfranzs** [comment]
Great, thanks!
