### ISSUE TITLE
Cannot recognize header level when import markdown files 

### ISSUE THREAD

**Issue by e0ns** [remnoteio/remnote-issues#16]
When you import markdown files, RemNote cannot indent the content according to the header level in the original markdown files, and the sequence of lines is different from the original one. 

![image](https://user-images.githubusercontent.com/38707987/89140897-88216000-d575-11ea-87e6-0eb070c35c63.png)
You got this:
![image](https://user-images.githubusercontent.com/38707987/89140910-940d2200-d575-11ea-9c1b-ef01696d9e8d.png)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and will deploy our fix soon.
