### ISSUE TITLE
Visual glitch when selecting something in the sidebar

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#160]
**Describe the bug**
When I click on something in the toolbar, a bullet point randomly appears under my cursor
**To Reproduce**
1. Click on something in the sidebar
2. See error

**Expected behavior**
That bullet point  shouldn't appear
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/95470788-7e571700-0981-11eb-83c5-96467bc20928.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iPadOS 14.0.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
