### ISSUE TITLE
Rem bullets not alligned correctly

### ISSUE THREAD

**Issue by Ryunaq** [remnoteio/remnote-issues#161]
**Describe the bug**
Bullet is not correctly alligned with the 

**To Reproduce**
1. Create a rem (bullet)

**Expected behavior**
Bullet is correctly vertically centered with the text

**Screenshots**
![image](https://user-images.githubusercontent.com/17756312/95485454-5f438f80-0957-11eb-9b3b-06a7087641d7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Not checked

**Fix**
Change the value of `rem-bullet__container` to `margin-top: 5px` instead of the current 3.75. This however will also move non-bullets (such as the document images) so maybe separate the classes and apply this fix.

**Comment by mfranzs** [comment]
Thanks for reaching out. I'm having some trouble reproducing this:
![image](https://user-images.githubusercontent.com/953103/95540401-b3ce2580-09be-11eb-999b-fcb0acc21514.png)

 1. Does this happen for all of your Rem, or only this one? If only this one, what do you have right above?
 2. Do you have any custom CSS?
 3. Is your line spacing set at "Default"?

**Comment by Ryunaq** [comment]
Hey, sorry for the late response. Hmm I find it really weird that you can't reproduce it. 1. It happens for all the Rem, 2. No, 3. Yes.
Just tested it again on incognito tabs on chrome and firefox to be sure (incognito overrides any possible custom modification so it should work as a clean install):

Chrome Version 85.0.4183.121 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/17756312/95796613-f93a6d80-0cb2-11eb-92a9-114e43e15d69.png)

Firefox Version 80.0.1 (64-bit)
![image](https://user-images.githubusercontent.com/17756312/95796473-977a0380-0cb2-11eb-8bdc-97ef449eb826.png)

Maaaybe it is a OS thing? (Though I doubt it) I am using Windows 10. Maybe you have some custom css or maybe the cache of a previous, correct, version?

**Comment by drkvj** [comment]
@Ryunaq If you are still experiencing this issue, we could benefit by porting this report to the forum where there are higher chances of other users providing additional info, which would help us reproduce the bug and fix it. 
Kindly start a bug discussion there, if that's the case. Thank you.
