### ISSUE TITLE
Remnote showing "no cards in this rem" after copy pasting Rem from one document to another

### ISSUE THREAD

**Issue by tobymyers** [remnoteio/remnote-issues#162]
**Describe the bug**

**To Reproduce**
1. Go to a document and make a card like test::testytest
2. Select the whole line with your mouse
3. Hit command x
4. Navigate to another document and hit command v

**Expected behavior**
The copied content appears, however at the bottom of the page when I hover my mouse over the cards icon it gives the message shown in the screenshot below. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11051864/95521793-49e25b80-097f-11eb-94c9-3d346831fb0d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS catalina
 - Browser [e.g. chrome, safari] chrome 
 - Version [e.g. 22] 10.15.6

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for reaching out. To clarify, what Rem is your text cursor focused on when you're hovering over the card icon in the bottom toolbar in this screenshot?

**Comment by tobymyers** [comment]
Ahh Martin, I wasn't hovering over a rem with a :: card in it!  So not a
bug after all.

I am obsessed with Remnote btw.  The week before I discovered it I
literally wrote down in my weekly retro that I needed a note-taking system
with spaced repetition.  I'd been doing it on paper for 2 months and it got
too big to search.  I'm working as a PM and so there's a lot of info, none
of it very difficult to understand, but difficult to synthesize and
remember, so this is a godsend.  Looking forward to getting a good system
set up and being able to make connections 6 months from now that would have
been impossible otherwise.

Also, you all should contact the people behind Learning how to Learn Mooc
on Coursera, because they recommend Anki and it's not nearly as good as
this.  Remnote ties the concepts of chunking and spaced repetition way
better.

**Comment by mfranzs** [comment]
Got it! We'll update the text to make that flow clearer.

That's awesome, I'm glad you found us! Thanks for the pointer - I didn't realize that Oakley's MOOC touched on SRS.
