### ISSUE TITLE
document preview of references is inconsistent

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#164]
**Describe the bug**
When I'm hovering over a reference it often doesn't give me a preview
**To Reproduce**
1. try hovering over a reference multiple times, it doesn't always happen
2. See error

**Expected behavior**
I should consistently get the preview to pop up

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/95562769-e3137f80-0a1c-11eb-9b7c-d2958e99813b.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iPadOS 14.0.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by anishaaa1** [comment]
Can confirm that this happens on MacOS running on Chrome as well - please fix!

**Comment by mfranzs** [comment]
Thanks for the report. Closing in favor of the duplicate #222 .
