### ISSUE TITLE
Pasting codeblocks does not work properly

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#166]
Pasting this

````md
- ```css
* {
  color: blue;
}
```
````

results in this:

![image](https://user-images.githubusercontent.com/4137110/95573264-7b186580-0a2b-11eb-8f39-c8c0ea4603ee.png)

- Blocks as part of a line work fine, but they still do not respect a language hint.
- Multiline blocks do not work at all.

Expected:

![image](https://user-images.githubusercontent.com/4137110/95573453-c2065b00-0a2b-11eb-9f91-2fff4dda58a7.png)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
