### ISSUE TITLE
mobile web can't use "/" and "[["

### ISSUE THREAD

**Issue by logseq20182018** [remnoteio/remnote-issues#167]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for reaching out. These features are not yet supported on the mobile version, but they're on the roadmap to add in the future.

**Comment by logseq20182018** [comment]
thank you!------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Martin&amp;nbsp;Schneider&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月10日(星期六) 凌晨2:08
收件人:&nbsp;&quot;remnoteio/remnote-issues&quot;<remnote-issues@noreply.github.com&gt;;
抄送:&nbsp;&quot;logseq20182018&quot;<1353575360@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [remnoteio/remnote-issues] mobile web can&#39;t use &quot;/&quot; and &quot;[[&quot; (#167)
