### ISSUE TITLE
Remnote hanging/freezing!

### ISSUE THREAD

**Issue by premhessenkamp** [remnoteio/remnote-issues#168]
**Describe the bug**
I have observed two situations where Remnote is constantly freezing up for me.

When I put a double hash to input a tag ##, (a search bar pops up) the moment I start typing after the ## it hangs.
When I put a forward slash / to insert a rem, (a search bar pops up) and again the moment I type it hangs.

Both situations end with my browser saying “Page unresponsive” and I have to exit the pages.
Error code: RESULT_CODE_HUNG is what the browser says.

**Desktop/Browser:**
 - OS: Mac and windows
 - Browser : Chrome and Edge

**Comment by mfranzs** [comment]
Thanks for reaching out. Do you observe the same behavior after refreshing the page and pressing Ctrl + P to open the global search popup?

**Comment by premhessenkamp** [comment]
Yes! Just checked, the same thing happens.

**Comment by premhessenkamp** [comment]
It is worth adding that I recently deleted a document with many thousands of rem. it's been happening since then. Is there a way to clear my trash?

**Comment by premhessenkamp** [comment]
@mfranzs Unable to use Remnote properly for half a month now, could you identify the issue?

**Comment by premhessenkamp** [comment]
Today this message showed up on my Remnote:

"Sorry - You Need to Refresh
A database error occurred in your browser, and you need to refresh.
No need to worry! No data has been lost.
A support ticket has automatically been logged. Additionally, if the problem persists, please contact support.
TimeoutError Transaction timed out due to inactivity."

**Comment by 8888Daniel8888** [comment]
Try deleting your internet history, that solved an issue where RemNote took like 15 mins to load, maybe that trick will work here too

**Comment by premhessenkamp** [comment]
I tried that, I even tried a different computer :-/

**Comment by premhessenkamp** [comment]
I've stopped using remnote as of now due to this bug, but just wondering if this issue is going to be solved in the near future?

**Comment by mfranzs** [comment]
Sorry again about the problems here. Are you still having problems after the latest update?

**Comment by premhessenkamp** [comment]
> Sorry again about the problems here. Are you still having problems after the latest update?
Yes! Still the same problems :(

**Comment by mfranzs** [comment]
If there are still problems here, please email us at support@remnote.io so that we can help debug. Thanks!
