### ISSUE TITLE
Backward preview of cards misaligned

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#169]
**Describe the bug**
When previewing the backward version of a card, I noticed that the entire preview appears misaligned.

**To Reproduce**
1. Hover over the cards button in the bottom toolbar
2. Notice that the backward preview is weirdly aligned

**Expected behavior**
Should be correctly aligned so that information that just fits in the preview so as to not have to scroll does not appear

**Screenshots**

![image](https://user-images.githubusercontent.com/68901589/95658002-b9e01580-0b28-11eb-81dc-93191fc8e603.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by mfranzs** [comment]
I believe that this has been fixed.
