### ISSUE TITLE
Adjust size of flashcard queue

### ISSUE THREAD

**Issue by spintas** [remnoteio/remnote-issues#17]
<img width="1191" alt="Capture" src="https://user-images.githubusercontent.com/69171047/89227104-ed834a00-d591-11ea-9b82-64e2ef6d58b3.PNG">

The flashcard only takes up a portion of the screen. It would be great if there was an expand feature on the bottom right corner to pull the screen larger.

**Comment by mfranzs** [comment]
This is on the roadmap!
