### ISSUE TITLE
Using "[[" (Reference) to create a new rem causes the rem to be created with a space in front even when no space is specified.

### ISSUE THREAD

**Issue by ericaweng** [remnoteio/remnote-issues#172]
**Describe the bug**
Using "[[" (Reference) to create a new rem causes the rem to be created with a space in front (as the leading character), even when no space is specified.

**To Reproduce**
In any Document, use "[[" (or ## depending on your settings) to create a reference to a not-before-created rem.

**Expected behavior**
Not have a space as the leading character of the newly-created Rem, unless explicitly specified.

**Screenshots**
![Screen Shot 2020-10-10 at 8 21 19 PM](https://user-images.githubusercontent.com/12485287/95667608-434a1480-0b36-11eb-882d-2ca3472b959a.png)
![Screen Shot 2020-10-10 at 8 21 36 PM](https://user-images.githubusercontent.com/12485287/95667603-34fbf880-0b36-11eb-9fc8-77397d2455ae.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome 
 - Version: 86.0.4240.75 (latest)

**Comment by mfranzs** [comment]
Thanks for the report Erica! We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
