### ISSUE TITLE
Can't edit document title after creating a new document

### ISSUE THREAD

**Issue by towhid087** [remnoteio/remnote-issues#174]
After creating a new document inside a folder I wasn't able to edit the title of the document. By default, it shows 'untitled'

1. Create a new document.  
2. document title shows "untitled'
3. Try to edit/remoted the text "untitled". It's not doable. I checked the console. This is the error coming up there. 

TypeError: Cannot read property 'updateRemBasedOnProperties' of undefined
    at we.setText (0823639cd92b80af1626e7fd7a1fb340eb9cd081.js:1159)
    at bn (0823639cd92b80af1626e7fd7a1fb340eb9cd081.js:1159)
    at 0823639cd92b80af1626e7fd7a1fb340eb9cd081.js:234
    at 0823639cd92b80af1626e7fd7a1fb340eb9cd081.js:234

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: chrome 
- Version: Version 86.0.4240.75 (Official Build) (x86_64)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
