### ISSUE TITLE
Custom scheduler sync

### ISSUE THREAD

**Issue by faerch90** [remnoteio/remnote-issues#176]
**Describe the bug**
Custom scheduler settings doesn't sync between devices.

**To Reproduce**
Make a custom scheduler on your computer.
Check your mobile device.

**Expected behavior**
If you change scheduler on one device it should be the same for all devices. If two devices runs on different schedules it could mess up the algoritm.. I guess.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.77

**Smartphone (please complete the following information):**
 - Device: iPhone se/iPad 8th gen.
 - OS: IOS 14/iPados 14
 - Browser Safari PWA
 - Version

**Additional context**
When a new schedule is created, it sometimes just changes it to "unnamed" and reset the settings.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
