### ISSUE TITLE
Uppercase and lowercase are not the same

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#177]
i and İ letters is same meaning in my language
![image](https://user-images.githubusercontent.com/20538090/95690809-f8f29180-0c22-11eb-93b8-9edf463f6143.png)
Can't find when I type in lowercase
![image](https://user-images.githubusercontent.com/20538090/95690818-0b6ccb00-0c23-11eb-9bbf-0e02ca9ee230.png)
but it finds if I write it in capital letters

**Comment by mfranzs** [comment]
Thanks for the report. What is the I character that you're typing here? It looks different than "I"; does it have an accent over it?

**Comment by Eikosa** [comment]
No, it is a letter like A or B, not accent character. 
Capitalization of the letter in the picture: İ
Lower letter: i

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
