### ISSUE TITLE
"Search for Document/Rem" fails to open the selected rem

### ISSUE THREAD

**Issue by RuiRojo** [remnoteio/remnote-issues#178]
**Describe the bug**
When searching for a rem with Ctrl+P and then accepting, it is not the proper Rem what gets opened but a document with some (embedded) queue which includes said rem. 

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Browser: Brave Browser 1.14.84

**Additional context**
I don't know how to turn it into a reproducible bug. It's been happening for weeks at least.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
