### ISSUE TITLE
Edit Now Error

### ISSUE THREAD

**Issue by spintas** [remnoteio/remnote-issues#18]
When I click on "Edit Now" it automatically tags the card with #EditLater even though I am editing the card right there and then. I then have to manually delete the **_Message_** text added to the end of my card each time which is extremely burdensome. 
![image](https://user-images.githubusercontent.com/69171047/89227353-608cc080-d592-11ea-9310-0b7e18580146.png)

**Comment by mfranzs** [comment]
Thanks for the report. This should go away if you press "Done Editing" - are you not seeing this?

**Comment by spintas** [comment]
If I press done editing it still remains tagged and in the “Edit Later” queue even though I originally pressed edit now. 

Thanks,
Stephanie Pintas

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
