### ISSUE TITLE
Numbered list appears scrolled down in queue

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#182]
**Describe the bug**
When a numbered list comes up in the queue, the queue first appears blank. It's actually been scrolled down to the bottom by default. You'd have to scroll up but once you've finished say 1., the same happens for 2. and every number that follows.

**To Reproduce**
1. Create a numbered list
2. Reach the associated flashcard in the queue
3. Notice that it appears blank, then scroll up
4. See this bug - you can also click Good and then you'll notice that it does the same for the following numbers
5. Also observe for the auto-scroll down (see **Additional context**)

**Expected behavior**
Numbered list should appear as it used to, i.e. you should be able to see whatever number you're currently at as well as any numbers before it without having to scroll (unless you have a lot of info on there).

**Screenshots**

How it appears at first

![image](https://user-images.githubusercontent.com/68901589/95812637-ec576180-0d26-11eb-8432-6de11d4aafc7.png)

What you have to do for each part of the numbered list (1., 2., 3. ...)

![ezgif-1-29c803563e9d](https://user-images.githubusercontent.com/68901589/95812689-05f8a900-0d27-11eb-8889-37919fa627fa.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 86.0.4240.75 (Official Build) (x86_64)

**Additional context**
If you don't click anything for a while after you've scrolled up, it gets scrolled back down by itself again.

**Comment by mfranzs** [comment]
I'm having some trouble reproducing this - are you still experiencing this? Does this happen for all of your lists, or only some?

**Comment by anishaaa1** [comment]
This still happens and it happens with all my numbered lists 😕

**Comment by anishaaa1** [comment]
I figured it out! It was actually a CSS snippet by Hannes ([Scroll Further Down](https://github.com/hannesfrank/awesome-remnote/blob/master/css/README.md#scroll-further-down)) that was probably breaking something. Once I turned it off, the numbered lists appeared to be fixed.
Thanks anyway!
