### ISSUE TITLE
Wrong Statistics Diagram Type for Actions in Queue etc.

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#183]
This will probably get a rework at some time anyway, but I just wanted to document it:

The diagram for queue actions, queue minutes and both activity by hour graphs should not be a line chart. It is wrong when there are not datapoints, e.g. for practice minutes on skipped practice days:
![image](https://user-images.githubusercontent.com/4137110/95829667-d487d980-0d36-11eb-8a5b-e13053183103.png)

A bar chart for example would fit better.

**Comment by drkvj** [comment]
Kindly make a copy of this to the feature requests on the forum, so that other users can vote as well. Closing this report here.

**Comment by hannesfrank** [comment]
Already done. It's linked on the Stats Page Mega Thread: https://forum.remnote.io/t/improved-and-more-in-depth-statistics-page/2920
