### ISSUE TITLE
Zoom in while editing is annoying

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#185]
**Describe the bug**
Don't know if that's on purpose or a bug but when you click on a rem to edit it, you get zoomed in, which is pretty annoying because you gotta zoom out again every time. This is on mobile, regardless it it's the mobile version or the desktop version
**To Reproduce**
1. Click on a rem to edit it
2. See "error"

**Expected behavior**
I don't want the zoom in because it doesn't help and only disrupts my workflow
**Screenshots**
Various options aren't visible anymore or slightly cut off because of the zoom in
![image](https://user-images.githubusercontent.com/69430941/95863197-31e64f80-0d64-11eb-8fce-d67fedbb65f3.gif)

The frontside of the flashcard is partially cut off and when I want to zoom out to see it completely, the answer gets revealed
![image](https://user-images.githubusercontent.com/69430941/95863481-8d184200-0d64-11eb-92cf-bf5edff72dd8.gif)

The zoom in also cuts off my rating options and when I want to zoom out(which is at times really awkward to do on mobile because sometimes you're using it one handed only, like while lying sideways) my card gets rated due to the swiping feature (please implement a toggle off feature for the swipe rating as well)
![image](https://user-images.githubusercontent.com/69430941/95863687-c781df00-0d64-11eb-9557-b2b87c12a0d2.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.0.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by faerch90** [comment]
+1 from me on this one. It is very annoying 😓

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by 8888Daniel8888** [comment]
The issue is still present for me even after updating ![image](https://user-images.githubusercontent.com/69430941/99560066-bbbdb400-29c5-11eb-86bc-5343b0743468.gif)

**Comment by mfranzs** [comment]
If you click on the "..." on the sidebar, can you please confirm that you see the new logo?

**Comment by 8888Daniel8888** [comment]
![image](https://user-images.githubusercontent.com/69430941/99560657-67670400-29c6-11eb-9f26-35e8b24811f3.gif)

**Comment by 8888Daniel8888** [comment]
I don't know how useful that is, but this seems to be built into ios because that zoom happens on other websites and browsers like chrome. Also some things I found online: https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by mfranzs** [comment]
Do you still have this issue after another refresh?

**Comment by 8888Daniel8888** [comment]
Nope, the issue is gone now I believe

**Comment by mfranzs** [comment]
Great, thanks for helping us work through this!
