### ISSUE TITLE
Copy paste image not working in android tablet and phones (in mobile app and web version)

### ISSUE THREAD

**Issue by arunnbabu81** [remnoteio/remnote-issues#186]
**Describe the bug**
Copy and pasting image in remnote web version using various android browsers not working at all. Android mobile app also has the same complaint. However I was able to copy paste image in web version of remnote using iOS safari

**To Reproduce**
1. Open web version of remnote in android browser ( I tried chrome, Firefox, kiwi , opera, Vivaldi and brave browsers)
2. Copy paste image 
3. No image gets pasted

**Smartphone (please complete the following information):**
 - Device: [Samsung tab s6]
 - OS: [android 10]
 - Browser [chrome, Firefox, kiwi , opera, Vivaldi and brave]
 - Version [android 10]

Please correct it early

**Comment by 8888Daniel8888** [comment]
already made a report on that (although my title could have been more specific) https://github.com/remnoteio/remnote-issues/issues/87

and the current workaround is to switch to the desktop version on mobile. In case you don't know how: while you are on RemNote, look at the search bar in safari. You will see “aA“ to the right, click on it and change to the desktop version ![image](https://user-images.githubusercontent.com/69430941/95898224-0462cb80-0d8f-11eb-8a41-22daeaaa2482.png)

(the iPad is usually in desktop mode by default but I switched it for demonstration)

**Comment by 8888Daniel8888** [comment]
oh wait I'm stupid... didn't read your report properly

**Comment by drkvj** [comment]
Hey @arunnbabu81 and @8888Daniel8888 , Thanks for submitting this, and apologies for not responding sooner, we are now cleaning up all the reports, to make sure this can be an efficient process from now. 

Can you guys update me here, if you are experiencing such issues still?

**Comment by 8888Daniel8888** [comment]
Yeah, still facing the same issue. 

(Realising this now, I shouldn't have closed this issue https://github.com/remnoteio/remnote-issues/issues/87 , I probably forgot to turn off the desktop view of the browser)

**Comment by drkvj** [comment]
Thanks for the reply, but I guess both are similar reports so let's keep your's open as it has more context for Martin. 
Merging this with #87
