### ISSUE TITLE
answer gestures issue

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#188]
**Describe the bug**
In the mobile version,when i use queue,in the muti-line card,if i scroll the page,the answer gesture will unexpectedly answer the flashcard

**To Reproduce**
1. Go to 'mobile web version'
2. Click on 'queue'
3. scroll the page in the mutiline flashcard

**Expected behavior**
A option to stop the answer gesture

**Smartphone (please complete the following information):**
 - Device: [iPhone11]
 - OS: [ios]
 - Browser [safari]
 - Version [14]

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
