### ISSUE TITLE
Display problem in the ipad’s landscape mode

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#189]
**Describe the bug**
Mobile web version in ipad’s landscape mode can’t display same as orientation mode. Icons in the top position are covered. In the queue, there are some space can’t be touched and blank

**To Reproduce**
use remnote mobile web version in the ipad’s lanscape mode

**Expected behavior**
Display as well as orientation mode

**Screenshots**

![](https://pic.downk.cc/item/5f883bfe1cd1bbb86b1257cf.png)

![](https://pic.downk.cc/item/5f883c9a1cd1bbb86b12a578.jpg)

**Smartphone (please complete the following information):**
 - Device: [iPad 7th]
 - OS: [ios14]
 - Browser [safari]

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
