### ISSUE TITLE
ReferenceError: isOnMobile is not defined

### ISSUE THREAD

**Issue by gbtb** [remnoteio/remnote-issues#19]
**Describe the bug**
Cant open my card queue.

**To Reproduce**
Click on queue link in sidebar, then blank page appears on the right with error message:
```
Something went wrong.
Please try refreshing the page. If the problem remains, please provide additional detail on the help page.

ReferenceError: isOnMobile is not defined. URL: https://www.remnote.io/help

```

If I switch to some document, and try to open queue again, then error message changes slightly:
```
Something went wrong.
Please try refreshing the page. If the problem remains, please provide additional detail on the help page.

ReferenceError: isOnMobile is not defined. URL: https://www.remnote.io/document/RM4cPNbuDKT7ZjphY
```

Tried to ctrl-f5 page - it didn't help

**Expected behavior**
Learn queue opening

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version 76.01

**Additional context**

**Comment by hanp0** [comment]
I'm also currently having this issue

![image](https://user-images.githubusercontent.com/20649672/89356936-089baa00-d6b7-11ea-9dbf-f651235274ff.png)

**Comment by TaQuangKhoi** [comment]
i don't have this issue on my Linux Desktop (Ubuntu 20.04)
-------------------------------------------------------------------------------
but this issue happen on my Android phone
![Screenshot_20200805-072034_Chrome](https://user-images.githubusercontent.com/45689286/89357987-4535c880-d6ec-11ea-86f7-744c196f20d8.jpg)

OS: Android 9 - SamSung Galaxy J4+
Browser: Chrome on Mobile - 84.0.4147.111

**Comment by mfranzs** [comment]
Thanks for the clear reports. A fix has been deployed.
