### ISSUE TITLE
Share/export and portal/latex

### ISSUE THREAD

**Issue by Bourous** [remnoteio/remnote-issues#190]
**Describe the bug**
the share/export function and portal and latex do not mach well together...

**To Reproduce**
1) try to add to your knowledge base the rem https://www.remnote.io/a/fiche-pour-l-interrogation/fM96KYzbrNEgJccod
2) Or the same rem in the makdown zip file: 
[RemNote_Export_October_15th_2020_Bourous_md.zip](https://github.com/remnoteio/remnote-issues/files/5385108/RemNote_Export_October_15th_2020_Bourous_md.zip)
3) in the first case the portal are empty for me
4) In the second case the latex is not parsed inside the portal, the portal is not reproduced  and the hierarchy inside the portal is very odd. Also the flashcard ::: and ::1. are not reproduced.

**Expected behavior**
To get an exact copy of the imported rems.

**Screenshots**
Use the link to reproduce the problem.

**Desktop (please complete the following information):**
 - OS: IpadOS and Linux
 - Browser: Safari and Firefox

**Comment by mfranzs** [comment]
We have fixed the first case. Unfortunately, we cannot fix the second case as we cannot export portals to markdown.
