### ISSUE TITLE
List do not clear off the queue

### ISSUE THREAD

**Issue by Bourous** [remnoteio/remnote-issues#191]
**Describe the bug**
List do not clear off the queue

**To Reproduce**
1. create a list ::1.
2. test yourself on the rem
3. the queue never clear. After you're done with the flashcards associated to the list it start again. Note that it does clear if you choose the option good but not the others...

**Expected behavior**
when you're done with the list flashcards it is removed from the queue

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
