### ISSUE TITLE
typing Enter after a plain rem creates a set

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#192]
**Describe the bug**
In the title
**To Reproduce**
1. Create a plain flashcard
2. Click on Enter
3. See error

**Expected behavior**
no set should be created
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/96147360-87a72d00-0f07-11eb-9d76-3985fbb8ff46.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iPadOS 14.0.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
