### ISSUE TITLE
"Avoided infinite recursion"

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#193]
![image](https://user-images.githubusercontent.com/20538090/96184501-3ddb3880-0f41-11eb-9f2c-a013d9d7fb84.png)
I exported all of my documents and i see meaningless rems in markdown and and it says Avoided infinite recursion

I also came across documents (title name is untitled) full of irrelevant rems in the remnote (sometimes they also have this message)
![image](https://user-images.githubusercontent.com/20538090/96186038-83006a00-0f43-11eb-9967-8574c1b25e16.png)
like this. (I didn't write this)

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
