### ISSUE TITLE
Clicking on go back in the queue doesn’t work at times

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#194]
**Describe the bug**
I don't know the trigger for this, will update when I find out but sometimes when I click on go back, nothing happens unless first click on show answers
**To Reproduce**
1. Go to queue
2. Solve some cards
3. Scroll click on the go back arrow and you might encounter the bug￼

**Expected behavior**
If I click on go back, it should go back
**Screenshots**
*maybe once I found the trigger*

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.0.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
