### ISSUE TITLE
Ctrl+P opens rem in portal and not in the original document

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#196]
**Describe the bug**

When I search and open a Rem
![image](https://user-images.githubusercontent.com/4137110/96332873-c8698800-1066-11eb-839a-e0095debb0ad.png)
it opens a portaled version of it
![image](https://user-images.githubusercontent.com/4137110/96332952-2c8c4c00-1067-11eb-907a-e6f1761744cf.png)
instead of the original document.

**To Reproduce**

Portal a child into a daily document and Ctrl+P to it.

**Expected behavior**

I expect RemNote to open this url: `https://www.remnote.io/document/TOP_LEVEL_ANCESTOR_REM?locationAnchor=SEARCHED_REM`.
Maybe instead of the top level ancestor chose the closest ancestor `#Document`.

The only exception I might make is to open a top level rem in a portaled location for more context, but only when it is not a document already. I find it more confusing than helpful.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
