### ISSUE TITLE
Insconsistent Portal UX

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#197]
I think the portal UX is too complicated and not consistent with other functions:

- There is Ctrl + S (Editor Scope > Add a Portal) and Ctrl + Shift + Enter (Rem-Level Editing > Add Portal) which both add a normal portal.
    - Ctrl + S does not appear in the slash menu.

- There are 4 different dialogs in RemNote (3 and 4 could/should be replaced with 1 and 2):
  
1. Ctrl + P (and Ctrl + Shift + M) modal.
  2. Inline search for `[[` and `##`.
  3. Ctrl + S `Add a Portal` at bottom right.
  4. Ctrl + Shift + Enter inline search.
    
- **Replacing 3 with 1:** I would like if Ctrl + S uses the same dialog as Ctrl + P. If this functionality should be displayed in the UI then maybe as an icon button (e.g. use external-link icon) next to the Ctrl + P magnifier icon (Sidebar > Documents). Remove the "Add a Portal" search at the bottom. I would even argue that this is advanced functionality which not every user needs to see (definitely more advanced than search which has less screen space).
- **Replacing 4 with 2:** Ctrl + Shift + Enter should use the same nice inline search box as `[[` and `##`. See also similar issue for emojis and dates (#198). (The Ctrl + Shift + Enter experience is not as slick as the `[[` box. Pressing Ctrl + Shift + Enter (then type) then Esc leaves an unfinished portal. I think it should be aborted completely and leave nothing. Reusing the `[[` box would fix this too I think.) Maybe even drop the shortcut (we already got one with Ctrl + S) and use the same double character prefix as other things, like `((` which is already used for portal ids.

- Ctrl + S does not make a portal when the target is in the same page, but instead focuses the target. when inside `other tree` it adds a portal, when inside the highlighted rem it focuses:
![image](https://user-images.githubusercontent.com/4137110/96335962-7fbcc980-107c-11eb-83cf-ba61e7eef851.png)

- Ctrl + S does not make a portal inside a portal, but prepends/appends it to the current portal (making what I call _compound portal_). Ctrl + Shift + Enter does make a portal inside a portal. I would like it to always make a portal.
- I find those compound portals confusing.
    - Is there a way to delete part of a compound portal?
    - What is their use case and (if they have one) how do I make one reliably?
- Sometimes Ctrl + Shift + Enter does not find a Rem but with Ctrl + S does. Ctrl + Shift + Enter seems to limit the results more than Ctrl + P and Ctrl + S.

- It is not obvious to me when exactly the "This Document is in X Folders" stub is generated and what it counts. I assumed it has something to do Portals but I can't see what exactly. (Forum Q/A [When does the “This Document is in X Folders” search portal stub appear?](https://forum.remnote.io/t/when-does-the-this-document-is-in-x-folders-search-portal-stub-appear/509))

**Comment by ognsya** [comment]
Agree. Portals are clearly super useful, but the UI isn't very intuitive.

**Comment by drkvj** [comment]
All great points, thank you! We will consider these during our UI/UX revamp! Since these are not actual bug reports, I will be closing them now.
