### ISSUE TITLE
Scroll when I reach the buttom

### ISSUE THREAD

**Issue by PandaBoy444** [remnoteio/remnote-issues#2]
**Describe the bug**
When I write and I get to the end of the vertical screen, it keeps writing but doesn't scroll to focus on the text. 

**To Reproduce**
1. Write a lot in one page
2. See error

**Expected behavior**
It should scroll

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
.

**Comment by mfranzs** [comment]
Thanks for the report. To clarify, are you writing all within a single bullet, or within multiple bullets?

**Comment by PandaBoy444** [comment]
Thanks for the response! The main issue is if I have a long bullet, but it's also partially present when creating new bullets at the bottom of the page

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
