### ISSUE TITLE
Drag and drop audio file

### ISSUE THREAD

**Issue by dahifi** [remnoteio/remnote-issues#20]
Dropping audio file in browser causes broken image with AWS url

**To Reproduce**
1. Create a new, blank Rem. 
2. Select an audio file from local file system
3. Drag to browser window. 
4. File is uploaded, broken image icon appears. Clicking on URL displays url to AWS S3 bucket. 

**Expected behavior**
Audio player displays for audio file. 
If this behavior is not supported, then the user should be prompted that the file format is not supported for drag and drop. 

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 84

**Comment by mfranzs** [comment]
Thanks for the clear report. We've reproduced this and will deploy a fix in the next update.
