### ISSUE TITLE
Tag collection power up does not collect old tags and is not removed automatically from orphans

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#200]
The new, experimental `Tag` collection power up is an awesome feature to help get an overview over your knowledge base.

There are 2 problems with it:
- It collects only new tags, probably the ones used after the feature was enabled. I think it should always find all tags.
- It includes tags which are no longer used, i.e. even if no rems use a tag it is still tagged with `#Tag`. While this is useful (? or can be, e.g. if you currently do not have `#urgent` tasks) it can also clutter the tag list. Maybe a powered up attribute (like `Finished`/`Unfinished` for `Todo`) could be used to store if a tags is currently in use, or even better how many times a tag is used and being able to sort by it.

**Comment by mfranzs** [comment]
For now, I'll mark this working as intended. Eventually, we'll be able to capture your requests through a query language that finds any Rem with tag-children.
