### ISSUE TITLE
Undo slash commands puts text back

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#203]
This is nitpicking/very low priority polish.

Undoing a slash command puts the slash command text in again. This text can not be used again for a different slash command and has to be deleted. 
![remnote-bug-undo-slash-command](https://user-images.githubusercontent.com/4137110/96375744-17084680-117b-11eb-869f-163ae5afa515.gif)

**Expected behavior**
After applying the slash command and pressing Ctrl + Z, either
- the slash command dialog should open again or
- the slash command text should be undone/deleted as well.

Opening the slash command dialog might be confusing when it is not the last command but further back in the history so I would prefer squashing everything from typing the `/` and appling the command to be squashed to a single history item effectively removing the slash command text.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
