### ISSUE TITLE
Rem Type (Concept, Descriptor) does not update on moving

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#207]
Removing the content of a descriptor changes the parent from concept to plain. Moving the descriptor away does not. Doing an edit action in the moved descriptor triggers an update again:

![remnote-bug-rem-type](https://user-images.githubusercontent.com/4137110/96502728-8309ae00-1252-11eb-889e-5caca6cc4ba8.gif)

This is inconsistent. I assume moving should recalculate Rem Types (just like editing does)?

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
