### ISSUE TITLE
Copy&Paste LaTeX does not close the LaTeX blocks

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#208]
![image](https://user-images.githubusercontent.com/4137110/96506600-332de580-1258-11eb-896a-98fc832286c2.png)

I want to duplicate a rem including latex. I copy the rem and try to paste it.

(Using Ctrl + V, nothing happens. I remember reading about this problem on Discord a while ago. And I think it worked around last week? Maybe it's a regression.)

Using Ctrl + Shift + V all text is latex after the first latex block.

**Comment by debanjandhar12** [comment]
**Better example**
Text to paste:
Let $$r(x)$$$$ be the remainder when the polynomial is $$x^{135}+x^{125}-x^{115}+x^{5}+1$$$$ .

What the result should be:
![resG](https://user-images.githubusercontent.com/49021233/97143448-b7b4c280-1788-11eb-8a62-f3322094de3d.png)

What the result actually is:
![resB](https://user-images.githubusercontent.com/49021233/97143470-c26f5780-1788-11eb-8e22-5a8965d8d3b7.png)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
