### ISSUE TITLE
Remnote.io fails to highlight some positive search results

### ISSUE THREAD

**Issue by Saurus-yeah** [remnoteio/remnote-issues#209]
**Describe the bug**

I have a large document (approx. 45 pages when I click 'print'). I searched, using ctrl+f for "195" and there were about a 1.5 pages of results. Some of the instances of "195" were highlighted, but others were not. Interestingly, when I hovered my mouse over a rem containing non-highlighted instances of "195", the first '195' in the rem highlighted, and vice versa for rems that were already highlighted properly.

ALSO, I use dark theme and the highlighting is barely visible against the dark background.

**To Reproduce**

**Expected behavior**
All instances of '195' highlighted in a way that stands out from the background.

**Screenshots**
ok!
![Screenshot 2020-10-19 163825](https://user-images.githubusercontent.com/73139719/96509497-1aa6d680-122a-11eb-9d2d-2d9a8f48e526.png)
![Screenshot 2020-10-19 164002](https://user-images.githubusercontent.com/73139719/96509503-1e3a5d80-122a-11eb-9632-3e98ff7574fb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.75

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
