### ISSUE TITLE
Collapsing using indentation line - bug for list or set rems

### ISSUE THREAD

**Issue by drkvj** [remnoteio/remnote-issues#21]
**Describe the bug**
this feature works perfectly in all other rems , but unfortunately does give us the ability to click on the darker indentation lines which are due to lists or cards

**To Reproduce**
1. Go to a rem , make into a list
2. Click on the experimental feature to collapse using indentation line
3. You will still not be able to collapse on the new list rem's indentation line 

**Expected behaviour**
The pointer should turn into a clickable hand icon and allow us to click on the line

**Comment by mfranzs** [comment]
Thanks for the clear report. We've reproduced this and the fix will be deployed in the next update.
