### ISSUE TITLE
Raw JSON Import does not work!

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#210]
The raw JSON import does not seem to do anything. It shows a success message, but neither are deleted rems restored, nor newly added ones removed, nor is the text of existing rems reverted.

(I don't know if this is a finished feature as it is not listed on the about page, but in the settings.)

(May I ask for a quick resolution as I want to use this to fix a syncing problem (#211) so I can't use this account in the meantime.)

**To Reproduce**

(On an empty daily note:)
1. Add a rem "Before Backup"
2. Export `backup.json`
3. Delete "Before Backup" and add new rem "After Backup"
4. Import `backup.json`.

There is still only a rem "After Backup".

**Expected Behavior**

It should only show "Before Backup".

Sidenote Replace or Merge: I would like it to replace my current knowledge base instead of doing a merge so I can make a full recovery of a past snapshot, i.e. show only "Before Backup" instead of both.
Merging can be useful as well to recover lost notes, but this should be covered by the trash.

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by hannesfrank** [comment]
I think it works if I delete All Rem in the account settings before. But this feels scary!

**Comment by hannesfrank** [comment]
I think there could be a problem with the unification of two knowledge bases. If I delete all rem and import again (on a different account) they are naturally assigned new `_id`s. I would rather not have this happen when I overwrite the current knowledge base weith a previous snapshot (e.g. from a daily backup) because it makes diffing impossible (in combination with version controlling the backups).

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
