### ISSUE TITLE
Icon disappears after installation of Remnote Clipper

### ISSUE THREAD

**Issue by SuzanaK** [remnoteio/remnote-issues#212]
**Remnote Clipper Chrome extension does not load**

I installed Remnote Clipper several times. Everytime I get a message that the addon was installed and I see the R icon in the top right corner. But then it disappears. I click on the icon and it just disappears. Restarting chrome does not help. I tried it being logged in and being logged out from Remnote. 

**To Reproduce**
1. Install the addon.
2. Click on the icon.
3. Icon disappears.

**Expected behavior**
The icon should be there and clickable. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. Is it possible that the icon is being moved to the "extra extensions" panel? Can you please try clicking on the puzzle piece on the right side of the extension bar and checking for the extension icon there?

**Comment by SuzanaK** [comment]
Uh yes, that's it. Sorry, I'm a Firefox user normally, I only use Chrome because of Remnote. So I didn't know I had to click the puzzle piece. Thanks for the hint :sweat_smile:

**Comment by mfranzs** [comment]
All good!
