### ISSUE TITLE
Deleted a whole folder and the files in it and cannot retrieve

### ISSUE THREAD

**Issue by Kelly58** [remnoteio/remnote-issues#213]
Hi!
I was attending lecture and decided to use Rem-note to write my notes.
I initially made a document called "Base Seminar". 
Then, I decided to make a folder called BASE and moved my "Base seminar" document to that folder
Then decided that I didn't want that folder anymore so I deleted the folder thinking my original document in it would still be seen under documents.
However; Remnote deleted my document that I needed as well.

Is there a way that I can retrieve this document?

**Comment by 8888Daniel8888** [comment]
https://www.remnote.io/trash

Also check out forum.remnote.io where you can post your questions, Github is for bug reports

**Comment by Kelly58** [comment]
Hi!
Thanks for the reply I think I deleted my lecture around 11am-12pm.

I clicked retrieve all but then it shows up as an undeleted Rem document
with a bunch of blue boxes but no text.

Am I doing something wrong?

**Comment by 8888Daniel8888** [comment]
"This page is in Alpha. Do not use it without advice from support." is the message on the page of the link I sent, so better do that because I have no clue how this works

**Comment by Kelly58** [comment]
I am a bit confused on what to do now.
Where do I ask for advice from a support?

**Comment by 8888Daniel8888** [comment]
Remnote.io/help

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
