### ISSUE TITLE
Can‘t collapse a rem

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#214]
**Describe the bug**
When I try to collapse a rem, it turns grey and doesn't collapse
**To Reproduce**
I don't understand it, especially because I don't know the purpose of that greying out, seen it often though but not like in this bug
**Expected behavior**
I should be able to collapse when I click on the triangle symbol
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/96639199-a8192200-1321-11eb-97b1-7251e35d461b.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iPadOS 14.0.1
 - Browser safari
 - Version 14

**Additional context**
I haven't been writing steps to reproduce lately, sorry for that but I don't have the time available at the moment

**Comment by 8888Daniel8888** [comment]
deleting my internet history got rid of the issue btw

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
