### ISSUE TITLE
Blank space between "References to this Rem" and "Text References to this Rem" blocks

### ISSUE THREAD

**Issue by kalimatas** [remnoteio/remnote-issues#215]
**Describe the bug**
When I press the array to unfold the "References to this Rem" block a blank space appears between the block and the next "Text References to this Rem".

It is fixed by unfolding the "Text References to this Rem" block.

And after it's fixed, the problem doesn't appear next time I open the original document and unfold the "References to this Rem"  block.

**To Reproduce**
1. Create a document "Test Document".
2. Create a document "Another Test Document".
3. Reference "Test Document" in "Another Test Document".
4. Go to "Test Document" and unfold the "References to this Rem"  block by pressing the arrow in the header.

**Expected behavior**
There is no blank space between reference blocks.

**Screenshots**
![image](https://user-images.githubusercontent.com/449551/96769840-f7258c80-13df-11eb-8755-f65ee124f958.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Brave 1.15.76 with PWA app or Firefox 82

**Additional context**

**Comment by hannesfrank** [comment]
It' not a bug, it's a feature 😄

The reason for this is that the portal _stubs_ are stuck to the bottom of the page and opened stubs are turned into a search portal which can be placed - like every rem - anywhere on the page. And on the bottom of the page there must be a space where you can create a new rem by clicking.

So we would need to have special case where search portals can be placed in the footer or have the ability to open stubs in place.

Or you can reduce or even hide this space with Custom CSS:

```css
.rem-hierarchy-bottom {
  display: none;
}
.invisible {
  display: none;
}
```

**Comment by kalimatas** [comment]
Thanks! Now it's clear 👍
