### ISSUE TITLE
for a single rem, search and reference links go to the wrong location (to the wrong rem)

### ISSUE THREAD

**Issue by webstert837** [remnoteio/remnote-issues#216]
**Describe the bug**
I've had trouble with a rem (a person in my "people" folder named Jikai).  When I search for Jikai, the search preview shows his rem in "people" just as I have entered it and as it displays in the people folder.  However, when I click on this entry, it takes me to a meeting note rem where I originally made the rem for Jikai.  I have several other references to Jikai, and all of them link to these meeting notes rather than the Jikai entry in the people folder.  I can get to Jikai in my people folder, but only by manually scrolling to Jikai or using Chrome Find on the people folder page.  

Even when I remove Jikai text and the reference in that meeting note, a search still takes me there (even though it continues to preview correctly in the people folder).  I have tried deleting and re-entereing Jikai (with sub-rem) and keep having the same problem.  

I believe Jikai was originally a top-level rem that I moved to my people folder.  I do that a lot (add a new person using [[ in meeting notes then later move them to the people folder), but this particular rem is buggy.  I thought I had another one but can't locate it.  It seems I have a bad link somewhere in remnote, but haven't figured out how to get rid of it.  

**To Reproduce**
Remnote consistently takes me to the wrong rem from a search and from other reference links. 

**Expected behavior**
Remnote should take me to the same rem that is it previewing in search. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome
 - Version 86

**Additional context**
I remember there being other irregularities with this rem but I don't remember when it started.  I may have had a computer crash that didn't sync remnote.

**Comment by hannesfrank** [comment]
Can you confirm that you don't have a portal to Jikai in your meeting notes? There is an issue (#196) that the rem is opened in a portal and not at its location as well.

**Comment by webstert837** [comment]
Sorry I didn't follow up on this earlier.  I can no longer reproduce the problem with this particular rem (Jikai).  Clicking references to Jikai now opens it correctly in my People folder.  It looks like it has been resolved with a previous update.
