### ISSUE TITLE
Moving/indenting multiple rem skips rem/indentation depths

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#217]
![remnote-bug-moving-indenting-skip](https://user-images.githubusercontent.com/4137110/97024879-9e78ff80-1557-11eb-985d-52c1d38f561b.gif)

I'm pressing alt+up/down and tab, shift+tab.

**Comment by mfranzs** [comment]
I'm having some trouble reproducing this - do you know what makes this happen?

**Comment by hannesfrank** [comment]
I can not reproduce this now as well. It was on Windows Chrome and it works fine now. Sorry for wasting your time. I am a bit sloppy lately testing on multiple browsers, because I have to redo so many edits (#211). 😅 

I have found another issue though: Indenting/Dedenting deselects a selection of rems on Firefox 81, both Windows and Linux.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
