### ISSUE TITLE
Cloze creates unnecessary place holders when the cloze contains references

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#219]
**Describe the bug**
When a cloze card is generated for some text that contains a reference, cloze ends up creating unnecessary placeholders. Check the issue in the attached GIF

**To Reproduce**
1. Select two words, one regular text and the other a reference to something
2. Then select 'Create cloze' option from the popup tool bar to generate cloze cards
3. Check the generated cards in the card preview 

**Expected behavior**
Cloze should create one place holder for a selection 

**Screenshots**
In the first rem here, I for one selection cloze created three placeholders. 
In the second case it is worse. I just wanted to hide **Classification** and therefore selected only that. However, cloze ended up hiding even the unselected word as well
![cloze_extra_placeholders_for_refs](https://user-images.githubusercontent.com/24322880/97099233-13296800-1644-11eb-8684-7029c959871f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 2004
 - Browser: Chrome 
 - Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
