### ISSUE TITLE
Math equation improvement suggestion

### ISSUE THREAD

**Issue by zhanghanduo** [remnoteio/remnote-issues#22]
**Description**
I quite enjoy using Remnote. Just the math mode annoys me. When you have multiple math equations to edit in a rem, there will pop up multiple math editing bars which block the words I am typing.

Like this:

![image](https://user-images.githubusercontent.com/8006682/89617939-b082c480-d8bd-11ea-882c-27fe577c0706.png)

**Describe the solution you'd like**
Some kind of lazy or late WYSIWYG mode.

Personally I prefer the style closing equations with $$ and does not display the final look of the equation until you close that with $$ signs. Or each equation has its own editing bar. Therefore when you are writing another equation, the previous equations will now show their irrelevant editing bars.

**Describe alternatives you've considered**
Just try to avoid multiple equations in one bullet rem. This is a bit hard when you are taking some academic notes with a lot of math equations.

**Comment by mfranzs** [comment]
Thanks for the clear report. We're actively working on this and the fix will be deployed in the next update.
