### ISSUE TITLE
Delay when typing into the filterbox

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#220]
**Describe the bug**
If I open the filter and then type into the text field of the filter, the letters appears pretty delayed on the screen. I'm not sure if it's just my old hardware  or if it's a bug, because typing everywhere else is basically instant
**To Reproduce**
1. Click on the triple dots
2. Click on "Filter this document"
3. Write into the text field

**Expected behavior**
I expect the letters to appear instantly

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iPadOS 14.1
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for the report. For now, this is working as intended as typing in the filter box runs a search that can be slow on some documents.
