### ISSUE TITLE
automatically add template powerup doesn‘t work

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#221]
**Describe the bug**
When I want to tag  a rem with the ”automatically add template” powerup, it creates an ”automatically sort" powerup instead

**To Reproduce**
1. write /slot after a rem
2. Click on apply automatically add template powerup in the popup window  
3. See error

**Expected behavior**
The correct powerup to be assigned
**Screenshots**

https://forum.remnote.io/t/can-someone-help-me-with-the-automatically-add-template-powerup/643/3?u=88dm88

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iPadOS 14.1
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
