### ISSUE TITLE
Remnote Experimental feature Full Page Preview only works sometimes

### ISSUE THREAD

**Issue by scruffsc** [remnoteio/remnote-issues#222]
**Describe the bug**
 - Show a full document preview when you hover over a Rem Reference
This feature was working fine for me before a recent Remnote update (probably a few weeks ago), but now only works sometimes. 

**To Reproduce**
* hovering over a Rem Reference.

**Expected behavior**
Should show in a small box above it a preview of the document.

**Screenshots**
You cant see my cursor, but it is hovering over the rem reference in both cases. 

![Annotation 2020-10-26 135541](https://user-images.githubusercontent.com/73500065/97227607-f6e81100-1792-11eb-8d0f-f2f69928db56.png)
![Annotation 2020-10-26 135520](https://user-images.githubusercontent.com/73500065/97227609-f780a780-1792-11eb-95c8-63ff3b13948c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Version (Chrome): 86.0.4240.111 (Official Build) (64-bit)

**Additional context**
I really love this feature for my studying so I would love a solution! :)

**Comment by 8888Daniel8888** [comment]
Already made a bug report https://github.com/remnoteio/remnote-issues/issues/164

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
