### ISSUE TITLE
Flash cards disappearing 

### ISSUE THREAD

**Issue by aisha-AO** [remnoteio/remnote-issues#223]
hello, 

I am having an issue when practicing my flash cards. a lot didn’t show in my queue even though Ive never practice them. I don’t know how to fix this thank you. 

I added some pictures to make it clear: 
![4061BD1D-DC20-45C0-A6F3-1E32A77BEFE8](https://user-images.githubusercontent.com/73512564/97254955-96071a00-1820-11eb-9746-8879815f2644.jpeg)

![C8EB1393-5CF0-4CB0-95C8-F89ED9FA6882](https://user-images.githubusercontent.com/73512564/97254976-a0291880-1820-11eb-87bc-a65b907f19e0.jpeg)

thank you.

**Comment by mfranzs** [comment]
Thanks for the report. This document looks like it only has 5 cards in it. To clarify, have none of those cards appeared in your queue? If you click the "Practice without spaced repetition" option, do they appear?

If they don't appear, would you feel comfortable sending us a full backup of your account to help debug this issue? I normally wouldn't ask for this, but we've been having trouble tracking down this issue. Feel free to say no, especially if you have anything remotely private. If you're okay with this, please download a "Full Raw Backup (JSON)" backup from https://www.remnote.io/export and email it to us at support@remnote.io . Thanks!

**Comment by mfranzs** [comment]
Thanks for sending the backup over - it was very helpful! We've identified a possible cause. Closing this in favor of #125
