### ISSUE TITLE
I‘m not able to write in any of my documents

### ISSUE THREAD

**Issue by MarcWiem** [remnoteio/remnote-issues#225]
I have an issue for the past couple of hours, in which I can’t edit my documents that have text in them. When I try it on the phone it does work, but not on the iPad (don’t have a desktop setup).

**Desktop 
 - iPad Pro 2020
 - iPadOS 14.1
 - safari, brave, firefox, I‘ve tried a couple. Doesn’t work anywhere
 

**Smartphone
 - Device: iPhone X
 - OS: iOS 14.2
 - safari
 

**Additional context**
I hope you can help me. Kind regards

**Comment by 8888Daniel8888** [comment]
@mfranzs could this be fixed ASAP? (Sorry for the @ but this is urgent)

**Comment by huylenq** [comment]
I'm having the same problem. RemNote works fine on macOS & iOS Safari but not iPad OS.
Use "Request Mobile Website" does make rems editable but break other features (buttons don't respond, Search doesn't work).

**Comment by scheatwo** [comment]
Same trouble here. iPad using Safari. iPadOS 14.0

**Comment by mfranzs** [comment]
Thank you all for the clear report and for your patience. We've fixed this issue and deployed a fix. Please let me know if you're having any more issues after a reload.

**Comment by scheatwo** [comment]
Thank you! Remnote is great! Keep up the good work!!

________________________________
