### ISSUE TITLE
Error when going to queue

### ISSUE THREAD

**Issue by Thai0812** [remnoteio/remnote-issues#226]
**Describe the bug**
I'm greeted with an error sign every now and then when I try to go to my queue

**To Reproduce**
1. Go to 'queue'
2. See error

**Expected behavior**
I expect to see my queue cards but an error sign keeps showing up.

**Screenshots**
![Screenshot_2020-10-27-19-34-29-752_com remnote](https://user-images.githubusercontent.com/73533992/97302437-aaccc780-188b-11eb-91f5-54e4f4c43335.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: latest update

**Smartphone (please complete the following information):**
 - Device: Redmi 5 plus
 - OS: Android 8.1
 - Browser: I use the RemNote app with the latest update (October 26th)

**Additional context**
I tried refreshing, closing and reopening the app but the problem persists not only on my phone but also on my PC

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
