### ISSUE TITLE
No Syntax Highlighting in Code Blocks

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#229]
All code blocks are have black only text or grey text in a checked block (Custom CSS).
I think this regression was introduced with the backend upgrade.

![image](https://user-images.githubusercontent.com/4137110/97339786-4c035000-1883-11eb-9f3f-45ab6191f45a.png)

Latest Chrome on Windows 10.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
