### ISSUE TITLE
Disappeared text when using tagging 

### ISSUE THREAD

**Issue by HanzhenWu** [remnoteio/remnote-issues#230]
**Describe the bug**
 I have used tagging for a parent bullet and write child bullets below, but the next day when I want to review the text in the child bullets, all texts disappeared, but for the child bullets under a parent bullet that I didn't use a tag, the text remains.

**To Reproduce**
1. Go to 'Document'
2. Click on 'Seminar' (the name of my document)
3. Scroll down to 'Week 3 How to make a perfect date night'
4. Open 'Writing with criticism', and open the first and second bullet point 'No listing but generalising' and 'Show own involvement in the language'
5. error occurs: all texts in the child bullets disappear

**Expected behavior**
The texts should be there.

**Screenshots**
![截屏2020-10-27 下午9 30 23](https://user-images.githubusercontent.com/72510020/97364950-c42a3f80-189c-11eb-9b97-a11ba26776f0.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Browser: Chrome
 - Version: 86.0.4240.111 (the latest version of chrome)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
