### ISSUE TITLE
Queue malfunction

### ISSUE THREAD

**Issue by DocAwesomebjb** [remnoteio/remnote-issues#231]
**Describe the bug**
Whenever I select recalled immediately my queue starts going back each time I subsequently press recalled immediately. I switched the recalled immediately keystroke to be “R” because that makes the most sense for my hand position so that might contribute to it, but I cannot use RemNote without that functionality

This problem was happening before the most recent update.

**To Reproduce**
1. Change the keyboard shortcut for recalled immediately to "R"
2. Go to Queue
3. Go thru a couple of cards until you select Recalled immediately 
4. then each time you press "R" the queue goes backward to cards you've already completed

**Expected behavior**
I expect the argument for R to be taken without any problems 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.15
 - Browser chrome
 - Version newest

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the very clear report! We've reproduced this and have deployed a fix. Please let me know if you're still having any problems.
