### ISSUE TITLE
Cmd + ↓/↑ and Cmd + Shift + ↓/↑ not working properly

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#232]
**Describe the bug**
As the title says, it seems to only partly expand/collapse rems when selecting multiple rems and then carrying out the commands. Sometimes it does so one by one from the bottom up. The behavior is even stranger when the child rems are part of a multiline rem.
❗️ NOTE: Does not seem to be happening when using these commands with individual (single) rems, just with multiple rems.

**To Reproduce**
1. Select multiple rems having child rems and/or multiple line child rems hidden
2. Cmd + Shift + ↓ or any of the other commands mentioned above
3. Note that the commands initially seem to work only on the last rem with child rems
4. Upon carrying out the command again, it works on the second to last rem
5. Repeats with the third to last rem and so on

**Expected behavior**
Selecting all rems and then using any of the above commands should carry out the command on all the rems at once, not one after the other

**Screenshots**

Here is what I'm seeing, first while trying out Cmd + shift + ↓ and carrying this command out multiple times, then trying out some of the other commands on individual rems

![ezgif-6-53f04f6d80a7](https://user-images.githubusercontent.com/68901589/97399152-ee641780-1905-11eb-87de-4444f16a15e9.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
