### ISSUE TITLE
Portal stubs are empty when opened

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#233]
Portal stubs are empty after opening them and have to be reloaded manually.
![remnote-bug-portal-stubs-empty](https://user-images.githubusercontent.com/4137110/97429126-49523a80-1917-11eb-85e6-c0b5904294e5.gif)

I like the new default style of the stubs btw. They fit nicely into the design!

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
