### ISSUE TITLE
Move and keep portal function no longer works

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#235]
**Describe the bug**
Previously, we used Cmd + M to move rems and it would leave a portal behind. Since the update, this feature seems to be missing. The rem is moved but there is no portal left behind.

**To Reproduce**
1. Focus on a rem
2. Cmd/Ctrl + M to move it elsewhere
3. Observe that there is no longer a portal left behind

**Expected behavior**
When moving a rem, a fairly recent update allowed a portal to be left behind in its place (expected behavior).

**Screenshots**

![ezgif-6-42fef4b94a1e](https://user-images.githubusercontent.com/68901589/97466657-ca7ff080-195c-11eb-8d7c-d3d6ed4b6220.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by mfranzs** [comment]
Thanks for the extremely clear report! We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
