### ISSUE TITLE
/plain does not work

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#236]
I can't reset rem types with the `/plain` command:

![remnote-bug-plain](https://user-images.githubusercontent.com/4137110/97546264-7ca2d100-19cc-11eb-827c-cb31d82628ce.gif)

I think those things worked previously.

**Comment by mfranzs** [comment]
This is perhaps somewhat confusing, but you need to run this command on the "list" Rem. 

It would be nicer if you could also run this command on the Rem within the list itself, but we might need to do so through a different command for the case in which the list also contains a sub-list.

Please let me know if I've misunderstood!

**Comment by hannesfrank** [comment]
Thanks for clarifying! Hmm, I was pretty sure that it had worked in those instances prevoiusly. I think used this mostly to work around bugs like to clear the concept above (which does not have any children or content). Is there a way to do it now?

I'll keep an eye out for things that I want to plain and report back.
