### ISSUE TITLE
Bug keyboard word duplicates

### ISSUE THREAD

**Issue by Gloria-hue** [remnoteio/remnote-issues#237]
**Describe the bug**
All my attempts to type result in doubledouble characterscharacters.
Just as the above sentence demonstrates.

**To Reproduce**
1. Go to ' keyboard ' of your device.
2. Click on ' the letters to form your desired word'
3. Scroll down to ' the space bar'
4. See error ,in this case, the desired word duplicates itself and no longer serves my purpose!

**Expected behavior**
I expect to type without such distractions. 

**Screenshots**
Couldn't load the screen shot.

**Desktop (please complete the following information):**
Not applicable to me

**Smartphone (please complete the following information):**
 - Device: [ TECNO 7.0,TECNO P701,BUILD NRD 901]
 - OS: [ ANDROID ]
 - Browser [new Microsoft edge]
 - Version [ 45.09.2.5079]

**Additional context**
No other context about the problem.

**Comment by mfranzs** [comment]
Thanks for reaching out. This is on mobile, right? Is it possible that you've accidentally requested the desktop version? The desktop version is not currently supported on all mobile devices.

**Comment by kalloyan** [comment]
This is also happening with a tablet and a keyboard. I use the Samsung Galaxy Tab S7+ and the keyboard as a laptop and when using RemNote through a browser (every browser does this) and in desktop viewing it's very buggy and you can't write at all and that mobile view is just not suitable for the tablet. Write something, click space, the word appears again twice.

**Comment by drkvj** [comment]
@kalloyan thank you for taking the time and sharing your finding with everyone :) really appreciate that!
