### ISSUE TITLE
Not able to click and type in a certain rem

### ISSUE THREAD

**Issue by tdw-mmbgz** [remnoteio/remnote-issues#238]
**Describe the bug**
I can't click certain rems to start typing. Every time it jumps back to the beginning of the doc

**To Reproduce**
1. scroll down the document
2. Click on a rem
4. It jumps back to the beginning of the document

**Expected behavior**
Click the rem and be able to type content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser mozilla firefox

**Smartphone (please complete the following information):**

**Additional context**
afterward I noticed the last few lines of my notes were not saved

**Comment by tdw-mmbgz** [comment]
When I scroll down my doc to one of the last rems and click to start typing, it always jumps back to the beginning of the document. I can click in all the rems above and below but not in that specific rem.

Desktop windows 10
browser mozilla

**Comment by mfranzs** [comment]
Thanks for reaching out. Are you still having this problem? This is in Firefox, correct? If you're still having problems, can you try refreshing with Ctrl + Shift + R first?

**Comment by drkvj** [comment]
If you are still experiencing problems, kindly make a new report on the forum. Thanks!
