### ISSUE TITLE
Latex formula export to anki miss $$

### ISSUE THREAD

**Issue by JonasxRie** [remnoteio/remnote-issues#239]
**Description**
I noticed that the Anki export has a problem with latex formulas. In fact, for a formula in Remnote created with double-$, the corresponding Anki note only contains [latex]formula[/latex] and miss the latex-$-sign within the latex boundaries.

**To Reproduce**
1. Create a Card in RemNote (::)
2. Add a math formula using double-$ to the card
3. Export cards to Anki and open the downloaded deck
4. See in the corresponding note that there is only [latex][/latex] around the math stuff.

**Expected behavior**
A latex formula needs to be exported as [latex]$ some math $[/latex] to Anki.

**Comment by JonasxRie** [comment]
Maybe using MathJax is also a possibility to reduce tex compilation issues.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by JonasxRie** [comment]
Thanks, works fine for normal Rems!

But for multiline rems introduced by `:::`, formulas in the sub rems are exported with `$$` and not surrounded with `[$$]` and `[$$]`.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
