### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by Hahlh** [remnoteio/remnote-issues#24]
**Describe the bug**

Typos in the docs. 
1. Missing "c" for "can"
2. Superfluous "them" 

[Link to Page: Templates for Knowledge](https://www.remnote.io/documentation/Js45qiFuERfd6BwG9)

**Screenshots**
<img width="589" alt="2020-08-07_15-56" src="https://user-images.githubusercontent.com/45669613/89653023-afa26080-d8c6-11ea-84de-8ef1f692268f.png">

**Comment by mfranzs** [comment]
Thank you for taking the time to report this! We've deployed a fix.
