### ISSUE TITLE
Sidebar buggy while in split screen

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#240]
**Describe the bug**
The sidebar kind of plays hide and seek when trying to access it while in split screen with another app/browser window. The gif attached is only from the RemNote window, but it is in split screen with another browser window.

**To Reproduce**
1. Open RemNote in split screen with another browser window or app
2. Try to access the sidebar
3. Observe that it does not appear properly

**Expected behavior**

**Screenshots**

![ezgif-6-2d7aced41868](https://user-images.githubusercontent.com/68901589/97609865-97596200-1a2d-11eb-852b-aeac9a6358a1.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
