### ISSUE TITLE
(Normal) Portal search in hierarchical search up after deleting characters 

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#243]
![remnote-bug-portal-search](https://user-images.githubusercontent.com/4137110/97627503-c1aa2000-1a2b-11eb-82a8-5ed5e916f4cb.gif)

(Additional issue: Sometimes the search does not work, as seen in the beginning of the video.)

Steps to reproduce:
1. open a portal
1. tabbing into a rem for hierarchical search
1. type something and delete it
1. the text before the tab matches all rem again instead of starting a new hierarchical search

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
