### ISSUE TITLE
TypeParent-TypeChildren relation (little x) disappears randomly

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#244]
![remnote-bug-typerelation-disappears](https://user-images.githubusercontent.com/4137110/97628845-8dcffa00-1a2d-11eb-8bf5-da0ac5477ded.gif)

This is important for the `data-rem-tags` used by the Rem Level CSS Feature Request.
I'd also like an option to restore the relation after it was removed manually.

**Comment by mfranzs** [comment]
The current convention is that a Rem is only implicitly tagged if the reference is at the end of the Rem. 

For example, you could have:
"October 26th Launch [[Demo]]"

Could you achieve a similar effect using a tag? 

For now, I'll mark this working as intended.

**Comment by hannesfrank** [comment]
Ohh, it finally makes sense! This is why it works right before `::`, because it _is_ the last thing of the key/name.

I want to use this with templates/slots in conjunction with https://forum.remnote.io/t/custom-rem-level-formatting-with-tags/168?u=hannesfrank
(Sorry, my screenshot did not make that clear) It is not always practical to turn a slot instance into a flashcard, is it? (I am investigating how to insert structured metadata. Roam also uses :: now.) Maybe the best practice is use :: and disable the card. But this is not quite semantic and it messes up card stats if you have a lot of instances. It is also natural to have the reference in front so having it trailing is cumbersome.

Using tags should work as a workaround, but you'd then have to add it manually and it duplicates the reference. I would not prefer that. Or have an option to automatically tag all slots? Maybe a slot should be a power up like Automatically Add Template? Just brainstorming here.

In the FR I mention having a second mechanism to make the inheritance explicit for slots. How does it work that a rem is recognized as the corresponding slot instance after editing it anyway?

(I am not satisfied with this yet. Should I migrate this to the forum?)
