### ISSUE TITLE
markdown export doesn't work (again)

### ISSUE THREAD

**Issue by old479** [remnoteio/remnote-issues#248]
**Describe the bug**
1. Export-Parameter: 
Format = Markdown
Also Export All Top-Level Rem = Create files for each...
Include Hidden Rem = All descendants ...
![grafik](https://user-images.githubusercontent.com/73693292/97690121-d7a3f900-1a9c-11eb-906e-bf53987a9b73.png)

2. Export doesn't work. 
error message:
sorry! error message is in german:
![grafik](https://user-images.githubusercontent.com/73693292/97691201-55b4cf80-1a9e-11eb-8f0d-3975587d40d4.png)
translation: "A website slows down your browser. What should be done?"

**OS and browser:**
 - Browser [e.g. chrome, safari]: I'm using Mozilla-Firefox, V. 82, Ubuntu 20.04.1 LTS

thank you!

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!

**Comment by old479** [comment]
It is not done yet! Unfortunately, the mistake has remained. Same error message. 
thank you

**Comment by DataSciLearner** [comment]
I too have problem with export, both markdown and JSON; both in exporting the knowledge base or even a single document as markdown. The site repeatedly hangs with "aw snap" message when downloading the entire knowledge base as markdown. The zip file from a single document has no markdown files and is empty. The JSON zip file has only 10kb data with just some barebones and none of my Rems content.

**Comment by mfranzs** [comment]
We've identified another possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
