### ISSUE TITLE
icons on the left-sidebar, below: "multiple windows / statistics / settings / about" are not visible!

### ISSUE THREAD

**Issue by old479** [remnoteio/remnote-issues#249]
**Describe the bug**
icons on the left-sidebar, below: "multiple windows / statistics / settings / about" are not visible!
you have to hover in order to see the icon-descriptions

**Screenshots**
![grafik](https://user-images.githubusercontent.com/73693292/97691724-06bb6a00-1a9f-11eb-83b6-2fe99bde61bd.png)

![grafik](https://user-images.githubusercontent.com/73693292/97692139-aed13300-1a9f-11eb-8d48-943864f31e6c.png)

**Desktop (please complete the following information):**
Mozilla-Firefox, V. 82, Ubuntu 20.04.1 LTS

thank you!

**Comment by mfranzs** [comment]
Thanks for reaching out. I'm having some trouble reproducing this in Firefox on Ubuntu 18 LTS. 

Does this go away if you refresh with Ctrl + Shift + R?

**Comment by drkvj** [comment]
If you are still having troubles, kindly make a new report on the forum. Thanks!
