### ISSUE TITLE
RemNote clipper keeps signing out of account

### ISSUE THREAD

**Issue by alysha9110** [remnoteio/remnote-issues#25]
**Describe the bug**
RemNote clipper doesn't work. When the sidebar pops up, it doesn't load the documents and will eventually sign out of my account when I attempt to refresh the page

**To Reproduce**
Click on RemNote Clipper button and wait for sidebar to pop-up. Error pops up:

Sorry - You Need to Refresh
A database error occurred in your browser, and you need to refresh.
No need to worry! No data has been lost.

Attempting to refresh doesn't do anything and signs me out of the account on the side-bar

**Expected behavior**
After clicking on the RemNote clipper, the side-bar pops up after a slight loading time and the text can be added to it. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Vivaldi]
 - Version [3.1.1929.48 (Stable channel) (64-bit)]

**Additional context**
![image](https://user-images.githubusercontent.com/37675070/89695349-c1881000-d967-11ea-9ad8-0c0c8d2efdbf.png)

**Comment by mfranzs** [comment]
Thanks for the report. 

1) Is this only happening for you in Vivaldi, or also in Chrome?
2) We've identified some possible fixes here and will deploy them in the next update.

**Comment by mfranzs** [comment]
We've deployed the updates here - closing this for now.
