### ISSUE TITLE
automatically add template only adds one of multiple slots

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#250]
**Describe the bug**
when I tag a rem with a template, that has the automatically add slots powerup, it only adds one slot instead of 2. This only happens to rems that are the at least children of the children of top level rems
**To Reproduce**
1. create a template with two slots and the automatically add slot powerup
2. create a top level rem, a child and a child of the child
3. tag the child of the child with the template

**Expected behavior**
I want all slots to be added
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/97783888-effa3d80-1b9a-11eb-93c8-3612b84c27ad.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 2020 edition
 - OS: ios 14.1
 - Browser safari
 - Version 14

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
