### ISSUE TITLE
Missing Rem

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#251]
![image](https://user-images.githubusercontent.com/20538090/97787375-c1905880-1bc2-11eb-9840-8e71e631b51d.png)
Normally I shouldn't have seen the residuals of rems I deleted earlier here (document searching area)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
