### ISSUE TITLE
Cursor jumps backwards after typing the name - content separator (?::) for Question Rems

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#255]
**Describe the bug**
While creating a Question type rem, after typing the **?::** the cursor jumps backwards

**To Reproduce**
Check this GIF 
![question_rem_cursor_jumps_backwards](https://user-images.githubusercontent.com/24322880/97818971-86d9ff00-1c5a-11eb-9ce9-1c8d2592fe25.gif)

**Expected behavior**
The cursor should not jump backwards after typing **?::**

**Screenshots**
Check the GIF above

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, Version 2004
 - Browser: Google Chrome, Version 86.0.4240.75 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Haven't tested

**Additional context**
None

**Comment by anishaaa1** [comment]
To add to this, it also happens when I use the keyboard shortcut Cmd + / to set practice to None.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
