### ISSUE TITLE
bug in anki sm-2 Scheduler

### ISSUE THREAD

**Issue by drstrangez0** [remnoteio/remnote-issues#258]
first i changed only changed the values of the Re-Learning Phase as show in the picture 
![ref](https://user-images.githubusercontent.com/70066742/97970608-d04d5a00-1dd2-11eb-80a5-7e79b79dfcf2.png)

the bug is that whenever i learn a new rem and i prees ("again") the interval will be 48 hours instead of 24 hours as shown in the video 

![vi](https://user-images.githubusercontent.com/70066742/97970770-199da980-1dd3-11eb-8808-3b72c19dc440.gif)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
