### ISSUE TITLE
/ Commands not erasing after pressing enter

### ISSUE THREAD

**Issue by adr123** [remnoteio/remnote-issues#259]
**Describe the bug**
Whenever I use the /remove or /list commands, they apply but fail to delete the written command, as in, I'll type /list (Or /remove), it'll create a list but the "/list" will remain in place. 

**To Reproduce**
Enter a /list or /remove to any rem.

**Expected behavior**
For the command to apply, and for the command to get deleted at the same time from the rem.

**Screenshots**
![gif](https://user-images.githubusercontent.com/24881520/98005042-4099b280-1db6-11eb-95e1-1e3fc048e7ea.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 86.0.4240.111

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
