### ISSUE TITLE
Cursor jumps left/back a random amount of characters

### ISSUE THREAD

**Issue by claubervs** [remnoteio/remnote-issues#260]
**Describe the bug**
Cursor jumps left/back a random amount of characters while typing anything. 
This behavior is erratic and happens at random.
The amount of characters it jumps is also not fixed.

**To Reproduce**
No clear steps to reproduce as this happens every time I'm typing anything.

**Expected behavior**
Just to simply keep writing like any normal place.

**Screenshots**
See animated GIF below
![RemNotev2](https://user-images.githubusercontent.com/302173/98048074-04d50c00-1dfb-11eb-963c-416144c656ca.gif)

**Desktop (please complete the following information):**
 - OS: MacOS X 10.15.7
 - Browser: 
        Chrome 85.0.4183.121
        Safari Version 14.0 (15610.1.28.1.9, 15610)
        Firefox 82.0.2 (64-bit)
        Chrome App 

**Additional context**
This problem happens with the above mentioned browsers.
It just happens as I’m typing any document, the page seems to blink like it’s refreshing and the cursor jumps left/back a random amount of characters. As I keep typing the cursor changes position and my words endup in another place.

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!

**Comment by Mesh959** [comment]
This is still happening after the recent update

**Comment by Mesh959** [comment]
> Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!

This is still happening after the recent update
