### ISSUE TITLE
Incorrect next repetition time after answering hard

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#263]
**Describe the bug**
When I answer hard on a card, for some reason the card gets scheduled again on that same day thus resulting in more than one review on a day for that card as shown here 
![image](https://user-images.githubusercontent.com/24322880/98201863-84d7a080-1ee5-11eb-942a-5db589566e0a.png)
I think, every time the card gets rated/answered in the queue, the next repetition time gets incremented. So, in this case the increment happened twice and therefore resulting in a next repetition time too far (14 days) in future. The previous interval was three days, regardless of whether I rated/answered solid or hard, the next repetition of 14 days is too far 

**To Reproduce**

1. Create bunch of cards
2. Pick one card and answer it (over a period of time) solid - solid - hard - hard - solid (hopefully these last two gets scheduled on the same day)
3. Make sure that you have enough cards to review each day for this to happen
4. Make sure that you clear your queue everyday.
5. After the above steps, check the metadata, hopefully that shows the same behavior as what I am seeing.

**Expected behavior**
The card shouldn't get scheduled on the same day in the first place. The next repetition time after answering hard shouldn't be that far away 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: Version 86.0.4240.183 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
- haven't tested

**Additional context**
If you just create a brand new card and in the first review if you answer hard, the card gets scheduled immediately, is that the expected behavior ? (because I don't see that in the scheduler examples in the settings) If that is not the expected behavior then this itself could be the bug

**Comment by ad1tyachaudhary** [comment]
[mG4DdLiHuK.zip](https://github.com/remnoteio/remnote-issues/files/5493471/mG4DdLiHuK.zip)
This is just one of the bug I am encountering and managed to record, missing cards and sync are other major issues.

**Comment by tfiwm** [comment]
Found another card with similar issue. I think the root cause is, somehow some cards are getting scheduled more than once a day. I got the following card twice in the queue today. The _next practice time_ for this particular card is in 20 days, instead it must have been something between 6 to 10 days. I think it calculated wrong _next repetition time_ because of the bogus review. It is not because I made edits to that card. Also, this issue could be related to https://github.com/remnoteio/remnote-issues/issues/256 and https://github.com/remnoteio/remnote-issues/issues/264. I think these issues are exposing some bug in the scheduler algorithm.

![image](https://user-images.githubusercontent.com/24322880/98955837-3c574e80-24b4-11eb-92f7-703ef228bc30.png)

**Comment by tfiwm** [comment]
At this point I am quite confident that the issue is consistently reproducible. Whenever a card is answered with 'Hard', it gets added to the queue immediately, resulting in two back to back reviews, which results in wrong next repetition time. Here is another card - Since I answered 'Hard' I expect the next repetition time to be less than around 16 days but it is 21 days here (probably the combined effect of answering 'hard' and 'solid' back to back on the same day)
![image](https://user-images.githubusercontent.com/24322880/99355054-729e2080-285c-11eb-883f-9873561945f6.png)
