### ISSUE TITLE
RemNote remains on loading screen 100%

### ISSUE THREAD

**Issue by Zarar98** [remnoteio/remnote-issues#265]
<img width="1280" alt="Screenshot 2020-11-05 at 20 04 02" src="https://user-images.githubusercontent.com/74021194/98291037-671c4100-1fa2-11eb-8803-6424209ff04f.png">

I do not know if you can see the screenshot above but for some reason I tried to open my RemNote and it just keeps showing Loading 100%. Logging out did not even work.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
