### ISSUE TITLE
Cloze Arrows

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#266]
![image](https://user-images.githubusercontent.com/20538090/98453866-fe35f400-216e-11eb-8641-1f670b8af572.png)"
The arrows still don't go even though the mouse is not on it (But when you bring mouse cursor on it and away it is disappearing, it's a little annoying)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
