### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#267]
**Describe the bug**
endless loading and updating your account without any progress  
**To Reproduce**
Select some texts by mouse
**Screenshots**
![image](https://user-images.githubusercontent.com/72897552/98463186-6ed32400-21f4-11eb-913a-499fc7d6e25c.png)
**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]

**Comment by mfranzs** [comment]
This should be fixed in the next update. For now, can you please try logging out and then back in? Sorry for the inconvenience.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
