### ISSUE TITLE
Connecting to Google Acount links to Error 404 on Smartphone

### ISSUE THREAD

**Issue by Klemens98** [remnoteio/remnote-issues#268]
**Describe the bug**
Hey suddenly when I open up remnote either in Safari or Google Chrome I was logged out, and when I try to click on the sign in with google button, I am linked to the error 404 page.

**To Reproduce**
Either Open Safari or Google Chrome
Try to click on any button to sign
Then click on Sign in with Google
Error 404 Page shows up

**Expected behavior**
Link to google to log in with your Google account

**Screenshots**

**Desktop (please complete the following information):**
IOS
Google Chrome and Safari have been tried out.

**Smartphone (please complete the following information):**
iPhone 11 Pro Max, the newest version of IOS

**Additional context**

**Comment by Spidersouris** [comment]
Not on smartphone but same problem here. Windows 10, Firefox Nightly 84.0a1 (2020-11-09). Redirected to https://www.remnote.io/auth/google but leads to a 404 error. No particular error in the console.

**Comment by DataSciLearner** [comment]
I have the same problem with iOS safari and google browser.  [See my post on this at the forum.](https://forum.remnote.io/t/help-unable-to-log-back-into-remnote/774) A [solution ](https://forum.remnote.io/t/help-unable-to-log-back-into-remnote/774/16?u=brindha)provided that worked for me was to use Ecosia browser.

**Comment by anishaaa1** [comment]
+1, have this issue with Safari and Chrome on the mobile version.

**Comment by mfranzs** [comment]
This should be fixed in the next update. Are you able to log in if you directly navigate to https://www.remnote.io/auth/google, or refresh that page after loading? Sorry for the inconvenience.

**Comment by anishaaa1** [comment]
> This should be fixed in the next update. Are you able to log in if you directly navigate to https://www.remnote.io/auth/google, or refresh that page after loading? Sorry for the inconvenience.

Hey, I tried this and it worked once but with every subsequent attempt, it showed me the 404 Error page.

**Comment by Spidersouris** [comment]
> 
> 
> This should be fixed in the next update. Are you able to log in if you directly navigate to https://www.remnote.io/auth/google, or refresh that page after loading? Sorry for the inconvenience.

Doesn't work for me. Thanks for fixing the issue though.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
