### ISSUE TITLE
Rem still in sidebar when not taged as document

### ISSUE THREAD

**Issue by yannisTr** [remnoteio/remnote-issues#27]
**Describe the bug**
Hi ! I really love Remnote and use it for taking notes on my academic readings. This morning a little problem that i never had before occured : I was working on some documents, and when I untaged them as docs they were still visible in my sidebar and the only way for me to make it invisible is to delete it (and I don't want to do this). Later on I discovered that when I create a document it doesn't appear auttomatically in my sideby either. This problem occured this morning and I never had it before. 

**To Reproduce**
1. Choose one of your doc
2. Untag it at a doc
3. See that it is still visible in your sidebar

OR

1.Create a doc
2. See that it doesn't appear in your sidebar

**Desktop (please complete the following information):**
 - OS: [Chrome OS]
 - Browser [chrome]
- Version 84.0.4147.94 (Build officiel) (64 bits)

Best Regards, 

Yannis

**Comment by mfranzs** [comment]
Thanks for the report. 

A) When you say "this morning", was this less than 3 hours ago or greater than three hours ago?

B) Can you follow these steps, please?
1) Press "Ctrl + O".
2) Search for "Document Sidebar".
3) Press the "Restore default sections" button at the top of the page that opens.

**Comment by yannisTr** [comment]
It was less than 3 jours ago. 
I did the steps in B), here is what happens : 
1. The documents that I created appear
2. Those I untagged do not disapear (I still should delete them to do do)
3. When I create a Doc it still doestn't appear automatically (I need to do B again) 

Thanks for your reactivity !

**Comment by yannisTr** [comment]
Problem solved ! 
To solve the problem I juste deleted all my browsers datas (cookies, cache...). Gor the moment it works fine and all the problems mentionned above are solved. 

Thanks again, and sorry for having report before doing that

**Comment by mfranzs** [comment]
Glad to hear that this is resolved - please let us know if this shows up again!
