### ISSUE TITLE
Pasting references shows reference in bolded format

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#271]
**Describe the bug**
Upon pasting a reference to a rem, the reference appears in bold format (see screenshot).

**To Reproduce**
1. Copy a reference to a rem ~~using Ctrl + Shift + R or~~ by right-clicking the reference and selecting Copy Rem Reference to Clipboard
2. Paste it anywhere
3. See that the reference appears in bolded format

**Expected behavior**
Should just display the reference without any formatting.

**Screenshots**

![image](https://user-images.githubusercontent.com/68901589/98932945-7565e200-24f9-11eb-975d-8c16c7b8ec15.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 86.0.4240.193 (Official Build) (64-bit)

Edit: Does not happen with Ctrl + Shift + R, only the other alternative mentioned.

**Comment by mfranzs** [comment]
Thanks for reaching out. I'm having some trouble reproducing this. Does this happen for all of your Rem?  Do you have any custom CSS?

**Comment by anishaaa1** [comment]
It happens with all rems. Nope, no custom CSS. I attempted it again and realized that I made a mistake in the report and have corrected it. Could you try to reproduce the bug by right-clicking > Copy Rem Reference to Clipboard and then pasting?

**Comment by anishaaa1** [comment]
> Thanks for reaching out. I'm having some trouble reproducing this. Does this happen for all of your Rem? Do you have any custom CSS?

It happens with all rems. Nope, no custom CSS. I attempted it again and realized that I made a mistake in the report and have corrected it. Could you try to reproduce the bug by right-clicking > Copy Rem Reference to Clipboard and then pasting?

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
