### ISSUE TITLE
keeps on "updating the account"

### ISSUE THREAD

**Issue by hatchellm8** [remnoteio/remnote-issues#272]
**Describe the bug**
it keeps on "updating the account", but the files always stays "0/(total files)"
**To Reproduce**
1. Go to 'left side menu panel'
2. below the option of 'documents'

**Expected behavior**
eventually the update should stop at some point of time 
**Screenshots**
![image](https://user-images.githubusercontent.com/74457097/99147775-a127ca00-26a9-11eb-8ddf-bd3a9f1bf5e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 32 bits
 - Browser - chrome
 - Version - 86.0.4240.198 

**Additional context**
Is it because my notes contain large number of image files?

**Comment by mfranzs** [comment]
This should be fixed in the next update. For now, can you please try logging out and then back in? Sorry for the inconvenience.

**Comment by hatchellm8** [comment]
thank you.
