### ISSUE TITLE
Cards sometimes appear in portals in queue

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#274]
**Describe the bug**
Some rems appear in portal form in the queue and can be scrolled through to see the rest of the document that they are a part of. This only happens **sometimes** and an inconsistent fix is to just refresh the page or exit/re-enter the queue via the sidebar and the same rem would appear normally. But sometimes it retains the weird, portal format.

**To Reproduce**
You could try to reproduce Screenshot 2:
1. Create a rem named A (same as Thenar muscles in screenshot) and also create child rems B, C and D (same as Opponens pollicis etc. in screenshot) which are multilines with their own content
2. Convert A into a multiline (B, C and D are not a part of the multilines) 
3. Create a single portal to B, C and D with their card contents hidden, i.e. focus on B/C/D and Cmd + Shift + ↑
4. Drag this portal to the blank rem created when converting A into a multiline such that the portal (to B, C and D) is now a content of the multiline rem A
5. Have a look at the queue - try a few times since it happens occasionally

**Expected behavior**
The rem should appear as any normal rem would even if it has been incorporated in the form of a portal somewhere - especially if within the portal its card contents are hidden.

**Screenshots**

1 - Portal form of a rem appearing in the queue (can be scrolled up to see the rest of the document that it is a part of)

![image](https://user-images.githubusercontent.com/68901589/99178473-dcb7a800-272c-11eb-8573-1e67b0aa6f55.png)

2 - Document that this rem is a part of in case there is a relation

![image](https://user-images.githubusercontent.com/68901589/99178481-ef31e180-272c-11eb-8e7d-64e9f7131db5.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by anishaaa1** [comment]
Not restricted to the above situation apparently. If rems are in portals somewhere in your knowledge base, sometimes they get asked as they are in the portal regardless of if there are other rems in there with all their content showing.

I come across these a lot but here's one that isn't like the above, it's just a rem that is in a portal somewhere and instead of appearing normally, it appears as it does in portal form :

![image](https://user-images.githubusercontent.com/68901589/99868070-aec4de80-2bd8-11eb-99a5-91e2b30e3f57.png)

**Comment by mfranzs** [comment]
This is the experimental "Documents Cards" feature - if you dislike this, you can disable it in your settings. We do still want to polish and improve the UX here, but for now I'll mark this "working as intended". Thanks!
