### ISSUE TITLE
Creating a question causes the cursor to go back two units

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#275]
**Describe the bug**
When I input ?:: my cursor moves two "units" backwards, so between ? and the first :

**To Reproduce**
1. Write something starting with a capital letter
2. Write ?:: at the end
3. See error

**Expected behavior**
The cursor not to move backwards

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/99185509-9ffaa980-274a-11eb-9da1-de7982d85b98.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 2020
 - OS: iPadOS 14.2
 - Browser safari
 - Version 14

**Comment by ad1tyachaudhary** [comment]
Already reported and probably will fix in the next update.
https://github.com/remnoteio/remnote-issues/issues/260

**Comment by tfiwm** [comment]
This is the exact issue (hopefully fixed in next update) https://github.com/remnoteio/remnote-issues/issues/255

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
