### ISSUE TITLE
Issue with Queue - Flashcards & Spaced repetition

### ISSUE THREAD

**Issue by KindlyJournalist69** [remnoteio/remnote-issues#277]
I started using remnote yesterday. I prepared around 160 flashcards yesterday and decided to do the reviews today morning.

1. When I opened on my mobile app, queue was 0 and was shown as completed. Same on logging on my mobile browser.

When I logged in via my laptop, queue was only 16.
I solved them and I realized that most of my flashcards werent shown. I went to the document seperately and clicked practice flashcards with spaced repetition and it showed that i already completed them. (when I didnt)

2. Also, do we need to pin the documents everyday again. I cant see the documents I pinned yesterday in the pinned section today morning.

3. When I started my reviews and finished my target, there was an option of "keep Learning" ( I thought since there are remaining cards left) and when I clicked that, 2 cards were coming repeatedly and I kept answering recalled immediately and later only noticed that the space repetition went quickly from days to months without me noticing. 
There are some severe bugs. Please rectify it!!

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
