### ISSUE TITLE
Created Rem cards never show

### ISSUE THREAD

**Issue by lishh** [remnoteio/remnote-issues#279]
**Describe the bug**
Not all my rem cards are included in my queue, not even for the first time 
**To Reproduce**
1.- I created some new cards

**Expected behavior**
I hoped automatically they are added to my queue 

**Screenshots**

**Desktop (please complete the following information):**
Chrome in Linux

**Smartphone (please complete the following information):**
Android, but the cards were created on a desktop computer with Linux and Chrome

**Additional context**
Is this a problem with the configuration of my Rem cards?
Any help in how to check if this is ok?

**Comment by mfranzs** [comment]
Thanks for reaching out. Are you still encountering this issue if you refresh after the latest update?

**Comment by lishh** [comment]
Now, it is ok, but I did many things, I reorder my documents inside the main carpet, also I deleted all those rems and added them again. So, not sure what of those I did actually worked
