### ISSUE TITLE
Scoped Search Portals (isDecendant) are empty

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#28]
Edit: see [comment below](https://github.com/remnoteio/remnote-issues/issues/28#issuecomment-671274654).
<hr>

**Problem**
When I take notes about a book I try to tag valuable insights. When I do this for multiple book I struggle to get a list of tagged Rems from a single book which I would like to include as a Search Portal at the top of that books page.

**Preferred solution**
A query syntax for Search Portals to only get the decendants of Rem, i.e. I search for the book `Sapiens` like `Sapiens >` which matches all decendant Rems and filter further (AND) with a tag.

**Describe alternatives you've considered**
I don't know if there already is special syntax for Search Portals. I could only figure out how to search for text, Rems or Tags separately, like the Search Portal stubs on each page.

Searching for multiple tags seems to use OR by default (list all Rem which match either tag).
RoamResearch seems to solve this with queries.

**Comment by hannesfrank** [comment]
I found this functionality in the search dialog (ctrl + f) where you can add a Search Portal from the search. It is prefixed with `isDecendant:<title of the Rem>`

It does not work for me though. The generated search portal always stays empty no matter if I search for text or just use a tag.

**Comment by hannesfrank** [comment]
Duplicate of/related to #36 #35

**Comment by mfranzs** [comment]
Thanks for the clear report! We've reproduced this and will deploy a fix in the next update.
