### ISSUE TITLE
Importing Arabic cards

### ISSUE THREAD

**Issue by kmz123** [remnoteio/remnote-issues#280]
I tried importing my Arabic vocabulary cards from Anki to RemNote desktop. While it was being imported some cards were randomly sent to trash. While I was able to recover them, I tried importing them again to see if it would happen and unfortunately it did.

I would appreciate if you could fix this issue

**Comment by mfranzs** [comment]
Thanks for reaching out. Would it be possible to share the Anki deck with us, or just a subset of the deck?

**Comment by kmz123** [comment]
The file format isn't supported.

Here's the link to it instead https://ankiweb.net/shared/info/905814418

**Comment by kmz123** [comment]
Is there any way I could get an update on this

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
