### ISSUE TITLE
Type Chinese in the begining position of the line cause the page crash in the Firefox!

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#281]
**Describe the bug**
Type Chinese in the begining position of the line cause the page crash in the Firefox!
Even in the search bar has the same problem

**To Reproduce**
1. Go to Firefox'
2. Type some Chinese in the begining of the line
3. See error

**Expected behavior**
fix it

**Screenshots**

![](https://pic.downk.cc/item/5fb5d9abb18d6271138c53e1.gif)

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [Firefox]
 - Version [lastest version]

It has existed for a long time
Hope developer could fix it as soon as possible!

**Comment by drkvj** [comment]
merging with #812
