### ISSUE TITLE
large Data Anki Deck is causing remnote not to load properly

### ISSUE THREAD

**Issue by EngAhmed91za** [remnoteio/remnote-issues#282]
**Describe the bug**
uploading Anki deck especially one that contains lots of data (images/ audio files) is causing my anki account to crash in firefox and not load properly in chrome and takes ages to delete the large date in the anki decks

**To Reproduce**

**Expected behavior**
uploading large anki deck is probably the cause of the issue, one that could reach 200Mbs

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 86.0.4240.198 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
the 3 dots next to the rem takes ages to load on a large data file deck from anki

**Comment by mfranzs** [comment]
Thanks for reaching out. Do you know approximately how large the Anki Deck you tried to import was?
