### ISSUE TITLE
arabic text not supported proparly, and flashcard preview sidebar not working proparly

### ISSUE THREAD

**Issue by EngAhmed91za** [remnoteio/remnote-issues#283]
**Describe the bug**
there seems to be an issue after uploading anki deck with arabic text as it reverses the text of the panel

**To Reproduce**

**Expected behavior**
it's clear that it happened after uploading arabic anki deck

**Screenshots**
![image](https://user-images.githubusercontent.com/24923960/99638602-8661a680-2a57-11eb-8c4c-8a798676e860.png)

![2020-11-19_7-26-41](https://user-images.githubusercontent.com/24923960/99638685-a2fdde80-2a57-11eb-8739-498850f910ee.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari]Chrome
 - Version [e.g. 22] Version 86.0.4240.198 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
this happens after making arabic text rems and uploading anki arabic deck, the sidebar below that add portals also have icons mixing with one on top the other

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
