### ISSUE TITLE
Do not use event.which for keyboard shortcuts

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#284]
It creates localization issues and some other inconsistencies and it is deprecated anyway.

I'll make a larger FR about keyboard driven workflow with more details soon. 

Maybe you just [forgot the `byKey: true` option](https://github.com/ianstormtaylor/is-hotkey#api)?

**Comment by mfranzs** [comment]
Wow, thanks for finding the fix for us! How did you figure out that we're using `is-hotkey`? :smile:

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
