### ISSUE TITLE
My Todo powerup got duplicated (temporarily) in the last update

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#285]
Before the last update I had a the todo power up and some additional notes in it.

Now I have 3 Todo rems:

- The power up + `#Document` which is my old TODO. It has no slots anymore but all my old todos are tagged with this rem. (It has document because I pinned it to the sidebar.)
- The power up which is the new TODO.
- An initially _Unnamed_ rem holding my additional notes. I renamed it to `Todo Notes` to be able to find it more easily now.

![image](https://user-images.githubusercontent.com/4137110/99647465-1d2b6480-2a52-11eb-9390-1f1abaae8fa3.png)

I don't think this affects any other power ups.

Update: When I exported my knowledge base just now it caused a reload and now both PowerUps are merged again.

**Comment by drkvj** [comment]
Since this is already resolved, I am closing this.
