### ISSUE TITLE
The context menu has a lower z-index than a preview

### ISSUE THREAD

**Issue by kirill-tkachev** [remnoteio/remnote-issues#286]
**Describe the bug**
A preview of a document is over the context menu in chrome.

**To Reproduce**
1. Go to https://www.remnote.io/knowledge-base
2. Right click on any particular document that you want to open with spaced repetition
3. Click on 'Practice Rem in Document'
4. See error - context menu is under document preview

**Expected behavior**
The context menu has a higher z-index than the preview. Or preview isn't showing while the context menu is open.

**Screenshots**
<img width="797" alt="Screenshot 2020-11-19 at 11 36 24" src="https://user-images.githubusercontent.com/13299081/99649375-d131ed00-2a5c-11eb-8de7-9a67711c9288.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version:  86.0.4240.111

**Comment by moritzWa** [comment]
Sorry, I could not reproduce this. Is this issue still occurring? And have you installed or applied CSS modifications that might result in this issue?

**Comment by kirill-tkachev** [comment]
> Sorry, I could not reproduce this. Is this issue still occurring? And have you installed or applied CSS modifications that might result in this issue?

Looks like it's working properly now.
