### ISSUE TITLE
.code-nodes should be blocks

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#287]
**Describe the bug**
I think code blocks should have `display: block;` instead of `inline-block`.
![image](https://user-images.githubusercontent.com/4137110/99702059-a3b56580-2a95-11eb-81e6-3aebb155bce0.png)

If I put a linebreak after "Example" it creates an empty line which is only there when the rem is hovered/focused. This is also no option.

**Desktop**
 - OS: Windows
 - Browser Chrome 85

**Comment by hannesfrank** [comment]
This probably caused to have Custom CSS code blocks to be striked out.
`text-decoration` seems to be only stopped from propagating by `display: inline-block`: see e.g. https://stackoverflow.com/questions/13857853/why-does-display-inline-block-remove-an-underline-from-a-child-element/13857910

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
