### ISSUE TITLE
Line through :: does not appear when disabling rem unless you focus elsewhere

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#288]
**Describe the bug**
When disabling a flashcard fully using the keyboard shortcut Cmd + /, the visual indication that the card has been disabled, i.e. the line through the separator ::, does not appear unless you focus your cursor elsewhere.

**To Reproduce**
1. Create a flashcard — X:: y
2. Disable it fully using the keyboard shortcut Cmd + /
3. Notice that the / through the :: does not appear unless you focus elsewhere (focus on another rem or hover over bottom toolbar etc.)

**Expected behavior**
The line should appear through the flashcard as soon as it's been disabled the way it used to, it's rather confusing otherwise.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Chrome
 - Version 86.0.4240.198 (Official Build) (x86_64)

**Additional context**
Visual depiction of which side of the card is enabled/disabled is correctly displayed in the bottom toolbar, it's only the visual indicator on the :: itself that is buggy

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by anishaaa1** [comment]
Hey, this problem has resurfaced recently. Not sure if it was the update that triggered it, but I've just noticed it.
