### ISSUE TITLE
Descriptor without value vs plain Rem

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#29]
**Describe the bug**
A lowercase plain Rem and a descriptor without value are indistinguishable (without clicking on them), but references to them are displayed differently. This has confused me.

**To Reproduce**
1. write a lowercase (plain) rem
2. add `::` to turn into a descriptor
3. delete `::` again (it stays a descriptor)
4. wait until you forget or just don't notice that you turned it to a descriptor accidentally
5. get confused by its Rem Reference

**Expected behavior**
I don't know if it stays a descriptor by design (if so, why?). Maybe it should not. If this is intended then I would like more documentation on this (see context below).

**Screenshots**
![image](https://user-images.githubusercontent.com/4137110/89729266-3c1e6180-da34-11ea-9dad-05dad5992c0b.png)

**Desktop (please complete the following information):**
Linux Mint, Chromium 84

**Additional context**
I find it hard to extract all the information about different Rem types from the documentation. Maybe an additional summary page about Rem types, how they are displayed and how flashcards are generated would be helpful. For example I don't know what the little x after a Rem Reference means exactly and when it happens. I know there was a tooltip once, but I forgot and I can't find the info now. I also remember wondering at the beginning what the bar before a Rem Reference is but this was easier to find out.

**Comment by mfranzs** [comment]
Thanks for the clear report. This was unintended behavior - removing the `::` should revert the Rem to no longer be a descriptor. We've reproduced this and will deploy a fix in the next update.
