### ISSUE TITLE
Endless reload loop

### ISSUE THREAD

**Issue by matleonii** [remnoteio/remnote-issues#290]
**Describe the bug**
When I enter RemNote's website using Firefox it enters a endless page reload loop.

**To Reproduce**
Access RemNote using Firefox.

**Expected behavior**
Enter RemNote

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser FireFox 
 - Version 82.0.3 (latest version)

**Additional context**
(I tried clearing the date from the browser and the bug persists)
(using opera it works just fine)

**Comment by calebringabell** [comment]
hey, i just posted about this too. should i delete mine?

**Comment by matleonii** [comment]
> 
> 
> hey, i just posted about this too. should i delete mine?

I guess so. in order to make the issue tracker more organized.

I guess that knowing that this is something that is happening with more people already helps.

**Comment by anishaaa1** [comment]
Happens on my iPad running on iPadOS 14.2 on Safari as well.

**Comment by amithm7** [comment]
Have the same issue Firefox 84. I see these errors in network log: 

![image](https://user-images.githubusercontent.com/7036770/99873935-aafd8000-2c09-11eb-9df9-7bb223ba7756.png)

**Comment by kirill-tkachev** [comment]
Hey, guys, I had the same issue.
Clearing all the application storages (cookies, sessionStorage, localStorage, etc.) worked for me as a fix.
Perhaps some caching issue.

**Comment by matleonii** [comment]
> 
> 
> Hey, guys, I had the same issue.
> Clearing all the application storages (cookies, sessionStorage, localStorage, etc.) worked for me as a fix.
> Perhaps some caching issue.

I had tried this before posting this here but it did not worked. But I tried again and now it solved the problem

**Comment by nhanvu327** [comment]
> Hey, guys, I had the same issue.
> Clearing all the application storages (cookies, sessionStorage, localStorage, etc.) worked for me as a fix.
> Perhaps some caching issue.

it's not a fix. It's a workaround. Seem like the sync endpoints failed when they have to handle a big payload. Ex when you delete a folder which contains a huge amount of rems inside.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
