### ISSUE TITLE
Mozilla Firefox Constant reload bug

### ISSUE THREAD

**Issue by calebringabell** [remnoteio/remnote-issues#291]
**Describe the bug**
When I was on Firefox anytime I tried going to renmote, after making an account, I was brought to the main page of my notes? and then it would reload the page, and then reload it again, and then again. Does not do it on chrome.
**To Reproduce**

**Expected behavior**
I expected to use Remnote on mozilla firefox
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] microsoft
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 83.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kirill-tkachev** [comment]
I had the same issue.
Clearing all the application storages (cookies, sessionStorage, localStorage, etc.) worked for me as a fix.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
