### ISSUE TITLE
search for rem orients the wrong position

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#293]
**Describe the bug**
When i use search bar to search a rem and click it,it often jumps to a wrong position in a document instead of the rem page

**Comment by mfranzs** [comment]
Thanks for the report. What browser and operating system are you using? Does this happen in all documents, or any some?

**Comment by plusjhjhjh** [comment]
> Thanks for the report. What browser and operating system are you using? Does this happen in all documents, or any some?

In some document which is set be the no parent rem from child rem.Even i delete the potral, when i try to search it, it still orients the last position.And the rem page appear it still in it's orgin document.I don't know how to separate it from it's orgin document

**Comment by plusjhjhjh** [comment]
Chrome on Windows10 and Safari on iOS both have the same issue

**Comment by drkvj** [comment]
Thanks for submitting this, and apologies for not responding sooner, we are now cleaning up all the reports, to make sure this can be an efficient process from now
Have you been noticing such behaviour still? Kindly follow this discussion on the forum, where we will be actively handling such matters from now on.
