### ISSUE TITLE
Self-generated Blank Documents

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#294]
![image](https://user-images.githubusercontent.com/20538090/99887487-e32ab000-2c55-11eb-968b-4ff4b2491343.png)
sometimes i see empty documents when i open the remnote
![image](https://user-images.githubusercontent.com/20538090/99887505-fdfd2480-2c55-11eb-9c4c-88c3f7ba1a82.png)

**Comment by mfranzs** [comment]
Thanks for the report. Have you noticed any pattern for when these documents generate? Which sidebar section do they appear in?

**Comment by Eikosa** [comment]
**these are all top level rem**
![image](https://user-images.githubusercontent.com/20538090/101371682-16a74480-38bc-11eb-9813-60746f1bf11a.png)
![image](https://user-images.githubusercontent.com/20538090/101371752-2f175f00-38bc-11eb-9722-819f7deaae0e.png)
![image](https://user-images.githubusercontent.com/20538090/101371828-435b5c00-38bc-11eb-9a09-6734d8bfc43a.png)
![image](https://user-images.githubusercontent.com/20538090/101371853-49e9d380-38bc-11eb-9969-49ee2d0e013b.png)
I did not create that named (I) and (0) documents
their content consists entirely of random things or is empty
![image](https://user-images.githubusercontent.com/20538090/101371971-6f76dd00-38bc-11eb-9310-9337fab77e2a.png)
![image](https://user-images.githubusercontent.com/20538090/101372033-7ef62600-38bc-11eb-92a1-66303fb4b251.png)

**Comment by drkvj** [comment]
Thanks for the report, kindly follow up on this thread [here](https://forum.remnote.io/t/documenting-the-zombie-rems-and-sync-related-issues/2966?u=karthikk) if you are still experiencing similar problems. Once we have a better idea about how this can be reproduced, we can submit a report here.
