### ISSUE TITLE
Sorry, you don't have access to this document

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#295]
![image](https://user-images.githubusercontent.com/20538090/99887572-71069b00-2c56-11eb-802d-611e75fcea4f.png)
"Sorry, you don't have access to this document."
after deleting the document, it does not redirect anywhere and the following text appears

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
