### ISSUE TITLE
Rem option tooltip is occluded in Dark Mode

### ISSUE THREAD

**Issue by younke** [remnoteio/remnote-issues#296]
**Describe the bug**
Rem option tooltip is occluded in dark mode. Everything is fine when dark mode is off.

**To Reproduce**
1. Make a rem
2. Select one of rem configuration icons
3. Hover on one of the options
4. Tooltip appear behind options window

**Expected behavior**
Tooltip should appear normally and be readable

**Screenshots**
![image](https://user-images.githubusercontent.com/12050609/99896994-f7fc5780-2cd8-11eb-91e6-5b54d12f105f.png)
![image](https://user-images.githubusercontent.com/12050609/99897058-a43e3e00-2cd9-11eb-8025-67b69b0240b8.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version 86.0.4240.198 (Official Build) (x86_64)

**Additional context**
Remnote update: November 17th, 2020

**Comment by drkvj** [comment]
This has been fixed, thank you for the report.
