### ISSUE TITLE
"Selection area" of breadcrumbs exceeds its margins

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#297]
**Describe the bug**
When trying to click something in the breadcrumbs, regardless of if the rem has a short title or a long one, the area of text within which you click to select the breadcrumb is extra long and exceeds the margins of the breadcrumbs menu (see Screenshots).

**To Reproduce**
1. Hover over to the breadcrumbs
2. Observe that the "selection area" exceeds the margins of the breadcrumbs menu

**Expected behavior**
Selection area should be limited to the margins of the breadcrumb menu.

**Screenshots**

Rem with a long title:

![Screen Shot 2020-11-20 at 8 28 46 AM](https://user-images.githubusercontent.com/68901589/99898366-5b2ac180-2cba-11eb-8403-74816a13ce49.png)

Rem with a short title:

![Screen Shot 2020-11-20 at 8 28 34 AM](https://user-images.githubusercontent.com/68901589/99898369-5cf48500-2cba-11eb-9fae-65089e68aa8f.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Chrome
 - Version 87.0.4280.67 (Official Build) (x86_64)

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
