### ISSUE TITLE
RemNote clipper puts under "Links"child of another document

### ISSUE THREAD

**Issue by kalimatas** [remnoteio/remnote-issues#298]
**Describe the bug**
When I use RemNote clipper extension, it creates new documents under the random "Links" document. For example, I have "Some Document -> Links" hierarchy, and then the clipper creates all new documents as children of "Links".

**To Reproduce**
1. Create a "Some Document -> Links" hierarchy.
2. Use RemNote clipper extension to create a new document.

**Expected behavior**
To be honest, I'm not sure what is the expected behavior. Maybe a "Links" document at the root? Or some power-up document.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser Brave
 - Version 1.17.73

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
