### ISSUE TITLE
There are no way to delete the notification

### ISSUE THREAD

**Issue by link-ding** [remnoteio/remnote-issues#3]
**Describe the bug**
when I change some Rems to a multiple-line card item without a parent. Then after I delte all these Rems it will leave a notification and I can not find any way to delete this notification

**To Reproduce**
1. change some Rems to multiple-line card item without a parent also means no indent
2. delete all these Rems in the multiple-line card item
3. See error

**Expected behavior**
I do not want this notification show in my document

**Screenshots**
1. change some Rems to multiple-line card item
![image](https://user-images.githubusercontent.com/49264539/88525600-237a7880-d03e-11ea-9be8-dada82409d15.png)
2. delete all these Rem will give a notification
![image](https://user-images.githubusercontent.com/49264539/88525672-38570c00-d03e-11ea-8e2b-d06f5e2cf414.png)

**Desktop (please complete the following information):**
 - OS: [macos]
 - Browser [chrome]
 - Version []

**Additional context**

**Comment by TaQuangKhoi** [comment]
i think the video i made will help you..

https://mega.nz/file/mYMCWYKB#KFoVUDynm6H4_Y_so4La9U4zTX4_dJPjQsv6NTECS4Q

**Comment by link-ding** [comment]
> i think the video i made will help you..
> 
> https://mega.nz/file/mYMCWYKB#KFoVUDynm6H4_Y_so4La9U4zTX4_dJPjQsv6NTECS4Q

Thank you so much!!!

**Comment by mfranzs** [comment]
Thanks @TaQuangKhoi! Closing as this seems resolved.
