### ISSUE TITLE
Customizable keyboard shortcuts

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#30]
**Is your feature request related to a problem? Please describe.**
Some shortcuts (involving symbols) can not be pressed on some non-QWERTY layouts.
For example on a German QWERTZ layout (and probably many similar european QWERTZ variants) it is not possible to press press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>?</kbd> because `?` already is <kbd>shift</kbd>+<kbd>ß</kbd>.

**Describe the solution you'd like**
Keyboard shortcuts should be configurable, either in the options, or like many new fancy tools in a special Rem (which would be nice since you could learn the shortcuts directly).

Alternatively they should be simple enough to work on all layouts.

**Additional context**
I just recently found the page in the Community hub listing some more shortcuts than in the sidebar which could be incorporated in the tutorials.

There are also shortcuts not listed like <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>k</kbd> to open the second pane.

**Comment by mfranzs** [comment]
Thank you for the request. We will be releasing this feature in an upcoming update, and are also cleaning up the default shortcuts.
