### ISSUE TITLE
Remnote Clipper not having access

### ISSUE THREAD

**Issue by EngAhmed91za** [remnoteio/remnote-issues#300]
**Describe the bug**
Remnote clipper after the latest update takes a very very long time to sync and process and also at the end says I don't have access to this document, even after deleting the extension and reinstalling it, I checked via the three dots on the top right and I have access to my account via the clipper

**To Reproduce**
1. Go to 'remnote clipper icon'
2. Click on 'icon then open document'
3. Scroll down to 'go to the sidebar'

**Expected behavior**
it's possible the latest update to remnote affected it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 87.0.4280.66 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
![2020-11-23_18-23-27](https://user-images.githubusercontent.com/24923960/99980413-43863280-2db9-11eb-81c4-8990a4fd4cd0.jpg)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
