### ISSUE TITLE
Card counter resetting at inappropriate times

### ISSUE THREAD

**Issue by adr123** [remnoteio/remnote-issues#302]
**Describe the bug**
My time zone is CST. 
The counter of studied cards will reset at around 12pm every day. More specifically, the card counter will start going down around 30 minutes before 12pm , and by 12pm they would all be gone. 

**To Reproduce**
Study cards and wait till sometime before 12pm CST and see amount of cards studied that day go down (The blue line in the queue).

**Expected behavior**
I expected the card counter to preserve its information throughout the full day, resetting only at around ~12am.

**Desktop**
OS: Windows 10
Browser Chrome
Version 86.0.4240.198

**Additional information**
This is what happened one of these days (Although it always happens, I dont always study my cards in the morning or before noon so I dont always get to see this happening.)

I completed 83 cards at around 7am (CST) and went to check up on remnote a few minutes ago (~11:36AM). I saw that the card counter had decreased by around 40 cards, and then it continued to go down to 29 cards by 11:43AM. By 12pm the counter was at 0.

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
