### ISSUE TITLE
My rems have not been synced for a while

### ISSUE THREAD

**Issue by nhanvu327** [remnoteio/remnote-issues#304]
**Describe the bug**
My rems are not synced between devices in a day, I have very recent changes though.

![image](https://user-images.githubusercontent.com/31462490/100158855-f1e8bf80-2f00-11eb-8893-f4dc1ea2539d.png)

**To Reproduce**
Steps to reproduce the behaviour:
I just deleted a bunch of old rems

**Expected behavior**
They should be synced.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: chrome
 - Version: latest

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
