### ISSUE TITLE
Problems in exporting markdown or JSON

### ISSUE THREAD

**Issue by DataSciLearner** [remnoteio/remnote-issues#305]
**Describe the bug**
I have problem with export, both markdown and JSON; both in exporting the knowledge base or even a single document as markdown. The site repeatedly hangs with "aw snap" message when downloading the entire knowledge base as markdown (though the internet connection is fast and I have only a few Rem documents so far), or produces a zip file with no markdown files. The zip file from a single document too has no markdown files and is empty. The JSON zip file has only 10kb data with just some barebones and none of my Rems content

**To Reproduce**
Steps:
Click on settings. Then click on export and backup. Select markdown. Select files for each document and include all descendants. 

**Expected behavior**
I would expect the knowledge base to be exported as markdown or html or JSON. 

**Desktop and iPAD (please complete the following information):**
Devices info:
 - OS: Both Windows 10 and iPadOS
 - Browser : Chrome (version 87) in windows, and Safari/chrome in iPadOS 14.2

**Comment by drkvj** [comment]
Thanks for submitting this, and apologies for not responding sooner, we are now cleaning up all the reports, to make sure this can be an efficient process from now
Have you been noticing such behaviour still? Kindly follow this discussion on the forum, where we will be actively handling such matters from now on.
