### ISSUE TITLE
Cloze Deletion on Reference

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#309]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/20538090/100487710-28018b80-311b-11eb-8fd7-3973dfd89cd5.gif)
![O1H5KrLGei 555](https://user-images.githubusercontent.com/20538090/100487778-79aa1600-311b-11eb-97fb-20c00f58b133.gif)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
