### ISSUE TITLE
Copy pasting an image from geogebra

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#31]
**Describe the bug**

Copy pasting an image from geogebra makes the image appear twice. Edit: Using copy through the sharing button (square with arrow up) seems to cause the issue. Just tried pasting a screenshot and the same thing happened.

**To Reproduce**
1. Create something in geogebra
2. Click import image and then copy
3. Go to RemNote and paste

**Expected behavior**
Only one image should appear after the paste

**Screenshots**
![4E5FC2AF-82B3-4F9F-BB00-67631BFB71CA](https://user-images.githubusercontent.com/69430941/89737719-81ae4f00-da73-11ea-98c6-fab8950df28e.jpeg)
![9EDCE98E-3997-4018-BDE5-B1DF05A18C6E](https://user-images.githubusercontent.com/69430941/89737721-8410a900-da73-11ea-98d1-44e5d48ae562.jpeg)

**Desktop (please complete the following information):**
 - OS: 
 - Browser

**iPad (please complete the following information):**
 - Device: iPad Pro 9.7 inch
 - OS: iPadOS
 - Browser: Safari
 - Version 13.6

**Additional context**

**Comment by mfranzs** [comment]
Thank you for the report. Do you know if this is only happening on mobile Safari, or if it's also happening on other browsers?

**Comment by 8888Daniel8888** [comment]
I tried it on Chrome, Google, Firefox and even Safari (all on the iPad) and the issue seems to be completely gone
