### ISSUE TITLE
right to left language like Arabic is not fully supported

### ISSUE THREAD

**Issue by gotoayman** [remnoteio/remnote-issues#310]
while enabling right to left language in setting makes RemNote handle Arabic easily, especially with the movement of the sidebar to the right-side of the screen, there still a problem with the title of the rems  which shows from left to right. For example if i rote "رجل"  in the title it well show inverted like this "لجر".
this makes the program useless for right to left languages users.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
