### ISSUE TITLE
"Tagged rem" portals are not working in newly created dailies

### ISSUE THREAD

**Issue by SplitZadar** [remnoteio/remnote-issues#311]
**Describe the bug**
When I create a daily document, say November 29th, 2020 and tag some other document with it - my daily document doesn't update with expandable "Tagged Rem" portal.

Even if I create a search portal manually and search for the tag #November 29th, 2020, there are no results.

It used to work fine, I was able to find my latest daily with a working portal from November 16th , 2020.

One thing I did that maybe connected to this is mess with custom day format. Although since the issue I have reset the format to default and it didn't help.

[Screenshot of tagged document with todays date, and todays daily with empty tag portal](https://i.imgur.com/FRrzaNR.png)

**Comment by mfranzs** [comment]
Thanks for the report. Do your tags appear if you click the blue "refresh" icon on the right of the search portal?

**Comment by drkvj** [comment]
Have you been noticing such behaviour still? Kindly follow this discussion on the forum, where we will be actively handling such matters from now on.
