### ISSUE TITLE
image occlusion flashcards do not show up when I practice rems + only the first point of numbered card is shown as the answer when practicing rem (I expect all numbered points show together when answer is shown)

### ISSUE THREAD

**Issue by leungchunyuetjanice** [remnoteio/remnote-issues#316]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. I'm having some trouble reproducing this. Can you please give a screenshot or more detail?

**Comment by drkvj** [comment]
Closing this as the user hasn't responded and not able to reproduce.
