### ISSUE TITLE
image occlusion flashcards do not show up when I practice rems + only the first point of numbered card is shown as the answer when practicing rem (I expect all numbered points show together when answer is shown)

### ISSUE THREAD

**Issue by leungchunyuetjanice** [remnoteio/remnote-issues#317]
**Describe the bug**
image occlusion flashcards do not show up when I practice rems
only the first point of numbered card is shown as the answer when practicing rem (I expect all numbered points show together when answer is shown)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser -- chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Closing in favor of #316
