### ISSUE TITLE
Removing heading tag from multiline cart also removes concept status

### ISSUE THREAD

**Issue by visika** [remnoteio/remnote-issues#318]
**Describe the bug**
I have a Multiple Lines concept card. If the entry has a header property, say H2, and it is a Concept type Rem, when I remove the Heading property, also the Concept property gets deleted.

**To Reproduce**
1. Create a Multiple Lines Rem
2. Give the Rem a Heading property
3. Remove the Heading property

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Chromium webapp
 - Version 87.0.4280.66-1

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
