### ISSUE TITLE
Copy code block content with ctrl+c does not work

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#319]
**Describe the bug**
I can not copy code using keyboard only. This is unexpected since the text is (almost) selected correctly.

**To Reproduce**
1. Put cursor in code block
2. Ctrl + A to select all code (note that the language drop down is also selected)
3. Press Ctrl + C

-> Clipboard does not change.

**Expected Behavior**

The same as clicking the copy button.

- OS: Windows 10
- Browser: Chrome 85

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
