### ISSUE TITLE
THE SPACED REPETITION ALGORITHM IS NOT WORKING WELL!!!

### ISSUE THREAD

**Issue by danibermor** [remnoteio/remnote-issues#32]
when I study my flashcards, for example 100 flashcards, I only have 40 left to finish and instead of going to 39 this returns to 100 again even having answered all correctly,
I tried again from 100 ,  I advanced about 45(answering) and again it returns to 100, I tried this 4 times in that same moment but the same thing keeps happening, Rem Note HELP!!!!!!!!!!

**Comment by mfranzs** [comment]
Thanks for the report - this sounds strange.

1) What browser & device are you using?
2) Are you using multiple devices?
3) Did this problem only begin today?
4) Are these flashcards Cloze cards?
5) Is this in your main queue or your normal queue?
6) Do you see repeat cards coming through your queue?

**Comment by danibermor** [comment]
1.I am using Google chrome, using my laptop Lenovo windows 10
2. I am using just one device( My laptop)
3. this problem began like 3 weeks ago not at the beggining
4. yes many of them are cloze
5. that happens in both, when a study my main Queue and when I use the
queue in a folder
6. mm i dont think so ,  the cards repeats but  when it start since the
begining again and again , this is so stressful
Please help me as soon as possible!!!!! THE SPACED REPETITION IS ONE OF THE
PRINCIPAL FUNCTION AND THIS MUST WORK WELL ! :(

**Comment by mfranzs** [comment]
Thanks for the information. Can you please try these debugging steps?
1) Log out, then log back in.
2) Can you please check http://remnote.io/cards, sort by "Last Practiced" and let me know if the cards that you've most recently practiced appear?

**Comment by danibermor** [comment]
I did what you said me to do I tried these debugging steps, I logged out,
but now I cant enter again , and when try to log in it says username o
password incorrect, but I am sure i did it correctly, I even tried the
"forgot my password" option but when I put my email, it say "user not
found", PLEASE HELPPPPPP!!!!!! I have too much information an study time I
spent :( , Trying to solve a problem now I have another ,
my email account is "danielqm56@gmail.com" please give me a solution as
soon as possible!!!!

**Comment by mfranzs** [comment]
If you originally clicked the "log in with Gmail" button, please make sure
that you click that again to log back in.

**Comment by danibermor** [comment]
1. I logged out and enter log in again, so I started to study the flash
cards again, and the same error is happening I had 116 flashcards, and when
I was on the number 70 card I think, that started since 116 again and
believe me that happens so many times!!!!! what I tried yesterday was
refresh the page , and that made change the number from 116 to 70 again ,
but it doesnt matter , the problem is that  when you continue studying the
flashcards the problem continue and you return to 116 again, I am not the
onlyone with this problem, as I told you guys, please try to solve this
huge error as soon as possible,
2. In this option  "sort by Last practice"  yes  the most recently flash
cards I practiced appears.

 If you want, we can try another type of communication that is more fluid
and that does not take so long time to respond, in order to solve this
problem as soon as possible.
and about my problem to log in you meant tried the "log in with a google
account" option  right? because that worked for me

**Comment by mfranzs** [comment]
We've deployed a fix. Please let us know if you're still encountering problems!
