### ISSUE TITLE
Elixir language highlighting support in code block is broken

### ISSUE THREAD

**Issue by kolejomalba** [remnoteio/remnote-issues#321]
After creating code block, syntax highlighting works for other programming languages in the list, but not for Elixir.

Most likely cause for that is that Elixir is listed in the list of available programming languages as 'elixr' instead of elixir, ie. just a typo somewhere in the code.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
