### ISSUE TITLE
No Longer Able to Drag and Move Documents 

### ISSUE THREAD

**Issue by lritzer** [remnoteio/remnote-issues#322]
**Describe the bug**
I am no longer able to drag and move documents
**To Reproduce**
1. Go to '...' any document 
2. Click on '....' the document 
3. Scroll down to '....' try to move document 

**Expected behavior**
For the document to move 
**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lritzer** [comment]
When is the next update?

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
