### ISSUE TITLE
Multiple Panes: the non-active pane gets "stuck" as the one which updates rather than the (expected) active pane

### ISSUE THREAD

**Issue by webstert837** [remnoteio/remnote-issues#323]
**Describe the bug**
When in multiple pane mode, clicking a new sidebar document will not always update the active pane (by active pane I mean the one my cursor is currently in).  For example, I'm working in the right pane, then click a different document in the sidebar.  However, the _left_ pane is the one that changes to the new document, not the right (active) pane.   I get the same issue trying to follow a tag, reference or searching with ctrl-p: one pane gets "stuck" as the updating pane (sometimes the left, sometimes the right) even though it is not the active pane.  

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome  87.0.4280.88

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
