### ISSUE TITLE
my Rems it get random Document Tag ???

### ISSUE THREAD

**Issue by drstrangez0** [remnoteio/remnote-issues#325]
The tag ""Document"" is been adding to my rems randomly ??

**Comment by plusjhjhjh** [comment]
Same problem. When I zoom in a bullet, it will add “document“ tag automatically. It is happened on Ipad

**Comment by tfiwm** [comment]
Do you know if this is happening in your case ? [Why is the document tag automatically added to some rems?](https://forum.remnote.io/t/why-is-the-document-tag-automatically-added-to-some-rems/1154 )

**Comment by plusjhjhjh** [comment]
> Do you know if this is happening in your case ? [Why is the document tag automatically added to some rems?](https://forum.remnote.io/t/why-is-the-document-tag-automatically-added-to-some-rems/1154)

not this problem, i am sure i didn’t type anything in the source field

**Comment by drstrangez0** [comment]
> Do you know if this is happening in your case ? [Why is the document tag automatically added to some rems?](https://forum.remnote.io/t/why-is-the-document-tag-automatically-added-to-some-rems/1154)

no not this reason like @plusjhjhjh said when ever  i zoom to rem it get automatic ""Document"" Tag

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
