### ISSUE TITLE
Export and Backup not working

### ISSUE THREAD

**Issue by AnweshGangula** [remnoteio/remnote-issues#327]
**Describe the bug**
When I go to https://www.remnote.io/export and click on "Markdown", the page crashes and show the following error

> "Error: Invalid knowledgeBaseId 'undefined' available in cache for quanta. Only have keys: <`My User ID`>. URL: https://www.remnote.io/export"

**To Reproduce**
1. Go to 'https://www.remnote.io/export'
2. Select the 'Markdown' - radio button
3. See error

**Expected behavior**
This used to allow downloading an zip file of all the selected data from my Remnote Account in Markdown format.

**Screenshots**
![Remnote Export and Backup error](https://user-images.githubusercontent.com/22996896/101210968-63143980-369c-11eb-9695-4f27d45ea8c0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge Version 87.0.664.41 (Official build) (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
