### ISSUE TITLE
Pasting markdown code blocks does not work

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#328]
Like this:

````md
- my rem ```css
* {
  color: blue;
}
```
- my other rem
````

**Comment by mfranzs** [comment]
This is somewhat difficult to add, as it breaks our parser's assumption that new lines = new Rem. Would it be sufficient if we improved the parser to identify code blocks where the ``` stand alone on their lines?

**Comment by hannesfrank** [comment]
(See also our discussion on [Discourse](https://forum.remnote.io/t/remnote-library-request-for-comments/1182/14?u=hannesfrank))

Yes, this format would work as well. The format for pasting does not matter too much since I can configure it however I like.
My use case is to paste checked Todo CSS code blocks so the markup could look like that:
````
- [x]
```css
* {
  color: blue;
}
```
````
So the requirements are:
- The code block is joined with the previous (checked todo) rem and does not form a rem on its own. (I don't know if you have some flexibility here interpreting the bullet points, i.e. if it makes a difference to lead the code block with a `- ` or not.)
- The language hint is respected. I have to be able to set the language to CSS for example.

**Comment by hannesfrank** [comment]
Joining with the previous rem is not strictly necessary. I just assumed that a code block needs a checkbox which turned out to be false.

But then https://forum.remnote.io/t/custom-css-toggle-codeblocks-in-a-subtree/1280
would be an important QoL improvement since it is hard to checkbox a codeblock only rem.

**Comment by mfranzs** [comment]
This will be supported in the next update, along with a change such that any subtree with a "finished" todo will have all of its children ignored.

The ``` start and end tags must standa lone on their line (other than the code hint).

For example:

[ ] Feature
  ```css
  * {
    color: blue;
  }
  ```
  
  Gets parsed as 
  
![image](https://user-images.githubusercontent.com/953103/102425917-52d55600-3fdc-11eb-9f6c-0b29a28c2491.png)

**Comment by hannesfrank** [comment]
Woah! My favorite fearure since ever!

Martin Schneider <notifications@github.com> schrieb am Do., 17. Dez. 2020,
02:22:
