### ISSUE TITLE
Not able to edit Latex blocks

### ISSUE THREAD

**Issue by krankur** [remnoteio/remnote-issues#33]
Not able to edit Latex blocks.

**Steps To Reproduce**
1. Add a Latex block or go to an existing one.
2. Try editing the Latex block by clicking on it.
4. Following error is displayed:

> # Something went wrong.
> Please try refreshing the page. If the problem remains, please provide additional detail on the help page.
> 
> _Error: Cannot resolve a Slate point from DOM point: [object HTMLSpanElement],1. URL: https://www.remnote.io/document/..._

**Laptop:**
 - MacOS
 - Firefox
 - 79.0

**Comment by krankur** [comment]
The issue seems to happen only on clicking a Latex block. If arrow keys are used to navigate to the block then editing works fine.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this in Firefox and are deploying a fix.
