### ISSUE TITLE
"Uncaught Error: Invalid knowledgeBaseId 'undefined' available in cache for quanta." after deleting rem

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#334]
![image](https://user-images.githubusercontent.com/4137110/101244609-cd15f880-3707-11eb-8a93-6ce99315c997.png)

**To Reproduce**
I have not pinned it down exactly. It happens sometimes (?) after deleting a rem and then searching using Ctrl + P.
It is then also raised after each key press.

Reloading the page fixes it.

Windows 10, Chrome 85.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
