### ISSUE TITLE
Turning Plain Rem to Multiline Rem

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#336]
![Zwcj8cZXHT 591](https://user-images.githubusercontent.com/20538090/101260728-dd979480-3742-11eb-9e28-93b7be5c11ba.gif)
The answer of the rem is not deleted

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
