### ISSUE TITLE
Undo redo behavior unpredictable in Chrome

### ISSUE THREAD

**Issue by milessb** [remnoteio/remnote-issues#337]
**Describe the bug**
I'm experiencing unpredictable behavior for undo/redo (ctrl-z / shift-ctrl-z) while using Chrome. Basically at times it won't undo or it won't redo or it won't do multiple undo/redo. 

**To Reproduce**
So far I haven't figured out a consistent way of reproducing the problem. It seems to be more common when doing more complicated reformatting or editing like changing the bullet format/changing bullets to documents etc. But it has happened for just doing a series of highlighting too.

**Desktop (please complete the following information):**
 - OS: Mac OSX Big Sur
 - Browser: Chrome, current

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
