### ISSUE TITLE
Spaced-repetition has something wrong

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#341]
**Describe the bug**

![](https://pic.downk.cc/item/5fcc326e394ac523780e646a.jpg)

![](https://pic.downk.cc/item/5fcc326e394ac523780e6463.jpg)

 - OS: [ iOS14]
 - Browser [safari]

 Many cards in the queue have the same problem, which should be fixed as soon as possible.

**Comment by plusjhjhjh** [comment]
![](https://pic.downk.cc/item/5fcc364c394ac5237810b6f0.jpg)
![](https://pic.downk.cc/item/5fcc364c394ac5237810b6f2.jpg)
What happened?

**Comment by plusjhjhjh** [comment]
![](https://pic.downk.cc/item/5fcc36c9394ac5237810fdfd.jpg)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
