### ISSUE TITLE
 Doesn't convert to card when sending Rems via API

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#342]
![image](https://user-images.githubusercontent.com/20538090/101269375-62a09f00-377f-11eb-83ad-9c2ff903d3a5.png)

![image](https://user-images.githubusercontent.com/20538090/101269390-8237c780-377f-11eb-9c98-eb77d2c0361b.png)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
