### ISSUE TITLE
Expanding Rem References at the bottom of page automatically adds Search Portal

### ISSUE THREAD

**Issue by AnweshGangula** [remnoteio/remnote-issues#343]
**Describe the bug**
The References section at the bottom of any Rem is really helpful. But when I expand that to check all the references, a **search portal** gets added with the respective search condition (Text Reference, Tag etc..). But its not always useful. I often want to see the reference temporarily to go to the reference and make changes or view it. I would not want that to be a part of my current page.
So every time I click on the Reference, it creates the portal and I delete the portal. It would be nice if RemNote did not add the search portal every time its expanded.

**To Reproduce**
1. Go to Any REM which has references or tag associated.
2. Click on "Find Text References" or " _n_ Tagge Rem" at the bottom of the page
3. The respective section gets expanded and gets added as a search portal.

**Expected behavior**
Instead of the "Delete this Search Portal" button, there can be a button on the portal which says "Add to current REM" which can add it only if users wants to.

**Screenshots**
![REM Reference Portal](https://user-images.githubusercontent.com/22996896/101278304-78927c00-37e0-11eb-9162-9ffa51990b63.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge Version 87.0.664.41 (Official build) (64-bit)

**Comment by AnweshGangula** [comment]
Note that another issue with this behavior is

1. It gets listed in the "notIncludedChildren" section of the REM
2. They also get exported in the Export & Back-up which could create unnecessary duplicate.

**Comment by drkvj** [comment]
This report is not relevant anymore as the feature has been reworked and no longer produces these states. Thank you for the report!
