### ISSUE TITLE
Spaced Repetition Scheduler Not Working

### ISSUE THREAD

**Issue by tomlee95** [remnoteio/remnote-issues#344]
**Describe the bug**
The spaced repetition scheduler has stopped working. For some Rem, whilst the day interval on the flashcard seems to increase and the rem disappears from my queue each day, it will then reappear the next day, even if the schedule was set for it next to appear in a month and it stated as such on the flashcard response buttons

**To Reproduce**
1. Create Rem
2. Utilise document specific queue
3. Test a number of rem over a few days
4. Notice how some rem consistently reappear without being spaced in accordance with the algorithm

**Expected behavior**
For the Rem to be spaced rather than reappearing every day

**Desktop (please complete the following information):**
- Browser: Edge

**Additional context**
It appears to be more prevalent on Rems to which I have answered Hard, than on Rems which have been answered easy. Whilst the Rems which are hard should re-occur daily at first, that spacing should increase but it is not

**Comment by kirill-tkachev** [comment]
The same with me

**Comment by thibacg** [comment]
I've experienced the same issue glad its not just me

**Comment by tfiwm** [comment]
Most probably same as the issue #331

**Comment by mfranzs** [comment]
Thanks for the report. Closing in favor of #331.
