### ISSUE TITLE
References Changes Their Names When Deleting Document

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#345]
![image](https://user-images.githubusercontent.com/20538090/101289175-e607d200-380b-11eb-952e-d4fe2b38b471.png)
When deleting a rem with reference
![image](https://user-images.githubusercontent.com/20538090/101289184-f9b33880-380b-11eb-99e6-a9d27c8fb3db.png)
Its name is changing to "Deleted Rem: Iron", that shouldn't happen. It must stay the same as before. (Iron)

**Comment by mfranzs** [comment]
Thanks for reaching out. To confirm, do you mean that you are deleting the document "Iron"?

**Comment by Eikosa** [comment]
Yes, reference document was Iron

**Comment by mfranzs** [comment]
This is working as intended. We'll over a way to automatically ex. convert these to text or rename, in the future.
