### ISSUE TITLE
Links not working in Markdown Export due to incorrect generated relative URLs

### ISSUE THREAD

**Issue by webbaflux** [remnoteio/remnote-issues#347]
**Describe the bug**
Platform: Windows, Firefox, Web-Interface. 
If you have a build a directory structure with Documents inside and link (via rem reference) from a Document that is not at top-level to another Document deeper in the directory hierarchy, then in the markdown export a link is generated as if you would link from top-level (the relative url from the root), which does not match the target destination, of course.

**To Reproduce**
In the web interface create three folders inside another. From root down: 
projects
| app-dev
| | tech
In app-dev place a document 'app-development'.
In tech place a document 'technology'.
Inside app-development make a rem reference (link) to technology.
When you click then on the rem reference in app-development you will go to technology - the link will work.
Then, when you will export everything in markdown (only create files for Documents and include all descendants) and open app-development.md locally on your machine the link to technology will be 'projects/app-dev/tech/technology.md' what is wrong and not working in this place.

**Expected behavior**
The link should work in markdown export and should be 'tech/technology.md' in my example, since this would be the correct relative url to reach a document from projects/app-dev/app-development.md which is on the same level as tech.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
