### ISSUE TITLE
Adding tags doesn't work in Safari. 

### ISSUE THREAD

**Issue by ppeirce** [remnoteio/remnote-issues#348]
**Describe the bug**
Adding tags doesn't work in Safari. 

**To Reproduce**
Type ## to show the tag search window
No existing tags/rems are shown
Cannot create new tags

**Expected behavior**
The tag window, showing rems and the ability to create a new tag, should appear

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 14.0.1

**Comment by mfranzs** [comment]
We're having some trouble reproducing this. 
1. Can you please try to refresh with Ctrl + Shift + R and send us a screenshot of what happens if you're still having problems? 
2. Can you add references with [[ ?

**Comment by ppeirce** [comment]
Hmm.

Well, the behavior is working today.

I had hopped over to using Chrome for taking notes with remnote the past few days. Switching back to Safari now.

If it reoccurs I’ll take a screenshot and send it along to you.
