### ISSUE TITLE
Documents got divided into multiple Untitled documents

### ISSUE THREAD

**Issue by Mechkalito** [remnoteio/remnote-issues#349]
Three days ago I logged in into my RemNote account and sidebar categories were missing (Draft, Finished, Pinned), so I did a reset and after that got bunch of new documents named "Untitled". Most of them are empty, but some contain rems from other documents I'm currently working on. One thing I noticed, is that some of those new Untitled documents are split off from documents that contained source. For other ones, i.e. rems that got divided from documents without reference, I have no clue why certain rems remained in original place, and why certain ones got moves into new Untitled documents.

**To Reproduce**
I don't know how to reproduce this. One day this just happened after I logged in.

**Screenshots**
![image](https://user-images.githubusercontent.com/75589492/101295300-1ad05500-381d-11eb-8c8e-d9455deeb711.png)
![image](https://user-images.githubusercontent.com/75589492/101295306-1efc7280-381d-11eb-90d5-435cfe020ee8.png)

**Desktop (please complete the following information):**
 - Win 10
 - Opera (72.0.3815.400)

**Additional context**
I might repeat myself that those new Untitled documents are not all empty. Just to emphasize that since deleting them is not a solution.

**Comment by tfiwm** [comment]
Just want to emphasize that this is very severe issue data corruption (sometimes data loss) issue with Remnote. I am pretty sure that almost everyone with enough rems must have experienced this 2/3 days ago, it is just a matter of time they realize that some stuff is missing from their documents. This used to happen in the past as well.

In case you want to recover data from it, here is one way [How to recover data that went to 'Untitled' or 'Unnamed' document?](https://forum.remnote.io/t/how-to-recover-data-that-went-to-untitled-or-unnamed-document/1230)

**Comment by Mechkalito** [comment]
@tfiwm 
Thank you. I didn't touch anything, as I was scared of doing something that might lead to data loss. Basically, I need to do this manually? Was hoping it's possible to revert to a state before this happened (December 3rd).

**Comment by tfiwm** [comment]
Yes, the above one is manual. If you really want to restore the state, then I guess you will have to contact Remnote support.

**Comment by Mechkalito** [comment]
> Yes, the above one is manual. If you really want to restore the state, then I guess you will have to contact Remnote support.
This is an attempt to contact them. Hope someone will respond.

**Comment by Mechkalito** [comment]
Bump
