### ISSUE TITLE
Creating a search portal from filters isn't working for normal text 

### ISSUE THREAD

**Issue by drkvj** [remnoteio/remnote-issues#35]
**Describe the bug**
When you try to type a word be it inside of the quote box or outside of it , it searches in the filter box , but doesn't reproduce the results in the search portal that is created

**To Reproduce**
1. Go to a rem that has some searchable words in similar
2. Click on CTRL + F or CMD + F
3. Type the word in the legacy box or outside of it
4. Click on the + in the search box to turn it into a search portal 
5. The search portal comes empty

**Expected behavior**
The search portal should have the same results shown while typing in the filter box . This used to be working , must have broke recently

**Screenshots**
This shows that there is in fact text under the rem that I am trying to search or filter 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/69129342/89754536-edd39600-daf9-11ea-83c3-8f2fd00e3a6b.png">
This shows that the search portal doesn't return with the same results :
<img width="794" alt="image" src="https://user-images.githubusercontent.com/69129342/89754553-ff1ca280-daf9-11ea-8917-febe69a4999a.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser : Chrome
 - Version : 84.0.4147.105

**Comment by mfranzs** [comment]
Thanks for the clear report! We've reproduced this along with #28 and will deploy a fix in the next update.
