### ISSUE TITLE
hope to optimize export to anki

### ISSUE THREAD

**Issue by phoenixchl** [remnoteio/remnote-issues#351]
hope to optimize export to anki：
there is a puzzle,   although now can export to anki，After apkg  be exporting the text, the questions and answers are linked together, （There should be a “tab ”between the question and the answer）
for help！

**Comment by phoenixchl** [comment]
many of the cards are use“cloze tpye”，and then export  to anki ,  and export to txt.
if There is not a “tab ”between the question and the answer, i can not import to supermemo .thanks.

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you please post a screenshot of a Card in RemNote and the corresponding card in Anki that is malformed?

**Comment by drkvj** [comment]
Closing as can't reproduce and no response from poster
