### ISSUE TITLE
Using the keyboard to rate types the letter into the box

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#352]
**Describe the bug**
When I rate a card with 2/4, which in my case would be c, then the keyboard also inputs c

**To Reproduce**
1. Not sure if necessary but change your command of the 2/4 rating to c and enable type answer 
2. Go to the queue and click on reveal answer of a card
3. rate it with 2/4

**Expected behavior**
No c in the textbox

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/101343138-d0ce8a00-3883-11eb-9ea0-38c13cb3b175.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 2020 edition
 - OS: iPadOS 14.2
 - Browser safari
 - Version 14

**Comment by 8888Daniel8888** [comment]
also happens to 3/4

**Comment by edhowe721** [comment]
Also happens in fix later comment
