### ISSUE TITLE
Creating Multi-line Rem Cards

### ISSUE THREAD

**Issue by SertralineSH** [remnoteio/remnote-issues#353]
![93695e5418c94850cf6921c994a4c1cf90533558](https://user-images.githubusercontent.com/59762920/101392960-580e1300-3901-11eb-953a-ccb880934782.png)
Figure 1, unclean three colons left undeleted after a multi-line card is generated.
![00ba4f306bfc4a6a1f72f9f7307cdf76d444809d](https://user-images.githubusercontent.com/59762920/101393007-64926b80-3901-11eb-9fe9-3f5bb326a1a6.png)
Figure 2, after manually deleting the unclean colons the Rem Type of the multi-line card automatically turns unset, unbolding the text.
![5a83c39bce56f8b2428661a5b68c5a2db4ecc9b2](https://user-images.githubusercontent.com/59762920/101393012-66f4c580-3901-11eb-8744-810e539b6274.png)
Figure 3, Rem Type mysteriously unset.

Error 1: redundant colons left after creating a multi-line card with three colons added to the end of a line.
Error 2: Rem Type Unset after deleting the redundant colons.

1. add three colons to the end of a line to create a multi-line card, seeing error 1
2. deleting the redundant colons, seeing error 2
3. look at the Rem Type status of the multi-line card to confirm error 2

Usually there shall be no redundant colons, and the default Rem Type is "Concept."

 - phone: OnePlus
 - OS: Android, Win10
 - Browser: Via for Android, Microsoft Edge for Win10

Thank you for your time.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
