### ISSUE TITLE
Missing documents

### ISSUE THREAD

**Issue by richblack** [remnoteio/remnote-issues#354]
**Describe the bug**
I am using RemNote about 1 month, many Rem built and I tag many of them a Document, so that I can reach them with just a cick on the "Documents" button at the side bar to open Documents Folder.
But since last friday,  many of my document are disappeared in Documents Folder, to my panic.
After check, those documents are still there, but just not be collected in Documents Folder.
I switched my cell phone from iPhone 6s Plus to RedMi Note 7 (Android) last friday, and I tried to install RemNote Android version but fail to log in since can't access to Google auth from App, and then I am using Chrome.
Is it possible the change of cell phone caused the problem?

**To Reproduce**
1. Go to 'Side bar'
2. Click on 'Documents'
3. See error

**Expected behavior**
Can someone give an advice how to make it right? Or that is a bug?

**Screenshots**
---
![Only 10 items in Documents Folder](https://user-images.githubusercontent.com/16075080/101429387-cb357a80-393d-11eb-8f71-d290ab45e98b.jpg)
▶ There are only 5 items from Cards Folder, and 5 from Daily Documents Folder in Documents Folder.
---
![screencapture-remnote-io-document-GoJh8pMWvQ3cQdS6o-2020-12-08-09_53_15-redacted_dot_app](https://user-images.githubusercontent.com/16075080/101429404-d38db580-393d-11eb-8ff9-d7f3b8fcdc7c.png)
▶ But there are more than 30 docs in Cards Folder.
---
![screencapture-remnote-io-document-3Hj2PFcHN43FxoC2Q-2020-12-08-09_49_54](https://user-images.githubusercontent.com/16075080/101429411-dc7e8700-393d-11eb-94e1-f554bd562813.png)
▶ And 34 Daily Documents.
---

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 86.0.4240.198

**Smartphone (please complete the following information):**
 - Device: RedMi Note 7
 - OS: Android 10, MIUI Global 12.0.1
 - Browser Chrome
 - Version 86.0.4240.198

**Additional context**
No

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you follow these steps, please?

1) Press "Ctrl + O".
2) Search for "Document Sidebar".
3) Press the "Restore default sections" button at the top of the page that opens.

**Comment by richblack** [comment]
Thanks, it helps.
