### ISSUE TITLE
The sidebar won't hide unless I reload

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#355]
**Describe the bug**
When I click on the arrow that's for hiding the sidebar, it pops up again and covers my document

**To Reproduce**
1. Go to the sidebar
2. Click on arrow that's next to the user name
3. See error

**Expected behavior**
I expected the sidebar to be gone

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/101509025-9db9f280-3978-11eb-9851-c1c53a0dee1e.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 2020 edition
 - OS: iPadOS 14.2
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
