### ISSUE TITLE
"/" activates in the queue

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#356]
**Describe the bug**
Actually happened to me on accident but when you type /, you get the popup window and it looks really out of place

**To Reproduce**
1. Go to Queue
2. Click on /
3. See error

**Expected behavior**
The popup window not to appear in the queue

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/101554359-c3fe8300-39b6-11eb-9210-3d1342e6e96a.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 2020 edition
 - OS: iPadOS 14.2
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by 8888Daniel8888** [comment]
![image](https://user-images.githubusercontent.com/69430941/101994281-9c166480-3cc1-11eb-9f01-b6a8d1ecc6d7.gif)
Now it displays the metadata instead. I don't know if that's working as intended, I at least can't find the shortcut in the settings
