### ISSUE TITLE
blank space in note

### ISSUE THREAD

**Issue by leminhhien0301** [remnoteio/remnote-issues#357]
![msedge_IwgSJW6fr0](https://user-images.githubusercontent.com/38253149/101635932-3629a300-3a5d-11eb-8f41-c2aef32cac3c.png)
**Describe the bug**
when I choose to open the document, I can't see where to take note. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for reaching out. Is the problem that the clipper is not loading? Can you please try to update it?

**Comment by leminhhien0301** [comment]
I did try update it, reload it and reinstall it. None of the way have
worked.

2020年12月9日(水) 23:56 Martin Schneider <notifications@github.com>:

**Comment by drkvj** [comment]
This should have been fixed, have you been noticing such behaviour still? Kindly follow this discussion on the forum, where we will be actively handling such matters from now on.
