### ISSUE TITLE
Command + Left Right Arrow Keys not working as expected on Mac

### ISSUE THREAD

**Issue by halhenke** [remnoteio/remnote-issues#358]
**Describe the bug**
Command + Left does not move to the beginning of the line but instead Navigates backward in History
Command + Right does not move to the beginning of the line but instead Navigates Forward in History

**To Reproduce**
1. Use `Command + Left` Shortcut in a Rem

**Expected behavior**
Cursor should move to the beginning or end of the line.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.01
 - Browser: Chrome Canary
 - Version 89.0.4

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
