### ISSUE TITLE
Can't Cancel out Reference

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#359]
![image](https://user-images.githubusercontent.com/20538090/101686825-a266cf80-3a7a-11eb-9976-b08295bdda56.png)
After trying to create a reference, if I give up on it, there is no way to cancel it without deleting it
**none of them work ->** ESC, [

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
