### ISSUE TITLE
Creating a is descendant search query from the filters option isn't working

### ISSUE THREAD

**Issue by drkvj** [remnoteio/remnote-issues#36]
**Describe the bug**
When a search portal is created using the commands from a filter box, it needs to include only the rems that belong to it underneath that specific rem. But in the example I have shown , it pulls in the references from the entire knowledge base

**To Reproduce**
1. Go to any rem
2. Click on 'CTRL + F / CMD + F
3. Enter any reference that is seen in the rem
4. Turn it into a search portal
5. You will see that the portal doesn't limit the search to the specific rem but pulls info from the entire database

**Expected behavior**
It should clearly restrict to the descendants when making search portals from within filter box

**Screenshots**
<img width="794" alt="Screenshot 2020-08-10 at 11 04 46 AM" src="https://user-images.githubusercontent.com/69129342/89754777-c0d3b300-dafa-11ea-8a79-f45924832f35.png">

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser Chrome
 - Version 84.0.4147.105

**Comment by mfranzs** [comment]
Thanks for the clear report! We've reproduced this along with #28 and will deploy a fix in the next update.
