### ISSUE TITLE
Clicking Top Level Rem with Portal on Searchbar

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#360]
it was supposed to open his own top level page directly, but it's opening the portal in the another document.
![image](https://user-images.githubusercontent.com/20538090/101715539-af9cb200-3aac-11eb-96bb-c65cd1936263.png)
---------------
![image](https://user-images.githubusercontent.com/20538090/101715549-b5929300-3aac-11eb-85b1-8d3f941da3e8.png)

**Comment by drkvj** [comment]
This is working as intended, feel free to provide ideas of how this could be better implemented on the forum under feedback. Thank you!
