### ISSUE TITLE
Pasting of markdown todos

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#361]
I want to be able to paste checked Todo rems.
The commonly used markdown syntax is
```md
- [ ] this is a unchecked todo
- [x] this is a checked todo
```
Unchecked todos can be somehow done using the powerup as a tag (`#Todo`) but it is unreliable in case the user has renamed it and it does not allow pasting checked todos.

**Comment by hannesfrank** [comment]
Hope this was an easy extension :D I just discovered that codeblocks without a todo tag are enabled as well.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
