### ISSUE TITLE
Unnamed Rem in Portal

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#362]
![image](https://user-images.githubusercontent.com/20538090/101817341-4ad86a80-3b33-11eb-90d7-b2676288332f.png)

**Comment by mfranzs** [comment]
Thanks for the report. This is working as intended - these are unnamed children of "Hemoglobin".

**Comment by Eikosa** [comment]
I thought it should look like this
![image](https://user-images.githubusercontent.com/20538090/101858680-26a07c00-3b7b-11eb-950e-4701927db4c1.png)
