### ISSUE TITLE
Latex Rendering Bug

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#364]
![IbDWFZ34HB 623](https://user-images.githubusercontent.com/20538090/101821869-a0177a80-3b39-11eb-904b-bf0f9715b28e.gif)

**Comment by mfranzs** [comment]
Thanks for the report. Can you please copy that full text into here so that we can debug this?

**Comment by Eikosa** [comment]
Interestingly, this problem resolved by itself but another problem arose
![BSjGxSR0M6 632](https://user-images.githubusercontent.com/20538090/101856541-93654780-3b76-11eb-8413-427e297ceccc.gif)
(I just click on them)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
