### ISSUE TITLE
Ctrl+Z Deletes Too Much Thing

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#367]
![vyWERM9OEz 630](https://user-images.githubusercontent.com/20538090/101853005-f0a9ca80-3b6f-11eb-9ae4-a8e226a7c851.gif)
(also, why is it bring the cursor before the letter r in the first rem?)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
