### ISSUE TITLE
Ctrl+B also backspaces

### ISSUE THREAD

**Issue by hbbssub** [remnoteio/remnote-issues#368]
**Describe the bug**
When Ctrl+B is used to bold text, it also backspaces one space.

**To Reproduce**
1. Type a space after any un-bolded text.
2. Type Ctrl+B to bold text.
3. See error: results in backspace and bold.

**Expected behavior**
Bold only, no backspace.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (Version 1909)
 - Browser: Chrome 
 - Version: Chrome 87.0.4280.88

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for reaching out. I'm having trouble reproducing this - are you still encountering this issue?
