### ISSUE TITLE
Lag when hitting Return key to move part of text to the next line (rem)

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#37]
**Describe the bug**
Discord message links with full description of bug:
1. https://discordapp.com/channels/689979930804617224/722840095001935902/729630310018449428
2. https://discordapp.com/channels/689979930804617224/722840095001935902/729634066898616390

**To Reproduce
Steps to reproduce the behavior:**
Type a long sentence, for e.g.: abc. def. ghi. jkl. lmn. op.
Place the cursor after say 'def.'
Hit the Return/Enter key.
It should do either of two things:
1. Lag a bit during which you should see everything after 'def.' still on the same line as well as on the next line as a new rem (so the text still appearing in the original line has to deleted manually), or
2. Same as 1. except the text disappears on its own after the lag.

**Screenshots**
Screen recordings are in the discord message links.

**Desktop (please complete the following information):**
OS: Windows 10 / Mac OS Catalina
Browser : Edge / Chrome
Version : Edge - Version 84.0.522.58 (Official build) (64-bit) / Chrome - Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by mfranzs** [comment]
Thank you for the clear report! We've reproduced this and will deploy a fix in the next update.
