### ISSUE TITLE
Can not move out of code blocks with arrow keys

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#370]
When inside a code block there is no way (?) to move out of it using the keyboard.
The arrow keys (which should work I think) don't do it.

And "Navigate to Sibling Above/Below" does not work if there is no sibling.

Chrome 87, Windows 10.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
