### ISSUE TITLE
the delete button is too long

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#371]
[![](https://pic.downk.cc/item/5fd4d2cc3ffa7d37b359f254.jpg)](https://pic.downk.cc/item/5fd4d2cc3ffa7d37b359f254.jpg)
[![](https://pic.downk.cc/item/5fd4d2cc3ffa7d37b359f256.jpg)](https://pic.downk.cc/item/5fd4d2cc3ffa7d37b359f256.jpg)

Mobile version in every mobile device

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
