### ISSUE TITLE
LaTeX problems: paste/typing $$ in code blocks, selecting issues

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#373]
The following things are wrong:

- You can paste latex into code blocks (and quotes?).
- Selecting latex and copying _a part_ of a rem containing latex (not a whole rem with shift + up/down) copies it like 4 times with strange formatting.
- You can't type double $ in code blocks or quotes.
- You can not select the word before latex with double click.
- Deleting an empty latex environment by pressing backspace while inside still shows it. It is not there anymore, e.g. typing something removes it.
- ctrl + shift selecting the word left of the latex environment in the direction of the environment also selects the environment. There should be a stop point on the boundary.

See also #218 

Windows 10, Chrome 87.

**Comment by eohomegrownapps** [comment]
c.f. https://forum.remnote.io/t/improve-latex-support/1363/2 and https://forum.remnote.io/t/markdown-edit-mode/1368

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
