### ISSUE TITLE
In backwards-enabled cards generated by child rems, :: after the parent rem persists

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#374]
**Describe the bug**
1. In backward-enabled rems, when clicking 'Show answer', the concept/parent appears with a :: at the end despite the original concept/parent rem not having any "back side content".
1a. If this concept does have some "back side content" itself, it also appears in the backwards-enabled card generated by the child rem.

(Sorry if this isn't explained clearly, screenshots would help clarify.)

**To Reproduce**
1. Enable the Backwards form of a child descriptor rem
2. See it in the queue, note that the concept (which is the answer since it is a backward-enabled rem) appears with a :: next to it, which is followed by itss content if it is a rem itself 

**Expected behavior**
The back side of the concept card should not appear in the backwards-enabled child rem's card.

**Screenshots**

A backward-enabled child rem wherein the concept, **B cells** (parent rem), has no content itself on the back side

![image](https://user-images.githubusercontent.com/68901589/101992582-ec93bf00-3ccd-11eb-95b8-7d16647a45b4.png)

A backward-enabled child rem wherein the concept, **Posture of fetus** (parent rem), has its own content on its back side (which should not appear in this backwards card)

![Screen Shot 2020-12-12 at 10 59 17 PM](https://user-images.githubusercontent.com/68901589/101992603-0cc37e00-3cce-11eb-804f-811234768d16.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Safari (... also in the desktop app beta which is what I mostly use 👀)
 - Version: 14.0.1

**Comment by drkvj** [comment]
This isn't per se a bug, would be better if you could port this into a feature request or make a new topic on the feedback section of the forum, where it might get better reception from other users. This will help us better understand the needs of the users as a whole, thank you!

**Comment by anishaaa1** [comment]
I'm not sure I understand. How is this not a bug (and a feature request instead)? I'm not asking for anything, I just do not think it is the intended behaviour and know for a fact it for sure didn't use to happen before. This may have changed - is this now the default?

By this, I mean, if the parent rem is a concept that generates its own card and has a descriptor that also generates its own card, is it intended for the "back side" of the parent rem to also be visible when answering the backwards form of the descriptor card?

Expected/old behaviour (?): It used to only show the parent rem as the answer (to the backwards card generated by the descriptor rem) without the "back side" of the parent rem.
