### ISSUE TITLE
Wrong count of cloze cards

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#375]
![XFFSWbPGrR 647](https://user-images.githubusercontent.com/20538090/101993038-51e4b180-3cc8-11eb-962a-b84bfff9dfee.gif)
I created 2 clozes, but it acts like there is only one cloze

**Comment by mfranzs** [comment]
Thanks for the report. This is working as intended. You can split the clozes into separate cards by clicking on their dropdown arrow.
