### ISSUE TITLE
Resizing a Image is little bit hard

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#376]
![CDndyrI5FW 653](https://user-images.githubusercontent.com/20538090/101995874-5c11aa80-3cde-11eb-9ab8-2f242e9b59ff.gif)
the smaller the picture, the harder it is to resize and one more thing i want to say is images get smaller as soon as you touch the resize button because pictures are larger than their maximum size

**Comment by drkvj** [comment]
This should be fixed now, thank you for the report!
