### ISSUE TITLE
Global Shortcuts (Operating System/Desktop) have localization issues which cannot be solved by remapping

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#377]
Ctrl + Alt + Shift + ` is not possible on German QWERTZ.
This is an issue because they cannot be remapped.

**Comment by drkvj** [comment]
I am referencing this report to the forum discussion [here](https://forum.remnote.io/t/documenting-any-keyboard-shortcut-related-bugs/2770/12), let's figure this out on a macro level, this might help the team to understand how big a problem this is and to come up with a solution for all related issues. Thanks!

**Comment by hannesfrank** [comment]
Basic i18n is not the main concern here and there is not much left to figure out on the technical side.

I logged this issue/FR this short because I'm pretty sure the devs are already aware of the limitation because they introduced it themselves: Remapping global shortcuts is just not implemented already because the mechanism for global shortcut is different from normal application shortcuts (i.e. you need to define them on startup and prompt the user to restart the app when the shortcut is changed, or reload the window programmatically). So it is only implemented in this simple, non-configurable form yet where the value/time invested ratio was high enough. See e.g. here: https://stackoverflow.com/questions/61057124/make-global-shortcut-configurable-in-electron-app/61242479

The reason I logged this issue was because RemNote v1.0 was happening and global shortcuts are not accessible for non QWERTY pro users even which would contribute to the "buggy" image of RemNote.

IMHO this is a nice and resonably well formulated package for a dev to work on already, so you may leave this open?
