### ISSUE TITLE
Pressing Ctrl + Shift + B to toggle backwards practice also toggles bold

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#378]
I think this is because Ctrl + B for bold is a subset.

![remnote-bug-bold](https://user-images.githubusercontent.com/4137110/101995940-590ebe00-3cce-11eb-942b-d3bdf0db20ea.gif)

Windows 10, Desktop app.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
