### ISSUE TITLE
Universal Descriptors function doesn't support non-latin characters

### ISSUE THREAD

**Issue by e0ns** [remnoteio/remnote-issues#38]
When I define a universal descriptor which contains non-latin characters, it cannot be recognized as descriptor  in document (i.e. italic).

**Comment by mfranzs** [comment]
Thanks for the report. Is the problem that it's not recognized as a descriptor because it doesn't start with a lowercase letter? You can manually set a Rem to a descriptor using the dropdown in the bottom toolbar or the `Ctrl + Alt + D` shortcut.

**Comment by e0ns** [comment]
No, if you define a universal descriptor which is capitalized (in official tutorial),  it should automatically be recognized as descriptor. So, it's not about lowercase letter.

**Comment by e0ns** [comment]
And the shortcut is conflict with show/hide dock on Mac.

**Comment by drkvj** [comment]
This is not a bug, closing the report for now. Thanks!
