### ISSUE TITLE
Image Occlusion Cards Function Improperly

### ISSUE THREAD

**Issue by soulertsai** [remnoteio/remnote-issues#381]
**Describe the bug**
After clicking the images with occlusion mask, the mask didn't show up.

**To Reproduce**
1. Go to images with mask and click on it.

**Expected behavior**
Show occlusion masks on the images

**Screenshots**
![image](https://user-images.githubusercontent.com/7892194/102001755-7eccaf00-3d30-11eb-8aae-11f64893ce71.png)
![image](https://user-images.githubusercontent.com/7892194/102001760-960b9c80-3d30-11eb-8395-0761daa18d02.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chromium
 - Version 87.0.4280.66

**Additional context**
This phenomenon exists on Android app as well.
What's worse is that if I want to click on images when reviewing the queue to see the content more clearly, the answer will show up directly.

Btw, Thanks for the effort by the team. Remnote does help me a lot ❤️️

**Comment by Eikosa** [comment]
I think it's not a bug, it's a feature added to be able to look at the picture without cloze. If you click the "Generate image occlusion cards" button, you can see masks

**Comment by soulertsai** [comment]
@Eikosa 
![image](https://user-images.githubusercontent.com/7892194/102037986-21546300-3e01-11eb-8fc1-4e2cf02eb439.png)
![image](https://user-images.githubusercontent.com/7892194/102038004-2addcb00-3e01-11eb-998e-0e96c20af5aa.png)

This should not show when clicking on images when reviewing cards in queue.
At least it didn't show before this update and I think not showing is the right behavior when reviewing cards.

**Comment by soulertsai** [comment]
In the first section, I posted the wrong images in the document instead of the described usage in the queue.
So I decided to close this and reopen in the https://github.com/remnoteio/remnote-issues/issues/417
