### ISSUE TITLE
Navigation buttons and shortcuts not working

### ISSUE THREAD

**Issue by Robertgreene123** [remnoteio/remnote-issues#383]
Using the windows desktop app and a local knowledge base, the back and forward buttons do not work; instead, a "404- page not found" message is seen.

**Comment by drkvj** [comment]
Related posts from the forum : https://forum.remnote.io/t/forward-and-back-navigation-buttons-dont-work/1673?u=karthikk 

@Robertgreene123 can you confirm if you are still facing this issue in the current version?

**Comment by Robertgreene123** [comment]
I still have this issue

**Comment by drkvj** [comment]
merging with #477
