### ISSUE TITLE
Desktop app image loading problem

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#384]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/20538090/102012204-11ce0f00-3d5a-11eb-9397-c5f9b3d2504d.gif)
I have windows 10

**Comment by claforte** [comment]
I have the same issue. To me, this seems to happen when I paste an image, add occlusions, then I realize I need a different image (e.g. with more notes on it), I delete the original image, paste the new one, and then add the same occlusions again. I get quizzed on the old image/occlusions even though the image was deleted. It's very annoying.

**Comment by SMerlock7** [comment]
I have the same issue. I'm unable to create image occlusion cards.

**Comment by ZekeRexington** [comment]
Same. I can create occlusion cards on the RemNote website, but not on the RemNote Windows 10 app.

**Comment by mfranzs** [comment]
Merging with #447
