### ISSUE TITLE
asks the same rem's cloze questions in a row

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#386]
![qH1OBIoHID 663](https://user-images.githubusercontent.com/20538090/102012475-b56bef00-3d5b-11eb-856e-e24f44654f8e.gif)
it's pointless to ask this in a row because I've already seen its answers

that's also happens in image occlusion questions

**Comment by drkvj** [comment]
This is not a bug, but intended behaviour for now. Kindly submit this as a feature request on the forum, so that other users can also share their views and upvote for higher priority
