### ISSUE TITLE
Cloze space at the end

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#388]
![image](https://user-images.githubusercontent.com/20538090/102013682-c4a26b00-3d62-11eb-9dbf-8b451c96d80b.png)
I think it should automatically remove the space at the end

**Comment by hannesfrank** [comment]
I noticed that too, I made an issue here: #218.

I suppose automatically trimming would be nice as well.

**Comment by Eikosa** [comment]
Duplicate of #218
