### ISSUE TITLE
When typing ::1. in the middle of text, the text to the right of the ::1. does not get put into 1. of the list

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#389]
**Describe the bug**
Typing ::1. in the middle of a sentence does not push the text to the right of the ::1. into the next line as point 1.

**To Reproduce**
1. Type a sentence, e.g. Abc xyz
2. Type ::1. after 'c' in Abc
3. Observe that nothing happens
3a. What should happen → 'Abc' should turn into the concept and xyz should be pushed into the next line as point 1.

**Expected behavior**
See 3a (this used to work before).

**Screenshots**

![ezgif-3-1f04e6a2f8db](https://user-images.githubusercontent.com/68901589/102013699-3ed6ed80-3d6b-11eb-8bc0-5637ce4cb3a6.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Desktop App
 - Version 1.0.36

**Additional context**
1. When you simply type xyz::1., it does create a numbered list. The issue only arises when typing ::1. in the middle of a sentence.
2. Typing ::: in the middle of a sentence works for multilines, i.e. it pushes the text to the right of ::: into the first rem in the multiline.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
