### ISSUE TITLE
Turn `plain` into `multiple lines/list/set`, there are two redundant colons

### ISSUE THREAD

**Issue by e0ns** [remnoteio/remnote-issues#39]
When you change the content from `plain` to `multiple lines/list/set`, the two colons which belongs to `plain` still there.

![image](https://user-images.githubusercontent.com/38707987/89978609-79872700-dca0-11ea-9413-82459a807480.png)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
