### ISSUE TITLE
cannot delete at once

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#392]
![mEAPe0AApr 673](https://user-images.githubusercontent.com/20538090/102020363-dd724700-3d89-11eb-8b2c-e711a1100d0a.gif)
(btw I accidentally pasted it on the custom css page)

**Comment by hannesfrank** [comment]
It sounded like there is a problem when trying to delete too many rems at once.

**Comment by drkvj** [comment]
Can you please elaborate on the issue? The information provided is very vague and I am unable to understand the report. IF you are still facing similar issues, start a new discussion on the forum.

**Comment by hannesfrank** [comment]
I just benchmarked this with 1000 plain rem generated by loremipsum.de: Pasting and mass deleting works fine. Both operations take a few seconds on my laptop, but complete without problem.
It could be that processing heavily referenced/tagged content causes problems, but this can not be tested as easily.

In any case I suggest adding a few of those bulk operations to RemNote's automated test suite to catch performance regressions.

One problem remaining here is that RemNote freezes temporarily when doing those bulk operations. The program should be reactive at all times and show visual feedback for those operations, e.g. a spinner or small progress bar. #UX-rework :)
