### ISSUE TITLE
(Option to) warn when pasting many rems/lines at once

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#393]
RemNote is considerably slowed down when pasting too many lines at once.
In case a user (on a slow device) does not know this yet or is unaware that there are this many lines in the clipboard, RemNote whould display a warning dialog the user has to confirm first.

The message could be like "You are about to create 2000 new rem. This may take a while. Do you want to continue?"

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
