### ISSUE TITLE
You can’t type your answer on mobile

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#396]
**Describe the bug**
When I try to type something into the textbox, it reveals the answer
**To Reproduce**
1. Go to Queue
2. Click on "type your answer" box
3. Try to type

**Expected behavior**
The keyboard not to reveal the answer 

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.2 
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
