### ISSUE TITLE
Table and Tex

### ISSUE THREAD

**Issue by kamranmuazzam** [remnoteio/remnote-issues#40]
First of all, love RemNote. Just love it.

I understand that RemNote is still under development and I believe that the features I am suggesting has already been considered or even being worked on.

It would be very important for RemNote to allow for tables. I make notes using RemNote and whenever there is something I need to represent in the tabular form I have to go back to Google Docs or some other program.

Also the Tex. I switched to RemNote from Notion. Notion allows Tex, which allows the user to type chemical equations. It would be extremely important for learners who study Chemistry.

Thanks Again. Could you inform on the roadmap of these if any. 

Love from a learner.

**Comment by mfranzs** [comment]
Thanks for reaching out!

1. Tables are on our roadmap, but they're further down the line. 
2. We support Tex (specifically LaTeX), which you can enter by typing $ twice!
