### ISSUE TITLE
Sign in with Google fails when local port 8000 is already in use

### ISSUE THREAD

**Issue by zabbarob** [remnoteio/remnote-issues#400]
**Describe the bug**
Desktop app can't sign in with Google when a local web server is already running on port 8000.

**To Reproduce**
1. First time install of desktop app
2. Start the app
3. Click on "Sign in with Google"
4. The app opens Google's account selection page in the default browser (Chrome in my case)
5. After selecting the account I want to log in with I'm redirected to http://127.0.0.1:8000/ where my local web server for development is running
6. Nothing happens in the app (still showing login screen)
7. Clicking on "Sign in with Google" again pops up an error message: "A JavaScript error occurred in the main process ... Uncaught Exception: Error: listen EADDRINUSE: address already in use :::8000"

**Expected behavior**
After selecting the Google account I'm logged in.

**Screenshots**

![image](https://user-images.githubusercontent.com/419922/102096359-e49a6300-3e24-11eb-94db-6e13a9060f51.png)

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (x86_64)

**Additional context**
I'm running a local server for web development at port 8000. Once I stop the server, RemNote's login procedure successfully completes.

**Comment by drkvj** [comment]
merging #446  here

**Comment by dewil-official** [comment]
Can be reproduced easily and should be an easy fix. Will do that now.
