### ISSUE TITLE
Cloze mask boxes

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#403]
I think boxes need to be more transparent in terms of increased legibility
![image](https://user-images.githubusercontent.com/20538090/102106276-6b5d3900-3e41-11eb-9500-2505a3f8d445.png)
(printing page)
![image](https://user-images.githubusercontent.com/20538090/102106342-80d26300-3e41-11eb-8b76-4a68133dd6df.png)
(website rem page)

**Comment by mfranzs** [comment]
Thanks - we'll take a look at this and incorporate it into our design.
