### ISSUE TITLE
Adds to queue everything inside Portal

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#404]
it just has to show what I've added
![image](https://user-images.githubusercontent.com/20538090/102108439-fccdaa80-3e43-11eb-8525-5f06c00f9e40.png)

![image](https://user-images.githubusercontent.com/20538090/102108496-11aa3e00-3e44-11eb-9339-a995f10f407c.png)
(I didn't add this card to the portal, but it still asks)

**Comment by mfranzs** [comment]
Sorry, I don't quite understand. Are you saying that a card is appearing in a document-level queue even though it wasn't included in the portal?

**Comment by Eikosa** [comment]
yes I meant that

**Comment by drkvj** [comment]
Can you please update on the status of this bug? Are you still facing similar issues?

**Comment by Eikosa** [comment]
my problem seems to have been solved
