### ISSUE TITLE
cmd+opt+g doesn't do anything

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#408]
**Describe the bug**
The card type toggle doesn't work

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4. Gen
 - OS: 14.2
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you please double check what this keyboard shortcut is in your settings? If you have a newer account, this shortcut now defaults to Ctrl+**Shift**+G.

**Comment by 8888Daniel8888** [comment]
![image](https://user-images.githubusercontent.com/69430941/102324479-34427100-3f82-11eb-8504-4a42c9b3f2f9.png)

**Comment by 8888Daniel8888** [comment]
I think I found the issue. On my CH layout keyboard, option + g results in @. Cmd+opt+a also doesn't work but when I go to settings and "change" the command by typing cmd+opt+a (which actually results in cmd+opt+å because opt+a is å) it works again
