### ISSUE TITLE
Email verification not working

### ISSUE THREAD

**Issue by webbaflux** [remnoteio/remnote-issues#409]
**Describe the bug**
Email verification without effect. After verifying with the link I got from you via email, there is no change at all.

**To Reproduce**
I got a email verification link like: 
Hi [...] - Please verify your email for your RemNote account by following this link: https://www.remnote.io/verify_email?t=V_ZZ5fA3RNgAK3wk7l-qAzStyxANob6A97UvF0b_[...]
I visited the link target.

Then, when I'm logged in and go to https://www.remnote.io/help there is still the message
'Your email is not verified, so please double check your email address! Otherwise, we cannot reply to you.'
'Send Verification email'.
even after several times and days after I got the verification email and used the link inside it.

I can login to RemNote in a normal way, but when I try to login in the forum https://forum.remnote.io/ I get a 'Incorrect username, email or password' message.

**Expected behavior**
After successful verification the messages 
'Your email is not verified, so please double check your email address! Otherwise, we cannot reply to you.'
'Send Verification email'.
should be disappeared after reloading the webpage.
Login into the forum should be possible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 83.0 (64-Bit)

**Additional context**
After verification I get no explicit 'verification successful' message while landing on https://www.remnote.io/sign_in , but I don't know if this should appear or is just not implemented. I also tried with Opera Browser, but with the same not successful outcome.

**Comment by mfranzs** [comment]
Thanks for reaching out. 
1. What is your RemNote username? (Please email us at support@remnote.io if you don't feel comfortable posting here.)
2. The login system for the forum is separate; please create a new account there.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
