### ISSUE TITLE
Lots of CPU and Memory usage

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#410]
for about 5 minutes, when I open the tab or refresh the page, there is a lot of use and fan noise, as in the picture.
also, nothing loads during these 5 minutes
![image](https://user-images.githubusercontent.com/20538090/102297050-a5bcf800-3f5f-11eb-9a21-931fdd18a4e1.png)
![image](https://user-images.githubusercontent.com/20538090/102297056-a9507f00-3f5f-11eb-83f7-fef43aae41ab.png)
![image](https://user-images.githubusercontent.com/20538090/102297060-ace40600-3f5f-11eb-9b28-f2e05351def2.png)
and I encounter these problems when I enter the trash or want to logout

and always out of sync
![image](https://user-images.githubusercontent.com/20538090/102297258-01878100-3f60-11eb-9f17-03395e068f86.png)

cpu usage disappears after a long wait and returning to normal but still not syncing
![image](https://user-images.githubusercontent.com/20538090/102297073-b0778d00-3f5f-11eb-8482-428c6710e75d.png)

and every once in a while the tab started crashing when I was using it normally

![image](https://user-images.githubusercontent.com/20538090/102303035-5b417880-3f6b-11eb-9a5d-e0c866ee6344.png)
![image](https://user-images.githubusercontent.com/20538090/102305644-9f377c00-3f71-11eb-9b02-80362625896d.png)
![chrome_4CSl1qRosz 688](https://user-images.githubusercontent.com/20538090/102303049-61cff000-3f6b-11eb-9282-be87e3d1800c.png)
![image](https://user-images.githubusercontent.com/20538090/102304897-a8274e00-3f6f-11eb-9012-d75eb15de298.png)
![chrome_RVhQnlMHm8 687](https://user-images.githubusercontent.com/20538090/102303053-64324a00-3f6b-11eb-96fe-c6db8afbc8a8.png)

Windows 10
Chrome
Web version of remnote

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you please go to https://www.remnote.io/download_sync_debug_log and email us the output file at support@remnote.io?

**Comment by Eikosa** [comment]
it's not downloading anything.
