### ISSUE TITLE
Back and forward buttons not working

### ISSUE THREAD

**Issue by Robertgreene123** [remnoteio/remnote-issues#412]
Using the windows 10 desktop app, with both the synced and local knowledge bases, navigation buttons don't work; instead a "404 page not found" message is seen. Even shortcuts alt + right/left arrow don't work.

![IMG_20201216_200054](https://user-images.githubusercontent.com/68683404/102381766-acd51c00-3fda-11eb-9bb7-ca19128d9771.jpg)

**Comment by mfranzs** [comment]
Thanks for reaching out. I'm having trouble reproducing this; is this still happening for you?

**Comment by Robertgreene123** [comment]
Yes, i too can't reproduce the issue on other computers around me. I can't
tell why. Every other installer I use doesn't work.

**Comment by kevinsu2** [comment]
I'm having the same problem on both my desktop and laptop, synced and local knowledgebase. I'm using Windows 10, RemNote version 1.3.6, fresh install.

**Comment by drkvj** [comment]
Merging this with #477
