### ISSUE TITLE
RemNote Desktop app doesn't work well on Linux

### ISSUE THREAD

**Issue by imalightbulb** [remnoteio/remnote-issues#413]
**Describe the bug**
The RemNote window becomes like this after I run it for several minutes, it is still usable but every time I open the app for a few minutes and it becomes unresponsive/turn white.  ( using desktop app, appimage because I'm on Linux)

**To Reproduce**
1. I'm using Linux
2. Download AppImage
3. open RemNote app
4. wait several minutes
5. become unresponsive or completely turn white

**Expected behavior**
Run smoothly on Linux

**Screenshots**
![image](https://user-images.githubusercontent.com/66677431/102445926-95904000-4067-11eb-86ac-e4da5d576b06.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser : Desktop
 - Version: v1

**Comment by mfranzs** [comment]
Thanks for reaching out. Are you logged in here? Are you using a synced or local knowledge-base?

**Comment by imalightbulb** [comment]
I'm logged in and using a synced knowledge base

**Comment by imalightbulb** [comment]
I'm logged in and using a synced knowledge base

**Comment by drkvj** [comment]
This should be fixed now, if you are facing similar problems, kindly open a new report on the forum. Thank you.
