### ISSUE TITLE
Bug when pasting plain text starting with numbers followed by "."

### ISSUE THREAD

**Issue by ognsya** [remnoteio/remnote-issues#415]
**Describe the bug**
Pasting **plain text** with lines starting with incrementing numbers followed by “.” automatically changes the parent to a list type, and the first item is omitted.

**To Reproduce**
Copy this, and try pasting in RemNote.

```
1. A
2. B
3. C
```

**Expected behavior**
Normal numbered list, without losing the first item.

Personally I’d rather it just behaved like plain text (or better, to have a proper numbered list type which is not associated with the cards).

(web and desktop, Windows)

Discussed here: https://forum.remnote.io/t/small-bug-when-pasting-plain-text-starting-with-numbers-followed-by/1366/6

**Comment by drkvj** [comment]
N.B. The forum discussion contains a much more documented discussion.

**Comment by drkvj** [comment]
This has been fixed, let us know if you are experiencing anymore difficulties. Thanks for the patience.
