### ISSUE TITLE
loading rems has become slow since several days ago 

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#416]
every device syncs the rems becomes more and more slower

**Comment by plusjhjhjh** [comment]
In the most time, it only load a page's rems and load whole database slowly
![](https://pic.downk.cc/item/5fe0b5263ffa7d37b3b04a11.jpg)

**Comment by drkvj** [comment]
This should have improved by now, thanks to the numerous backend fixes that have been done since the report. If you are facing any more sluggishness, kindly provide feedback on the forum and ping me there.
