### ISSUE TITLE
Image Occlusion Cards Function Improperly

### ISSUE THREAD

**Issue by soulertsai** [remnoteio/remnote-issues#417]
Describe the bug
When reviewing cards in the queue, after clicking the images with occlusion masks, the mask didn't show up.

To Reproduce

Go to images with mask and click on it.
Expected behavior
Show occlusion masks on the images

Screenshots
![image](https://user-images.githubusercontent.com/7892194/102509423-7e7e3c00-40c1-11eb-99df-d2ae4b38006c.png)
![image](https://user-images.githubusercontent.com/7892194/102509435-8211c300-40c1-11eb-931b-19fbf39e4164.png)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by soulertsai** [comment]
Thanks for the effort! <3
