### ISSUE TITLE
Referencing doesn't work

### ISSUE THREAD

**Issue by Mechkalito** [remnoteio/remnote-issues#418]
When I try to reference another Rem (using "[[" syntax), I don't get any suggestion for existing rems. 

**Desktop**
 - Win 10
 - Opera (latest version)

**Additional context**
My suspicion is that this has something to do with [this bug](https://github.com/remnoteio/remnote-issues/issues/349). I didn't touch my RemNote in hopes someone would reach to me, but after this much waiting I started working again in RemNote, and first thing that I noticed is that referencing function does not work.

**Comment by mfranzs** [comment]
Thanks for reaching out. Is this working for you now?

**Comment by drkvj** [comment]
Closing as there is no response from the user and most likely fixed
