### ISSUE TITLE
Sharing problem

### ISSUE THREAD

**Issue by Levap-ami** [remnoteio/remnote-issues#421]
**Describe the bug**
When a file is shared then the information of that file can't be accessed by the other party. The information that can't be accessed is the children of the rem.

**To Reproduce**
1. just share the file.
2. the person who got the shared file can't get the rems.

**Expected behavior**
you can only access the title or the parent rem.

**Screenshots**
![image](https://user-images.githubusercontent.com/51047736/102608426-0ca30280-4154-11eb-9257-9cd13dcdcc60.png)

**Desktop (please complete the following information):**
 - OS: windows 8
 - desktop app

**Additional context**
from what i gathered from the forum, it seems the shared button acts like a screenshot. So, if you hide the children of the rem than, those rem will not be visible and can't be accessed from the shared file. 

example-

LaLaLa
 ∟ blah blah blah
 
[if it is written like the above one, then the information can be accessed from the shared files.]

•LaLaLa

[if you collapse the children, then the rem will only act as a text and once it is shared the other party will not be able to access the children.]

**Comment by Levap-ami** [comment]
>  A clear and concise description of what the bug is.

When a file is shared with others then the information can't be accessed. The information that can't be accessed are the children of the rem.

**Comment by mfranzs** [comment]
Thanks for reaching out. This is working as intended for now; the share feature intentional shares a snapshot of only the visible Rem for privacy reasons. We're working on adding more customization sharing settings in the future.
