### ISSUE TITLE
"Draft" headline is missing

### ISSUE THREAD

**Issue by aktivde** [remnoteio/remnote-issues#422]
**Describe the bug**
In the left sidebar the headline of my drafts disappeared.
Surprisingly, that's only true for my hosted knowledge base. The local one is not affected.

The issue appears in both, Desktop App and Web App. However, it is displayed in the Android App.

UPDATE: It did turn up again after adding a new draft via the Android App. Peculiar, however.

**To Reproduce**
---

**Expected behavior**
Headline to be there

**Screenshots**
![image](https://user-images.githubusercontent.com/65334274/102616463-e1aab580-4137-11eb-82ad-03b09db5f94d.png)
![image](https://user-images.githubusercontent.com/65334274/102616495-eec7a480-4137-11eb-93b7-920223cc1d33.png)

Any ideas?

**Comment by a22a-dev** [comment]
I also have the same Issue but with finished & pinned.

**Comment by mfranzs** [comment]
Can you follow these steps, please?

1) Press "Ctrl + O".
2) Search for "Document Sidebar".
3) Press the "Restore default sections" button at the top of the page that opens.

**Comment by drkvj** [comment]
This should be fixed, please make a new topic on the forum if you are facing any more difficulties.
