### ISSUE TITLE
Issue while collapsing the note.

### ISSUE THREAD

**Issue by a22a-dev** [remnoteio/remnote-issues#423]
**Describe the bug**
When I am collapsing a note, notes on same level is also getting hidden. It is working as intended for note that I am trying to collapse, but it is also collapsing/hiding the other note on same level.

**To Reproduce**
It is happening randomly, I faced it twice in past 3 days. It is happening randomly, but once it occurs, then it happens all the time for that specific set of notes.

**Expected behavior**
It should only collapse the notes that I am trying to collapse by clicking on triangular button next to note/rem.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 20.2
 - Browser : Desktop App
 - Version [e.g. 22] 1.0.36.117

**Comment by drkvj** [comment]
hey @a22a-dev can you confirm if you are still facing with these issues still?

**Comment by a22a-dev** [comment]
I am closing the issue since I haven't faced this issue in last few months.
