### ISSUE TITLE
Imports of Anki cards with images into RemNote shows broken image links in Document once import completes

### ISSUE THREAD

**Issue by JakeVerged** [remnoteio/remnote-issues#424]
**Describe the bug**
RemNote says successfully imported 84 cards from my Anki deck, which had images. But the images come out as broken links in RemNote. Did another import of another anki card deck with 50 cards, and same problem occurs. All cards are 'successfully' imported but the images all have broken links in RemNote.

**To Reproduce**
1. Go to 'Settings>Account>Import' in RemNote
2. Select tab 'Anki'
3. Choose file ...  (your  local .apkg anki file)
4. Click 'Import an Anki Deck Package'

All the desired cards are imported successfully, but all the images just show broken image links.

**Expected behavior**
A new Document with the Anki Card deck name having a full list of RemNote Concept flashcards created along with the images for each flashcard.

**Screenshots**
![image](https://user-images.githubusercontent.com/24814472/102699653-594e1280-4214-11eb-904a-531cbdadeabe.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX Catalina
 - Browser: chrome
 - Version: 10.15.6

**Additional context**
This is a consistent behavior and I was able to reproduce this issue with another set of Anki cards with images, and was in fact also smaller card set.

**Comment by JasonBenn** [comment]
+1 this is still an issue.

**Comment by Rush7474** [comment]
Same issue here too.

**Comment by salmanmkc** [comment]
Any ETA on this?

**Comment by salmanmkc** [comment]
I noticed this is marked as closed, is this in production on the web version, still doesn't work for me

**Comment by mfranzs** [comment]
Currently image import is only supported on local-only knowledge bases in the Desktop App. We'll look into expanding this in the future.

**Comment by salmanmkc** [comment]
What are the exact steps to get image importing to work?
Still doesn't seem to work on 1.2.3 for me
image](https://user-images.githubusercontent.com/32169182/108624555-8948aa80-743d-11eb-8e94-9aa094d394bb.png)

**Comment by salmanmkc** [comment]
ah I see it's working now on local, thanks! :)
