### ISSUE TITLE
Last Line Overlaps with Bottom Toolbar

### ISSUE THREAD

**Issue by a22a-dev** [remnoteio/remnote-issues#425]
**Describe the bug**
Last Line Overlaps with Bottom Toolbar

**To Reproduce**
Just open any document and fill till the last line in view is reached and you will notice that while typing normall and pressing enter the last line should come inside view, but it is not. I am guessing view of notes is not aware of bottom toolbar. Because after clicking enter one more time after reaching end of note, document scrolls automatically upwards, bringing the typed things in view.

**Expected behavior**
Moment we click enter while typing, our last line should be in view & automatically scroll a bit up. Rightnow it only scrolls upward after the second enter key press.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 20.2
 - Browser : Desktop Version
 - Version : 1.0.36.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
