### ISSUE TITLE
Android App typed 2 Capital Letters at the Beginning of a Rem

### ISSUE THREAD

**Issue by mashannon** [remnoteio/remnote-issues#426]
**Describe the bug**
When you type in a new note in the Android App, you get two capital letters.

**To Reproduce**
1. Start a new document
2. Give it a title. It doesn't seem to happen in the title
3. go to the first rem/bullet point
4. Start typing
5. The Auto Cap will capitalize the first letter
6. The cap appears to deactivate, but it activates again
7. Type the next character, and it is a cap

**Expected behavior**
The auto cap is OK, but I am fine if it is not there.

**Screenshots**
![image](https://user-images.githubusercontent.com/2413737/102701413-a0440400-4224-11eb-9d3a-79b3db2dec39.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8 Active
 - Model Number: SM-G892A
 - OS: Android 9 Kernal Version: 4.4.153-16888298
 - RemNote App
 - Version: 11

**Additional context**
The autocorrect seems to think that the second character is the first character of the word.  Note in the attached screenshot, near the end. I was typing the word "Fill."  Auto cap capitalized the 'F' then it seemed to deactivate, then the auto cap activated again, and I typed "ill"  It came out as "Ill" (upper case 'i', lower case 'L' twice).  Autocorrect ignored the 'F' and assumed I had meant to type I'll.

**Comment by drkvj** [comment]
Hey! Could you pls confirm if this still happens to you? Kindly PM me or the moderators on the forum to open the topic again. Thanks for the report!
