### ISSUE TITLE
Synced images in Remnote Desktop App not visible on Windows 7

### ISSUE THREAD

**Issue by dean84matt** [remnoteio/remnote-issues#429]
An issue with remnote desktop app on windows 7. The synced images are not visible..some error showing up. The images are viewable on windows 10 and android app. 

Below is a screenshot of the same
![Image 1](https://user-images.githubusercontent.com/15055102/102719406-dac1a580-42e5-11eb-9419-4a5786f31d6f.jpg)

 - OS: Windows 7 Service Pack 1

**Comment by drkvj** [comment]
This issue was fixed in one of the earlier updates, kindly check and revert back on the forum if still persisting for you. Closing the report here. Thank you!
