### ISSUE TITLE
LIst bug

### ISSUE THREAD

**Issue by drkvj** [remnoteio/remnote-issues#43]
**Describe the bug**
When a parent rem is a set , its children are always stuck as set type . Its not possible to turn them into numbered

**To Reproduce**
1. Go to a rem that has children
2. Click on turn into multi line card
3. Go to any of its children 
4. Click on numbered
5. You will see that it doesn't turn into a numbered list
6. Now turn the parent into a numbered list 
7. It is now possible to turn the children into numbered as well

**Expected behavior**
NO matter the type of the parent content , the children should have no restriction

**Comment by mfranzs** [comment]
Thanks for the report - we've deployed a fix. Please let us know if you're still encountering problems!
