### ISSUE TITLE
RTL the three dot menu and arrow to collapse are on wrong side and they overlap

### ISSUE THREAD

**Issue by binabdilwali** [remnoteio/remnote-issues#430]
**Describe the bug**
The arrow for collapsing a rem and the three dot menu should be on the right when we change to RTL
also the arrow overlaps with the three dot menu it took me a while to find it and figure out what's happening.

This behaviour is currently happening on the desktop and web browser

**To Reproduce**
Make the document RTL
and then make a few child rems and try to collapse it. You will find that the arrow overlaps with the three dots and it should be on the same side as the Dot (node) as it is in LTR

<img width="969" alt="Screen Shot 2020-12-21 at 9 41 15 AM" src="https://user-images.githubusercontent.com/44670449/102747598-9a0f6e00-4371-11eb-9b03-ed67572c6a64.png">

<img width="966" alt="Screen Shot 2020-12-21 at 9 42 52 AM" src="https://user-images.githubusercontent.com/44670449/102747601-9bd93180-4371-11eb-89ef-92fa41bc20f4.png">

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
