### ISSUE TITLE
Sometimes CTRL + Enter is not working on referance selection panel

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#431]
![LxxxSkzUDZ 706](https://user-images.githubusercontent.com/20538090/102814524-d37cc380-43db-11eb-8745-a1ed3345cdfc.gif)

**Comment by drkvj** [comment]
This seems to be a very edge case where one might wanna use the todo function while in the reference selector. Kindly make a feature request on the forum for this. Thank you!
