### ISSUE TITLE
Access Denied for Windows Desktop download?

### ISSUE THREAD

**Issue by jovinelly** [remnoteio/remnote-issues#433]
I'm not able to download the windows desktop version of RemNote

Here are the steps to reproduce the issue:
1. go to https://www.remnote.io/download
2. click on Download for windows
3. See error
![image](https://user-images.githubusercontent.com/7636716/102825979-d8c31980-43ad-11eb-9468-c7d495a7c887.png)

Browser - tried Chrome first, then Edge - both resulted in the same error. Also changed the site's security settings to allow everything (in Chrome). Same error :(

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
