### ISSUE TITLE
Download of AppImageresults in error page: This XML file does not appear to have any style information associated with it. The document tree is shown below. 

### ISSUE THREAD

**Issue by Cmhorn** [remnoteio/remnote-issues#434]
**Describe the bug**
When accessing the link: https://remnote-electron.s3.amazonaws.com/RemNote-1.0.37.AppImage

An error is produced: 
**This XML file does not appear to have any style information associated with it. The document tree is shown below.**
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>44BE89877551B88F</RequestId>
<HostId>
Z3zg26qc0S4rlY9RCpnBxbWxRUOwjRAZll3btAhT3VrXwrwrIsE844/hjnfDeQpRVvobKhrasMc=
</HostId>
</Error>
```

**To Reproduce**
1. Go to ' https://www.remnote.io/download '
2. Click on 'Desktop/ Linux Download'
3. See error

**Expected behavior**
AppImage downloads

**Screenshots**
![error](https://user-images.githubusercontent.com/50580012/102832638-fb106380-43bc-11eb-845a-0077cec9b1cc.png)

**Comment by mfranzs** [comment]
Thanks for the report. Can you please check again now? This should have been temporary while we were pushing a new app version (we've fixed this going forward).

**Comment by Cmhorn** [comment]
It was working again as of this morning.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
