### ISSUE TITLE
Edit later cannot be found

### ISSUE THREAD

**Issue by Svenfr** [remnoteio/remnote-issues#435]
The badge says there are rems to be edited later, but I cannot find them anywhere.
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/47762358/102876154-1e7ef100-4445-11eb-8b2e-01680c10ced6.png">

**Comment by drkvj** [comment]
Hey! Could you pls confirm if this still happens to you? Kindly PM me or the moderators on the forum to open the topic again. Thanks for the report!

**Comment by Svenfr** [comment]
Hello,

Yes, it still happens, but I´ve found a way round by entering something in the search string, and then the Edit laters appear. Recently I had a problem though, because even the search bar was gone. I solved it by hitting the undo button, so I must have deleted it by accident, but it would be great if there was some other way.
