### ISSUE TITLE
Web Clipper issues with backspace

### ISSUE THREAD

**Issue by EngAhmed91za** [remnoteio/remnote-issues#439]
**Describe the bug**
when pressing backspace in webclipper on normal text (not code) it crashes and shows "something went wrong"

**To Reproduce**
1. Go to 'article i want to turn to rem'
2. Click on 'press webclipper then start adding on text and then press backspace to reformate it'
4. See error "something went wrong"

**Expected behavior**
there seams to be an issue with coding the backspace button

**Screenshots**
![image](https://user-images.githubusercontent.com/24923960/102976130-2a84b480-4512-11eb-936e-01f6eac5798a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for reaching out. 

1. Does this happen every time? 
2. Can you confirm that this doesn't happen in the same document in the normal editor?
