### ISSUE TITLE
Cloze and text format dialog lag (desktop Windows app)

### ISSUE THREAD

**Issue by EngAhmed91za** [remnoteio/remnote-issues#440]
**Describe the bug**
whenever i try and make a cloze flashcard on a text the highligh takes a bit long and the text formate window is a bit laggy

**To Reproduce**
1. Go to 'highlight a text'
2. Click on 'cloze icon'
4. See error (no error just laggy)

**Expected behavior**
a laggy work in the format dialog windows

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 (using Desktop App)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by drkvj** [comment]
Are you still experiencing this issue? Kindly report to the forum if you are.
