### ISSUE TITLE
Search works only for recently added / updated rems

### ISSUE THREAD

**Issue by krankur** [remnoteio/remnote-issues#445]
Not able to search rems that have not been added / updated recently.

**To Reproduce**
- Type `[[`.
- Type first few characters of any of the rems which haven't been modified recently.
- Nothing show up in the search result.

**Expected behavior**
Should be able to old and new rems.

**Screenshots**
<img width="473" alt="Screen Shot 2020-12-25 at 2 07 35 AM" src="https://user-images.githubusercontent.com/11840300/103105924-14344100-4657-11eb-83b0-0373432f6174.png">
<img width="495" alt="Screen Shot 2020-12-25 at 2 08 18 AM" src="https://user-images.githubusercontent.com/11840300/103105927-19918b80-4657-11eb-955d-12aab1100b5a.png">

**Desktop:**
 - OS: MacOS
 - Browser: Firefox
 - Version: 83

**Additional context**
I was away and didn't use Remnote for a while (2-3 months). After I came back I was not able to reference any of the old rems that I created. I created some new rems and tried searching them and I was able to reference them. So, I tried updating some of the old rems and I was able to search them after the update. I thought this was a one time thing and that once a rem is updated it will always show in search henceforth. But I noticed that those rems disappeared again from search after few days and I had to again update them to make them searchable.

**Comment by mfranzs** [comment]
Thanks for reaching out. Could you please try logging into an incognito window and letting me know if you see the same behavior?

**Comment by krankur** [comment]
@mfranzs When I try to load Firefox in a Private Window I get the following error (I tried multiple times):
<img width="713" alt="Screen Shot 2020-12-25 at 12 25 36 PM" src="https://user-images.githubusercontent.com/11840300/103124253-1f19c080-46ad-11eb-8555-2be78a60c008.png">

Then I tried in Chrome and things seem to be working fine in Incognito as well as Normal mode. So, seems like the issue is specific to Firefox.

**Comment by krankur** [comment]
@mfranzs facing similar issue on Chome as well, sometimes. Refreshing the page fixes the issue.
