### ISSUE TITLE
Can't Sign in on desktop app

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#446]
![image](https://user-images.githubusercontent.com/20538090/103111442-0a620c00-465e-11eb-9982-800616724214.png)
I encounter this error when I try to log in with google

**Comment by mfranzs** [comment]
Thanks for reaching out.
 1. Do you see any difference if you close and re-open? 
 2. Are there possibly any RemNote instances running in the background?
 3. Is there anything else on your computer that might be using port 8000?

**Comment by Eikosa** [comment]
1. No
2. No, only desktop app
3. I don't know

**Comment by immadolf** [comment]
And i can't sign in with google on desktop app on macos.
Click the button and nothing happened.

**Comment by SpondonShabab** [comment]
Here's what happened, @mfranzs :
1. The sign in With Google button is pressed once
2. Nothing happens
3. When you press the Google button after the first try, it shows that the 8000 port is occupied:
> ![image](https://user-images.githubusercontent.com/64481777/103333374-f53f1000-4a97-11eb-9553-72dbdc296606.png)
This happens everytime after the first click. Closing the app and reopening it restarts the process from 1.
It seems like RemNote is using the port, but fails to send the command to Chrome (or the other default browser). And when it retries, it finds the port occupied (by itself).

**Comment by drkvj** [comment]
Merged with the above report

**Comment by peter1786** [comment]
> And i can't sign in with google on desktop app on macos.
> Click the button and nothing happened.

Me.too
