### ISSUE TITLE
Image Occlusion Cards Don't Load on Windows

### ISSUE THREAD

**Issue by mfranzs** [remnoteio/remnote-issues#447]
"On the desktop version, it won't allow you to do "image occlusions". When you click on the image, a blank canvas shows. The online website does not have this bug. I'm able to do image occlusion cards there."

Electron 11.0.3 / Windows 10.0.0 / Desktop App Version 1.0.37

**Comment by jpresco** [comment]
https://forum.remnote.io/t/image-occlusion-isnt-working/2129/5
