### ISSUE TITLE
Large rem cursor snap

### ISSUE THREAD

**Issue by BlindOpimism** [remnoteio/remnote-issues#45]
Cursor snaps screen to center in large rems and doesn't drop the cursor in where selected.

I linked a screen cap you can see me select the rem above and below no problems but as soon as I select inside the large rem it snaps up and down.
https://drive.google.com/file/d/1DTqXRzwxGjv9nlvRxI8SEf_McA_mQiFT/view?usp=sharing

Windows 10
Chrome
Version 84.0.4147.125

**Comment by BlindOpimism** [comment]
Here's a zip file of the screen cap if that's easier


[Remnote Scroll Bug.zip](https://github.com/remnoteio/remnote-issues/files/5073157/Remnote.Scroll.Bug.zip)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
