### ISSUE TITLE
The Back Button in the Android App Leads to a 404 Page

### ISSUE THREAD

**Issue by mfranzs** [remnoteio/remnote-issues#450]
"Using back key while in a subpage and going back to main page is a issue here. I'm using the android app. Whenever I press back key it shows a error message this page has been forgotten"

**Comment by Robertgreene123** [comment]
Hey, the same issue occurs with the windows desktop app.

**Comment by Robertgreene123** [comment]
Hey, I have this issue on my windows desktop app and I can't reproduce it on other computers around me, what could be wrong with my pc?
