### ISSUE TITLE
Todo Trash Text

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#452]
removing the todo creates a text that was sent to the trash, but there is nothing that goes to the trash
![gifntext-gif](https://user-images.githubusercontent.com/20538090/103161586-25b34f80-47f5-11eb-931a-ceb865e7486f.gif)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
