### ISSUE TITLE
Unable to create new document 

### ISSUE THREAD

**Issue by lritzer** [remnoteio/remnote-issues#454]
Unable to click, or alt N a new document, nor create a new folder 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for reaching out. What character does pressing the Alt + N key while typing enter?
