### ISSUE TITLE
Creating a reference from a selected text doesn't immediately show reference search popup window

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#456]
**Describe the bug**
If I want to convert a selected text to a reference, I can select the text and click on the **Make Rem Reference (link)** button from the popup menu. After clicking on this button, the popup gets dismissed and the selected text goes into search mode (but doesn't show any search results). Then only if we click on the highlighted search area (the dark portion) it shows search results for the potential reference candidates.

![select_reference_creation_triggers_search](https://user-images.githubusercontent.com/24322880/103185678-479ee780-4872-11eb-841c-6f8d8c1da57b.gif)

**To Reproduce**
Do exactly like in the above GIF

**Expected behavior**
After selecting some text, once I click on **Make Rem Reference (link)** button it should directly show the search results pop up window.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
haven't tested

**Additional context**
Rarely, for some selected texts the search results window shows up immediately. Not able to spot a pattern for such cases yet

**Comment by thedamsch** [comment]
I have the same problem.
