### ISSUE TITLE
Adding a tag or any power up rem, indents the text with RTL

### ISSUE THREAD

**Issue by binabdilwali** [remnoteio/remnote-issues#458]
**Describe the bug**
Whenever I add a tag to an RTL document rem, the rem gets indented.

**To Reproduce**
Steps to reproduce the behaviour:
Make document RTL
and add a tag
You will see the text getting indented on the right, which shouldn't happen. Look out for the empty space on the right on any rem with a tag, same applies to powerup when I hover over its tag.

**Expected behaviour**
The text shouldn't get indented, just the way it doesn't with LTR

**Screenshots**

**Additional context**
This is a problem I have been facing for a long time, and it's also happening on the desktop application
<img width="814" alt="Screen Shot 2020-12-29 at 9 32 56 AM" src="https://user-images.githubusercontent.com/44670449/103263647-88554880-49b9-11eb-98f7-0fc3a0740db0.png">

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
