### ISSUE TITLE
Spaced Repetition schedule failure

### ISSUE THREAD

**Issue by gabriel-at-gthb** [remnoteio/remnote-issues#460]
I'm using the desktop version, and the browser version on a windows pc.  I also use remnote on my iphone and ipad.
Remnote is displaying cards marked "easy" (as well as other levels) too soon, one day later, or sometimes again on the same day.   This is happening with MANY cards.  I have around 200 cards.   

**To Reproduce**
1.  Create many rem cards.   Practice them daily.  
2. Easy cards will be displayed every day, sometimes more than once on the same day, or far less than the selected S.R.S. 

**Expected behavior**
I expect a card that I mark not to be seen again for two weeks, not to be seen for two weeks.   

**Screenshots**
![remnote srs failure](https://user-images.githubusercontent.com/76802208/103396348-89849380-4ae7-11eb-887d-3bc9fd52dcb5.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10 pro build 19041.685
 - Browser [e.g. chrome, safari]  I use chrome, safari on my iphone and ipad  
 - - Version  Chrome version is Version 87.0.4280.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iphone 10xs
 - OS: 14.3
 - Browser safari 
 - Version 14

**Additional context**
This happens on all my devices and browsers.  The SRS schedule is not working reliably.

**Comment by mfranzs** [comment]
Thanks for reaching out. Is there any chance that you're practicing the same card on both your iPhone and iPad without syncing in between? (Ex. do you practice without an internet connection? This is unlikely to happen if you leave your internet connection on.)

**Comment by mfranzs** [comment]
Also, have you customized your spaced repetition settings at all, or are you using the default global scheduler? (Not the customizable Anki-SM2 scheduler.)

**Comment by gabriel-at-gthb** [comment]
Hi Martin,
   I'm always connected to the internet with any device, but I primarily use my windows pc to study cards.  This is especially true as I'm trying to document the problem I'm running into with the cards repeating.  
I've started my own excel spread sheet to track card repetition.  I'm not going to add any more cards until I figure out if Remnote is reliable.   No one wants Remnote to work more than I do, so I'm determined to understand what is happening.   The reliability and accuracy of Remnote's SRS will be what makes it or breaks it for most of us.     
Thanks for writing.  Gabriel Nobles541-705-7792 

 On Thursday, December 31, 2020, 04:24:24 PM PST, Martin Schneider <notifications@github.com> wrote:  
 
 


Thanks for reaching out. Is there any chance that you're practicing the same card on both your iPhone and iPad without syncing in between? (Ex. do you practice without an internet connection? This is unlikely to happen if you leave your internet connection on.)

**Comment by mfranzs** [comment]
Thanks for the information, and for helping us analyze! We'll 100% get this fixed ASAP once we find the problem. 

Is there a chance that you had been editing any of these cards in between repetitions?

(I also personally care a lot about optimizing my study time, so this is also personal for me ;) - not to mention making sure that this feature is working perfectly.)

**Comment by gabriel-at-gthb** [comment]
Here's an example of the problem I'm having.  I just saw this card yesterday:  

![srs fail example](https://user-images.githubusercontent.com/76802208/103447115-adf18480-4c3b-11eb-95d3-6b3a27a2a95d.jpg)

**Comment by gabriel-at-gthb** [comment]
I'm trying to prove to myself that remnote's SRS is working, or not, before I invest massive time and effort into it.   I'm tracking cards carefully now.   **I'm looking for suggestions on how to make an efficient spread sheet to track remnote SRS cards.**     I realize that remnote displays time shown data, but Its not proving accurate for me.  Hence my spread sheet efforts.

Again, I'm looking for positive suggestions on improving the spread sheet... for the ultimate goal of proving to myself that the SRS is working.    Here is a picture of my initial effort:
![REMNOTE SRS TRACKING](https://user-images.githubusercontent.com/76802208/103566795-8555ce80-4e77-11eb-9bbf-168713fe509a.jpg)

**Comment by gabriel-at-gthb** [comment]
I'm hoping this google docs link can be viewed.   The spread sheet is a giant test, not necessarily what I'm studying.

https://docs.google.com/spreadsheets/d/1qo4IcfQBXjy3ha4Vh0bsDweZfO-PF6rXjJw51xPSPkw/edit?usp=sharing

**Comment by gabriel-at-gthb** [comment]
After further testing for 10 days... Its a complete mystery to me why a card that I shouldn't see for two years, is popping up every few days.   "Sigh"

A lot of cards work right, according to the schedule.   Random cards completely ignore the SRS.   These cards have not been edited.    I really look forward to the resolution of this.

**Comment by gabriel-at-gthb** [comment]
Thanks for your continued work on this.  Nothing about Remnote is more important to me than the reliability of the SRS.   Its the foundation for all my other work.

**Comment by mfranzs** [comment]
We've found some possible explanations for what's going on here:
- When the same **global** queue was open on multiple devices and the first card was finished on one device, it wasn't getting removed on other devices
- When the same **folder/document** queue was open on multiple devices, cards were not being automatically removed from the other open queues
- The scheduler didn't properly handle repetitions that happened before the next scheduled date 

Do you mostly practice in global queues, or folder queues?

Fixes to the three above issues will be pushed soon. We're also now tracking the scheduled date for all new queue interactions, and this can be viewed up an updated metadata page.

I don't quite understand the columns in your spreadsheet. Some rows seem to only have a single date on them. How did you decide what a SRS failure was? I assume that you saw two responses near each other in time on your metadata?

**Comment by gabriel-at-gthb** [comment]
I’m sorry Martin, I didn’t expect anyone to actually follow my spreadsheet.
 I found the meta-data to be unreliable.    That is why I started using a spreadsheet.   The spreadsheet showed me that the problem was so frequent that I gave up using the spreadsheet.
 I threw my problems into the… “I hope someone fixes this someday soon” hat, because this is wearing me out.
  It’s encouraging to hear that you are working on this. It’s a major issue.
I counted an SRS failure when the predicted next appearance of a rem did not match the actual appearance of the rem.   For example, I would test myself on a rem and choose the seven days from now option. But the rem would appear again the NEXT day, ignoring the seven day request.   So I marked it as an SOS failure.    
I am certain the many of us are looking forward to the resolution of this frustrating problem.


On Friday, January 29, 2021, 3:19 PM, Martin Schneider <notifications@github.com> wrote:




We've found some possible explanations for what's going on here:
   
   - When the same global queue was open on multiple devices and the first card was finished on one device, it wasn't getting removed on other devices
   - When the same folder/document queue was open on multiple devices, cards were not being automatically removed from the other open queues
   - The scheduler didn't properly handle repetitions that happened before the next scheduled date

Do you mostly practice in global queues, or folder queues?

Fixes to the three above issues will be pushed soon. We're also now tracking the scheduled date for all new queue interactions, and this can be viewed up an updated metadata page.

I don't quite understand the columns in your spreadsheet. Some rows seem to only have a single date on them. How did you decide what a SRS failure was? I assume that you saw two responses near each other in time on your metadata?

**Comment by mfranzs** [comment]
I believe that these issues have been fixed. If anyone is still encountering problems, please re-open this.
