### ISSUE TITLE
Adding a slot by shortcut (Ctrl + Alt + P) and by mouse click behave differently

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#463]
The shortcut to add all slots adds them as a descriptor while clicking on a single slot in the `unfilled slots` dropdown creates them as plain rem.

![image](https://user-images.githubusercontent.com/4137110/103454479-edc07680-4ce4-11eb-8de6-2fa4cb965f5d.png)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
