### ISSUE TITLE
Ctrl + Alt + 7..0 are resolved differently on Linux and Windows on German Keyboard

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#464]
Basically I have Ctrl + Alt + 7 on Linux (the default) and have to change that to Ctrl + Alt + { whenever I switch to Windows.
This is the same Ctrl + Alt + 7 shortcut, it is just recognized differently on windows:

`{` = Ctrl + Alt + 7 = AltGr + 7 on a german keyboard.

I believe the `keydown` event provides the correct information on Windows while the `keypress` event has the `{` as the `keyCode`. Here is the output of [a key event tester](https://unixpapa.com/js/testkey.html):

```
keydown  keyCode=17        which=17        charCode=0        
         shiftKey=false ctrlKey=true  altKey=false metaKey=false
keydown  keyCode=18        which=18        charCode=0        
         shiftKey=false ctrlKey=true  altKey=true  metaKey=false
keydown  keyCode=55  (7)   which=55  (7)   charCode=0        
         shiftKey=false ctrlKey=true  altKey=true  metaKey=false
keypress keyCode=123 ({)   which=123 ({)   charCode=123 ({)  
         shiftKey=false ctrlKey=false altKey=false metaKey=false
keyup    keyCode=55  (7)   which=55  (7)   charCode=0        
         shiftKey=false ctrlKey=true  altKey=true  metaKey=false
keyup    keyCode=17        which=17        charCode=0        
         shiftKey=false ctrlKey=false altKey=true  metaKey=false
keyup    keyCode=18        which=18        charCode=0        
         shiftKey=false ctrlKey=false altKey=false metaKey=false
```
Compare the 3rd and 4th event.
Stragely enough there is only a `keypress` for shortcuts that have the AltGr slot filled. AltGr + 6 doesn't have a character assigned and Ctrl + Alt + 6 does not create a `keypress` event.

I haven't checked its output on linux yet. Edit: On Chrome on Linux it has the same output but without the `keypress` event generated.

**Comment by hannesfrank** [comment]
Obsidian uses the button location (`.code`) now for symbol and number keys.

**Comment by mfranzs** [comment]
This should be fixed as of the latest update; please let me know if you have more issues.
