### ISSUE TITLE
Can't upload or generate image occlusion card

### ISSUE THREAD

**Issue by Faisalchy** [remnoteio/remnote-issues#467]
**Describe the bug**
Whenever I try to insert an image from local drive of my PC the image won't upload. It will only take images from the copied link from the app. Moreover, when I tried to create custom diagram image and paste the link through google drive and another image hosting website, it wont upload too.
And the image which were uploaded, the image occlusion function doesn't work on them. It just shows a blank page. Please solve the issues. It would really help a lot.
Thank you for the amazing work you guys are doing.

![Screenshot (2)](https://user-images.githubusercontent.com/73018583/103468205-e77fd800-4d80-11eb-96ef-0138921fac6a.png)
![Screenshot (3)](https://user-images.githubusercontent.com/73018583/103468207-e9e23200-4d80-11eb-94b2-7a1ef321a253.png)
![Screenshot (1)](https://user-images.githubusercontent.com/73018583/103468209-e9e23200-4d80-11eb-90f9-09822e969864.png)

**Comment by mfranzs** [comment]
Merging with #447
