### ISSUE TITLE
Editing at end of equation moves cursor and edit outside equation

### ISSUE THREAD

**Issue by marcodetini** [remnoteio/remnote-issues#468]
**Describe the bug**
After an equation has been created, attempts to add characters to the end of that equation cause those characters and the cursor to leave the equation box and be input as normal text instead.

**To Reproduce**
1. Create an equation and move the cursor to a block of normal text.
2. Re-enter the equation, red box visible.
3. Move cursor to end of equation but still in red box.
4. Add a character.
5. Character will be added outside of equation, red box disappears and equation is shown in Latex.

**Expected behavior**
1. Create an equation and move the cursor to a block of normal text.
2. Re-enter the equation, red box visible.
3. Move cursor to end of equation but still in red box.
4. Add a character.
5. Character is added to equation code.

**Screenshots**
![Screen Shot 2021-01-02 at 6 13 19 PM](https://user-images.githubusercontent.com/76890863/103470325-38161780-4d26-11eb-979a-cf54412bc04d.png)
![Screen Shot 2021-01-02 at 6 14 33 PM](https://user-images.githubusercontent.com/76890863/103470363-6267d500-4d26-11eb-9967-bb0fccf9148e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Big Sur 11.1]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Version [e.g. 87.0.4280.88]

**Additional context**
My workaround right now is to input text into the equation at the second-to-last character until it's complete, then delete the last character.

**Comment by hannesfrank** [comment]
Possibly a special case of #218

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
