### ISSUE TITLE
Can't Change Password

### ISSUE THREAD

**Issue by koru1130** [remnoteio/remnote-issues#469]
**Describe the bug**
As far as I know, there isn't a way to change my password.
![image](https://user-images.githubusercontent.com/10102332/103485905-c4166500-4e34-11eb-9b59-44bdd83add16.png)
I thought the most likely place it would be is here, but I can't find "Change Password" on It.

I guess further information in the default bug reporting template won't be needed. If you need it, please let me know.

**Comment by mfranzs** [comment]
There is now a button in this section - thanks!
