### ISSUE TITLE
Rem Aliases / Bilingual support

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#47]
## Problem Description

As a bilingual user I sometimes want to write in a different language, for example when I reading a non-english book and want to avoid context switching or when expect to share with someone who does not perfectly speak english.

Another problem is synonyms (or things that are so closely related that I want them on one page). There are many Concepts which can be expressed with multiple words. When I research in different contexts, different words are used. Also I tend to forget about if I already have a Concept somewhere, search for a different word and do not find something.

## Possible Implementation/Solution

- Definition: An alias could be defined using a Power-Up rem similar to Edit Later with its message descriptor. There should to be multiple/arbitrary many aliases though. This could be extended further to allow to define 
- Usage: When I `##` tag or `[[` reference a rem have each synonym pop up in the search separetely, possibly marked as synonym of the main concept.
- (The alias definition should be as frictionless as possible, maybe with a command/shortcut like Edit Later.)

## Alternative / Current workaround

- Have one (master) page with the name `Synonym1||Synonym2||...` which shows up in the search for each synonym. But it has the full name in a reference (which could be desired too).
- Build something with Portals under the master page.
- I also have a `- [[synonym]]: [[Alias]]` reference at top of the page which will help me clean up when maybe a feature is released.

**Additional context**
See RoamResearch's [Synonyms, plurals, acronyms, aliases, multi-lingual usage of Roam, abbreviations, or: redirects](https://forum.roamresearch.com/t/synonyms-plurals-acronyms-aliases-multi-lingual-usage-of-roam-abbreviations-or-redirects/215) discussion.

**Comment by mfranzs** [comment]
Thank you for the well-thought-out request! Aliases are on our roadmap, and we'll take your suggestions into consideration in our design process. Closing this for now as this is a longer-term feature request.

**Comment by Jackiexiao** [comment]
so how to add alias now?  `Alt + A` ？
