### ISSUE TITLE
Settings aren‘t accessible on mobile

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#472]
**Describe the bug**
When I click on the settings icon in the sidebar, I get this ![image](https://user-images.githubusercontent.com/69430941/103553877-5c046500-4eae-11eb-897b-1cfe06ab6819.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: ios 14.3
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
