### ISSUE TITLE
You can't sort the sidebar

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#473]
**Describe the bug**
Clicking any of the options in settings option "sort sidebar" does nothing

**To Reproduce**
1. Go to Settings>Sidebar>sort sidebar
2. Click on any of the options
3. See error

**Expected behavior**
My sidebar to be sorted differently after I click on a setting

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/103554888-e5686700-4eaf-11eb-9b36-148cf0c149e8.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.3
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
