### ISSUE TITLE
Image conclusion desktop app

### ISSUE THREAD

**Issue by Dovydas0927** [remnoteio/remnote-issues#474]
**Describe the bug**
Image conclusion doesn't work properly on desktop app.

**To Reproduce**
1. Go to 'queue'
2. Wait for image to show up.
3. See error

**Expected behavior**
Clearly seeing image and image conclusion feature.

**Screenshots**
![Screenshot (105)](https://user-images.githubusercontent.com/63964560/103769581-38b3f400-502d-11eb-985d-0158f3d39929.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [e.g. chrome, brave]
 - Version [latest]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Merging with #447
