### ISSUE TITLE
Update makes change of flashcard type impossible

### ISSUE THREAD

**Issue by kizlu** [remnoteio/remnote-issues#478]
If you want to change the way the queue askes you a question it's impossible, because the preview of the flashcard is in the way.

**To Reproduce**
1. Go to any flashcard
2. Click on it
3. Scroll down to the flashcard symbol on the bottom of remnote
4. See error = only the preview and no option to change if you want it (only front, only back or both)
5. At some flashcards you can see on the left side the shadow of the window with the change options, so my guess is, that it is just a overlay. I marked it on the picture.

**Expected behavior**
The version before made it possible to change the way a flashcard is questioned: only front, only back or both

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome AND desktop app
 - Version 1.1

**Additional context**
![Flashcard_Issue](https://user-images.githubusercontent.com/77139156/103979067-352f8280-517d-11eb-8730-f8dddd6f04be.jpg)

**Comment by a22a-dev** [comment]
@mfranzs when will the update be rolled out?. This issue is of blocking me from using the remnote altogether.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
