### ISSUE TITLE
Portal, Empty Rems, Power-Ups show up in Hierarchical Search suggestions

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#48]
**Describe the bug**
The Hierarchical Search window shows suggestions which might be not useful as references. Those could be hidden.

**To Reproduce**
Have a document like this:
![RemNote Hierarchical Search](https://user-images.githubusercontent.com/4137110/90307555-8b064400-ded7-11ea-83e0-bec927655f59.png)
Type: `[[RemNote <Tab>`

**Expected behavior**
The following Rems could be hidden:
- Portal-related (I don't know if there is any use for such a reference, as one can not zoom into thouse, but only show the parent)
  - Stubs: text, reference, tag (not shown here)
  - Portal, shown as Unnamed
  - Serach Portal (not shown here)
- Empty Rems: shown as Unnamed. I use them for spacing sometimes. They don't make sense as References, because they have not meaning/content.
- (Some?) Powerups: here Document Status

**Comment by mfranzs** [comment]
Thanks for the report - we've deployed a fix. Please let us know if you're still encountering problems!
