### ISSUE TITLE
The content is cut off if the Rem is long in Card preview

### ISSUE THREAD

**Issue by nhanvu327** [remnoteio/remnote-issues#481]
**Describe the bug**
I can't scroll down to see the rest of Rem in Card Preview

**To Reproduce**
This happens when a Rem is long.

**Expected behavior**
Don't cut it off if the height's Rem is long. Please make a scroll if it's longer than max height of the container 
![image](https://user-images.githubusercontent.com/31462490/103987149-16aea300-51e0-11eb-9a78-e8534e20aa45.png)

**Desktop (please complete the following information):**
Chrome - latest version - Mac

**Comment by nhanvu327** [comment]
@mfranzs

**Comment by luke-nehemedia** [comment]
Same on the mobile version on iOS. I cannot scroll to see the complete answer which is quite annoying!

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by luke-nehemedia** [comment]
I still have the problem - at least on my iPhone. 

When trying to scroll (esp. for entries with images) it will just show a kind of „swipe action“ for easy/hard, but I cannot scroll the content of the answer.

**Comment by luke-nehemedia** [comment]
Here is a [video](https://www.dropbox.com/s/o43ag469mv3vsp2/RPReplay_Final1610181588.mov?dl=0) that demonstrates the behavior.

https://www.dropbox.com/s/o43ag469mv3vsp2/RPReplay_Final1610181588.mov?dl=0

**Comment by luke-nehemedia** [comment]
Any updates on this issue?

**Comment by mfranzs** [comment]
I'm having trouble replicating this - can you let me know if it's still happening after today's update, please? https://imgur.com/a/o6C1Gzb
