### ISSUE TITLE
can't update to the latest version on the desktop app.

### ISSUE THREAD

**Issue by nhanvu327** [remnoteio/remnote-issues#482]
**Describe the bug**

Closed and opened again many times but can't update to the latest version on the desktop app.

![image](https://user-images.githubusercontent.com/31462490/103987347-7147ff00-51e0-11eb-8b9f-c20a8180f0a7.png)

Mac - OS 11.1

**Comment by nhanvu327** [comment]
@mfranzs, please help!

**Comment by mfranzs** [comment]
Thanks for reaching out. Do you have any luck if you unpin, then re-open the app?

**Comment by nhanvu327** [comment]
That doesnt solve the problem. I had to download the new installer to
install again. It's all good for now
