### ISSUE TITLE
LaTeX editor popup not visible in queue

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#483]
**Describe the bug**
When a user attempts to edit LaTeX via the Remnote queue, the LaTeX editing popup is not visible.

**To Reproduce**
1. Go to Queue
2. Click on 'Edit card'
3. Attempt to edit a LaTeX equation

**Expected behavior**
The LaTeX editing popup should appear

**Screenshots**
<img width="844" alt="Screenshot 2021-01-08 at 10 43 36" src="https://user-images.githubusercontent.com/8283298/104006418-610f3000-519e-11eb-9f18-fded90c36b19.png">

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
