### ISSUE TITLE
Queue layout issue on tablet

### ISSUE THREAD

**Issue by nhanvu327** [remnoteio/remnote-issues#484]
[](url)
![Screenshot_2021-01-08-08-05-23](https://user-images.githubusercontent.com/31462490/104024261-f948fb80-5216-11eb-85f6-775dacda81d0.png)

Height does not span 100% screen height

Samsung Tab A7, RemNote mobile app.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
