### ISSUE TITLE
Shortcut to convert inline LaTeX to block LaTeX broken on macOS

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#485]
The shortcut to convert inline LaTeX to block LaTeX is broken on macOS -- when I attempt to press alt+b in a LaTeX editing dialog, it inserts an integral sign ∫ instead of / as well as converting inline LaTeX to block LaTeX.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
