### ISSUE TITLE
Unexpected scrolling up when backspace pressed after modifying a block of LaTeX

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#487]
When creating a block of LaTeX, pressing enter and then pressing backspace, the document unexpectedly scrolls up:

https://user-images.githubusercontent.com/8283298/104042541-8d44a400-51d2-11eb-967b-60ffa7e451fa.mov

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
