### ISSUE TITLE
Feature request: make popup that appears upon hovering over a reference scrollable

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#498]
As in e.g. Obsidian -- user would be able to hover over a reference and move their cursor into the popup with the popup remaining open, to scroll through the popup.

**Comment by ognsya** [comment]
Agree. Like happens when you hover a bullet (if it's folded).

Would also be good to be able to interact with the content within the preview (unfold, or even edit stuff).

**Comment by drkvj** [comment]
Kindly make this feature request on the forum please, where users can provide feedback and also upvote based on priority. Thanks :)
