### ISSUE TITLE
Settings gear not visible

### ISSUE THREAD

**Issue by ajbrads** [remnoteio/remnote-issues#50]
The bottom frame with 'Tutorial' 'Stats' etc. does not show 'about' or the 'settings' option. The dividing line between the left hand side and editor pane dows not move to enlarge bottom frame. Thus settings are inaccessible.

![image](https://user-images.githubusercontent.com/69697435/90338116-3817b400-dfdf-11ea-9b24-5c1894e51af8.png)

I trust the above image will appear to show the problem

OS: Windows 10 64 bit
Version: 1909
OS build: 18363.1016

Browser: MS Edge Version 86.0.601.1 (Official build) dev (64-bit)

I have just begun with RemNote today

**Comment by mfranzs** [comment]
Thanks for the report - we've deployed a fix. Please let us know if you're still encountering problems!
