### ISSUE TITLE
RemNote not recognizing correct answers for cloze 

### ISSUE THREAD

**Issue by beegeek** [remnoteio/remnote-issues#507]
**Describe the bug**
The file I am sending to you is for learning German Vocab.  RemNote gives error messages when the answers are correct.  The problem seems to be occurring with all of my flashcards.  However, I am only sending you one example.  When this file was much smaller, it worked. I am very new to RemNote.  Apologies if this is my mistake.

**To Reproduce**
1. Go to '...' Flashcard Mode
2. Click on '....' Answer, Enter Answer, Hit Enter
3. Scroll down to '....'  N/A
4. See error  Answer is identified as an error, even though the answer is correct.

**Expected behavior**
I expected answers that are typed in correctly to be identified as correct.

**Screenshots**
This is the flashcard answer:
![image](https://user-images.githubusercontent.com/12114719/104111382-5cca3c00-529e-11eb-8045-8c4241f61139.png)
Here is my code. 
![image](https://user-images.githubusercontent.com/12114719/104111468-41136580-529f-11eb-9f43-fb346a2738c3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Mac Big Sur 11.1
 - Browser [e.g. chrome, safari]  Chrome
 - Version [e.g. 22] 87.0.4280.141

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Resolved in #531
