### ISSUE TITLE
Image Occlusion Card Bug

### ISSUE THREAD

**Issue by StefanJordy** [remnoteio/remnote-issues#508]
**Describe the bug**
When try to create image occlusion card, the chart where you create the card is white, and can't create anything.

**To Reproduce**
1. Go to image
2. Click on 'Generate Image oclussion card'
3. See error

**Expected behavior**
Create an image occlusion card

**Screenshots**
![SS](https://user-images.githubusercontent.com/75457367/104112060-14b81300-52b8-11eb-976c-5c01808088dd.jpg)
![SS 2](https://user-images.githubusercontent.com/75457367/104112078-5d6fcc00-52b8-11eb-87bd-a3ffd9afb05a.jpg)
![SS 3](https://user-images.githubusercontent.com/75457367/104112094-8728f300-52b8-11eb-8dd6-560bf6fbc22f.jpg)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: chrome **( In browser works perfect, desktop software is the problem)**
 - Version: 1.1.4

**Comment by VmXF** [comment]
I'm also having the same issue with the desktop version.

**Comment by Experien1985** [comment]
same here, I think is general

**Comment by drkvj** [comment]
Closing as the bug has been fixed. If you are facing any further issues, kindly ping us.
