### ISSUE TITLE
PDF Upload Syncing issues

### ISSUE THREAD

**Issue by aaronweewee** [remnoteio/remnote-issues#509]
**Describe the bug**
Uploading **some** PDF on Machine A (Mac App), will only allow Machine A to view the pdf, other machines or browsers will always end up on the loading PDF page for hours and never load. This is not tied to any particular type of OS, I have tried uploading the same PDF on the Windows app, Chrome, Safari, iPadOs. Only the Windows App which uploaded will be able to view, or the Mac App which I uploaded will be able to view. uploading on the browser will cause the PDF to be unlovable once there is a hard refresh.

Edit: Uploading it onto the Safari or Chrome browser solves this issue. Only uploading it on the Mac or Windows desktop app that this issue occurs

**To Reproduce**
1. upload a pdf on Mac or Windows app
2. open it on any other browser or app

**Expected behavior**
It will end up loading the PDF forever (essentially its data loss if you use multiple machines)

**Screenshots**
Image of forever loading pdf on a Windows Machine
![IMG_0038](https://user-images.githubusercontent.com/24728980/104120775-78077b00-5374-11eb-865d-264378efa701.PNG)
Image of the actual pdf still accessible on the original machine
<img width="1440" alt="Screen Shot 2021-01-10 at 6 49 02 PM" src="https://user-images.githubusercontent.com/24728980/104120783-8786c400-5374-11eb-8c68-9e837da0ea7e.png">

**Desktop (please complete the following information):**
 - OS: Mac and Windows 
 - Browser Any Browser
 - Version 1.1.4 (Mac App Version)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 10.5
 - OS: iOS 14.2
 - Browser Safari
 - Version iOS 14.2 Safari Browser

**Additional context**
It might be due to specific types of PDFs. I've uploaded 15 PDFs and only 3 of them have this problem. I am not able to identify why. But uploading these 3 particular PDFs on any machine will cause the same issue where I can only view it on the original machine. If you would like the PDF please contact me, and ill send you the files, they are my school notes os im not allowed to distribute it openly here. 

Doing a full backup on my Mac which can view the pdf, then restoring it onto a windows computer still does not allow me to view the pdf. Hope this helps!

**Comment by aaronweewee** [comment]
Doing a full backup on my Mac which can view the pdf, then restoring it onto a windows computer still does not allow me to view the pdf. Hope this helps!

**Comment by aaronweewee** [comment]
Upon further investigation I've found some more bugs with a java script error. Only for PDFs that are affected by these, 
1. on the original machine open the pdf in Remote, 
2. click the view highlights, 
3. click on the source
4. click open link
5. Error will appear

<img width="1440" alt="Screen Shot 2021-01-10 at 7 14 02 PM" src="https://user-images.githubusercontent.com/24728980/104121363-940d1b80-5378-11eb-9225-81e3ad43ae4a.png">

After this bug appears, the entire Remote hangs and I need to force quit. for most other unaffected PDFs it will open the link PDF on my browser. 

Error Code: Uncaught Exception:
URIError: URI malformed
at decodeURI (<anonymous>)
at Object.<anonymous> (/Applications/RemNote.app/Contents/Resources/app.asar/build/electron/main.js:172:39)
at Object.emit (events.js:315:20)
at internalWindowOpen (electron/js2c/browser_init.js:181:2714)
at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:181:3875)
at IpcMainImpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:157:9393)
at Object.emit (events.js:315:20)

I have tried to delete the PDF and re upload it, but it still has the same problem on both windows and Mac app, if you'd like the PDF do let me know. All the best guys!

**Comment by mfranzs** [comment]
Thanks for the help debugging this - if you could share the PDF that would be really appreciated!

**Comment by aaronweewee** [comment]
On further investigation i realized its not PDF specific. I Duplicated the PDF (copy and paste) and i was able to upload it via the browser to ensure that it is properly hosted on the Remnote's server. I think the core issue is the Mac/Windows app is using the cached version store locally, while there may be some bugs uploading the file. The app does not retrieve the PDF from the server again or attempts to reuploads it. This allows the local machine to have access to the file while no other machine or browser does. 

Also when attempting to open link from the browser instead of the app, there is no error code, but it will open up a webpage that says error 404 instead of loading the PDF (which leads me to believe its not uploaded to the remnote servers properly)

**Comment by akemisetti** [comment]
I am facing the same problem with pdfs in my windows app. It works from the browser and the machine I have uploaded it. It does not open pdfs on the new machine. This is important for me. I would request you to increase the priority of this issue if possible?

Thanks
Anil

**Comment by treeml** [comment]
This has not been fixed. I still get the never-ending pdf loading bug.

**Comment by treeml** [comment]
![image](https://user-images.githubusercontent.com/79728312/109365515-7d4d6480-78e5-11eb-92b5-942ae634dede.png)

**Comment by Flummic** [comment]
I also still have this problem in App-Version 1.4.10 on two Windows Machines. The PDF only loads on the machine it was uploaded.
![image](https://user-images.githubusercontent.com/78422787/136095375-ed1a5caa-b29b-4ba2-b793-b6e21168f8e2.png)

**Comment by aaronweewee** [comment]
This issue is ald closed open up a new one, and I’ll add on, I realised copying and pasting images on the app causes issue and the image won’t load on other pages as well
