### ISSUE TITLE
bullets appear in strange places when hitting enter

### ISSUE THREAD

**Issue by tangodavid** [remnoteio/remnote-issues#51]
**Describe the bug**
On this rem:  https://www.remnote.io/document/Hm7sZGsA7NTCSzrar
When I click "enter" after a line in the middle, the new bullet and cursor appear at the top, and then after typing the phrase and hitting enter, appears in some other random place

**To Reproduce**
1. Go to https://www.remnote.io/document/Hm7sZGsA7NTCSzrar
2. Click on a bullet in the middle
3. Hit enter
4. Type some text and hit enter again
5. See error

**Expected behavior**
The bullet should appear below the line where you hit enter

**Desktop (please complete the following information):**
 - OS: Chromebook 
 - Browser Chrome
 - Version Version 85.0.4183.25 (Official Build) dev (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. For security reasons, we cannot access your document to reproduce the issue. Can you please provide some more info?

1) Is there anything unique about this text?
2) Does this happen on other documents?
3) Does the bullet and cursor end up at the top of the document?
