### ISSUE TITLE
Documents won't show up in pinned section in the sidebar unless all its parent documents are set to pinned

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#52]
**Describe the bug**
Setting status of documents to 'pinned' doesn't make them appear in the pinned section of document sidebar unless each document in its upper hierarchy is in 'pinned' status.

**To Reproduce**

1. Create a document (inner) under another document (outer)
2. Set the status of inner to 'Pinned', outer to 'Draft' and check Document Sidebar, you won't see inner in 'Pinned' section.
3. Try refreshing the search portal inside Document Sidebar - no change
4. Try resetting document sidebar - no change
5. Now set outer as well to '**Pinned**' status and viola now the **inner** will show up in the document sidebar

**Expected behavior**
Setting the status of a document to pinned should show that document under pinned section of document sidebar. Also, it is better to not show the full hierarchy of the document, the side bar is just wide enough to show the name of the document

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
