### ISSUE TITLE
LatEx subscript

### ISSUE THREAD

**Issue by wizzajen** [remnoteio/remnote-issues#533]
Hey amazing dudez behind screens, I must say REMnote worked for me perfectly and it would be more interesting if a LatEx command would give me a subscript with two or more digits. I tried using the 'x_y' to write H sub 12 and it only allows me to write one digit subscript. Anyway, thanks guys for making this wonderful app.

**Comment by eohomegrownapps** [comment]
@wizzajen you can render multi-digit subscripts using curly braces: e.g. $H_{12}$

[see also: http://tug.ctan.org/info/undergradmath/undergradmath.pdf ]
