### ISSUE TITLE
Desktop app crashed after a few minute everytime.

### ISSUE THREAD

**Issue by AkamaiOkole** [remnoteio/remnote-issues#536]
I have version 1.1 running on Catalina.  When I open remnote, everything is fine until a few minutes go by, they BOOM: everything goes blank. No sidebar, no rems, nothing works. Only remedy is to restart the app. can you assist?

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you please email us at support@remnote.io about this account-specific issue?
