### ISSUE TITLE
Concepts made out of Stub power ups don't show up properly when searching

### ISSUE THREAD

**Issue by tfiwm** [remnoteio/remnote-issues#54]
**Describe the bug**
Concepts made out of **Stub** power ups don't show up properly when searching

**To Reproduce**
1. Create a concept with name **Stub1** as a **Stub** type. So you will have to basically do **[[** then type **Stub1** and select **create rem** (or Ctrl + Enter) to create it as a **Stub** type
2. Similarly create another concept with the name **Stub2**
3. The create another concept by combining the references of **Stub1** and **Stub2**. So it will basically look like **Stub1 Stub2** and both these are links to the first two stubs
4. Now in the next line try searching for the reference of **Stub1 Stub2** (our third concept) by typing **[[** and then typing **Stub1 Stub2**, you won't get this in search results. Check the below screenshot. This **Stub1 Stub2** was not even in the entire search results. The issue is there if you search using Ctrl + F or Ctrl + o

**Expected behavior**
When I type **Stub1 Stub2** while searching for references, the third rem we created (**Stub1 Stub2**) should be the first result

**Screenshots**
![image](https://user-images.githubusercontent.com/24322880/90599890-8200c580-e1aa-11ea-9cd0-1a088ecd4275.png)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: 84.0.4147.125 (Official Build) (64-bit)

**Comment by drkvj** [comment]
This is working now as show in the picture here. Thank you for the report! 
![image](https://user-images.githubusercontent.com/69129342/113553768-dd86a300-9615-11eb-8912-0d3323fcb115.png)
