### ISSUE TITLE
Change Shift + Up/Down to Select Single Lines of Text, Rather Than the Full Block

### ISSUE THREAD

**Issue by mfranzs** [remnoteio/remnote-issues#542]
"When I try to highlight a line within a block Using the shift and up and down arrow keys, it forces the highlight to select the entire block rather than the one line I'm trying to highlight. Is there a way around this? I find it really annoying due to the repeated friction it causes in my experience. "

**Comment by ognsya** [comment]
Agree. I posted about this in the forums awhile ago:
https://forum.remnote.io/t/better-text-handling-when-writing-editing-and-searching/1107
