### ISSUE TITLE
Document is not immediately visible in new location after moving

### ISSUE THREAD

**Issue by lukf** [remnoteio/remnote-issues#548]
**Describe the bug**
When moving a document into another document, it is not immediately visible there.

**To Reproduce**
1. Open document A
2. In the other pane, open document B
3. In B, select "Move this Document"
4. Enter the name of A, or one of the Rem it contains. Move B into A.

**Expected behavior**
A immediately updates to show B as a Rem inside it.

**Actual behaviour**
A does not update automatically. Instead, B only appears inside A after navigating away and opening A again.

**Desktop (please complete the following information):**
 - macOS 11.2
 - Safari 14.0.3

**Comment by mfranzs** [comment]
Thanks for reaching out. I'm having trouble reproducing this. Does this happen every time for you?

**Comment by lukf** [comment]
This happened multiple times, but now I'm having trouble reproducing. Seems to happen when moving B multiple levels deep into a child of A, not top-level.

**Comment by lukf** [comment]
See #559 for a related and completely reproducible issue.

**Comment by mfranzs** [comment]
I see! This is likely working as intended for now; when moving a Rem, it's only included in its parent context by default, not any surrounding documents. We'll take a look at redesigning this, though.
