### ISSUE TITLE
Long rem names do not show up correctly in breadcrumb list

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#55]
**Describe the bug**
When a rem has a long name, it either appears as a blank breadcrumb or with Eva's theme switched on, appears displaced.

**To Reproduce**
1. Create a rem with a long name, for e.g. Refractile (dioptric) media of the eye (cornea, aqueous humor, lens and vitreous body)
2. Zoom into this rem so it comes up in the breadcrumbs
3. You should see a blank breadcrumb (without any active theme such as Eva's)

**Expected behavior**
Name should appear fully.

**Screenshots**

_Without any theme_

![image](https://user-images.githubusercontent.com/68901589/90636910-5b8b6a80-e23c-11ea-8a2e-087fa49ee07a.png)
<br></br>
_With Eva's theme_

![image](https://user-images.githubusercontent.com/68901589/90636638-f768a680-e23b-11ea-988d-de87ec080b51.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: Version 84.0.522.59 (Official build) (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
