### ISSUE TITLE
forzen on a specific page

### ISSUE THREAD

**Issue by zxc18874151571** [remnoteio/remnote-issues#553]
**Describe the bug**
Whenever I try to check one of my Rems, my RemNote froze. It happens to both desktop (mac) and web versions. In the browser, I can still open other pages. In Desktop, either I see a white blank page or I see that problematic page with Rems as 'loading'.

**To Reproduce**
1. Go to 'document'
2. Click or hover on 'conditional statement' (the problematic page)
3. See error

**Expected behavior**
Infinite time of loading Rems
or blank page

**Screenshots**
Desktop:
<img width="1679" alt="Screenshot 2021-01-15 at 11 52 56" src="https://user-images.githubusercontent.com/54632186/104716420-371eb600-5728-11eb-88ca-4a72932df198.png">
Desktop:(froze like this, when open) 
<img width="1368" alt="Screenshot 2021-01-15 at 11 58 59" src="https://user-images.githubusercontent.com/54632186/104717163-30dd0980-5729-11eb-992f-05a3ac891814.png">

Browser:
<img width="1368" alt="Screenshot 2021-01-15 at 11 53 44" src="https://user-images.githubusercontent.com/54632186/104716502-54538480-5728-11eb-99a7-495da477f54f.png">

**Desktop (please complete the following information):**
 - OS: [Macos]
 - Browser [chrome]
 - Version [87.0.4280.141 ]

**Comment by mfranzs** [comment]
Resolved over email.
