### ISSUE TITLE
Inconsistent Editor Pop-Up

### ISSUE THREAD

**Issue by pormonto** [remnoteio/remnote-issues#556]
Every time I highlight anything, the box that pops up does not STAY UP.
I put my cursor on it and it goes away. But it so happens when I put the cursor away that it starts working again. The entire highlight goes away when this happens too. It's not the pop-up box by itself.

**To Reproduce**
1. Highlight a Rem
2. Move the cursor to click on any of the options (cloze, colors)

**Expected behavior**
I expected the box to stay and allow me to pick an option.
It only works when I move cursor diagonally into the center of the box. And I have to do it QUICKLY. Just as long as it's anywhere in the center area.

**Screenshots**
![image](https://user-images.githubusercontent.com/72433858/104757687-38dd7f00-5712-11eb-8d8b-0032bf712f12.png)
I'd like to note that the issue isn't clear on the screenshot because the cursor never displays on Chrome screenshots. I highlighted the Rem right above the picture, but then the box disappeared (along with the highlight). The light blue that you see is not part of the bug.

**Desktop:**
 - Chrome 84.0.4147 / Chrome OS 13099.110.0

**Comment by mfranzs** [comment]
[Reproduction Note]: This is because the selection is briefly expanding to the neighboring Rem.
