### ISSUE TITLE
Unexpected behaviour when creating alias of collapsed bullet

### ISSUE THREAD

**Issue by lukf** [remnoteio/remnote-issues#559]
**Describe the bug**
When adding the alias power-up to a collapsed Rem, the alias Rem appears while its sibling Rem are still hidden.

**To Reproduce**
1. Create a Rem with children Rem below it
2. Collapse the top-level Rem
3. Using alt-A, add the Alias power-up to the top-level rem

**Expected behavior**
Upon adding the Alias power-up, the top-level Rem expands. Both the newly created Alias Rem, as well as its sibling are visible. The top-level Rem's chevron indicates its expanded state.

**Actual behavior**
The top-level Rem stays collapsed. Its chevron still indicates a collapsed state, even though the newly created Alias Rem is visible below it.

**Screenshots**
https://user-images.githubusercontent.com/6568478/104807320-74457f80-57de-11eb-82da-f88df4e66016.mp4

**Desktop (please complete the following information):**
 - macOS 11.2
 - Safari 14.0.3

**Comment by mfranzs** [comment]
Thanks for reaching out. In RemNote, it's possible to include some children without including all of them (right click on a bullet to attempt this). This is working as intended.
