### ISSUE TITLE
Making a Latex equation by highlighting text and pressing $ key no longer working

### ISSUE THREAD

**Issue by halhenke** [remnoteio/remnote-issues#56]
**Describe the bug**
This used to work up until the update before this one so i had assumed it was a bug.

**To Reproduce**
1. Select some text that you would like to display as latex
2. Press `$` key, much as you would press `[` key twice if you wanted to link to a Rem
3. Instead of creating a Latex span it simply replaces the selected text with a $ sign.

**Expected behavior**
The selected text should be wrapped in a box to display it as an equation in Latex - much like if you had originally used the double `$` key sequence

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 
 - Browser Opera 
 - Version 70.0

**Additional context**
If this was a feature that got dumped thats a real shame because it was way easier than the other way of Latex editing in a lot of cases.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by halhenke** [comment]
Awesome! the Latex stuff is much improved in general now - best its ever been 👍
