### ISSUE TITLE
Remnote freezes when PC is connected to internet

### ISSUE THREAD

**Issue by ao-kamal** [remnoteio/remnote-issues#562]
**Remnote freezes when PC is connected to internet**
Whenever I connect to the Internet, Remnote Desktop freezes then changes to a blank white screen. It works fine when I'm offline.

**To Reproduce**
1. Open Remnote(works fine offline)
2. Connect PC to the internet
3. Remnote freezes

Also:
1. Open Remnote while connected to the internet
2. Remnote freezes

**Expected behavior**
I expected remnote to sync.

**Screenshots**
![recording](https://user-images.githubusercontent.com/58620889/104820334-64588a80-5834-11eb-8914-ede7452ea7e9.gif)
![recording (1)](https://user-images.githubusercontent.com/58620889/104820396-af729d80-5834-11eb-985c-6d89eea9efd1.gif)

**Desktop:**
 - OS: Windows 10
 - Desktop App
 - Version 1.1.6

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you please email us at support@remnote.io to help with this account-specific issue?
