### ISSUE TITLE
Can't select formatting box when there is an image below

### ISSUE THREAD

**Issue by Experien1985** [remnoteio/remnote-issues#569]
**Describe the bug**
Can't select formatting box when there is an image below

https://user-images.githubusercontent.com/47003462/104853330-055c4980-58f8-11eb-8ab9-ed0aa74a61de.mp4

**Comment by drkvj** [comment]
This has been fixed, but there's still a related bug : https://github.com/remnoteio/remnote-issues/issues/1088
