### ISSUE TITLE
Cursor occasionally loses focus on a Rem for no reason, while typing

### ISSUE THREAD

**Issue by halhenke** [remnoteio/remnote-issues#57]
**Describe the bug**
This is a very intermittent thing but it happened this morning - was entering a Rem and suddenly, after a couple of letters i wasnt writing anything anymore. I thought i might have hit a tab key or something but this then, after refocusing the Rem and trying to type more, it happened consistently until i gave up and began entering the same text in a different Rem. Basically after a couple of seconds the cursor would disappear and you could not enter any text.

**To Reproduce**
1. As noted above its something that has only happened a couple of times a week if most - no idea why

**Expected behavior**
To be able to type and have text appear in the Rem

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Opera
 - Version 70

**Comment by ognsya** [comment]
This has been happening to me quite frequently as well. (Desktop, Windows)
Though I also am not sure what triggers it, or how to reproduce.

I am able to click place the cursor where I want. Then I am allowed to type 1 character. After that it loses focus.

Whenever this happens it always seems to be on just one specific Document.
Changing to other documents, no problem occurs. Going back to he problematic document, the issue persists.

Restarting the app fixes it.

**Comment by mashannon** [comment]
I also have this problem a lot.  I can not seem to make it reproducible.  However, I have noticed the following:

1. Like mentioned above, type 1 character and loses focus
2. Click on it, and the focus returns, but it loses it again after a second without typing.
3. It seems to happen more morning, which is when I start the app.
4. If I refresh, it seems to clear up for a little bit.
5. It eventually clears up on its own
6. I am using it in the chrome browser Version 87.0.4280.88 (Official Build) (64-bit)
7. Using it on a windows 10 machine
8. When I refresh, I do get the not saved message

**Comment by tfiwm** [comment]
Here is this issue in action. I am trying to type **sdsdsdsd** but after typing **s** the cursor loses focus. For me this happens when I use RemNote for every long time. Probably some actions are putting the GUI into weird state. Looking forward to next update with 'possible fix'

![cursor_losing_focus](https://user-images.githubusercontent.com/24322880/103305470-13394180-49c0-11eb-81d9-33b1dc54135e.gif)
