### ISSUE TITLE
Rems that are placed into portals, do not get the Stub tag

### ISSUE THREAD

**Issue by drkvj** [remnoteio/remnote-issues#574]
**Describe the bug**
Rems that are placed into portals, do not get the Stub tag

**To Reproduce**
1. Create a new rem from anywhere - ABC
2. Open a portal 
3. Drag the ABC rem into the portal
4. The Rem doesn't get the Stub tag

**Comment by mfranzs** [comment]
Thanks for the report. Why would you like the Rem to get the stub tag here? Currently this is working as intended, as "Stub" is only applied to Rem that are created via a search and not embedded in any document.

**Comment by drkvj** [comment]
Ah, that makes more sense. I assumed stub was given to every top level rem. Hence I thought that it should be applied to Rems that were made into top-level as well, as opposed to just the ones which were created as top level using the search. 

So, to confirm, a stub tag is applied only to Top-level rems that were created using Search?
