### ISSUE TITLE
Image Oclusion Cards don't work in the app

### ISSUE THREAD

**Issue by TinaTintin** [remnoteio/remnote-issues#581]
When I try to generate occlusion card the photo doesn't appear.

1. Go to any document
2. Click on a photo
3. Click "generate image occlusion cards"

This photo should appear and I shoul be able to create image occlusion. It does work in the browser, but it doesn't in the RemNote app.

Screenshot
![image](https://user-images.githubusercontent.com/77639871/104955807-14f89280-59cb-11eb-974e-a5f5a76ff366.png)

Desktop 
 - OS: Windows 10
 - Browser: Chrome

**Comment by mfranzs** [comment]
Merging with #447
