### ISSUE TITLE
The reference selection dialog sometimes does not work

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#582]
Periodically, upon typing [[ to open the reference selection dialog, no search results appear -- I then have to restart RemNote in order to regain reference functionality.

**Comment by tfiwm** [comment]
I have also encountered this several times after the new 1.1 update. I am suspecting if this is due to bigger underlying problem. Because when this happens even the *Ctrl + P* global search wouldn't work.

**Comment by nhanvu327** [comment]
same issue with me!!
