### ISSUE TITLE
"Create Alias" button doen't work by clicking the button but by pressing enter. 

### ISSUE THREAD

**Issue by akiorange** [remnoteio/remnote-issues#583]
**Describe the bug**
I believe an alias should be created either by clicking the button or by pressing enter. However, it works only by pressing enter, not by clicking the button. This error occurs both in desktop app and browser version.

**To Reproduce**
1. Create a rem reference.
2. Right click the rem reference.
3. Type a new alias name in the field.
4. Click the "Create Alias" button.

**Expected behavior**
An alias should be created by clicking the "Create Alias" button.

**Screenshots**
![Screenshot 2021-01-19 142120](https://user-images.githubusercontent.com/44665462/104991851-09f14100-5a63-11eb-9ffe-f3ecee379c33.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by Prudentist** [comment]
same issue!

**Comment by nhanvu327** [comment]
same
