### ISSUE TITLE
Error on Online mode Remnote

### ISSUE THREAD

**Issue by Theunissen-Guillaume** [remnoteio/remnote-issues#589]
**Describe the bug**
When I am on Online mode, Remnote send me an error when i write some texte. But on Offline mode, it's correct

**To Reproduce**
1. Go to Remnote.io
2. Go to online mode
3. Write some text

**Expected behavior**
I don't know

**Screenshots**
![image](https://user-images.githubusercontent.com/57918452/105141097-ea0c5c80-5af8-11eb-91c7-9cde530b9fea.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64X
 - Browser: chrome
 - Version  87.0.4280.141

**Comment by mfranzs** [comment]
Merging with #579
