### ISSUE TITLE
enter but get weird result

### ISSUE THREAD

**Issue by Jackiexiao** [remnoteio/remnote-issues#596]
Window 10 PC latest version

![remnote-bug-enter](https://user-images.githubusercontent.com/18050469/105375143-6dd26000-5c43-11eb-8062-eba381760b42.gif)

text: 
```
variables.data-00000-of-00001  variables.index
```

**Comment by drkvj** [comment]
Seems to me like there is a CSS issue, do you have any custom CSS installed?

**Comment by Jackiexiao** [comment]
I can't reproduce it now, thx for reply
