### ISSUE TITLE
Can't click subscription portal

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#598]
![image](https://user-images.githubusercontent.com/20538090/105414429-88f39e80-5c48-11eb-98fa-fbec4cbecfb7.png)

**Comment by ferdieperante** [comment]
I'm having the same problem. 
![image](https://user-images.githubusercontent.com/21334837/105429805-2375d100-5c8d-11eb-866e-9c0c5f74f8e6.png)
![image](https://user-images.githubusercontent.com/21334837/105429813-28d31b80-5c8d-11eb-9faa-ccde58c53af4.png)
I posted a bug discussion on the forum: https://forum.remnote.io/t/subscription-portal-is-not-working/2091

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
