### ISSUE TITLE
Jump to Rem defintion not working in Firefox

### ISSUE THREAD

**Issue by krankur** [remnoteio/remnote-issues#6]
**Describe the bug**
In Chrome, double-clicking the reference of a Rem, which is defined in the current document, takes you to the line on which the Rem is defined. This doesn't work in **Firefox**. Single click does nothing either on Chrome or Firefox.

**To Reproduce**
1. Define a Rem in a document.
2. Reference the Rem created in Step 1 somewhere in the same document (To ensure that the issue is apparent, the Rem should be referenced at such a location that the Ref definition is not in the browser view port).
3. Clicking or double clicking the reference does nothing.

**Expected behavior**
There should be a way to go to the definition of the Rem. Either the Rem should open as a document or the focus should jump to the line on which the Rem is defined.

**Laptop:**
 - OS: MacOS
 - Browser: Firefox
 - Browser Version: 78.0.2

**Comment by mfranzs** [comment]
Thanks for the clear report. This will be fixed in the next update.
