### ISSUE TITLE
Underline (double underscore) doesn't work properly

### ISSUE THREAD

**Issue by tangodavid** [remnoteio/remnote-issues#60]
When I type "__mytext__" what should appear is "mytext" (but underlined) instead what appears is "_mytext_" (whole thing underlined)

Desktop (please complete the following information):

OS: Chromebook
Browser Chrome
Version Version 85.0.4183.25 (Official Build) dev (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
