### ISSUE TITLE
Google sign in on Desktop app failing

### ISSUE THREAD

**Issue by Tryboid** [remnoteio/remnote-issues#600]
Here's what happened, @mfranzs :
1. The sign in With Google button is pressed once
2. Nothing happens
3. When you press the Google button after the first try, it shows that the 8000 port is occupied:
> ![image](https://user-images.githubusercontent.com/64481777/103333374-f53f1000-4a97-11eb-9553-72dbdc296606.png)
This happens everytime after the first click. Closing the app and reopening it restarts the process from 1.
It seems like RemNote is using the port, but fails to send the command to Chrome (or the other default browser). And when it retries, it finds the port occupied (by itself).

Update: I'm at Version 1.0.38. Problem is still there.

_Originally posted by @Tryboid in https://github.com/remnoteio/remnote-issues/issues/446#issuecomment-752341209_

this might have some relation with this [post:](https://github.com/remnoteio/remnote-issues/issues/400)

#400 
I repeat. "**MIGHT**"

**Comment by Tryboid** [comment]
@mfranzs this might have some relation with this post:
https://github.com/remnoteio/remnote-issues/issues/400#issue-766561375

I repeat. "**MIGHT**"

**Comment by mfranzs** [comment]
I agree that these are the same - merging with #400, thanks.
