### ISSUE TITLE
Using Chinese input will have some problem

### ISSUE THREAD

**Issue by link-ding** [remnoteio/remnote-issues#61]
**Describe the bug**
Once I use chinese input at the first of the Rem, if I type backspace or enter button it will automatically backspace to the last Rem or go to next Rem rather than delete a single charactor in the Chinese input.

**To Reproduce**
like what I am talking in the description.

**Expected behavior**
It should only delete a single charactor rather than backspace or enter to anthor Rem

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version: latest version

**Additional context**
Hope this gif will help you know what I am talking about.
![](https://im6.ezgif.com/tmp/ezgif-6-b56cacf796a3.gif)

**Comment by dive2Pro** [comment]
Yeah, please!
This is so annoying

**Comment by mfranzs** [comment]
Merging with #451 451

**Comment by immadolf** [comment]
Same for me.
And another problem is when i typed a word in Chinese input method then click the enter button, I will get a new line by mistake.
