### ISSUE TITLE
Use Chinese input method to type any character in the search bar will cause crash

### ISSUE THREAD

**Issue by plusjhjhjh** [remnoteio/remnote-issues#610]
**Screenshots**
![image](https://user-images.githubusercontent.com/72897552/105574713-59a47500-5da1-11eb-8174-3b437077a3e9.png)

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [edge]
 - Version [lasted]

**Comment by uvcybs** [comment]
me too. Korean Character
![Screenshot 2021-01-24 at 1 26 50 AM](https://user-images.githubusercontent.com/61214655/105607715-c0e31900-5de3-11eb-8478-e453b1c4141c.png)

**Comment by Nshcn** [comment]
me too

**Comment by Prudentist** [comment]
= issue #584

**Comment by drkvj** [comment]
Merging with #584 and closing this
