### ISSUE TITLE
 When using remnote's search function (ctrl+p) : Type in the Type in the chinese text, then the error message will pop up, then the error message will pop up

### ISSUE THREAD

**Issue by vdpolg** [remnoteio/remnote-issues#619]
**Describe the bug**
When using remnote's search function (ctrl+p) 
Type in the chinese text, then the error message will pop up

**To Reproduce**
1. The default input method is Chinese character input method
![pY4yJ9JHpT](https://user-images.githubusercontent.com/42104472/105621133-6081c500-5e3f-11eb-90ef-04a1d50fdcfa.jpg)

2. When using remnote's search function (Ctrl+P)
2. Click on 'Ctrl +P'
3. Type in the Chinese text
![pwpBxMdL3j](https://user-images.githubusercontent.com/42104472/105621058-97a3a680-5e3e-11eb-91f6-56998784e1c4.jpg)

![7W9fDvVbR9](https://user-images.githubusercontent.com/42104472/105621037-42679500-5e3e-11eb-83a9-54302d277088.jpg)

5. GIF
![82b1f4DBNJ](https://user-images.githubusercontent.com/42104472/105621543-6f6a7680-5e43-11eb-9a16-9dc84d2a8a2a.gif)

**Expected behavior**
Show search results.

**Screenshots**
Attached is the quick fix solution
1. Enter English or numbers first
2. Then enter Chinese characters
3. No error message will pop up
4. GIF
![Z8GJt8vz7K](https://user-images.githubusercontent.com/42104472/105621571-d2f4a400-5e43-11eb-9e9e-d75782e282f0.gif)

**Desktop (please complete the following information):**
 - OS: Win10 1909 18363.1316
   - Browser 1: Firefox
     - Version : 84.0.2

   - Browser 2: Opera, μTorrent edition
     - Version : 73.0.3856.344

**Comment by drkvj** [comment]
This is a dupllicate issue, so closing it and linking it to another issue report.
