### ISSUE TITLE
Problem with Full Width - The interface is skewed to the left

### ISSUE THREAD

**Issue by TaQuangKhoi** [remnoteio/remnote-issues#62]
**Describe the bug**
See screenshot and video to understand the problem
I does not use Custome CSS

**To Reproduce**
1. Go to 'RemNote.io'
2. Access to a document
3. See error
4. F5 to reload
5. the error still happens

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45689286/90976521-13d05000-e568-11ea-8601-74a0a567e16b.png)
![image](https://user-images.githubusercontent.com/45689286/90976551-45e1b200-e568-11ea-85d2-214eff639f42.png)
![image](https://user-images.githubusercontent.com/45689286/90976718-71b16780-e569-11ea-8e74-50ab22294125.png)
![image](https://user-images.githubusercontent.com/45689286/90976723-7a09a280-e569-11ea-88ed-05a5a4667ca7.png)
![Screenshot_20200823-180223_Chrome](https://user-images.githubusercontent.com/45689286/90976862-efc23e00-e56a-11ea-8f4e-c14b6c862dda.jpg)
![Screenshot_20200823-193715_Chrome.jpg](https://user-images.githubusercontent.com/45689286/90978719-0fad2e00-e57a-11ea-8432-acb56e5f0c5d.jpg)
**Video**
https://mega.nz/file/SUEXmCLY#ioFCiveX24Gf6otSFwAM_0OPJF7Y6BxFaAySGuJhV4s

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 84.0.4147.135 (Official Build) (64-bit)

**Smartphone:**
 - Device: SAMSUNG Galaxy J4+
 - OS: Android 9
 - Browser Chrome Mobile
 - Version 84.0.4147.125

**Additional context**

**Comment by TaQuangKhoi** [comment]
I always use **Full Width** option ..
Now I deactivate it to wait for the fix in the next update

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.

**Comment by TaQuangKhoi** [comment]
Thanks you..!!
