### ISSUE TITLE
Images on Remnote Mac do not sync to Remnote Windows and vice versa

### ISSUE THREAD

**Issue by choosemess** [remnoteio/remnote-issues#628]
Images uploaded in the mac version of Remnote do not sync to the the windows version of Remnote and vice versa. This is ongoing for 3-4 weeks now. 

This is the error that shows up (Mac, trying to load picture that was uploaded on windows):
![image](https://user-images.githubusercontent.com/77931373/105636902-70f76700-5e62-11eb-9f56-b38e04826582.png)

This can be easily replicated by just uploading a picture on either version and then checking it on the other application. This behaviour occurs with no exception. 

MacOS Big Sur 11.0.1 Remnote 1.1.6
Windows 10 Remnote 1.1.6

**Comment by choosemess** [comment]
This has been fixed on my end! Thanks guys. Have really been looking forward to this fix.

**Comment by choosemess** [comment]
Nevermind - Windows to Mac does not work, but Mac to Windows does.

**Comment by mfranzs** [comment]
Thanks for reaching out. We had pushed what we thought was a fix for this, but we can take another look if there are still problems.

A) 
Can you please try force-syncing your files by performing the following?

	1. Opening your settings
	2. Clicking "Account"
	3. Clicking "Force sync all files"

Please let me know if that works.

B) Does this still happen for newly uploaded images?

**Comment by choosemess** [comment]
Hi Martin,

Clicking 'Force sync all files' rectified the issue. All previously and
newly uploaded pictures appear now on both machines irrespective of which
machine the picture was uploaded to originally.

Thanks for fixing the issue.

BW

Ronas
