### ISSUE TITLE
LaTeX editor sometimes glitches for the first LaTeX block on a line

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#630]
https://user-images.githubusercontent.com/8283298/105647345-ebdd7380-5e9c-11eb-9585-e67ea721855c.mov

Typing `$ $ \ f r a c`

First line -- desired behaviour; second line -- unexpected behaviour

**Comment by drkvj** [comment]
@eohomegrownapps can you confirm if you are still having this behaviour?

**Comment by eohomegrownapps** [comment]
@drkvj This is still occurring:

https://user-images.githubusercontent.com/8283298/115086151-a19be980-9f03-11eb-88ed-393ffc9e1af7.mov

**Comment by hannesfrank** [comment]
@eohomegrownapps This looks similar to #492, right?
