### ISSUE TITLE
Image occlusion not working

### ISSUE THREAD

**Issue by Zsotyo** [remnoteio/remnote-issues#632]
**Describe the bug**
In the desktop app, when I want to generate image occlusion cards, the picture turns into a full white window.

**To Reproduce**
1. Import a picture
1. Click on the picture
2. Click on Generate image occlusion
3. The picture disappears. Only a white screen remains

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46581823/105677036-07c03400-5ef4-11eb-8bc9-1f6cfa40c889.png)
![image](https://user-images.githubusercontent.com/46581823/105677070-14448c80-5ef4-11eb-8120-e99694971eca.png)
![image](https://user-images.githubusercontent.com/46581823/105677088-19a1d700-5ef4-11eb-970d-2c67533f97b6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 -Desktop app

**Additional context**
In the browser the image occlusion works properly (sometimes the occlusions (the blue boxes) disappear, right after I generated them)

**Comment by SMerlock7** [comment]
#447 #384 
most of us having same issue

**Comment by mfranzs** [comment]
Merging with #447 - will be fixed soon.
