### ISSUE TITLE
When I try to study my Remnote flashcards in spaced repeition form It starts off by being able to give me the definition and being able to answer it. My remnote flashcards I need to complete would be 78 cards then after completing one rem it would go to 25 cards and the format changes as well. It ends up saying I have completed my daily queue cards. There are multiple glitches while doing this as well.

### ISSUE THREAD

**Issue by 4122pingu** [remnoteio/remnote-issues#65]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
