### ISSUE TITLE
Document tags don't refresh

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#652]
I don't think they should.

I created them with Alt + N and never used them for any tags/references.

![image](https://user-images.githubusercontent.com/4137110/106122883-84a01780-6159-11eb-8551-4a56f688abaf.png)

OS: Windows 10
Desktop 1.1.7

**Comment by gregskupien** [comment]
It may be a different bug. 
What I've noticed after today's update is that the tags displayed in upper right corner don't get refreshed after you move between documents! 
So chances are you had document with #Tag and #Stub opened and then you switched to 2021-01-28 Thu.

**Comment by mfitzhugh** [comment]
I'm also seeing this issue in some form, I think. I'm using Chrome 88.0.4324.96 on MacOS 11.1, but have replicated the problem on recent versions of Safari and Firefox on the same machine.

On hover over the rem "Jim," tags appear fine:
<img width="782" alt="Tags Displayed on Hover" src="https://user-images.githubusercontent.com/183787/106370224-d3da7980-630c-11eb-8b45-deab751511e0.png">

When the same rem is opened in a new pane, with Shift + Click, the tags also appear fine:
<img width="1280" alt="Tags Displayed When Rem Opened in New Pane" src="https://user-images.githubusercontent.com/183787/106370225-d4731000-630c-11eb-801c-20c395ee8b61.png">

When the same rem is opened via double-clicking it, the tags do not display when I expect that they would.
<img width="1280" alt="Tags Not Displayed When Rem Opened Via Double-Click" src="https://user-images.githubusercontent.com/183787/106370227-d50ba680-630c-11eb-8643-7236fe45f6f2.png">
