### ISSUE TITLE
How do I delete 744 empty rem or upper level docs without doing it one at a time?

### ISSUE THREAD

**Issue by gabriel-at-gthb** [remnoteio/remnote-issues#655]
I did an import from Anki.  It did not work.  Now **I have 744 empty documents or rems to delete**. Surely there is another way to do this other than clicking each one and deleting them one… at… a… time.

**Comment by gabriel-at-gthb** [comment]
So there is no mass select function yet?

**Comment by drkvj** [comment]
Yes, that would be quite difficult at the moment. This would be a feature request, kindly make one on the forum, so that others can vote on it.
