### ISSUE TITLE
problem with spellcheck

### ISSUE THREAD

**Issue by matleonii** [remnoteio/remnote-issues#66]
**Describe the bug**
Spellcheck not working

**To Reproduce**
right click on a work that is wrong
click the write word
exit the Rem, by click on any other Rem

**Expected behavior**
To have the word corrected.

**What happens**
The word gets corrected as expected, but when I click on another Rem it goes back to the original wrong word

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox and opera
 - Version latest

**Comment by drkvj** [comment]
This issue should be fixed now, kindly open a new bug discussion on the forum if you are still experiencing any further issues.
