### ISSUE TITLE
Android App Syncing issue 

### ISSUE THREAD

**Issue by JL16168** [remnoteio/remnote-issues#662]
**Describe the bug**
I downloaded the android app for my chromebook, but it takes forever to sync the notes i did on the Remnote website, and no matter how many times i click on the refresh, the App remnote still showing "synced 2 days ago" , it didn't sync anything I just did on the web remnote.

**Comment by mfranzs** [comment]
Thanks for reaching out. Do you know what version of the app you have?

**Comment by JL16168** [comment]
I don't know where to find the version for the app, it's the Remnote(early
access), I just saw the update released on Jan 27, so I updated my App, it
solved the syncing problem, so I guess maybe because the app was not
updated...

And I have another question , is there any differences between the web
remnote and the app ?

**Comment by mfranzs** [comment]
Oh good!

They are mostly the same; some rich text editing is not yet supported on the app.
