### ISSUE TITLE
scheduler not working 🔴🔴🔴

### ISSUE THREAD

**Issue by drstrangez0** [remnoteio/remnote-issues#664]
The scheduler not working whatever I press it till appear tomorrow as the gif shows 
Tested on desktop and web version same thing 
![2021-01-30-12-32-49](https://user-images.githubusercontent.com/70066742/106352947-0332bb80-62f8-11eb-91b9-4d79b5890e40.gif)

**Comment by drstrangez0** [comment]
![image](https://user-images.githubusercontent.com/70066742/106354039-03cf5000-6300-11eb-932e-cc74c9dc41e2.png)

**Comment by 8888Daniel8888** [comment]
Reported on the same issue a few hours ago although your post has more context that I don't have https://github.com/remnoteio/remnote-issues/issues/663

**Comment by mfranzs** [comment]
Thanks for reaching out. I don't quite understand what the error is in your gif. Do you expect the scheduled interval to be longer?

**Comment by drstrangez0** [comment]
> Thanks for reaching out. I don't quite understand what the error is in your gif. Do you expect the scheduled interval to be longer?

The interval will not update whatever I press 
for example, if I pressed Easy 10 times the interval still will be 24 hours 
I tried with android, browsers, desktop, other accounts,  the same problem 
![image](https://user-images.githubusercontent.com/70066742/106366149-05723580-634b-11eb-97b7-18419a5c66e5.png)

**Comment by mfranzs** [comment]
Got it. This is due to an upgrade in the scheduler to make it aware of the **real world time interval** between presses. The previous behavior here was that this interval would explode to multi-year intervals, violating the underlying SRS principles.

Did this change break a workflow for you? Did you want it to yield a longer time interval?

**Comment by 8888Daniel8888** [comment]
The ratings 24h 24h immediate immediate seem to be a mistake though ![image](https://user-images.githubusercontent.com/69430941/106367079-7b24d400-6340-11eb-9b97-edc299bd1ccc.gif) 
and are related to this https://github.com/remnoteio/remnote-issues/issues/663

**Comment by mfranzs** [comment]
Do you mean that they're a mistake because they're the same intervals? What seems wrong about them to you? 

(These are the same intervals that have always been the "first response intervals".)

**Comment by mfranzs** [comment]
Oh! I understand now 888Daniel - I believe that the issue you're talking about in 663 is different - that seems like a real bug (for the first time the card is loaded), while this seems like a "working as intended" from what I understand now.
