### ISSUE TITLE
Questions are Forward & Backward

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#665]
**Describe the bug**
When I create a question, the card is forward & backward

**To Reproduce**
1. Create a question with ?::
2. See error

**Expected behavior**
A question to be forward only

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/106356246-8eaf4b00-62fe-11eb-8fa2-d0a20c4202d9.gif)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.3
 - Browser safari
 - Version 14

**Comment by hugomarins** [comment]
The same happened to me. Questions should be one way only, at least by default.
