### ISSUE TITLE
Cloze cards with Rem References within it are broken; Queue crashes, and Rem metadata shows error

### ISSUE THREAD

**Issue by hugomarins** [remnoteio/remnote-issues#667]
Today I started facing a problem with some of my flashcards/Rems. I suspect it is happening when, inside a cloze text, there is a Rem Reference.

Reviewing my cards in the Queue, it suddenly crashes. No matter what button I press, it remains stuck, no answering to the "show answer" command. 

Look that in this Rem there is a Rem Reference inside a cloze.

![image](https://user-images.githubusercontent.com/54500828/106364927-e9ea3900-6310-11eb-87d1-9cff75eb6948.png)

When I go to metadata, I see this error:

![image](https://user-images.githubusercontent.com/54500828/106364756-3719db00-6310-11eb-94f2-970f69d3de57.png)

Below, I removed the Rem Reference, and left inside the cloze the same word, but not being a Rem Reference.

![image](https://user-images.githubusercontent.com/54500828/106364981-477e8580-6311-11eb-93a7-fb649e2357bb.png)

By doing this, no error is shown in the metadata, and it works again:

![image](https://user-images.githubusercontent.com/54500828/106364999-64b35400-6311-11eb-89bd-3ccd638332be.png)

But as me and I imagine lots of people have Rem References inside Clozes, it is a huge problem indeed. Actually, I can't even use RemNote anymore; when I start reviewing, soon a flashcard with Rem References inside clozes appear, and the queue crashes. As it is not possible to filter only the non-cloze cards for a section of reviewing, I really gave up. It is impossible to study my cards. So, I ask you kindly to try to solve this soon! :)

Even though the relationship of Clozes and Rem References where always difficult (for example, a cloze card would show many [...] for a single word if it is a Rem Reference), this is the first time I noted this issue. 

It happens both in the web and desktop versions. As the app was updated today, I imagine this issue is related with this late update.

Thanks for the incredible software. I'm pretty sure these minor problemns will soon be solved, making this a very powerful and stable learning tool.

I'll also use this space to request the "burying sibling cards" feature, just as Anki, what in my point of view greatly improves the effect of recall & spaced repetition. Thanks again!

**Comment by Tryboid** [comment]
Good to mention that, when you type {{ then add a reference with [[ inside it, the cloze acts weird and has two handles (arrows) on each side. The "Show answer" button for that card doesn't work at all.

**Comment by hugomarins** [comment]
With the recent update, this bug is back, and clozes with Rem References inside are broken.

**Comment by hugomarins** [comment]
Well, I'm not sure the problem is the same; in one case the card was shown regularly in the queue, but a bug in the metadata presentation, both in the queue and in the editor, always happens:

![image](https://user-images.githubusercontent.com/54500828/109424052-db9b4580-79c0-11eb-8277-f3e31cadcdf3.png)
