### ISSUE TITLE
Image Occlusion Card - image does not load on Windows desktop app

### ISSUE THREAD

**Issue by hbbssub** [remnoteio/remnote-issues#669]
**Describe the bug**
When "Generate image occlusion cards" is clicked, the "Generate Image Occlusion Cards" popup appears, but the image does not load.

**To Reproduce**
1. Insert an image in a document on the Windows desktop app.
2. Click on the image.
3. Click "Generate image occlusion cards"
4. See error.

**Expected behavior**
Image loads to allow creation of occlusion cards.

**Screenshots**
![image](https://user-images.githubusercontent.com/75822548/106372779-cf2bba80-6338-11eb-9a6a-ea2bbd138051.png)
Link to screen capture: https://drive.google.com/file/d/12srH0BR82wgotpR2AjFKONVPC_rbsmUn/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome (but issue is on desktop app only)
 - Version: Windows OS build 18363.1316

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Experien1985** [comment]
Same problem here and It has been like this for a long time. Will these going to be fixed? It's broking the desktop app for at least one month!

**Comment by Kaaru07** [comment]
image address works but it's annoying
