### ISSUE TITLE
[mobile] touching an image, even without releasing enlarges it

### ISSUE THREAD

**Issue by PandaBoy444** [remnoteio/remnote-issues#67]
**Describe the bug**
same as title

**To Reproduce**
1.have image
2.try to scroll past it like you should be able to
**Expected behavior**
I could scroll past an image with my finger on it

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]:: pocophone f1
 - Browser [e.g. stock browser, safari] chrome

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.

**Comment by PandaBoy444** [comment]
It seems the problem is sill there /:
