### ISSUE TITLE
Text in quotes gets swallowed by small spacing

### ISSUE THREAD

**Issue by PandaBoy444** [remnoteio/remnote-issues#68]
**Describe the bug**
same as title. it seems to be fine on mobile

**To Reproduce**
1. Go to have quoted text for multiple lines
2. try to read it

**Expected behavior**
I expect it to look a bit more like Eves theme::
![chrome_R2023UQ74D](https://user-images.githubusercontent.com/8178413/91547321-6923ad00-e92c-11ea-9c68-e55119231114.png)

**Screenshots**
how it looks on desktop
![chrome_SRwW63iiCG](https://user-images.githubusercontent.com/8178413/91547341-704abb00-e92c-11ea-940c-9c8babbfa527.png)
on mobile
![WhatsApp Image 2020-08-28 at 12 47 16 PM](https://user-images.githubusercontent.com/8178413/91547508-b30c9300-e92c-11ea-84de-b492d727bfae.jpeg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] winodws 10
 - Browser [e.g. chrome, safari] chrome 
 - Version [e.g. 22] 84.0.4147.135 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Xioami Pocophone f1
 - Browser [e.g. stock browser, safari] chrome
 - Version [e.g. 22] 84.0.4147.125

Thank you!

**Comment by PandaBoy444** [comment]
In my case it's important because when I publish a document and send it to a friend he doesn't have my css skins

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
