### ISSUE TITLE
Pressing Enter key on automatically add template & slot

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#680]
1. create document with automatically add template 
2. add a slot
3. create a rem (like rems that starts with A. on video)
4. then press enter key like in the video
5. ta da

https://user-images.githubusercontent.com/20538090/106401577-eac8bb00-6435-11eb-90e9-404780586f83.mp4

**Comment by drkvj** [comment]
This is not reproducible, Have you been noticing such behaviour still? Kindly follow this discussion on the forum, where we will be actively handling such matters from now on.
