### ISSUE TITLE
indent bug

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#685]
https://user-images.githubusercontent.com/20538090/106407381-f2478e80-644c-11eb-9c85-91e20bd81e1d.mp4

https://user-images.githubusercontent.com/20538090/106407386-f378bb80-644c-11eb-999d-3ef9b0e17c74.mp4

**Comment by mfranzs** [comment]
Thanks for reaching out. I don't quite understand the issue - is it not indenting properly when you select multiple Rem? Does this always happen, or only sometimes?

**Comment by Eikosa** [comment]
no, I've seen this problem for the first time
yes, it can't indent properly i dont know why
