### ISSUE TITLE
Highlighting the "hide all, test one" toggle in a cloze closes the cloze window.

### ISSUE THREAD

**Issue by yuvve** [remnoteio/remnote-issues#688]
**Describe the bug**
When opening the cloze menu, and then highlighting the "hide all, test one" toggle (or anything in the same row) closes the cloze window.

**To Reproduce**
1. Create a rem with at least 2 clozes
2. Click on the little arrow next to the cloze
3. Move your mouse over the "hide all, test one" toggle
4. The window closes

**Expected behavior**
The cloze menu shouldn't close.

**Screenshots**
![6H2XrHoMAB](https://user-images.githubusercontent.com/37124628/106468537-59d9fa00-649e-11eb-8a77-d934baff85ad.gif)
Note about the recording: I am not pressing anything the first times the window closes. In the end I try to press the toggle just before the window disappears, and eventually succeed.

**Desktop (please complete the following information):**
 - OS: Windows 10 OS Version 2004 (Build 19041.746)
 - Browser Chrome 
 - Version 88.0.4324.104 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
This doesn't seem to happen with all rem, but I can't find anything in common with the bugged rems or their parents.

**Comment by 8888Daniel8888** [comment]
https://forum.remnote.io/t/hide-all-test-one-option-disappears-whenever-i-try-to-click-on-it/2264/14?u=88dm88
