### ISSUE TITLE
Cant upload image.

### ISSUE THREAD

**Issue by LeFasser** [remnoteio/remnote-issues#689]
**Cant upload image.**

When I want to drag and drop an image it loads for ever.

![Screenshot 2021-02-01 152146](https://user-images.githubusercontent.com/74878408/106470824-40867d00-64a1-11eb-94a8-910b5f0cbfb6.png)

Windows
Chrome 
Version:   87.0.4280.77

**Comment by mfranzs** [comment]
Thanks for reaching out. Are you still experiencing this issue?

**Comment by LeFasser** [comment]
No the problem suddenly dissappeared :)
Love this programm btw.
But is there a way to upload a picture with more than 5mb?

Thank you.

Martin Schneider <notifications@github.com> schrieb am Mo., 1. Feb. 2021,
19:01:

**Comment by 8888Daniel8888** [comment]
you could use this image compressor https://imagecompressor.com/

**Comment by mfranzs** [comment]
Not currently other than compressing it as mentioned - we'll look into this option in the future.

**Comment by LeFasser** [comment]
The problem with the images taking infinite time to load up has reappeared.
I dont know whats the reason.

Thank you for your help.

Martin Schneider <notifications@github.com> schrieb am Mi., 3. Feb. 2021,
04:23:
