### ISSUE TITLE
Tag pills don't support color anymore

### ISSUE THREAD

**Issue by krankur** [remnoteio/remnote-issues#69]
I use tags extensively and to make them prominent I assign colors to them by setting some back highlight color to the tag's rem. This used to add colored background to the tag pills as well. But this no longer works.

**Steps To Reproduce**
1. Create a tag rem.
2. Zoom into the rem and highlight the tag with some color.
3. Go to some document and apply the tag to any rem.
4. The pill has the default background color and not the highlight color used on the rem.

**Expected behavior**
The tag pill's background color should be same as the highlight color used on the tag rem.

**Screenshots**
"Note" Tag Rem with green highlight color:
<img width="847" alt="Screen Shot 2020-08-29 at 2 16 13 AM" src="https://user-images.githubusercontent.com/11840300/91613719-b2601500-e99d-11ea-943e-c32164973d96.png">
"Note" Tag pill doesn't have green background color:
<img width="779" alt="Screen Shot 2020-08-29 at 2 17 54 AM" src="https://user-images.githubusercontent.com/11840300/91613820-e76c6780-e99d-11ea-883f-90aa7f2c638a.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 79.0

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
