### ISSUE TITLE
Card preview closes immediately after clicking Show Answer button

### ISSUE THREAD

**Issue by alvinlucillo** [remnoteio/remnote-issues#694]
**Description**
The card preview immediately closes after clicking the Show Answer button for flash card with enumerated answers

**Steps to reproduce the behavior:**
1. Select a concept or descriptor with bulleted list (created by triple colons)
2. Hover the mouse cursor over the cards icon below and click Show Answer

**Expected behavior**
Show Answer should display the list of answers and not close the preview window

**Screenshots**
![remnote-show answer issue](https://user-images.githubusercontent.com/78399587/106553903-4a69b800-6555-11eb-8da4-b56b21d2ba0a.gif)

**Desktop (Desktop app)**
 - OS: Microsoft Windows 10
 - Version: 1.1.10

**Desktop (Google Chrome)**
 - OS: Microsoft Windows 10
 - Version: 88.0.4324.104 (Official Build) (64-bit)

**Additional context**
I'm trying to see the what the flashcard will look like for enumerated list of answers

**Comment by drkvj** [comment]
This has been fixed in a previous update, kindly get back to us if this is still a problem for you

**Comment by drkvj** [comment]
merging with #792
