### ISSUE TITLE
Japanese input bug

### ISSUE THREAD

**Issue by kebifurai** [remnoteio/remnote-issues#7]
**Describe the bug**
After the language update 

"Something went wrong.
Please try refreshing the page. If the problem remains, please provide additional detail on the help page.

Error: Cannot resolve a Slate point from DOM point: [object Text],4. URL: https://www.remnote.io/document/pBvSet9SbobfXFcBK"

error is continuosly displayed when typing in japanese

**To Reproduce**
1. Type something using the japanese inpute method

**Screenshots**
![image](https://user-images.githubusercontent.com/49175327/88917725-39d53e00-d2a3-11ea-9f9c-33c4774ae73a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Firefox

**Comment by mfranzs** [comment]
Thanks for the report. Do you have the same issue in Chrome?

**Comment by kebi-jp** [comment]
> Thanks for the report. Do you have the same issue in Chrome?

No, in chrome I can type without any problems

**Comment by backwind1233** [comment]
@ mfranzs  the chinese inpute method meets the same issue.

**Comment by epq** [comment]
I also have this issue when typing Chinese in Firefox.

**Comment by backwind1233** [comment]
@epq type space at the beginning ,it seems work

**Comment by epq** [comment]
@backwind1233 you're right, thanks! 謝謝！

**Comment by uvcybs** [comment]
Wow this issue have a long histroy.

**Comment by drkvj** [comment]
This bug is the same as the other one here : https://github.com/remnoteio/remnote-issues/issues/1053 

Closing this to reduce duplicates. Thanks for the submit, we will be addressing all these related issues as part of the internationalisation of RemNote.
