### ISSUE TITLE
could not search after "tab" into document

### ISSUE THREAD

**Issue by Jackiexiao** [remnoteio/remnote-issues#704]
I want to go to remnote -> feature request ( I toggle "only search concept" for performance concern)

( tab into  remnote and search in remnote document to jump to feature request)

![remnote-tab-search](https://user-images.githubusercontent.com/18050469/106614308-21bdde80-65a6-11eb-99e5-dd62dd17ce2d.gif)

may be this is not a bug?

**Comment by mfranzs** [comment]
Thanks for reaching out. As commented, this seems like not a bug if you have "Only search concepts" enabled. Does using the arrow key to go down work for you?

**Comment by Jackiexiao** [comment]
yes, you are right.... hope remnote could improve performance, so I don't need to enable "Only search concepts"
