### ISSUE TITLE
Note layout not consistent when mouse hovering over equations and images

### ISSUE THREAD

**Issue by zhanghanduo** [remnoteio/remnote-issues#72]
**Describe the bug**
When I hover the mouse over the note (normally with latex equations and images), blank space starts to shrink when the mouse pointer is over it and expand again when the pointer leaves. For latex equations, the horizontal space shrinks and expands; for images, the vertical space changes. 
This makes the reading experience not so good.

**To Reproduce**
In the image, I did not even click the mouse. You can see the layout changes and the page even starts to scroll itself.
![remnote hover2](https://user-images.githubusercontent.com/8006682/91830817-d8273b80-ec75-11ea-91dc-84e98645b6f4.gif)

**Expected behavior**
A more consistent layout is to be expected. 

Moreover, I wish Remnote could provide a "lock" button for the page so when I enable it, the page is inedible so I can read it without worrying about accidentally change anything.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux, Windows 10
 - Browser: Chrome, Firefox
 - Version: 85.0.4183.83 

**Smartphone (please complete the following information):**
 - Device: Oneplus 8
 - OS: Android 10
 - Browser Edge, Chrome

**Additional context**

**Comment by zhanghanduo** [comment]
To make the problem clearer, I made another video.
![hover3](https://user-images.githubusercontent.com/8006682/91831553-cabe8100-ec76-11ea-9bee-a24388b06292.gif)

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.

**Comment by zhanghanduo** [comment]
@mfranzs Hi. Thanks for the efforts! The new UI is nice and clean and 99% of the consistency disappears. But I still sometimes find some tiny issues.
1) If there is an accidental blank line left between two rems, there is a chance that the space expands when you hover the mouse over it. I can manually delete it and after that the "ghost line" the layout is good again. 
![test2](https://user-images.githubusercontent.com/8006682/92420722-97648080-f1a7-11ea-85e9-77dfa51d17e3.gif)

The "ghost line" was generated by staring a new line and typing **/insert Code**. I suspect some other commands might also lead to this.

2) The inline latex still has slight inconsistency (but the amplitude is much smaller).
![test1](https://user-images.githubusercontent.com/8006682/92420790-e0b4d000-f1a7-11ea-9e0d-9945c5d6c018.gif)
