### ISSUE TITLE
Cannot open Document viewer when using RemNote Clipper with forum.remnote.io

### ISSUE THREAD

**Issue by TaQuangKhoi** [remnoteio/remnote-issues#726]
**Describe the bug**

**To Reproduce**
1. Go to 'https://forum.remnote.io/t/bible-references-in-remnote/2286'
2. Click on 'RemNote Clipper icon'
3. See error
4. Open RemNote.io
5. See that RN Clipper has created a new Document for my self
6. But i cannot use **Document viewer** in forum.remnote.io

**Expected behavior**
I want to open Document of RemNote Clipper in RemNote Forum website.
**Screenshots**
![image](https://user-images.githubusercontent.com/45689286/106903411-873bd780-672c-11eb-99b5-de46c7cd48ba.png)

**Desktop**
 - OS: Windows 10
 - Browser : Chrome
 - Version 
    Chrome :  88.0.4324.146
    RemNote Clipper : 1.3.12

**Additional context**

**Comment by drkvj** [comment]
This is not a bug _per se_, kindly make a feature request out of this on the forum. Thank you :)
