### ISSUE TITLE
Android: No easy/intuitive way to exit queue

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#732]
This is how it looks for me:

![Screenshot_20210204-212324_RemNote.jpg](https://user-images.githubusercontent.com/4137110/106950992-7d67a380-672f-11eb-965f-ce11d222fb7b.jpg)

I don't see a way to e.g. record something in the thought queue from there. The phones back button also just goes to a *random* card after briefly flashing "Looking for cards to practice".

I think it should still show the toolbar and exit the queue on back.

I noticed that it is shown and then disappears when the app is loaded. Maybe my theme accidentally hides something?

**Comment by mfranzs** [comment]
It should appear like this:

![image](https://user-images.githubusercontent.com/953103/106952928-c869c280-66ff-11eb-989d-d1da9cc45bcf.png)

Could you please check if it's related to some custom CSS?

**Comment by hannesfrank** [comment]
Sorry, you are right. It is a CSS issue on my end.

**Comment by hannesfrank** [comment]
Found it: I was hiding the collapsed sidebar since I want to toggle it manually via shortcut:
```css
  #document-sidebar--collapsed {
   display: none;
 }
```

Is there a way to target the mobile apps specifically? E.g. could we get extra classes on the `#react-root` or `#main` to target `.mobile` (=`.android`+`.ios`) and `.desktop` (=`.desktop-app` + `.web` and `.linux` + `.windows` + `.macos`)? Or should we just use media queries?

I fixed it now like this:

```css
@media (min-width: 700px) {
 #document-sidebar--collapsed {
   display: none;
 }
}
```
