### ISSUE TITLE
Can't update to version 1.1.11

### ISSUE THREAD

**Issue by skovacevic94** [remnoteio/remnote-issues#735]
**Describe the bug**
When i try to update my client desktop app, it crashes without updating the client. Reproduction is pretty easy. Either click on blue update button and installer (progress bar) will crash, or if you exit the client, it doesn't get updated as stated.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 10.0.19042
 - Browser Edge
 - Browser Version 88.0.705.56
 - Remnote Desktop Client Version 1.1.10

**Comment by Experien1985** [comment]
Did you tried to uninstall and install again?

**Comment by skovacevic94** [comment]
Yep.

пет, 5. феб 2021. у 14:13 Experien1985 <notifications@github.com> је
написао/ла:
