### ISSUE TITLE
Opening Remnote Error

### ISSUE THREAD

**Issue by k2mikaili** [remnoteio/remnote-issues#736]
![image](https://user-images.githubusercontent.com/69951928/106956771-b33f6480-66fc-11eb-9fd8-3a232c75bf67.png)
Refreshing works.

**Comment by mfranzs** [comment]
Thanks for reaching out. Does this issue go away if you refresh with  Ctrl + Shift + R?

**Comment by k2mikaili** [comment]
Yes, it goes away on refresh. Ctrl + Shift + R doesn't do anything though.

>

**Comment by mfranzs** [comment]
Can you please try:
 1. Clicking on the URL bar
 2. Ctrl + Shift + R
And see if that works?

**Comment by k2mikaili** [comment]
It's fine now. Weird.

Thank you for the help!

Have a selended day!
