### ISSUE TITLE
Context menu spelling correction overriden after changes

### ISSUE THREAD

**Issue by Hahlh** [remnoteio/remnote-issues#74]
**Describe the bug**

**To Reproduce**
1. type a word incorrectly
2. Right click to open up the context menu
3. Select the correction
4. Use space after the word (any new changes trigger an override)

**Expected behavior**
Corrections should stick

**Gif**
![Peek 2020-09-02 10-37](https://user-images.githubusercontent.com/45669613/91959312-b9be5000-ed08-11ea-9f1a-c7ed9f7bf3b8.gif)

**Desktop (please complete the following information):**
<img width="470" alt="image" src="https://user-images.githubusercontent.com/45669613/91959351-c8a50280-ed08-11ea-9b00-e0e06da945db.png">

**Comment by Skankhunt42069** [comment]
This happens on regular Firefox as-well although it was fixed temporally 24 or so hours ago.

**Comment by drkvj** [comment]
I am currently closing the issue as a part of the clean up process, if this issue is still persisting kindly make a new bug report on the forum or contact me to open this back. Thank you.

**Comment by drkvj** [comment]
This issue is duplicated here : https://github.com/remnoteio/remnote-issues/issues/165
