### ISSUE TITLE
Added images not shown in native MacOS app, but shown within browser

### ISSUE THREAD

**Issue by ushabuntu** [remnoteio/remnote-issues#740]
**Describe the bug**
When reading through the document within the native MacOS app, I can't see my images at all, see here: 
![Screen Shot 2021-02-05 at 14 07 32](https://user-images.githubusercontent.com/23134021/107032101-ee549d00-67bb-11eb-85a8-986d0cdddb3f.png)

But the same document within the browser works fine with images and all the info, as shown here:
![Screen Shot 2021-02-05 at 14 07 45](https://user-images.githubusercontent.com/23134021/107032154-06c4b780-67bc-11eb-9aad-c2d74cd5f2a2.png)

To be clear, images were originally uploaded within the Desktop app, copied from Word, or via screenshot. Screenshots were deleted after use. 

**To Reproduce**
1. Add an image to remnote desktop app
2. Make sure all info is synced
3. Quit the app completely
4. Reopen and the image is blank
5. Images are shown within the browser app (Brave, in this case)

**Expected behavior**
Images are shown in all apps (Desktop, mobile, and web)

**Screenshots**
Added above 

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [e.g. Brave]
 - Version [Desktop 1.1.12]

**Comment by drkvj** [comment]
@ushabuntu are you still facing these issues? Are these images normal or did you use image occlusion in them?

**Comment by ushabuntu** [comment]
> @ushabuntu are you still facing these issues? Are these images normal or did you use image occlusion in them?

So far, I haven't had this issue recurring, but some of the older images (from the time of the post) are still not shown. 

All images are regarding normal added images, without image occlusion
