### ISSUE TITLE
Image colors strongly altered on import

### ISSUE THREAD

**Issue by Hahlh** [remnoteio/remnote-issues#75]
I also tested inserting the same image into other applications, which maintained the colors.

**Screenshots**
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/45669613/92085723-82fc3e80-edc9-11ea-9d24-03516c767bcf.png">

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/45669613/92087442-c3f55280-edcb-11ea-864d-5d69cd064d99.png">

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/45669613/92120807-cff80900-edf9-11ea-8c70-603333d05d0c.png">

By the way, huge recommendation for the book you can see in the screenshots! Refactoring UI by Steve Schoger and Adam Wathan, if you don't already know it.

I believe, that additional info is unnecessary for this issue and you are likely already aware of that behavior, but please write, if you need any additional info.

**Comment by drkvj** [comment]
Thanks for submitting this, and apologies for not responding sooner, we are now cleaning up all the reports, to make sure this can be an efficient process from now
Have you been noticing such behaviour still? Kindly follow this discussion on the forum, where we will be actively handling such matters from now on.
