### ISSUE TITLE
Text References/Unlinked References portal no longer shows up automatically

### ISSUE THREAD

**Issue by SG60** [remnoteio/remnote-issues#750]
The *Text References* (unlinked references) search portal no longer shows up on rem automatically. The *References* portal still does.

**To Reproduce**
Look at a rem which used to have an unopened *Text References* portal suggested.

**Expected behavior**
The *Text References* portal should also appear.

**Screenshot**
![image](https://user-images.githubusercontent.com/2552620/107127371-91391400-68ad-11eb-8d81-0d62a2093d9b.png)

**Desktop (please complete the following information):**
- Windows 10
- Desktop App

**Comment by anishaaa1** [comment]
Also an issue on the MacOS app.
