### ISSUE TITLE
Vanished document

### ISSUE THREAD

**Issue by beegeek** [remnoteio/remnote-issues#752]
**Describe the bug**
Around 12:30pm MST on Sunday, February 7 I was working on a document called German Vocab 1 using my RemNote Desktop App. It was stored in a folder called German. I had been working on this document for ~two weeks.  I was adding an audio clip when the document vanished. No error messages, nothing.  I can't find it anywhere, not even in my deleted files.  I lost a HUGE amount of work.  Frustration doesn't even begin to say what I feel right now.  Can you possibly find my vanished file?
**To Reproduce**
No idea.  
**Expected behaviour**
I expected my file to be there and synced.
**Screenshots**
N/A
If applicable, add screenshots to help explain your problem
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Max OS Big Sur 11.1
 - Browser Chrome
 - Version 88.0.4324.146

**Comment by mfranzs** [comment]
Sorry that we didn't see this sooner - can you please email us with the details at support@remnote.io? We're able to help with account-specific issues more rapidly through that channel; the GitHub is intended for non-user-specific bugs.
