### ISSUE TITLE
shortcut for delete current document

### ISSUE THREAD

**Issue by Jackiexiao** [remnoteio/remnote-issues#757]
I know this is a feature request rather than a bug. But I really need this feature since I have a not successful import from obsidian due to this [history issue](https://github.com/remnoteio/remnote-issues/issues/555), this issue result in many "stub" rem in my search list (and also, a lot unformat note, but I could cut and paste again to solve that)

**Comment by mfranzs** [comment]
We'll add a shortcut for "Delete Rem/Document" `Cmd + Shift + Alt + Backspace` in the next update - thanks.
