### ISSUE TITLE
Disable underscore-to-underline automatic conversion

### ISSUE THREAD

**Issue by claforte** [remnoteio/remnote-issues#76]
Hi, I love RemNote but there are a few "features" that are extremely annoying. One of them is automatic conversion of text that contains underscore into underline text. This is especially grating when cut-and-pasting code, e.g.

`run_get_pal_steps_for_this_gpu` gets converted into rungetpalstepsforthisgpu, where 'get', 'steps', etc get underlined.

Please create an option to disable this. If I want to underline, I can easily use CTRL-I. Thanks,

Christian

**Comment by claforte** [comment]
I found a work-around. Enter `` (back-quote back-quote), then paste within the backquotes. That way Remnote doesn't mistakenly replace underscores by underlines.

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.

**Comment by claforte** [comment]
Thanks, much appreciated!
