### ISSUE TITLE
PDF Upload Crashes RemNote

### ISSUE THREAD

**Issue by tnice123** [remnoteio/remnote-issues#763]
**Describe the bug**

Starting today, every time I go to upload a new PDF to my document, the desktop app stalls, takes up most of my CPU and then essentially crashes and requires a force quit. Thus, unable to upload new PDFs.

**To Reproduce**
Simply try to upload a new PDF using the pro plan.

**Expected behavior**
Typically it uploads within a couple seconds without any issue.

**Desktop (please complete the following information):**
 - OS: big sur version 11.0.1 - using desktop app

**Comment by mfranzs** [comment]
Thanks for reaching out. Is this only on the desktop app, or does this also happen in the browser?

**Comment by tnice123** [comment]
I only work on the desktop so I only noticed it there but it’s since resolved (not sure how/why!).

Thanks!

**Comment by mfranzs** [comment]
Oh great - let me know if it comes up again!
