### ISSUE TITLE
Insert Existing Rem After Typing New Rem Has Strange Behavior

### ISSUE THREAD

**Issue by Add-HX** [remnoteio/remnote-issues#768]
**Describe the bug**
Typing a new Rem sometimes produces an "insert existing Rem" page, but when enter is pressed, the existing Rem is not inserted. Instead, the editor jumps to where the existing Rem currently is.

**To Reproduce**
1. Start creating Rem with a similar name to a previous Rem
2. Wait for Insert Existing Rem pop-up to appear (not with [[)
3. Press enter on any Rem

**Expected behavior**
That pressing enter would simply input the reference (or that the pop-up page wouldn't appear in the first place because I didn't press [[).

**Screenshots**
![before_enter](https://user-images.githubusercontent.com/78433128/107369418-c319c880-6aaf-11eb-884d-bfe6e908ab26.png)
![after_enter](https://user-images.githubusercontent.com/78433128/107369422-c4e38c00-6aaf-11eb-9a49-d9b6ce9a5d67.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Remnote App
 - Version: 1.2.1

**Comment by mfranzs** [comment]
This is working as intended to enable you to find existing Rem and avoid duplication. Do you find this gets in your way?

**Comment by Add-HX** [comment]
I see. It does not really get in my way, I just thought that the heading "Insert Existing Rem" was misleading. I thought that the program was asking if I wanted to insert a Rem reference.
