### ISSUE TITLE
If we can use Alt + Up/Down to move portals

### ISSUE THREAD

**Issue by TaQuangKhoi** [remnoteio/remnote-issues#77]
*Is your feature request related to a problem? Please describe.*
**I can easy to move rems up and down, but when i select a portal and use Alt + Up/Down to move portal.. it cannot be done..**
![image](https://user-images.githubusercontent.com/45689286/92248018-42e4ab00-eef2-11ea-854a-e0faa56d65b8.png)

*Describe the solution you'd like*
**I want to move portals with Alt + Up/Down**

*Describe alternatives you've considered*

*Additional context*

**Comment by TaQuangKhoi** [comment]
Thanks @mfranzs ..❤️..

**Comment by mfranzs** [comment]
Thanks for the suggestion - this has been included in the latest update :)

**Comment by TaQuangKhoi** [comment]
Thanks You.. Fall in Love with Sep 2020 Update..
