### ISSUE TITLE
Remnote not Loading 

### ISSUE THREAD

**Issue by lritzer** [remnoteio/remnote-issues#772]
Remnote is not loading my Rem. I Tried Restarting my Computer. It has not loaded my rem for over 2 hrs.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you please email us the details of this account-specific issue at support@remnote.io?
