### ISSUE TITLE
Multiline Card Viewer in Editor Closes Too Easily/Preemptively

### ISSUE THREAD

**Issue by Add-HX** [remnoteio/remnote-issues#774]
**Describe the bug**
In the editor, when attempting to see what a multiline card would look like after answer is shown, slight mouse movement or no movement at all would close the card viewer.

**To Reproduce**
1. Create multiline card
2. View with card icon
3. Click on show answer (move mouse after)

**Expected behavior**
The card view would only exit after my mouse would leave the designated area.

**Screenshots**
![multi_line_card_bug](https://user-images.githubusercontent.com/78433128/107526294-b667a400-6b85-11eb-89be-887174e9d0a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Remnote App
 - Version: 1.2.2 (I think)

**Comment by drkvj** [comment]
merging with #694
