### ISSUE TITLE
Blank Rem flashcard

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#78]
**Describe the bug**
a blank flashcard appears in the queue

**To Reproduce**
1. Go to queue
2. Encounter the flashcard
3. See error

**Expected behavior**
That flashcard shouldn‘t even exist

**Screenshots**
![IMG_1445](https://user-images.githubusercontent.com/69430941/92307292-ad9af280-ef95-11ea-85f2-bdfa0ee23642.png)
![IMG_1446](https://user-images.githubusercontent.com/69430941/92307293-ad9af280-ef95-11ea-8645-68cc37cb430e.png)
![IMG_1447](https://user-images.githubusercontent.com/69430941/92307294-ae338900-ef95-11ea-92b9-f2c1dfbf57f4.png)

**Smartphone (please complete the following information):**
 - Device: iphone XR
 - OS: ios 13.7
 - Browser safari (and chrome)
 - Version 13.1

**Comment by mfranzs** [comment]
This looks like a list flashcard. Do the rest of the lines of the flashcard appear if you press a response button?

**Comment by 8888Daniel8888** [comment]
This is a rather old bug report, so the issue was probably solved already
