### ISSUE TITLE
Image files not uploading

### ISSUE THREAD

**Issue by VmXF** [remnoteio/remnote-issues#782]
**Describe the bug**
I'm having a problem when trying to paste an image into remnote. The image won't stop loading, and because of that, I'm not able to use image occlusion, which is a key feature for me

**To Reproduce**
Just copy an image and try to paste it into remnote

**Screenshots**

![image](https://user-images.githubusercontent.com/77556339/107680465-a7afe880-6c7c-11eb-8ba8-58f78f7fe897.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 88.0.4324.104

**Comment by mfranzs** [comment]
Thanks for reaching out. Is this only this one specific image, or all images? Do you see a change if you refresh?

**Comment by VmXF** [comment]
Thank you for the fast response. It's happening with all images. When i refresh the page, the image just keeps loading.

**Comment by VmXF** [comment]
It appears to be a problem with my internet provider, since today I tested it on my neighbor's network and it worked just fine.
