### ISSUE TITLE
Missing rem reference on source fields between export/import 

### ISSUE THREAD

**Issue by Nimamoh** [remnoteio/remnote-issues#786]
**Describe the bug**
Between export / import, you loose rem reference in source fields.

**To Reproduce**
1. Create a local kb. Then create two documents formatted like this (note the rem reference as source)
![image](https://user-images.githubusercontent.com/16213090/107797077-d13f4180-6d5a-11eb-95c0-f6a40cc7e468.png)

2. Export the whole kb by `settings> Account > Export and Backup > Full Raw Backup (JSON)`

3. Re create a new local kb. Then import previously saved backup `settings> Account > Import > RemNote`

4. Observe the imported local kb having missing rem in place of a valid rem reference
![image](https://user-images.githubusercontent.com/16213090/107800592-3dbc3f80-6d5f-11eb-8f2c-a40838815c57.png)

**Expected behavior**
Kbs should be exactly the same between exported one and imported one.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: I use the remnote desktop app
 - Version 1.1.13

**Additional context**
I only use local kbs, I'm not signed in.

**Comment by akashkarri** [comment]
+1 to this issue
