### ISSUE TITLE
Document Preview upon Hovering while in Split Screen Misaligned

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#787]
**Describe the bug**
When trying to preview a document by hovering over a reference, the preview is quite misaligned (mostly to the right) and cut-off (see screenshot).

**To Reproduce**
1. Hover over a reference located closer to the right edge of the screen while RemNote's window size is reduced to half the screen or less than the entire screen size
2. Note that the document preview of the references located closer to edges are cut-off

**Expected behavior**
The document preview should somehow adjust according to the window size in a way that a decent amount of information is viewable directly from the preview despite the relatively smaller window size.

**Screenshots**

In the below image, RemNote is in split screen with another app. This reference is close to the right edge of my screen and when hovering over it, I am unable to see the entire document preview.

<img width="222" alt="image" src="https://user-images.githubusercontent.com/68901589/107808818-76ade180-6d6a-11eb-95c4-18a001f60628.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Desktop App
 - Version 1.1.13

**Comment by 8888Daniel8888** [comment]
Reported on the same issue https://github.com/remnoteio/remnote-issues/issues/201

Seems like this will take a while to be fixed with it only being 4th priority

**Comment by mfranzs** [comment]
Thanks for the report. Merging with #201.
