### ISSUE TITLE
Documents don‘t load

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#79]
**Describe the bug**
the documents don't load on mobile chrome.
**To Reproduce**
1. Go to chrome
2. See error

**Expected behavior**
I expect the documents to load
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/92309552-d8da0d80-efa6-11ea-83ad-34f0a7df3b39.png)![image](https://user-images.githubusercontent.com/69430941/92309558-e099b200-efa6-11ea-87d4-fd841cc15a00.png)![image](https://user-images.githubusercontent.com/69430941/92309562-ed1e0a80-efa6-11ea-9fd1-a89911ad1bea.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 9.7
 - OS: iPadOS 13.6
 - Browser chrome
 - Version 85.0.4183.72 (Official Build) stable (64-Bit)

**Comment by mfranzs** [comment]
Thanks for the report. Do your cards load in your queue?

**Comment by 8888Daniel8888** [comment]
Been waiting a few minutes and I'd say the queue doesn't load too. ![image](https://user-images.githubusercontent.com/69430941/92313760-85c88080-efcf-11ea-93e8-45a5b8deef60.png)Although when I first started RemNote, everything was loaded like usual but after I reloaded the page, to make sure that the issue is gone, the loading issue came back

**Comment by 8888Daniel8888** [comment]
The loading issue seems to plague my iPhone now. Before the September update, RemNote semi consistently loaded ![image](https://user-images.githubusercontent.com/69430941/92468617-bd077f00-f1d3-11ea-8224-ab72261e54dd.png)

**Comment by 8888Daniel8888** [comment]
Found a workaround for the bug: when you switch to another App (I experimented with discord) for 30-40 seconds and then switch back go RemNote, the docs will be loaded. So there must be a bug preventing you from loading the docs while you are on the web app. Hope this info helps

**Comment by mfranzs** [comment]
Thanks for the extra information. If you press the magnifying glass in the sidebar to activate search, do your documents appear?

**Comment by 8888Daniel8888** [comment]
No they don't. Only thing that changes is that the new loading animation appears on the sidebar. There also seem to be some noticeable frame drops

**Comment by 8888Daniel8888** [comment]
Update: clearing my browser history got rid of the problem, no idea what caused it but it works now
