### ISSUE TITLE
In android app ( tablet), after typing / actions menu doesn't pop-up 

### ISSUE THREAD

**Issue by asknet** [remnoteio/remnote-issues#795]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by mfranzs** [comment]
Thanks for reaching out. This is a feature request on the roadmap. The slash commands are not supported on mobile right now.
