### ISSUE TITLE
'Cards' Icon Sometimes Shows Inaccurate Depiction of Card

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#799]
**Describe the bug**
Have been noticing for a couple of days now that some cards that do not generate any rems still have the "card-generating" equivalent appearance of the 'Cards' icon in the bottom toolbar. Not sure if this is somehow intended.

**To Reproduce**
1. Create a multiline card A
2. Create a child rem under it (B) that will not appear on the back of A
3. When focused on B, see that the 'Cards' icon incorrectly appears as though B is a card-generating rem (which it is not)

**Expected behavior**
'Cards' icon should not have any elaborations in case of rems that do not generate any flashcards.

**Screenshots**

Couple of points to note in the example below:
1. The parent rem of the Card in question, 'Epiglottis', **does** generate its own rem (multiline)
2. One of its child rems (that is part of the content) can generate its own rem as well but it has been toggled off (not sure if relevant, but in case it is)
3. Card in question does **not** generate any rem - it's plain text

Card in question: 

<img width="752" alt="image" src="https://user-images.githubusercontent.com/68901589/107954373-a9d7b700-6f9c-11eb-9c3e-03a26c8cdd27.png">

When focused, 'Cards' icon in bottom toolbar appears like this:

<img width="36" alt="image" src="https://user-images.githubusercontent.com/68901589/107954418-b9570000-6f9c-11eb-8b9b-f3d5198cd85c.png">

When hovering over 'Cards' icon:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/68901589/107954482-caa00c80-6f9c-11eb-9997-8e2a1a2f4e42.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Desktop App
 - Version 1.1.13

**Comment by mfranzs** [comment]
Thanks for reaching out. This is working as intended; we had a number of users confused about why their list cards weren't generating cards and this change is intended to help make it clearer that the parent is generating a card.
