### ISSUE TITLE
Cannot unbold text

### ISSUE THREAD

**Issue by taifok** [remnoteio/remnote-issues#8]
**Describe the bug**
There is no way to unbold a text, whether `Ctrl + B` or Click from panel.

**To Reproduce**
Just try to unbold any text.

**Expected behavior**
text is unbold

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84

**Comment by mfranzs** [comment]
I'm having some trouble reproducing this on Chrome 84. [See here](https://imgur.com/a/uWIJVey)

Is there a chance that the Rem you're trying to unbold one of the following?
A) Tagged as a header
B) A concept (with a ::), automatically causing the front part to become bold

If not, can you send a screenshot please?

**Comment by mfranzs** [comment]
(Re-opening, accidentally closed.)

**Comment by taifok** [comment]
Oh, just found I somehow made it a header-2.
then all new sub-bullet points were default a header-3.
and they just look like a bolded text.

Even header-2 looks like just a bolded text. The slightly larger font-size really cant tell the difference between a header 2/3 and a bolded text.

**Comment by mfranzs** [comment]
Got it, thanks! Improving the default heading CSS is on our roadmap, which will help avoid this confusion in the future.
