### ISSUE TITLE
Card preview window disappearing

### ISSUE THREAD

**Issue by lordjohann409** [remnoteio/remnote-issues#802]
**Description**
Card preview isn't working on multi-line cards and lists

**To Reproduce**
1. Create numbered or multi-line list
2. hover over card preview field in the bottom bar in the middle
3. click "show answer"

**Expected behavior**
it just disappears after showing for a split second

**Desktop (please complete the following information):**
 - OS: Windows 10, newest
 - Browser: Chrome-based Brave Browser and native Remnote Desktop Application
 - Version: newest 15th february 2021

**Comment by anishaaa1** [comment]
Hey, I've already reported this - #792.

**Comment by mfranzs** [comment]
Thanks for the report. Merging with #792.
