### ISSUE TITLE
No Verification Email - at risk of being locked out of my account?

### ISSUE THREAD

**Issue by DryIce1** [remnoteio/remnote-issues#81]
**Describe the bug**
On the Contact Us page, I cannot send RemNote any questions, feedback, or suggestions. 
In addition, I did not ever receive a "Verification Email". 

I am worried that my data may not be stored safely or that I may become locked out without a way back in.

As a precaution, I am downloading a back up regularly.

**To Reproduce**
1. Go to 'Contact Us' page
2. Write a message.
3. Unable to send message because there is no "send" button, rather a text field that states  "Your email is not verified, so please double check your email address! Otherwise, we cannot reply to you."

**Screenshots**
![image](https://user-images.githubusercontent.com/59501376/92318618-1cd61c80-f052-11ea-8403-1cbc98b3357b.png)

**Desktop (please complete the following information):**
Windows 10 x64
Chrome browser Version 84.0.4147.135

**Comment by mizurova** [comment]
@DryIce1 Have you tried manually entering an email to the "Your email" field? 
"Send" button becomes enabled after entering email and message

**Comment by DryIce1** [comment]
thanks for the reply, but I guess I didn't describe the problem accurately enough.
when I submit my email address, a pop up appears stating "you have no unverified emails", and no email is sent to the submitted email address.

What would you suggest here? 
I have never received any emails or verification emails from RemNote.
![image](https://user-images.githubusercontent.com/59501376/92337291-f1077500-f0eb-11ea-978c-c3d632c3dda5.png)

**Comment by mfranzs** [comment]
Thanks for the report. Did you log into your account with A) the "sign in with google" button, or B) with a username / password?

**Comment by DryIce1** [comment]
Sign in with google

**Comment by mfranzs** [comment]
We've reproduced this and have deployed a fix in the latest update. Please re-open this issue and let us know if you're still having any problems.
