### ISSUE TITLE
 Collapse cause by Chinese character in search bar 

### ISSUE THREAD

**Issue by ecybiss** [remnoteio/remnote-issues#812]
**Describe the bug**
Typing Chinese characters in search bar causes collapses.

**To Reproduce**
1.Use shortcut Ctrl+P to open the search bar.
2.Type some Chinese characters here and press Enter. (for example ：“链接地址”)

**Expected behavior**
3.Search bar then collapses.(As shown in screenshot)

**Screenshots**
![4](https://user-images.githubusercontent.com/79266776/108372356-b0cf2580-7239-11eb-889e-798d9cc7ea31.png)

**Desktop (please complete the following information):**
 - OS: Windows10 2004 (19041.508)
 - RemNote version: 1.1.10 or 1.1.12 or 1.1.13

**Additional context**
Many Chinese users are confused by this bug now and it realy degrades the user experience. Hope to see fixes in the future. : )

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment]
merging to #584
