### ISSUE TITLE
Redundant links in template

### ISSUE THREAD

**Issue by ecybiss** [remnoteio/remnote-issues#814]
**Describe the bug**
Links in template points to the same place where it is tagged

**To Reproduce**
1.Create a template in a document.
2.Tag this template in another document, fill some content and make sure that the template has been tagged only once.

**Expected behavior**
3.Go back to the previous document and then find redundant links in the document containing tags: there should be only one link for evey slot in the template, but some slots just get two and adress of them are just identical.

**Screenshots**
![2](https://user-images.githubusercontent.com/79266776/108373575-048e3e80-723b-11eb-8248-1611d297e7fb.png)

**Desktop (please complete the following information):**
 - OS: Windows10 2004 (19041.508)
 - RemNote version:  1.1.13

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by mfranzs** [comment]
I'm having trouble reproducing the issue shown in your screenshot. Does this happen for every template instance or only this one?

**Comment by ecybiss** [comment]
> 
> 
> I'm having trouble reproducing the issue shown in your screenshot. Does this happen for every template instance or only this one?

I've been using several template for a long time, no redundant links occurs thereafter.  Maby this issue has been solved
