### ISSUE TITLE
large amounts of memory and hard disk space consumed

### ISSUE THREAD

**Issue by ecybiss** [remnoteio/remnote-issues#815]
**Describe the bug**
large amounts of memory and hard disk space can be consumed sometimes

**To Reproduce**
1. No explicit reproduction procedure and just use RemNote desktop normally with few document created in the database.

**Expected behavior**
2. Memory space usage grow up to 9838.9MB or so.

**Screenshots**
![0_0](https://user-images.githubusercontent.com/79266776/108374693-32c04e00-723c-11eb-9601-bccce30c6041.png)

![0_1](https://user-images.githubusercontent.com/79266776/108374722-38b62f00-723c-11eb-875a-0446865b0be4.png)

**Desktop (please complete the following information):**
 - OS: win10 20H2 19042.804
 - Version: 1.1.10~13

origin discussion posted by Carter in RemNote forum: https://forum.remnote.io/t/sometimes-large-amounts-of-memory-and-hard-disk/2698

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by ognsya** [comment]
I also brought this up in Discord here:
https://discord.com/channels/689979930804617224/689979930804617283/811606456901435482

Screenshot:
![image](https://user-images.githubusercontent.com/67518000/108381387-aa23bc80-71ff-11eb-9ca7-13b187030a1c.png)
