### ISSUE TITLE
Rems without the edit later tag are in edit later

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#820]
**Describe the bug**
There are rems in my edit later page even though they don't have the edit later tag.
**To Reproduce**
I don't know

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/108489412-d2fc8e00-72a1-11eb-8f8c-5c81f8664bc8.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.4
 - Browser safari
 - Version 14

**Additional context**
It's not a new issue, I remember seeing this some months ago but because I rarely check edit later, I forgot about it. It's also quite easy to workaround, just tag with edit later and untag

**Comment by mfranzs** [comment]
It's likely that this is the result of an older, now resolved bug. Have you experienced this with any recently added Rem?

**Comment by 8888Daniel8888** [comment]
No, this also only happened to kinda old rems
