### ISSUE TITLE
Delete method via Backend API is not working

### ISSUE THREAD

**Issue by pavlohrab** [remnoteio/remnote-issues#821]
**Describe the bug**
Deleting rem via remId via delete method (Backend API, as described [here](https://www.remnote.io/api)) is not working.
1 .The UserId and API key are fine. I can create and search rems through them
2. The remID is also fine. I can view and edit the rem

**To Reproduce**
The following code (via Python, using requests library) is not working
```python
delete = { "apiKey": REMNOTE_API, 
            "userId":USER_ID, 
            "remId" : REMID,
          } 
delete_url = "https://api.remnote.io/api/v0/delete"
requests.post(delete_url, data=delete)
```
Result: Rem is not deleted

**Expected behavior**
Deleted rem

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Vivaldi

**Additional context**
The issue does not depend on the browser or the OS version (:

**Comment by hannesfrank** [comment]
Can confirm. Here in cURL:

```
❯  curl --data "apiKey=API_KEY&userId=USER_ID&remId=hTHePHfKkpecJNXyC" https://api.remnote.io/api/v0/get                         
{"found":true,"_id":"hTHePHfKkpecJNXyC","name":["test"],"nameAsMarkdown":"test","parent":"zWc3xsrHTZMgYX3p2","children":[],"visibleRemOnDocument":[],"remType":"no_content","source":[""],"isDocument":false,"updatedAt":1613731978120,"createdAt":1613731976081,"tagParents":[],"tagChildren":[]}%                                                                                         

❯  curl --data "apiKey=API_KEY&userId=USER_ID&remId=hTHePHfKkpecJNXyC" https://api.remnote.io/api/v0/delete
Server error. Please contact support if the problem persists.%
