### ISSUE TITLE
My flashcards don't load

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#825]
**Describe the bug**
![image](https://user-images.githubusercontent.com/69430941/108571151-d4fd3600-730f-11eb-9eeb-ba2068d17bf5.png)I've been stuck on this screen for a while now, probably like over 15-20 mins or so. There's also no loading symbol in the sidebar, there was one at first though.

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.4
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for reaching out. 

1. Any change if you refresh?
2. Have you changed any queue-related settings?
3. Did you see a brief "updating" notification in the sidebar already?

**Comment by 8888Daniel8888** [comment]
1. No change when I refresh
2. Yeah I have changed some queue related settings while I was waiting, changing everything back didn't make a difference for me though
3. Not sure what you mean, like a round loading symbol and numbers like 0/27484 under it?

**Comment by 8888Daniel8888** [comment]
https://forum.remnote.io/t/flashcards-don-t-load-since-version-1-2/2793 Either not many saw this thread or it's really something with my account only. Do you want me to send you a json file or something like that to maybe solve this issue?

**Comment by mfranzs** [comment]
Thanks for the info.

1. If you feel comfortable sharing the JSON file to support@remnote.io that would be the easiest way to resolve this. 
2. Do you have any other device to check? I wonder if this is a one-time issue.
3. Could you please try logging out & in to see if that resolves that?

**Comment by 8888Daniel8888** [comment]
1. No problem, will do 
2. I checked my phone and the same issue is there as well
3. Tried that multiple times but it didn't change anything
