### ISSUE TITLE
I can‘t change the rem type

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#83]
**Describe the bug**
When I click on the option that tells me what type of rem that is (plain, set, multilines etc.), it doesn't display the pop up window where I can change the type
**To Reproduce**
1. Create a set rem
2. Click on the option box named "set"
3. See error

**Expected behavior**
The pop up window should be displayed fully. Right now it seems to be cut off
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/92320430-cbae3480-f021-11ea-8e97-c4a73b743973.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: ios13.7
 - Browser safari
 - Version 13.1

**Comment by mfranzs** [comment]
Thanks for the report. This should be fixed in the latest update. Please let us know if you're still having problems.
