### ISSUE TITLE
Sub documents can't be shown correctly in the sidebar in version1.2.3

### ISSUE THREAD

**Issue by FuryMartin** [remnoteio/remnote-issues#830]
**Describe the bug**
When using the version 1.1.13, the documents will be shown in the sidebar without considering whether their parents are documents or not.
But when using the version 1.2.3, documents can only be shown in the sidebar if their parents are also documents.  

**Expected behavior**
Hopefully RemNote will show these sub documents correctly just like they were in 1.1.13. 
Because parent rems are usually meaningless, their children are what really matter. That means in 1.2.3, I need to do several unnecessary clicks to find the document I really want. It's quite bothering.

**Screenshots**
### no parents are documents
_in 1.1.13_ 
<img src="https://fury-markdown.oss-cn-beijing.aliyuncs.com/20210220170336.png" width="450">
_in 1.2.3_
<img src="https://fury-markdown.oss-cn-beijing.aliyuncs.com/20210220140322.png" width="450">

### one parent is document
_in 1.1.13_
<img src="https://fury-markdown.oss-cn-beijing.aliyuncs.com/20210220171436.png" width="450">
_in 1.2.3_
<img src="https://fury-markdown.oss-cn-beijing.aliyuncs.com/20210220140409.png" width="450">

### all parents are documents
_in 1.1.13_
<img src="https://fury-markdown.oss-cn-beijing.aliyuncs.com/20210220171508.png" width="450">
_in 1.2.3_
<img src="https://fury-markdown.oss-cn-beijing.aliyuncs.com/20210220140432.png" width="450">

**Desktop APP information:**
 - OS: [Windows 10 20H2]
 - RemNote Version [1.2.3]

**Comment by mfranzs** [comment]
We unfortunately removed this feature in RemNote 1.2 to enable performance improvements. Could you either mark "contents" as a folder or move the Rem up?

**Comment by FuryMartin** [comment]
I will close this
