### ISSUE TITLE
❗ RemNote not opening (desktop, Windows)

### ISSUE THREAD

**Issue by ognsya** [remnoteio/remnote-issues#831]
**Describe the bug**
Clicking the icon on the desktop briefly opens a white screen, then closes. See image below.

I'm specifically using an offline local-only solution to avoid being denied access to my own data. I appreciate the updates/fixes.  But Please fix this asap.

Edit: there seems to be some RemNote processes in the background. But nothing ever opens. (image below)
Edit 2: maybe latest update hasn't applied yet - the exe has an older date (image below).
Edit 3: still having the issue. After restarting Windows, I managed to open RemNote a couple times (It asked me to restart to update - twice). After that, I tried closing the app and reopening it, and again I'm not able to.

**To Reproduce**
Just try opening Remote

**Expected behavior**
Open RemNote.

**Screenshots**
Screen that briefly appears:
![image](https://user-images.githubusercontent.com/67518000/108591028-7ca15500-735e-11eb-9535-db7ebc16c477.png)

Processes:
![image](https://user-images.githubusercontent.com/67518000/108591245-9db67580-735f-11eb-8e79-0aa75e4d1b33.png)

Local exe file:
![image](https://user-images.githubusercontent.com/67518000/108593070-795f9680-7369-11eb-8b71-fb572037d4b2.png)

**Desktop (please complete the following information):**
Windows. Desktop. Can't tell if it updated already or not.

**Comment by ognsya** [comment]
Edit 4: 
After restarting Windows once again, RemNote seems to be opening/closing without issues.
Will close this after I have tested this a bit more.

**Comment by mfranzs** [comment]
Thanks for reaching out, and I'm glad that this is working again.

1. Do you know if you were on version 1.2.3 while the errors occurred?
2. Do you know if the update was running while this white screen was open? (If so, this is strange - it should have displayed an indicator)

**Comment by ognsya** [comment]
Thanks. It's hard to tell if the bug was happening before or after 1.2.3. It seems the bug happened as RemNote attempted to update (if that makes sense). You can see the sequence of events in my original post (Edits).

Once RemNote did update, it went through the KB conversion process (in the sidebar) for a minute, with no issues.

Sorry I can't help with much info on what happened. It was all quite messy/buggy, requiring multiple restarts (of RemNote and Windows).

Thankfully, RemNote doesn't behave buggy otherwise. It seems stable now, so feel free to close this.
