### ISSUE TITLE
Normal portals not supported in the sidebar anymore

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#832]
I know this was never officially supported, but I really liked that I could statically customize the sidebar with normal portals.
The sidebar rework in v1.2.3 broke this:

pre v1.2.3:
![image](https://user-images.githubusercontent.com/4137110/108596674-d289f300-7386-11eb-95ca-724b840e92bb.png)

v1.2.3:
![image](https://user-images.githubusercontent.com/4137110/108596708-06651880-7387-11eb-9e37-09e470c95f71.png)

![image](https://user-images.githubusercontent.com/4137110/108596753-547a1c00-7387-11eb-9019-e33098410ee7.png)

Is this an easy to fix regression, intentional design (won't fix), or should I report this as a Feature Request on the forum?
I mean this is similar to an always opened `#Pinned` section, but without the extra heading.

**Comment by tfiwm** [comment]
I used to this heavily as well. Would love to get it back

**Comment by tfiwm** [comment]
More complaints on this - [Sidebar not allowing only pinned documents to be displayed ](https://forum.remnote.io/t/sidebar-not-allowing-only-pinned-documents-to-be-displayed/2829)
