### ISSUE TITLE
"Delete rem" shortcut deletes the entire document if focused on first line

### ISSUE THREAD

**Issue by ShreyasKallingal** [remnoteio/remnote-issues#837]
**Describe the bug**
The "Delete Rem" shortcut, when applied to the first line rem in a document, deletes the entire document instead of deleting just the first line and moving the cursor to the title. 

**To Reproduce**
1. Place cursor on first rem in a document
2. Press shortcut keys for "Delete Rem" (default for Mac: shift + option + command + delete)
3. Entire document is deleted

**Expected behavior**
When the first rem is deleted manually with the 3 dots to the side, only the first line rem is deleted, and the cursor moves to the title. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Desktop
 - Version: 1.2.3

**Comment by mfranzs** [comment]
Thanks for reaching out. Merging with #894
