### ISSUE TITLE
The command "::1." doesn‘t work

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#84]
**Describe the bug**
When I write the command ::1. behind a multilines bullet point, it creates another multilines bullet point. The triple dots replace the ::1. when I click on another rem but the box that tells me what type the rem is, says list
**To Reproduce**
1. Create a multiline and write ::1. after one of the bullet points
2. See error

**Expected behavior**
The command should create a child with "1." at the beginning
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/92320823-ca323b80-f024-11ea-92a3-1e4ba97ede4b.png)![image](https://user-images.githubusercontent.com/69430941/92320824-cdc5c280-f024-11ea-85c4-f25b5fee4c5d.png)![image](https://user-images.githubusercontent.com/69430941/92320828-d1594980-f024-11ea-8ab2-84bdde3176ee.png)

**Smartphone (please complete the following information):**
 - Device: iphone XR
 - OS: ios13.7
 - Browser safari
 - Version 13.1

**Comment by mfranzs** [comment]
This looks like this is happening because you have already made this Rem a Multi-Line card. If you delete the child and then re-type ::1., it should turn into a List card. Please let me know ift hat doesn't work for you!
