### ISSUE TITLE
Sidebar trigger area covers triple dots of top level rem

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#840]
**Describe the bug**
I think it's best to just show:![image](https://user-images.githubusercontent.com/69430941/108618575-9a82be80-741f-11eb-8edf-117b3c97753b.png)
VS.
![image](https://user-images.githubusercontent.com/69430941/108618587-a2daf980-741f-11eb-8456-42df86de8410.png)
**Expected behavior**
The triple dots not to be hidden. Right now you simply can't click on it unless you turn off the full width expansion. Maybe squish the width a little but also make the trigger area of the sidebar a lot slimmer, I personally find it way too big. Imo the cursor has to touch the left border of the screen for the sidebar to activate. This will reduce the accidental activations, which is something complained about in the forum

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.4
 - Browser safari
 - Version 14

**Additional context**
https://forum.remnote.io/t/difficulty-accessing-the-triple-dots-on-the-side-a-rem/737?u=88dm88

https://forum.remnote.io/t/adjust-the-trigger-area-of-sidebar-auto-hide/2461?u=88dm88

https://forum.remnote.io/t/ui-hidden-menu-appears-too-quickly/1785?u=88dm88

there are a few more btw but they're basically all the same

**Comment by hannesfrank** [comment]
Similar to #737. I posted a Custom CSS fix there which also works for full width documents:
```css
#document {
  padding-left: 40px;
  width: calc(100% - 70px);
}
```

**Comment by 8888Daniel8888** [comment]
Thanks! This fixed everything
