### ISSUE TITLE
Shortcut for "Clear Header" doesn't work

### ISSUE THREAD

**Issue by mizurova** [remnoteio/remnote-issues#85]
**Describe the bug**
Pressing "Clear Header" shortcut (Cmd + Opt + `) doesn't have any effect on a text. 

**To Reproduce**
1. Make any rem a "Header 1"
2. Press "Cmd + Opt + `" when cursor is on that rem
3. Text format is not cleared

**Expected behavior**
Text format is cleared to the normal text

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - Browser Chrome 
 - Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
- Changing formatting using UI menu "Header Size" on the bottom of the page works fine
- Tried to change "Clear Header" shortcut and it's not working either

**Comment by mfranzs** [comment]
Thank you for the report. What keyboard shortcut is listed for you on https://www.remnote.io/keyboard_shortcuts? What other shortcut did you change this to?

**Comment by mizurova** [comment]
My default shortcuts are
![image](https://user-images.githubusercontent.com/5367421/92498391-3e2a3a80-f203-11ea-9643-9bd2b71df84b.png)
The alternative I've tried is "Cmd + Opt + –" which is not working either
![image](https://user-images.githubusercontent.com/5367421/92498573-7762aa80-f203-11ea-9cd5-5f1a13b9cd26.png)
However "Cmd + Ctrl + -" is working
![image](https://user-images.githubusercontent.com/5367421/92499194-42a32300-f204-11ea-9aa1-f6dcbda49375.png)

Looks like it might be related to `Option` key shortcuts

**Comment by mfranzs** [comment]
Thanks for the info. Have you remapped any of the bindings on your keyboard? Do the other keyboard shortcuts involving Opt work? (For example, does Header 1 work?)

**Comment by mizurova** [comment]
I'm using the default "ABC - Extended" keyboard and other shortcuts are working (e.g. Header 1). I have this laptop and keyboard layout for a couple of years and this is the first time I've noticed an issue like this (I use shortcuts a lot).

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
