### ISSUE TITLE
No highlight when I zoom out with a shortcut

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#855]
**Describe the bug**
Zooming out by clicking on a breadcrumb looks like this![image](https://user-images.githubusercontent.com/69430941/108622826-b431ff00-743b-11eb-80eb-b92948c2c16c.png)
While zooming out with a shortcut looks like this![image](https://user-images.githubusercontent.com/69430941/108622840-c3b14800-743b-11eb-8d0e-01bcaffc9116.png)
**To Reproduce**
1. Zoom out of a rem with the shortcut
2. See error

**Expected behavior**
I expected the blue highlighting thingy to appear as well when I zoom out with the shortcut

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.4
 - Browser safari
 - Version 14

**Comment by hannesfrank** [comment]
Can confirm. @ devs this is the highlight created by the `.flash` class.
