### ISSUE TITLE
Unable to move multiple rems using keyboard shortcut

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#86]
**Describe the bug**
Upon selecting multiple rems and trying to move them all using the keyboard shortcut (Cmd + M), they cannot be moved together. Moving a single rem works as it should, but more than 1 doesn't. This hasn't been working for weeks but did use to work before.

**To Reproduce**
1. Select multiple rems with Shift + ↓/↑
2. Use the dedicated keyboard shortcut for moving rems, i.e. Ctrl/Cmd + M
3. Observe that nothing happens

**Expected behavior**
I should be able to move multiple rems from one parent to another in the knowledge base the same way I'm able to move a single rem for the same purpose.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
