### ISSUE TITLE
Hover formatting menu disappears if selected text is exactly above a Rem with an image.

### ISSUE THREAD

**Issue by ognsya** [remnoteio/remnote-issues#860]
**Describe the bug**
See title. I guess the hover trigger of the image overrides the one for the menu (when it shouldn't)?

**To Reproduce**
1. Create a Rem with a few lines.
2. Create another Rem immediately below with an image (doesn't matter if direct sibling or not) 
3. Select text in the last line of first Rem, then try to hover menu.

**Expected behavior**
Text should be formattable.

**Screenshots**
If I select "doctor" in the image below, then try to hover over the formatting menu, it disappears. Doesn't happen with higher lines.
 
![image](https://user-images.githubusercontent.com/67518000/108626367-a8e4d080-7447-11eb-997a-ec947749f39a.png)

**Desktop (please complete the following information):**
Windows desktop 1.2.3

**Comment by mfranzs** [comment]
Thanks for reaching out. Merging with #26 26
