### ISSUE TITLE
Automatic search gives outdated results

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#863]
**Describe the bug**
Could see this as being on purpose but I activated automatic search on a typo, clicked on one of the results, edited the typo in the created portal, did another automatic search and the fixed rem is still shown as a result even though it's written correctly and no matter what I do, refresh, open new tab, delete internet history, the corrected result still shows up

**To Reproduce**
1. select a word with automatic search turned on
2. Click on one the results
3. Change the word that you searched in the portal that got created
4. Delete the portal
5. Select the same word
6. See error

**Expected behavior**
I expected it to not show up anymore but my guess is that this is intentional

**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/108629577-e30e9c00-7460-11eb-8293-480d4d24746c.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.4
 - Browser safari
 - Version 14

**Comment by mfranzs** [comment]
Thanks for the report. This is intentional - the Rem remembers "search aliases" that have been used for it.
