### ISSUE TITLE
siempre me sale algo salio mal, Error: no se puede resolver un punto DOM desde el punto Slate: {"path": [0,0], "offset": 2}

### ISSUE THREAD

**Issue by mariabelen22** [remnoteio/remnote-issues#866]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by mariabelen22** [comment]
Cuando trato de escribir en la hoja en blanco, pongo la segunda letra y sale algo salio mal y lo siguiente: Intente actualizar la página. Si el problema persiste, proporcione detalles adicionales en la página de ayuda .

Error: no se puede resolver un punto DOM desde el punto Slate: {"path": [0,0], "offset": 2} . URL: https://www.remnote.io/document/KTy3KZKzWqhR5Q6D4

Escritorio 

SO: [por ejemplo, iOS]
Navegador [Chrome]
Versión [por ejemplo, 22]

Aquí mando el link de la captura de pantalla: 
https://user-images.githubusercontent.com/79423722/108639734-04bd5280-7464-11eb-9955-0dce7a9af8f6.png


Error: no se puede resolver un punto DOM desde el punto Slate: {"path": [0,0], "offset": 2}

**Comment by mfranzs** [comment]
Thanks for reaching out. Merging with #893

**Comment by RenatoDav** [comment]
Cual fue la solucion al problema?
