### ISSUE TITLE
No. of Tagged Rems does not appear or appear incorrectly at bottom portal results

### ISSUE THREAD

**Issue by marcothesis** [remnoteio/remnote-issues#867]
Although there is indication of tagged rems existing in the bottom portal, upon expanding the portal there would be no results shown. 

In other instances, an incorrect count of Tagged Rems is reflected.

---
![Screenshot 2021-02-22 at 2 11 20 PM](https://user-images.githubusercontent.com/10230857/108669713-866eb800-7518-11eb-96da-635bb738bb1d.png)
---
![Screenshot 2021-02-22 at 2 11 32 PM](https://user-images.githubusercontent.com/10230857/108669721-8a023f00-7518-11eb-8eb8-023254accc9e.png)
---
![Screenshot 2021-02-22 at 2 26 00 PM](https://user-images.githubusercontent.com/10230857/108670571-0ba69c80-751a-11eb-9445-89f99bfb8c80.png)
---
![Screenshot 2021-02-22 at 2 26 09 PM](https://user-images.githubusercontent.com/10230857/108670587-12351400-751a-11eb-916e-e02ed640718e.png)

**Comment by mfranzs** [comment]
We've made some updates here. 
Are you still experiencing this issue as of RemNote 1.3?

**Comment by marcothesis** [comment]
Thanks for fixing. For now, I have not observed the same issue again with v1.3.6.
