### ISSUE TITLE
Can't find certain rems in the search window sometimes

### ISSUE THREAD

**Issue by FuryMartin** [remnoteio/remnote-issues#870]
**Describe the bug**
After updating to 1.2.3, my local knowledge sometimes can't find certain rems. 

It seems that only tagged rems will not be found.

 I guess that there are some failures of the index system after the update.

See the screenshot below.

**To Reproduce**
I am not sure how to reproduce.
I just updated my RemNote to 1.2.3. My Local Knowledge Base seemed having been rebuilt when I opened 1.2.3 RN for the first time. And then I began to find RN can't search for certain rems even if they are before my eyes.

**Expected behavior**
Fix the bug.

**Screenshots**
<img src="https://fury-markdown.oss-cn-beijing.aliyuncs.com/20210222223621.png"/>

**Desktop (please complete the following information):**
 - OS: [Win10 20H2]
 - Desktop APP Version [1.2.3]

**Comment by FuryMartin** [comment]
I just found this bug may be related to #867 : Tagged rems can't be found when searching.

**Comment by killer2alex** [comment]
Ich have the Same Problem.

**Comment by Echology88** [comment]
I've encountered this problem too. And the problem is not restricted to "tagged rems".  A Plain text rem (with no tag, no reference etc.)  which already written in the document could not be found within the search portal and search bar at right bottom corner.

**Comment by killer2alex** [comment]
Could be related (and fixed?) to #903?

**Comment by FuryMartin** [comment]
> Could be related (and fixed?) to #903?

Yes, they are the same bug.  As it has been fixed, I shall close this issue.
