### ISSUE TITLE
self-formed dozens of empty untitled rem

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#871]
Even if I delete them all one by one, over time it comes back after a while
![image](https://user-images.githubusercontent.com/20538090/108744011-7ff93400-754a-11eb-894c-01fc29377a14.png)
![image](https://user-images.githubusercontent.com/20538090/108744180-b20a9600-754a-11eb-8970-601e60575bc6.png)

**Comment by mfranzs** [comment]
Merging with #890
