### ISSUE TITLE
Hello, I've got this problem with the Window app: sorry - You Need to Refresh A database error occurred in your browser, and you need to refresh. No need to worry! No data has been lost.  A support ticket has automatically been logged. Additionally, if the problem persists, please contact support. UnknownError Internal error opening backing store for indexedDB.open. UnknownError: Internal error opening backing store for indexedDB.open.

### ISSUE THREAD

**Issue by rodfer1096** [remnoteio/remnote-issues#874]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you make sure that you're on RemNote 1.2.3?
