### ISSUE TITLE
code block bug

### ISSUE THREAD

**Issue by Jackiexiao** [remnoteio/remnote-issues#878]
**Desktop**
 - OS: window PC version
 - Version : v.1.2
![remnote-bug-code-block](https://user-images.githubusercontent.com/18050469/108807033-4bcf5300-75de-11eb-9a3c-348dcc98fee3.gif)

**Comment by Jackiexiao** [comment]
also code block has this bug

![remnote-bug-code-block-duplicate](https://user-images.githubusercontent.com/18050469/108868836-8dd5b480-7631-11eb-9a0d-f14c1896743e.gif)

**Comment by mfranzs** [comment]
Thanks for the report. Merging with  #674
