### ISSUE TITLE
Wrong intervals when sharing a document

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#880]
![image](https://user-images.githubusercontent.com/69430941/108866026-1a618200-75f4-11eb-8fdf-c0c6386e9a69.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.4
 - Browser safari
 - Version 14

**Additional context**
Looks like this issue https://github.com/remnoteio/remnote-issues/issues/663

**Comment by mfranzs** [comment]
Thanks for reaching out. Publicly shared documents will not have your custom schedulers applied - does that answer this?

**Comment by 8888Daniel8888** [comment]
Yeah sorry, my mistake. I didn't realise that RemNote's default is actually like that, because I'm used to seeing SM-2. Should have checked first
