### ISSUE TITLE
RemNote desktop keeps forgetting user defined zoom level

### ISSUE THREAD

**Issue by ognsya** [remnoteio/remnote-issues#897]
**Describe the bug**
Often RemNote reverts back to default zoom level (the equivalent of CTRL+0). When this happens, it seems to be just as I ALT-TAB back to the application (I can briefly see it changing from my chosen zoom level to the default one).

Related: https://github.com/remnoteio/remnote-issues/issues/883

**To Reproduce**
Not sure. Seems random.

**Expected behavior**
My chosen zoom level should persist (I like to keep it one step "smaller" than default). 

**Desktop (please complete the following information):**
Windows, 1.2.3

**Comment by badjerphoenix** [comment]
Same thing is happening with me on the desktop app

For me it seems to happen every time I have to close the app & open it again
Not sure about what the zoom level is but very tiny
