### ISSUE TITLE
No permite escribir en documento

### ISSUE THREAD

**Issue by Alexandra4p** [remnoteio/remnote-issues#898]
![Captura](https://user-images.githubusercontent.com/79678003/109247337-bd132f80-77b1-11eb-973e-f42d836ff936.PNG)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment]
merging with #921
