### ISSUE TITLE
Broken spellcheck

### ISSUE THREAD

**Issue by matleonii** [remnoteio/remnote-issues#9]
**Describe the bug**
Since the last update (27 of July) my spellcheck is broken.

**To Reproduce**
I click on the word that is marked as wrong and select the option I want it to turn into.

**Expected behavior**
Have the word corrected

**What happens**
Nothing happens. I still get the wrong word with no correction

**Desktop (please complete the following information):**
 - OS: windows 10 64 bits
 - Browser Opera
 - Version 70 (latest)

**Additional context**
Something odd that I noticed as well is that as soon as start typing the first letter of the word I get it marked as if it was wrong. Before the update the word was marked after I pressed the space bar to start a new one.

I checked on Firefox and it seams to be working fine there.

**Comment by mfranzs** [comment]
Thanks for the report! A fix has been deployed.

**Comment by matleonii** [comment]
Thanks for that. It's now working fine here!
