### ISSUE TITLE
Sidebar inaccessible when browser window size is reduced below a certain size

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#90]
**Describe the bug**
When the browser window is reduced to a size that is small enough to no longer be able to display the sidebar on the left (pinned or unpinned), the "mini version" of the sidebar appears on top but it cannot be accessed - neither by hovering nor by clicking.

**To Reproduce**
1. Put RemNote in split window mode with another browser window
2. Observe that "mini version" of sidebar appears on top
3. Try hovering/clicking on it - observe that it doesn't respond

**Expected behavior**
It should display the sidebar on the left upon clicking/hovering over the mini version on the top despite window size being reduced.

**Screenshots**

![image](https://user-images.githubusercontent.com/68901589/92468314-0364da00-f1e4-11ea-8b02-51c82a555c04.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
This "mini version" of the sidebar used to appear on top before the update too when window size was reduced this way but it was clickable (could be accessed) and once clicked, the sidebar would appear on the left.

**Comment by anishaaa1** [comment]
Fixed! 🙂

**Comment by anishaaa1** [comment]
This bug has come up again when in split window and to access the sidebar, I have to remove RemNote from split window and increase the window size until the sidebar appears on the left and can be hovered over to access.

**Comment by mfranzs** [comment]
I'm having trouble reproducing this - are you still encountering this issue?

**Comment by anishaaa1** [comment]
> I'm having trouble reproducing this - are you still encountering this issue?

It's been fixed since, thanks!
