### ISSUE TITLE
Can't use Alt+P or Alt+C keyboard shortcuts on a Mac and no way to change those shortcuts, cant use the Pin Global search context as a result

### ISSUE THREAD

**Issue by binabdilwali** [remnoteio/remnote-issues#900]
Please check the following video walkthrough

https://user-images.githubusercontent.com/44670449/109271590-cbe4fb00-7820-11eb-9a73-aa3b04771786.mp4

There generally seems to be a big problem with Mac OS and using the option key with 1 letters combinations for shortcuts.
Please check this post:
https://stackoverflow.com/questions/11876485/how-to-disable-typing-special-characters-when-pressing-option-key-in-mac-os-x/16019737 

I'm on the latest desktop version and the same applies to webapp

**Comment by 8888Daniel8888** [comment]
Probably has to do with the fact that RemNote isn't optimised for any other keyboard layouts besides US
