### ISSUE TITLE
Creating new references also creates duplicating #Stub tags

### ISSUE THREAD

**Issue by marcothesis** [remnoteio/remnote-issues#901]
Recently, I noticed multiple #Stub tags existing in my knowledge base so I tried to merge and consolidate them into the MAIN #Stub where all references have been tagged with since I started using RemNote.

Since then, each time I create a new reference, it does not create a #Stub that points back to the MAIN one but instead creates a duplicating #Stub. These individual #Stubs are now pointing to their own respective reference only.

This is going to get messy real soon.

![Screenshot 2021-02-26 at 4 36 16 PM](https://user-images.githubusercontent.com/10230857/109277196-f4d1b400-7851-11eb-841e-f3a4717cc30b.png)

![Screenshot 2021-02-26 at 4 47 35 PM](https://user-images.githubusercontent.com/10230857/109277504-64e03a00-7852-11eb-9929-ce541efa4f61.png)

**Comment by ft-fk** [comment]
![image](https://user-images.githubusercontent.com/79699896/109296944-76651a00-7831-11eb-820a-6d291d812da7.png)

Same

**Comment by mfranzs** [comment]
Thanks for reaching out. When you click into these Rem, do you see the merge button into the bottom toolbar?

**Comment by marcothesis** [comment]
Yes, the Merge button is present at the bottom for each of these rems. That Merge function still works as it got rid of all the other #Stub but new #Stubs are still being created for each new reference that I made.

**Comment by ft-fk** [comment]
> Thanks for reaching out. When you click into these Rem, do you see the merge button into the bottom toolbar?


In my case, I don't have the option to merge (I have now over 50 instances) : 

![image](https://user-images.githubusercontent.com/79699896/109487714-e28b8c00-7a84-11eb-9dbf-d06f5277dc3a.png)


Also, for me : **a new instance of STUB is created for every parentless rem created on the fly**!
created a few seconds ago


![image](https://user-images.githubusercontent.com/79699896/109488034-5037b800-7a85-11eb-95da-842f3f8a7064.png)

**Comment by drkvj** [comment]
is this still happening to you guys?

**Comment by ft-fk** [comment]
doesn't happen to me any more 👍

**Comment by drkvj** [comment]
@ft-fk what happened exactly ? was it an update that solved it?

**Comment by marcothesis** [comment]
No idea which update was it but it's fixed now.

**Comment by ft-fk** [comment]
@drkvj 
I've no idea what resolved it. 
However, I can tell you that didn't change a thing in my setup or use of RemNote before and after the resolution of the problem. So, I can only deduce that it is an update that had resolved it.
Thanks for the support 👍
