### ISSUE TITLE
Can't write during iPad split view or slide over

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#904]
**Describe the bug**
 When split view is activated, I can't input any text, same thing happens when another app is in slide over while using RemNote. This is an PWA only issue and also a little old. Until recently it was actually the reason why I didn't use the PWA but now that I started using it, I thought I should report this issue now.

**To Reproduce**
1. Have RemNote open (PWA)
2. Open another app in split view or slide over
3. See error

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th Gen
 - OS: iPadOS 14.4
 - Browser safari (PWA)
 - Version 14

**Comment by 8888Daniel8888** [comment]
Checked the pwa of notion and I'm facing the same issue. So it might be an apple issue and not really RemNote. I'm going to open a thread on the forum to see if all pwa's don't work or if it's only some

**Comment by drkvj** [comment]
Closing this as it seems to be an iPadOS issue.
