### ISSUE TITLE
ERROR CUANDO ESCRIBO

### ISSUE THREAD

**Issue by Alexandra4p** [remnoteio/remnote-issues#905]
**Describe the bug**
ME SALE ERROR CUANDO TRATO DE ESCRBIR

**To Reproduce**
CREO UN DOCUMENTO TAL COMO EN EL TUTORIAL
ESCRIBO E INMEDIATAMENTE ME SALE ERROR

![image](https://user-images.githubusercontent.com/79678003/109367980-99a9bc80-7865-11eb-82bc-3933b23c6c6b.png)

**Comment by drkvj** [comment]
This issue should’ve been fixed, kindly PM me or the mods if you are still having issues. Closing the topic for now. Thanks for the report!
