### ISSUE TITLE
Referencing and tagging doesn’t work

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#91]
**Describe the bug**
The issue happens on mobile. If you're using the mobile layout and type ## or [[, no pop up window appears like usually
**To Reproduce**
1. Type ## or [[
2. See error

**Expected behavior**
A pop up window for referencing should appear 
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/92485008-b33d4600-f1ea-11ea-9f6b-d99ff498a35a.png)![image](https://user-images.githubusercontent.com/69430941/92485023-b801fa00-f1ea-11ea-9462-0027e8fd2a92.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: ios 13.7
 - Browser chrome
 - Version 85

**Comment by mfranzs** [comment]
Thanks for the report. This is not supported on mobile yet, but it's on the roadmap to add this in the future.
