### ISSUE TITLE
New desktop update leaves app blank and inaccessible

### ISSUE THREAD

**Issue by ShreyasKallingal** [remnoteio/remnote-issues#913]
**Describe the bug**
There was an update available on the Desktop app. I restarted the app, and now I'm greeted by a white screen. Nothing works.

**To Reproduce**
1. Restart and update app from the button on the sidebar.

**Expected behavior**
Well, I would expect to have access to my notes.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Desktop
 - Version 1.2.3

**Comment by mfranzs** [comment]
Can you please try:
1) Opening and closing the app
2) Re-downloading from https://www.remnote.io/download if that doesn't work?

**Comment by ShreyasKallingal** [comment]
Opening and closing doesn't work, but re-downloading does. The update button still shows up, but I obviously won't click it now.

**Comment by ShreyasKallingal** [comment]
Looks like it's back to normal—thanks!
