### ISSUE TITLE
Missing flashcards and unclickable "Active" in www.remnote.io/cards

### ISSUE THREAD

**Issue by soulertsai** [remnoteio/remnote-issues#914]
**Describe the bug**
I used `/meta` to check a rem created by using cloze and found "Next repetition time" is the same as the time I created it.
"Last practice time" is empty.

Additionally, After I checked www.remnote.io/cards, I couldn't find this rem using browser's find tool. Besides, the slot "Active" cannot be clicked.

**To Reproduce**
1. Go to www.remnote.io/cards
2. Click on the slot "Active"

**Expected behavior**
1. Next repetition time should be in the future
2. Clickable in the "Active" slot

**Screenshots**
![image](https://user-images.githubusercontent.com/7892194/109415076-8592c600-79f1-11eb-9cce-6a21860f9e3d.png)
![image](https://user-images.githubusercontent.com/7892194/109415225-73655780-79f2-11eb-91b3-1f029a205a24.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 88.0.4324.182

**Additional context**
Related Issues:
1. https://github.com/remnoteio/remnote-issues/issues/125
2. https://github.com/remnoteio/remnote-issues/issues/262

**Comment by soulertsai** [comment]
Update:
After I change the rem with the cloze a bit, the problem disappear now.
So the problem I have now is about the unclickable slot "Active" in the www.remnote.io/cards page

**Comment by nicolosponziello** [comment]
i have the same problem. I have a lots of cards that are disabled and I don't know why. I cannot toggle them. Seems the queue and spacing repetition of cards is heavily broken for now

**Comment by comienzo2093** [comment]
I have the same problem.

**Comment by Beeybey** [comment]
Same here. A lot of cards that I create goes "inactive" as default and I can't click to active it... I hope they fix this soon ><

ps. I'm a new user but I am already in love with Remnote

**Comment by achseu** [comment]
Same here. Doing my work for nothing 'cause cards get disabled and you have to find them and go to each (!) card and enable it! This is reported since months (forum, reddit, etc.), every few weeks they say it is fixed and the "fixed" bug still continues...
Maybe get your code stable first and then create new features - i'm out of remnote now because i have to learn the full stuff and not only half and spent my time administering around bugs!

**Comment by nicolosponziello** [comment]
I basically stopped using remnote for the same reason for now. I don't want to waste time around the many software bugs

**Comment by mfranzs** [comment]
Thanks for the reports, all. This should be fixed as of RemNote 1.3. Please post here if you're still encountering issues.
