### ISSUE TITLE
Some Edit Later messages hidden in search portal

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#92]
**Describe the bug**
Some edit later messages of older rems do not appear in the search portal for edit later, they have to be manually shown by clicking on 1 hidden descriptor. These messages do not have the light blue background indicating that they are search results either.
Discord message link about this issue - https://discordapp.com/channels/689979930804617224/722840095001935902/741900429633257493

**To Reproduce**
Not sure how to reproduce this issue. This has happened with some older rems.

**Expected behavior**
Edit later messages should appear in search portal

**Screenshots**

![image](https://user-images.githubusercontent.com/68901589/92493487-a0843a80-f205-11ea-9465-486e9bb6b716.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
I've tried the following:
1. Refreshing the search portal
2. Refreshing RemNote
3. Logging in and out
4. Deleting the search portal and adding it again
5. Removing the rems 'Edit later' status and reassigning it as 'Edit later' with the same message

None of this has worked so far.

**Comment by mfranzs** [comment]
Thanks for the report. When you say "older Rem", do you know roughly how old these Rem are? And does this problem **only** Rem created in this earlier timeframe?

**Comment by anishaaa1** [comment]
> Thanks for the report. When you say "older Rem", do you know roughly how old these Rem are? And does this problem **only** Rem created in this earlier timeframe?

These rems were created about 2 months ago.
Yeah, I never faced this issue with any newly created rems put into Edit Later, just 4 older ones.

**Comment by mfranzs** [comment]
Got it, thanks for the info. We're going to put this on the backlog for now, unless we see it with new Rems going forward.
