### ISSUE TITLE
Backspace deletes the last letter

### ISSUE THREAD

**Issue by 8888Daniel8888** [remnoteio/remnote-issues#93]
**Describe the bug**
Whenever I press backspace to go to the Rem above, RemNote deletes the last letter

**To Reproduce**
1. Create a rem
2. Create an empty rem under the previous rem
3. Press backspace 

**Expected behavior**
The cursor should be right behind the last letter and not delete it
**Screenshots**
![image](https://user-images.githubusercontent.com/69430941/92510489-39b64f80-f20c-11ea-8766-d3e62458f840.png)![image](https://user-images.githubusercontent.com/69430941/92510501-3f139a00-f20c-11ea-9166-870de39f3244.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: ios 13.7
 - Browser chrome
 - Version 85

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
