### ISSUE TITLE
Printing Image Occlusion Problem

### ISSUE THREAD

**Issue by Eikosa** [remnoteio/remnote-issues#94]
![image](https://user-images.githubusercontent.com/20538090/92516313-b3a30480-f21d-11ea-8922-408aa6315ab5.png)

![image](https://user-images.githubusercontent.com/20538090/92516384-d2a19680-f21d-11ea-9152-72bd6e6c3657.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser:  Chrome
 - Version: 86.0.4240.22

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
