### ISSUE TITLE
Persistent yellow message box about update won't go away

### ISSUE THREAD

**Issue by ShreyasKallingal** [remnoteio/remnote-issues#941]
**Describe the bug**
I just opened my Desktop app and the following message appears on the upper right side:
<img width="348" alt="Screen Shot 2021-03-04 at 4 55 00 PM" src="https://user-images.githubusercontent.com/23715862/110051256-5d190d80-7d0a-11eb-979e-67bb598d4b60.png">

**To Reproduce**
1. Open RemNote desktop app on synced knowledge base
2. Notice message
3. Try restarting/refreshing
4. Same problem

**Expected behavior**
Message box should not be there; sync should function properly

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Desktop
 - Version 1.2.8

**Comment by smonv** [comment]
I got this problem too, same OS and version.

My document won't sync too, still, notice the last sync around 11 hours ago.

**Comment by efang160** [comment]
Same here on MacOS Desktop App.

Web version appears to be functioning properly.

**Comment by ulioa** [comment]
Same here on MacOS Desktop App

**Comment by badjerphoenix** [comment]
Same here for Windows & Android

**Comment by ShreyasKallingal** [comment]
A new update (1.2.9) fixed it!

**Comment by smonv** [comment]
> A new update (1.2.9) fixed it!

 How did you update? Did you re-download and re-install?

I just open RemNote again but no update

**Comment by badjerphoenix** [comment]
Same
I have the desktop updated but Android still a no go
