### ISSUE TITLE
Cannot update and download desktop app

### ISSUE THREAD

**Issue by ulioa** [remnoteio/remnote-issues#942]
**Cannot update and download desktop app**
The desktop app say I cannot sync until refresh, but I close it and open it 6 times, it didn't work.
The download page doesn't work. It shows: AccessDeniedAccess DeniedTB0QX6XFZ91BX3936NOkzXjopufTm0a7psMql1OoGyLsrfTVrgnFTHNi1SSzkoXFfJWC9gpeuPHiSyDyHx76RC02ow4=

Also, I'm using Chinese to take note. Chinese characters can only be typed in desktop app. When I typed Chinese characters in browser, every-time I finish typing a word the cursor jump to the very front of the sentence.

**To Reproduce**
1. Go to 'https://www.remnote.io/download'
2. Click on 'download'
3. See error: AccessDeniedAccess DeniedTB0QX6XFZ91BX3936NOkzXjopufTm0a7psMql1OoGyLsrfTVrgnFTHNi1SSzkoXFfJWC9gpeuPHiSyDyHx76RC02ow4=

**Expected behavior**
Let me update and be able to use the desktop app...
Or fix the Chinese characters typing bug

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS
 - Browser :safari
 - Version : I don't know

**Comment by lovedebug** [comment]
I just tested, the issue has been resolved, you can just download it from remnote website

**Comment by ulioa** [comment]
Yes, it work!
