### ISSUE TITLE
indent wrong

### ISSUE THREAD

**Issue by baihuzisid** [remnoteio/remnote-issues#943]
win10,
![image](https://user-images.githubusercontent.com/29114371/110082571-7b454300-7dc8-11eb-90f8-570bb83d1295.png)

**Comment by jcpfrancesconi** [comment]
Yeah, my sidebar hierarchy also doesn't have any indentation anymore:
![image](https://user-images.githubusercontent.com/49200282/110192401-a94c7680-7e0c-11eb-9bb2-e3f258d4b536.png)
