### ISSUE TITLE
UI Bug? | Multiline Cards

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#944]
**Describe the bug**
In multiline cards, _::_ **[...]** appears after the prompt (above the line separating Front/Back of the card) as well as under this line. It normally appears only under the line.

**To Reproduce**
1. Create a multiline card
2. See the preview or view it within the queue
3. See that _::_ **[...]** appears both under the line separating Front/Back + next to the prompt (above the line)

**Screenshots**
![image](https://user-images.githubusercontent.com/68901589/110086143-4b7b4880-7d92-11eb-8bba-da2841f4948b.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Desktop App
 - Version 1.2.9

**Comment by tfiwm** [comment]
Yup, UI bug from latest release. Thanks for reporting this already
