### ISSUE TITLE
All images disapeared from local-kb

### ISSUE THREAD

**Issue by Nimamoh** [remnoteio/remnote-issues#948]
**Describe the bug**
I had a local kb with a lot of image, everything is gone. 
Previously, remnote app looked for images in local-kb path on disk, now it looks for images in `C:\Users\XXX\remnote\Guest\files`
Additionnally, when pasting image in remnote, I have now a message "You must be logged in to upload images".

**Expected behavior**
Be able to paste images in documents and not loosing it between updates.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Remnote version: 1.2.9

**Additional context**
I use local kb only. No account neither sync feature.

This is not related to the bugreport but I noticed that advanced template features disappeared too (going into a paid version of remnote). 
Is it planned to strip the free version (local-kb only) from more feature? do I have to worry having to switch online or switching to a paid plan to retrieve complete, non-corrupted content of my knowledge base?

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you please double-check that your local knowledge-base path is still assigned correctly?

**Comment by Nimamoh** [comment]
Yes, when I check in storage location, the local-kb is still in its proper path (which is in another drive, ex: `E:\LOCAL_KBS\my-localkb`)

**Comment by Nimamoh** [comment]
Well, I do not know what happened (an update ?) but everything is back in order.

As of this morning, my local kb seems to load correctly, images are back and I can include them in rem now 👍

![image](https://user-images.githubusercontent.com/16213090/112717579-0b6d3880-8eee-11eb-84ed-58885db6b7d1.png)
