### ISSUE TITLE
Electron app: Spell checker cannot be deactivated. 

### ISSUE THREAD

**Issue by SuzanaK** [remnoteio/remnote-issues#949]
**Describe the bug**
I cannot deactivate the spell checker. 

**To Reproduce**
1. Open the desktop app.
2. Start writing any word.
3. Even a known word will be underlined red while I'm typing which is extremely distracting. Unkown words will stay underlined red while the cursor is in the same REM. 
4. I am writing in two languages (English and German). German is the system language, so English words get marked as wrongly spelled. I see no way to change the language. 

**Expected behavior**
A setting to disable spell checking completely. (I tried right click but there is no option to disable it or change the language) 

**Desktop (please complete the following information):**
 - OS: Linux Mint, Electron app
 - Version 1.2.9

**Comment by drkvj** [comment]
This is a feature request, kindly make one on the forum where other users can vote. Thank you :)

**Comment by drkvj** [comment]
merging with https://github.com/remnoteio/remnote-issues/issues/949
