### ISSUE TITLE
Backward cards appearing in forward only rems

### ISSUE THREAD

**Issue by Dhruba1802** [remnoteio/remnote-issues#95]
**Describe the bug**
Backward cards appearing in forward only rems with 'Practice card' auto unchecked/disabled for them

**To Reproduce**
1. Go to 'queue'

**Expected behavior**
only Forward cards should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/69080326/92517596-83b32b80-f234-11ea-8a18-e90ab0f161bb.png)
![image](https://user-images.githubusercontent.com/69080326/92517603-87df4900-f234-11ea-9d80-13423c6053b4.png)
![image](https://user-images.githubusercontent.com/69080326/92517610-8b72d000-f234-11ea-89be-9a1cc0da101a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [Edge]
 - Version [85.0.564.44]

**Comment by mfranzs** [comment]
Thanks for the report. Can you please view metadata for the _adjuvant in_ card by typing /data on that Rem, and send us a screenshot of that?

**Comment by Dhruba1802** [comment]
![image](https://user-images.githubusercontent.com/69080326/93041289-c8422b00-f669-11ea-93d7-c23abb4c5d73.png)

**Comment by Dhruba1802** [comment]
recently the bug also happened to another card... here its metadata
![image](https://user-images.githubusercontent.com/69080326/93041372-fb84ba00-f669-11ea-996a-940acc2dc957.png)

**Comment by xflashkey** [comment]
I have the same problem, it's really annoying. It also happens if you share the document.

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
