### ISSUE TITLE
after delete notes, "loading" show up when search

### ISSUE THREAD

**Issue by Jackiexiao** [remnoteio/remnote-issues#950]
![image](https://user-images.githubusercontent.com/18050469/110228390-a8fec900-7f3b-11eb-97ec-a31f3baa3b97.png)

windows
1.2.9

**Comment by drkvj** [comment]
Hey! Could you pls confirm if this still happens to you? Kindly PM me or the moderators on the forum to open the topic again. Thanks for the report!
