### ISSUE TITLE
Turn off the tutorial

### ISSUE THREAD

**Issue by Grover3293** [remnoteio/remnote-issues#955]
**I mistakenly clicked onto tutorial in help page.
Now every time I open the desktop app it opens with tutorial option**
In windows app the first time I open the app it starts with the page (not loading it when offline).
“Tutorial” seen Below the documents option.
When I click the documents only then my drafts and other things Come.
And tutorial goes away

**To Reproduce**
1. Go to 'Remnote desktop app'
2. Click on 'lower right help mark'
3. Scroll down to 'Tutorials'
4. Now  restart the app 

**Expected behavior**
 app starts directly with personal documents 

on starting the app -- ![image](https://user-images.githubusercontent.com/68772919/110252604-3a0d8880-7fac-11eb-9725-034396a66aa2.png)
then after clicking documents --- 
![image](https://user-images.githubusercontent.com/68772919/110252630-4f82b280-7fac-11eb-8cd1-14bbd709530e.png)

**Desktop
 - OS: Windows 10 pro
 - Browser : on chrome it works fine

**Comment by mfranzs** [comment]
Thanks for reaching out. Does the app still open on the tutorials page if you go to a document before closing it?

**Comment by Grover3293** [comment]
> Thanks for reaching out. Does the app still open on the tutorials page if you go to a document before closing it?
it does ( for 2-3 sec) but in a snap my previous doc opens .
though this has slowed down opening process ( since there is already some white screen issue that slow the app down but anyway original issues is resolves . thanks for that
![image](https://user-images.githubusercontent.com/68772919/112188238-d4b2cc00-8c28-11eb-9a49-62fc65093c90.png)
