### ISSUE TITLE
Autogenerated inactive backward cards for forward only rems

### ISSUE THREAD

**Issue by Dhruba1802** [remnoteio/remnote-issues#96]
**To Reproduce**
1. Go to 'https://www.remnote.io/cards'

**Expected behavior**
this should not generate. 

**Screenshots**
![image](https://user-images.githubusercontent.com/69080326/92519100-0d63f880-f237-11ea-8206-11a59ae90167.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [85.0.564.44]

**Additional context**
Not a major issue affecting my study, but in the past I've noticed to get rems inactivated & queue jumping... I used to reactivate them from here. But now, this ever-growing autogenerated cards will make the process to find & activate those auto-inactivated rems (if so happens unknowingly) more difficult.

**Comment by mfranzs** [comment]
Thanks for the clear report. Is this happening for all of your backwards cards? If not, do you know what sequence of actions makes this happen? We're having some trouble reproducing this.

**Comment by Dhruba1802** [comment]
No not for all cards... Not sure what triggers this, but deleting that rem & then recreating it in forward only solves the problem... but it's time consuming... Best wishes for getting this problem done in near future... Hats off to the effort the team is putting 👏

**Comment by Dhruba1802** [comment]
Hello, Martin. One thing to note that this backwards cards are formed before the September update. You have told that you have pushed some update recently regarding queue jumping on discord. after that no such above cards formed while practicing queue... If so happens, I shall inform you... rather now the issue#95 on github is the current problem. Please comment on there. 😊

**Comment by Dhruba1802** [comment]
To me, as I have found today, the reason for queue jumping are these cards ?? What's your thought ? DMing you a video on discord

**Comment by MarWeUMR** [comment]
I would like to confirm this behaviour. There are many backwards cards in my queue, which shouldn't exist.
The queue jumping phenomenon happens, too.

I don't know the exact purpose of the remnote.io/cards link, but it seems to me, that there are some entries not being deleted.

**Comment by mfranzs** [comment]
Thanks for the report. We've identified a possible fix for this issue, and have deployed it in the latest update. If you re-encounter this issue, please re-open this ticket so that we can continue debugging. Thank you!
