### ISSUE TITLE
Android input / invalid 

### ISSUE THREAD

**Issue by lll637637** [remnoteio/remnote-issues#964]
Android input / invalid

**Comment by mfranzs** [comment]
Thanks for reaching out. Please provide more information to help us reproduce.

**Comment by lll637637** [comment]
我是中文用户，使用的是讯飞输入法，我们国家很多人都是使用这个输入法，用这个输入法输入 / 无效。
I am a Chinese user ， I use the Xunfei input method. Many people in our country use this input method. Use this input method to input / invalid 。
https://srf.xunfei.cn/

**Comment by lll637637** [comment]
> 谢谢你伸出援手。请提供更多的信息，以帮助我们复制。

我是中文用户，使用的是讯飞输入法，我们国家很多人都是使用这个输入法，用这个输入法输入 / 无效。
I am a Chinese user ， I use the Xunfei input method. Many people in our country use this input method. Use this input method to input / invalid 。
https://srf.xunfei.cn/
