### ISSUE TITLE
Something went wrong with my tutorials page

### ISSUE THREAD

**Issue by jason2b29** [remnoteio/remnote-issues#972]
![image](https://user-images.githubusercontent.com/80371949/110566192-a0e89880-818a-11eb-9dda-669418c00a35.png)

**Comment by Grover3293** [comment]
Hey , can you turn it back to normal opening - like with no tutorials after opening the app. 
I mistakenly clicked onto tutorial in help page.
Now every time I open the desktop app it opens with tutorial option
In windows app the first time I open the app it starts with the page (not loading it when offline).
“Tutorial” seen Below the documents option.
When I click the documents only then my drafts and other things Come.
And tutorial goes away 
https://github.com/remnoteio/remnote-issues/issues/955
