### ISSUE TITLE
Flashcards on Pixel 3a not synchronising with web browser

### ISSUE THREAD

**Issue by bndxn** [remnoteio/remnote-issues#975]
**Describe the bug**
Thanks for making Remnote -it's great! 

Minor issue: 
- I've got a streak of 4 flashcards on mobile device, and internet connection is good, expect auto-sync
- I then go to web browser version of remnote and there's no streak - it's lost
- I then do one flashcard session on desktop, and it goes back to a streak of 1
- I double-check synchronising on the phone, it is synced, and it now shows a streak of 1 day

Shouldn't this have automatically synched or do I need to sync after each flashcard practice?

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="245" alt="Screenshot 2021-03-10 at 09 04 46" src="https://user-images.githubusercontent.com/67464282/110604179-aee4ec00-817f-11eb-8287-66005233b6fc.png">
![Screenshot_20210310-090545](https://user-images.githubusercontent.com/67464282/110604339-e18ee480-817f-11eb-9859-752dae48a2b2.png)

![Screenshot_20210310-090545 (1)](https://user-images.githubusercontent.com/67464282/110604935-86a9bd00-8180-11eb-9fbf-55d5acaa1f6d.png)

**Desktop (please complete the following information):**
 - Web browers

**Smartphone (please complete the following information):**
- Pixel 3a, Remnote app

**Additional context**

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by nicolosponziello** [comment]
I have the same problem. Basically every device I use RemNote with has a different number of card in the queue. Moreover, some cards appears to be disabled and don't show up in queue. This lead me thinking that the queue algorithms and synchronization is not working properly and it is unreliable

**Comment by bndxn** [comment]
Thanks!
