### ISSUE TITLE
The page freezes intermittently when searching using Korean or typing in Korean.

### ISSUE THREAD

**Issue by comienzo2093** [remnoteio/remnote-issues#978]
![image](https://user-images.githubusercontent.com/52667667/110650000-7f74c480-81fd-11eb-977e-1e84703008db.png)

Hello, I am a remnote user. I use Korean to write or search for documents.
However, sometimes I get an error like the image above.
This did not happen when using English.
Please fix the bug. Thank you.

**Comment by comienzo2093** [comment]
![E01](https://user-images.githubusercontent.com/52667667/110657101-e8f7d180-8203-11eb-9aa5-22c65dde7a58.JPG)


I have figured out a specific situation where this problem occurs.

1. As shown in the image above, there is text "Search for a Document or Rem" in the search box.

2. When I type'Hangul' to search for something, the two languages ​​overlap and an error occurs immediately.

3. So, before I type in Korean, I type in the space bar or English to remove the "Search for..." message and then search, it works fine.

4. However, this is very cumbersome and sometimes cannot be solved with the above method in other situations. Please fix the bug. Thank you.

**Comment by drkvj** [comment]
merging with #812
