### ISSUE TITLE
Date formatting display is wrong

### ISSUE THREAD

**Issue by pihentagy** [remnoteio/remnote-issues#98]
**Describe the bug**
Display bug in settings page on date format option. Works ok. Bugfix seems trivial :)

**To Reproduce**
1. Go to settings
2. Click on date format
3. Select "Year/Month/Day"
4. See picture (shot taken after successfully selecting the selected option), incorrectly states "Month/Day/Year" is selected

**Expected behavior**
Displaying Year/Month/Day

**Screenshots**
![dateformat-high](https://user-images.githubusercontent.com/29916/92590482-97927800-f29c-11ea-8a70-e50d72a96662.gif)

**Desktop (please complete the following information):**
 - OS: Linux Mint 
 - Browser Firefox
 - Version 80.0

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
