### ISSUE TITLE
automatically add template didn't work

### ISSUE THREAD

**Issue by jason2b29** [remnoteio/remnote-issues#980]
![image](https://user-images.githubusercontent.com/80371949/110744619-f305e880-8274-11eb-8d3f-bd25f5ddacb0.png)

**Comment by jason2b29** [comment]
![image](https://user-images.githubusercontent.com/80371949/110744936-7aebf280-8275-11eb-8405-478be7da864e.png)

it shows nothing,after i tag it

**Comment by 8888Daniel8888** [comment]
Did you turn the children into slots?
