### ISSUE TITLE
item links are unclickable

### ISSUE THREAD

**Issue by tangyuan233** [remnoteio/remnote-issues#982]
**Describe the bug**
When I add item links from other application and paste into rem, remnote doesn't recognize them as clickable links

**To Reproduce**
1. Copy item link from other application
2. Paste to rem

**Expected behavior**
I would like to make rem be able to jump between applications, eg. I paste a item link of a file in devonthink as a reference for a rem, then I can click the link to jump the file in devonthink.

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser : Chrome, Safari
 - Version :1.2.9

**Additional context**
item link looks like 'x-devonthink-item://319FE43B-A87A-4538-B65C-5843BC4519BB'

*Note*: Please contact us about account-specific issues directly at support@remnote.io.

**Comment by drkvj** [comment]
This is not a bug report per se, more of a feature request I guess? We are currently cleaning up all our platforms to make it easier for everyone, so kindly make a request on the forum where other users can vote on this as well.
