### ISSUE TITLE
Folder-Specific Queue showing Rem from Different Folder

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#985]
**Expected behavior**
It should show only rems from the Physiology folder in the example (see Screenshots).

**Screenshots**

![Screen Shot 2021-03-10 at 8 22 18 AM](https://user-images.githubusercontent.com/68901589/110909485-6ad52100-8310-11eb-97f3-46bfaaf48bac.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Desktop App
 - Version 1.2.9

**Additional context**
Not sure how to reproduce. There's only one card that has ever appeared in a different folder-specific queue so far and it's this one.

**Comment by mfranzs** [comment]
Thanks for reaching out. Is there any chance that this Rem is included in a portal?

**Comment by anishaaa1** [comment]
> Thanks for reaching out. Is there any chance that this Rem is included in a portal?

Haha, thank you! My bad, that was it 😃
