### ISSUE TITLE
Duplicate Search Results

### ISSUE THREAD

**Issue by anishaaa1** [remnoteio/remnote-issues#986]
**Screenshots**

![Screen Shot 2021-03-09 at 11 19 22 PM](https://user-images.githubusercontent.com/68901589/110910117-34e46c80-8311-11eb-996d-3a3f02a45351.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Desktop App
 - Version 1.2.9

**Comment by mfranzs** [comment]
Thanks for reaching out. Is there any chance these are duplicated aliases?

**Comment by anishaaa1** [comment]
No, they are not. Still have this issue as of now.

![image](https://user-images.githubusercontent.com/68901589/113503815-4b16ce80-9545-11eb-8d72-0dbec6c6f6ec.png)

**Comment by drkvj** [comment]
I have noticed this a several times too, it occurs only for rems that have aliases, but instead of displaying the different aliases they display the same name
