### ISSUE TITLE
Backward Only Card CSS Classes

### ISSUE THREAD

**Issue by hannesfrank** [remnoteio/remnote-issues#99]
The backward only cards and forward/backward cards can not distinguished by CSS. They both have the classes `.rem-container--practice-enabled.rem-container--backwards-practice-enabled`.

I suggest adding `.rem-container--forward-practice-enabled` to the rem container and either applying `.rem-container--practice-enabled` on `forward OR backward` or dropping it completely as it is redundant.

Previous feature request: #58

Unrelated note: I really like the new footer icons for the enabled card directions, but I got confused by its inversion in dark mode. Maybe use a white card for an enabled direction in both light and dark mode?

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix in the latest update. Please let us know if you're still having any problems.
